import ZFVP.SetTheory.CantorSpace

/-! The category core of Solovay's Baire-property argument, inside one model: the reals missing
a dense set of finite sequences form the body of a nowhere dense tree, so a set of reals that is
decided by a set `S` of finite sequences on every real meeting each member of a sequence of dense
sets differs from the open set generated by `S` by a meagre set. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-- A function restricted to the domain of a subfunction is that subfunction. -/
theorem restrict_domain_eq_of_subset {x s : V} [IsFunction x] [IsFunction s] (h : s ⊆ x) :
    x ↾ (domain s) = s := by
  apply mem_ext
  intro p
  constructor
  · intro hp
    obtain ⟨hpx, i, hi, v, rfl⟩ := mem_restrict_iff.mp hp
    obtain ⟨w, hw⟩ := mem_domain_iff.mp hi
    have hvw : v = w := by
      rw [← value_eq_of_kpair_mem hpx, value_eq_of_kpair_mem (h _ hw)]
    rw [hvw]
    exact hw
  · intro hp
    obtain ⟨X, Y, hs⟩ := (inferInstance : IsFunction s).mem_func
    obtain ⟨i, _, v, _, rfl⟩ := mem_prod_iff.mp (subset_prod_of_mem_function hs p hp)
    exact kpair_mem_restrict_iff.mpr ⟨h _ hp, mem_domain_of_kpair_mem hp⟩

theorem binarySequence_isFunction {s : V} (hs : s ∈ binarySequences V) : IsFunction s := by
  obtain ⟨n, _, hsn⟩ := (mem_binarySequences_iff s).mp hs
  exact IsFunction.of_mem hsn

theorem binarySequence_domain_mem {s : V} (hs : s ∈ binarySequences V) : domain s ∈ (ω : V) := by
  obtain ⟨n, hn, hsn⟩ := (mem_binarySequences_iff s).mp hs
  rw [domain_eq_of_mem_function hsn]
  exact hn

/-- A real extends a finite sequence exactly when the sequence is its restriction. -/
theorem subset_iff_restrict_eq {x s : V} (hx : x ∈ cantorSpace V) (hs : s ∈ binarySequences V) :
    s ⊆ x ↔ x ↾ (domain s) = s := by
  have : IsFunction x := IsFunction.of_mem hx
  have : IsFunction s := binarySequence_isFunction hs
  constructor
  · exact restrict_domain_eq_of_subset
  · intro h
    rw [← h]
    exact restrict_subset x (domain s)

/-- The real `x` meets the set `D` of finite sequences. -/
def Meets (D x : V) : Prop := ∃ s ∈ D, x ↾ (domain s) = s

theorem mem_openFrom_iff_meets (S x : V) : x ∈ openFrom S ↔ x ∈ cantorSpace V ∧ Meets S x :=
  mem_openFrom_iff S x

/-- The tree of finite sequences having no initial segment in `D`. -/
noncomputable def avoidingTree (D : V) : V :=
  {t ∈ binarySequences V ; ∀ s ∈ D, ¬ s ⊆ t}

theorem mem_avoidingTree_iff (D t : V) :
    t ∈ avoidingTree D ↔ t ∈ binarySequences V ∧ ∀ s ∈ D, ¬ s ⊆ t := by
  simp [avoidingTree]

def avoidingTreeFormula : SetTheorySemisentence 2 :=
  f“T D. ∀ t, t ∈ T ↔ t ∈ !binarySequencesFormula ∧ ∀ s ∈ D, ¬ s ⊆ t”

instance avoidingTreeFormula_defined : ℒₛₑₜ-function₁[V] avoidingTree via avoidingTreeFormula :=
  ⟨fun v ↦ by simp [avoidingTreeFormula, mem_ext_iff (y := avoidingTree _), mem_avoidingTree_iff]⟩

instance avoidingTree_definable : ℒₛₑₜ-function₁[V] avoidingTree :=
  avoidingTreeFormula_defined.to_definable

theorem avoidingTree_isTree (D : V) : IsTree (avoidingTree D) := by
  refine ⟨fun t ht ↦ ((mem_avoidingTree_iff D t).mp ht).1, ?_⟩
  intro t ht n hn
  obtain ⟨htb, hav⟩ := (mem_avoidingTree_iff D t).mp ht
  obtain ⟨m, hm, htm⟩ := (mem_binarySequences_iff t).mp htb
  rw [domain_eq_of_mem_function htm] at hn
  have hnm : n ⊆ m := (IsTransitive.nat hm).transitive n hn
  refine (mem_avoidingTree_iff D _).mpr ⟨(mem_binarySequences_iff _).mpr
    ⟨n, IsTransitive.ω.transitive m hm n hn, function_restrict_mem htm hnm⟩, ?_⟩
  intro s hs hst
  exact hav s hs (subset_trans hst (restrict_subset t n))

/-- The avoiding tree of a dense set of finite sequences is nowhere dense. -/
theorem avoidingTree_nowhereDense {D : V} (hD : D ⊆ binarySequences V)
    (hdense : ∀ s ∈ binarySequences V, ∃ t ∈ D, s ⊆ t) : IsNowhereDenseTree (avoidingTree D) := by
  refine ⟨avoidingTree_isTree D, ?_⟩
  intro s hs
  obtain ⟨t, ht, hst⟩ := hdense s hs
  refine ⟨t, hD t ht, hst, ?_⟩
  intro htT
  exact ((mem_avoidingTree_iff D t).mp htT).2 t ht (subset_refl t)

/-- The body of the avoiding tree consists of the reals missing `D`. -/
theorem mem_treeBody_avoidingTree_iff {D x : V} (hD : D ⊆ binarySequences V)
    (hx : x ∈ cantorSpace V) : x ∈ treeBody (avoidingTree D) ↔ ¬ Meets D x := by
  rw [mem_treeBody_iff]
  constructor
  · rintro ⟨_, h⟩ ⟨s, hs, hxs⟩
    have hn := binarySequence_domain_mem (hD s hs)
    exact ((mem_avoidingTree_iff D _).mp (h _ hn)).2 s hs (by rw [hxs])
  · intro h
    refine ⟨hx, fun n hn ↦ (mem_avoidingTree_iff D _).mpr
      ⟨restrict_mem_binarySequences hx hn, ?_⟩⟩
    intro s hs hsx
    exact h ⟨s, hs, (subset_iff_restrict_eq hx (hD s hs)).mp (subset_trans hsx (restrict_subset x n))⟩

/-- A set of reals decided by `S` on every real meeting each of a sequence of dense sets has the
Baire property, witnessed by the open set generated by `S`. -/
theorem baireProperty_of_decision {A S e : V} (hA : A ⊆ cantorSpace V) (hS : S ⊆ binarySequences V)
    (he : e ∈ (℘ (binarySequences V)) ^ (ω : V))
    (hdense : ∀ n ∈ (ω : V), ∀ s ∈ binarySequences V, ∃ t ∈ e ‘ n, s ⊆ t)
    (hdec : ∀ x ∈ cantorSpace V, (∀ n ∈ (ω : V), Meets (e ‘ n) x) → (x ∈ A ↔ Meets S x)) :
    BaireProperty A := by
  have hen : ∀ n ∈ (ω : V), e ‘ n ⊆ binarySequences V := fun n hn ↦
    mem_power_iff.mp (function_value_mem he hn)
  have hF : ℒₛₑₜ-function₁ (fun n : V ↦ avoidingTree (e ‘ n)) := by definability
  let f := definableGraph (ω : V) (fun n ↦ avoidingTree (e ‘ n)) hF
  have hf : f ∈ (℘ (binarySequences V)) ^ (ω : V) :=
    definableGraph_mem_function_of_mapsTo _ _ _ hF fun n _ ↦
      mem_power_iff.mpr (avoidingTree_isTree (e ‘ n)).1
  refine ⟨openFrom S, ⟨S, hS, rfl⟩, f, hf, ?_, ?_⟩
  · intro n hn
    rw [value_definableGraph _ _ hF hn]
    exact avoidingTree_nowhereDense (hen n hn) (hdense n hn)
  · intro x hx
    have hxc : x ∈ cantorSpace V := by
      rcases mem_union_iff.mp hx with h | h
      · exact hA x (mem_sdiff_iff.mp h).1
      · exact ((mem_openFrom_iff_meets S x).mp (mem_sdiff_iff.mp h).1).1
    by_contra hno
    push_neg at hno
    have hall : ∀ n ∈ (ω : V), Meets (e ‘ n) x := by
      intro n hn
      by_contra hm
      exact hno n hn (by
        rw [value_definableGraph _ _ hF hn]
        exact (mem_treeBody_avoidingTree_iff (hen n hn) hxc).mpr hm)
    have hAU : x ∈ A ↔ x ∈ openFrom S := by
      rw [hdec x hxc hall, mem_openFrom_iff_meets]
      exact ⟨fun h ↦ ⟨hxc, h⟩, fun h ↦ h.2⟩
    rcases mem_union_iff.mp hx with h | h
    · obtain ⟨h1, h2⟩ := mem_sdiff_iff.mp h
      exact h2 (hAU.mp h1)
    · obtain ⟨h1, h2⟩ := mem_sdiff_iff.mp h
      exact h2 (hAU.mpr h1)

end ZFVP
