import ZFVP.SetTheory.BlockPermutations
import ZFVP.SetTheory.CohenSymmetricSystem
import ZFVP.SetTheory.CohenNameSupport

/-!
The symmetric system of Jech's first embedding theorem, built with no atoms: Cohen forcing over
the index set `ω ×ˢ ω` (read as `ω` blocks of `ω` copies), the group of those Cohen automorphisms
that come from a block permutation, and the filter generated by pointwise stabilizers of finite
sets of conditions.

The last theorem is the one later modules use: a hereditarily symmetric name is fixed by every
block permutation that is the identity on a fixed finite set of blocks.
-/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-! ### The group -/

/-- The internal permutations of `ω ×ˢ ω` that permute the blocks. -/
noncomputable def blockPermutationSet : V :=
  {π ∈ internalPermutations ((ω : V) ×ˢ (ω : V)) ; ∃ ρ, IsBlockPermutation π ρ}

theorem mem_blockPermutationSet (π : V) :
    π ∈ (blockPermutationSet : V) ↔ ∃ ρ, IsBlockPermutation π ρ := by
  simp only [blockPermutationSet, mem_sep_iff, mem_internalPermutations]
  exact ⟨fun h ↦ h.2, fun h ↦ ⟨h.choose_spec.1, h⟩⟩

/-- The Cohen automorphisms of `ω ×ˢ ω` coming from a block permutation. -/
noncomputable def blockCohenGroup : V :=
  repl (cohenPermutation ((ω : V) ×ˢ (ω : V))) (by definability) blockPermutationSet

theorem mem_blockCohenGroup (σ : V) :
    σ ∈ (blockCohenGroup : V) ↔ ∃ π ρ, IsBlockPermutation π ρ ∧
      σ = cohenPermutation ((ω : V) ×ˢ (ω : V)) π := by
  simp only [blockCohenGroup, repl_spec, mem_blockPermutationSet]
  constructor
  · rintro ⟨π, ⟨ρ, hρ⟩, rfl⟩
    exact ⟨π, ρ, hρ, rfl⟩
  · rintro ⟨π, ρ, hρ, rfl⟩
    exact ⟨π, ⟨ρ, hρ⟩, rfl⟩

theorem blockCohenGroup_group :
    IsForcingAutomorphismGroup (cohenConditions ((ω : V) ×ˢ (ω : V)))
      (cohenOrder ((ω : V) ×ˢ (ω : V))) (blockCohenGroup : V) := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · intro σ hσ
    obtain ⟨π, ρ, hπρ, rfl⟩ := (mem_blockCohenGroup σ).mp hσ
    exact cohenPermutation_automorphism hπρ.1
  · exact (mem_blockCohenGroup _).mpr
      ⟨identity ((ω : V) ×ˢ (ω : V)), identity (ω : V), isBlockPermutation_identity,
        (cohenPermutation_identity _).symm⟩
  · intro σ hσ θ hθ
    obtain ⟨π, ρ, hπρ, rfl⟩ := (mem_blockCohenGroup σ).mp hσ
    obtain ⟨π', ρ', hπρ', rfl⟩ := (mem_blockCohenGroup θ).mp hθ
    exact (mem_blockCohenGroup _).mpr
      ⟨compose π π', compose ρ ρ', hπρ.comp hπρ',
        (cohenPermutation_compose hπρ.1 hπρ'.1).symm⟩
  · intro σ hσ
    obtain ⟨π, ρ, hπρ, rfl⟩ := (mem_blockCohenGroup σ).mp hσ
    exact (mem_blockCohenGroup _).mpr
      ⟨converseGraph π, converseGraph ρ, hπρ.inv, (cohenPermutation_inverse hπρ.1).symm⟩

/-! ### The filter and the symmetric system -/

/-- The filter generated by the pointwise stabilizers of internally finite sets of conditions. -/
noncomputable def blockCohenFilter : V :=
  finiteStabilizerFilter (cohenConditions ((ω : V) ×ˢ (ω : V))) blockCohenGroup

theorem blockCohenFilter_normal :
    IsNormalSubgroupFilter (cohenConditions ((ω : V) ×ˢ (ω : V)))
      (blockCohenGroup : V) blockCohenFilter :=
  finiteStabilizerFilter_normal blockCohenGroup_group

theorem blockCohen_symmetricSystem :
    IsSymmetricSystem (cohenConditions ((ω : V) ×ˢ (ω : V))) (cohenOrder ((ω : V) ×ˢ (ω : V)))
      (blockCohenGroup : V) blockCohenFilter :=
  ⟨cohen_poset _, ⟨∅, cohen_top _⟩, blockCohenGroup_group, blockCohenFilter_normal⟩

/-! ### The blocks used by a finite family of conditions -/

/-- The blocks (first coordinates) of the indices used by the conditions in `E`. -/
noncomputable def familyBlocks (E : V) : V := repl kpair.π₁ (by definability) (cohenFamilySupport E)

theorem mem_familyBlocks (E a : V) :
    a ∈ familyBlocks E ↔ ∃ z ∈ cohenFamilySupport E, a = kpair.π₁ z := by
  simp only [familyBlocks, repl_spec]

theorem familyBlocks_subset_omega {E : V} (hEP : E ⊆ cohenConditions ((ω : V) ×ˢ (ω : V))) :
    familyBlocks E ⊆ (ω : V) := by
  intro a ha
  obtain ⟨z, hz, rfl⟩ := (mem_familyBlocks E a).mp ha
  obtain ⟨b, hb, ξ, _, rfl⟩ := mem_prod_iff.mp (cohenFamilySupport_subset hEP z hz)
  simpa only [kpair.π₁_kpair] using hb

theorem familyBlocks_finite {E : V} (hEP : E ⊆ cohenConditions ((ω : V) ×ˢ (ω : V)))
    (hEf : IsInternallyFinite E) : IsInternallyFinite (familyBlocks E) :=
  internallyFinite_repl _ _ (cohenFamilySupport_finite hEP hEf)

/-! ### The support lemma -/

/-- A hereditarily symmetric name for the block system is fixed by every block permutation that
is the identity on all indices of some fixed finite set of blocks. -/
theorem blockCohenName_blockSupport {τ : V}
    (hτ : IsHereditarilySymmetricName (cohenConditions ((ω : V) ×ˢ (ω : V))) blockCohenGroup
      blockCohenFilter τ) :
    ∃ E, E ⊆ (ω : V) ∧ IsInternallyFinite E ∧
      ∀ π ρ, IsBlockPermutation π ρ →
        (∀ a ∈ E, ∀ ξ ∈ (ω : V), π ‘ ⟨a, ξ⟩ₖ = ⟨a, ξ⟩ₖ) →
        nameAction (cohenPermutation ((ω : V) ×ˢ (ω : V)) π) τ = τ := by
  obtain ⟨_, 𝔈, h𝔈P, h𝔈f, h𝔈⟩ :=
    (mem_finiteStabilizerFilter _ _ _).mp (hereditarilySymmetric_symmetric hτ).2
  refine ⟨familyBlocks 𝔈, familyBlocks_subset_omega h𝔈P, familyBlocks_finite h𝔈P h𝔈f, ?_⟩
  intro π ρ hπρ hfix
  have hmem : cohenPermutation ((ω : V) ×ˢ (ω : V)) π ∈ pointwiseStabilizer blockCohenGroup 𝔈 := by
    refine (mem_pointwiseStabilizer _ _ _).mpr
      ⟨(mem_blockCohenGroup _).mpr ⟨π, ρ, hπρ, rfl⟩, ?_⟩
    intro q hq
    rw [cohenPermutation_value (h𝔈P q hq)]
    apply cohenConditionAction_fix (h𝔈P q hq)
    intro z hz
    have hzf : z ∈ cohenFamilySupport 𝔈 := (mem_cohenFamilySupport 𝔈 z).mpr ⟨q, hq, hz⟩
    obtain ⟨a, ha, ξ, hξ, rfl⟩ := mem_prod_iff.mp (cohenFamilySupport_subset h𝔈P z hzf)
    have haE : a ∈ familyBlocks 𝔈 :=
      (mem_familyBlocks 𝔈 a).mpr ⟨⟨a, ξ⟩ₖ, hzf, (kpair.π₁_kpair a ξ).symm⟩
    exact hfix a haE ξ hξ
  exact (mem_sep_iff.mp (h𝔈 _ hmem)).2

end ZFVP
