import ZFVP.SetTheory.FiniteSequences
import ZFVP.SetTheory.CountableUnions
import ZFVP.SetTheory.UniformNumerals

/-! Internal reals as the Cantor space `2^ω`, binary trees and their bodies, basic open sets,
perfect and nowhere dense trees, meagre sets, and the perfect set property and Baire property
of a set of reals. All notions are given by fixed parameter-free formulas so that the
regularity assertions are sentences of the set-theory language. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

def cantorSpaceFormula : SetTheorySemisentence 1 :=
  f“C. C = !function.dfn (!(numeralFormula 2)) (!isω)”

def binarySequencesFormula : SetTheorySemisentence 1 :=
  f“S. S = !finiteSequencesFormula (!(numeralFormula 2))”

def treeBodyFormula : SetTheorySemisentence 2 :=
  f“B T. ∀ x, x ∈ B ↔ x ∈ !cantorSpaceFormula ∧ ∀ n ∈ !isω, !restrict.dfn x n ∈ T”

def openFromFormula : SetTheorySemisentence 2 :=
  f“U S. ∀ x, x ∈ U ↔ x ∈ !cantorSpaceFormula ∧ ∃ s ∈ S, !restrict.dfn x (!domain.dfn s) = s”

def isTreeFormula : SetTheorySemisentence 1 :=
  f“T. T ⊆ !binarySequencesFormula ∧ ∀ s ∈ T, ∀ n ∈ !domain.dfn s, !restrict.dfn s n ∈ T”

def incompatibleFormula : SetTheorySemisentence 2 :=
  f“t u. ∃ i, i ∈ !domain.dfn t ∧ i ∈ !domain.dfn u ∧ ¬!value.dfn t i = !value.dfn u i”

def isPerfectTreeFormula : SetTheorySemisentence 1 :=
  f“T. !isTreeFormula T ∧ !isEmpty ∈ T ∧
    ∀ s ∈ T, ∃ t ∈ T, ∃ u ∈ T, s ⊆ t ∧ s ⊆ u ∧ !incompatibleFormula t u”

def perfectSetPropertyFormula : SetTheorySemisentence 1 :=
  f“A. !CardLE.dfn A (!isω) ∨ ∃ T, !isPerfectTreeFormula T ∧ !treeBodyFormula T ⊆ A”

def isNowhereDenseTreeFormula : SetTheorySemisentence 1 :=
  f“T. !isTreeFormula T ∧ ∀ s ∈ !binarySequencesFormula, ∃ t ∈ !binarySequencesFormula, s ⊆ t ∧ t ∉ T”

def isMeagreFormula : SetTheorySemisentence 1 :=
  f“A. ∃ f ∈ !function.dfn (!power.dfn (!binarySequencesFormula)) (!isω),
    (∀ n ∈ !isω, !isNowhereDenseTreeFormula (!value.dfn f n)) ∧
    ∀ x ∈ A, ∃ n ∈ !isω, x ∈ !treeBodyFormula (!value.dfn f n)”

def isOpenFormula : SetTheorySemisentence 1 :=
  f“U. ∃ S, S ⊆ !binarySequencesFormula ∧ U = !openFromFormula S”

def bairePropertyFormula : SetTheorySemisentence 1 :=
  f“A. ∃ U, !isOpenFormula U ∧ !isMeagreFormula (!union.dfn (!sdiff.dfn A U) (!sdiff.dfn U A))”

/-- Every set of reals has the perfect set property. -/
def perfectSetPropertySentence : SetTheorySentence :=
  f“∀ A, A ⊆ !cantorSpaceFormula → !perfectSetPropertyFormula A”

/-- Every set of reals has the Baire property. -/
def bairePropertySentence : SetTheorySentence :=
  f“∀ A, A ⊆ !cantorSpaceFormula → !bairePropertyFormula A”

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-- The reals: functions from `ω` to `2`. -/
noncomputable def cantorSpace (V : Type*) [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙] : V :=
  ((2 : ℕ) : V) ^ (ω : V)

/-- Finite binary sequences. -/
noncomputable def binarySequences (V : Type*) [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙] : V :=
  finiteSequences ((2 : ℕ) : V)

instance cantorSpaceFormula_defined : ℒₛₑₜ-function₀[V] (cantorSpace V) via cantorSpaceFormula :=
  ⟨fun v ↦ by simp [cantorSpaceFormula, cantorSpace]⟩

instance binarySequencesFormula_defined :
    ℒₛₑₜ-function₀[V] (binarySequences V) via binarySequencesFormula :=
  ⟨fun v ↦ by simp [binarySequencesFormula, binarySequences]⟩

theorem mem_cantorSpace_iff (x : V) : x ∈ cantorSpace V ↔ x ∈ ((2 : ℕ) : V) ^ (ω : V) := Iff.rfl

theorem mem_binarySequences_iff (s : V) :
    s ∈ binarySequences V ↔ ∃ n ∈ (ω : V), s ∈ ((2 : ℕ) : V) ^ n :=
  mem_finiteSequences_iff _ _

theorem restrict_mem_binarySequences {x n : V} (hx : x ∈ cantorSpace V) (hn : n ∈ (ω : V)) :
    x ↾ n ∈ binarySequences V :=
  (mem_binarySequences_iff _).mpr ⟨n, hn, function_restrict_mem hx (IsTransitive.transitive _ hn)⟩

/-- The body of a tree: the reals all of whose finite restrictions lie in `T`. -/
noncomputable def treeBody (T : V) : V :=
  {x ∈ cantorSpace V ; ∀ n ∈ (ω : V), x ↾ n ∈ T}

theorem mem_treeBody_iff (T x : V) :
    x ∈ treeBody T ↔ x ∈ cantorSpace V ∧ ∀ n ∈ (ω : V), x ↾ n ∈ T := by
  simp [treeBody]

instance treeBodyFormula_defined : ℒₛₑₜ-function₁[V] treeBody via treeBodyFormula :=
  ⟨fun v ↦ by simp [treeBodyFormula, mem_ext_iff (y := treeBody _), mem_treeBody_iff]⟩

instance treeBody_definable : ℒₛₑₜ-function₁[V] treeBody := treeBodyFormula_defined.to_definable

/-- The open set generated by a set of finite sequences. -/
noncomputable def openFrom (S : V) : V :=
  {x ∈ cantorSpace V ; ∃ s ∈ S, x ↾ (domain s) = s}

theorem mem_openFrom_iff (S x : V) :
    x ∈ openFrom S ↔ x ∈ cantorSpace V ∧ ∃ s ∈ S, x ↾ (domain s) = s := by
  simp [openFrom]

instance openFromFormula_defined : ℒₛₑₜ-function₁[V] openFrom via openFromFormula :=
  ⟨fun v ↦ by simp [openFromFormula, mem_ext_iff (y := openFrom _), mem_openFrom_iff]⟩

instance openFrom_definable : ℒₛₑₜ-function₁[V] openFrom := openFromFormula_defined.to_definable

/-- A tree of finite binary sequences: closed under restriction. -/
def IsTree (T : V) : Prop := T ⊆ binarySequences V ∧ ∀ s ∈ T, ∀ n ∈ domain s, s ↾ n ∈ T

instance isTreeFormula_defined : ℒₛₑₜ-predicate[V] IsTree via isTreeFormula :=
  ⟨fun v ↦ by simp [isTreeFormula, IsTree]⟩

instance isTree_definable : ℒₛₑₜ-predicate[V] IsTree := isTreeFormula_defined.to_definable

/-- Two sequences disagree at a common coordinate. -/
def Incompatible (t u : V) : Prop := ∃ i, i ∈ domain t ∧ i ∈ domain u ∧ t ‘ i ≠ u ‘ i

instance incompatibleFormula_defined : ℒₛₑₜ-relation[V] Incompatible via incompatibleFormula :=
  ⟨fun v ↦ by simp [incompatibleFormula, Incompatible]⟩

instance incompatible_definable : ℒₛₑₜ-relation[V] Incompatible :=
  incompatibleFormula_defined.to_definable

/-- A nonempty tree in which every node has two incompatible extensions. -/
def IsPerfectTree (T : V) : Prop :=
  IsTree T ∧ (∅ : V) ∈ T ∧ ∀ s ∈ T, ∃ t ∈ T, ∃ u ∈ T, s ⊆ t ∧ s ⊆ u ∧ Incompatible t u

instance isPerfectTreeFormula_defined : ℒₛₑₜ-predicate[V] IsPerfectTree via isPerfectTreeFormula :=
  ⟨fun v ↦ by simp [isPerfectTreeFormula, IsPerfectTree]⟩

instance isPerfectTree_definable : ℒₛₑₜ-predicate[V] IsPerfectTree :=
  isPerfectTreeFormula_defined.to_definable

/-- `A` is countable or contains the body of a perfect tree. -/
def PerfectSetProperty (A : V) : Prop :=
  IsInternallyCountable A ∨ ∃ T, IsPerfectTree T ∧ treeBody T ⊆ A

instance perfectSetPropertyFormula_defined :
    ℒₛₑₜ-predicate[V] PerfectSetProperty via perfectSetPropertyFormula :=
  ⟨fun v ↦ by simp [perfectSetPropertyFormula, PerfectSetProperty, IsInternallyCountable]⟩

instance perfectSetProperty_definable : ℒₛₑₜ-predicate[V] PerfectSetProperty :=
  perfectSetPropertyFormula_defined.to_definable

/-- A tree whose body is nowhere dense: every sequence has an extension outside `T`. -/
def IsNowhereDenseTree (T : V) : Prop :=
  IsTree T ∧ ∀ s ∈ binarySequences V, ∃ t ∈ binarySequences V, s ⊆ t ∧ t ∉ T

instance isNowhereDenseTreeFormula_defined :
    ℒₛₑₜ-predicate[V] IsNowhereDenseTree via isNowhereDenseTreeFormula :=
  ⟨fun v ↦ by simp [isNowhereDenseTreeFormula, IsNowhereDenseTree]⟩

instance isNowhereDenseTree_definable : ℒₛₑₜ-predicate[V] IsNowhereDenseTree :=
  isNowhereDenseTreeFormula_defined.to_definable

/-- `A` is covered by the bodies of a sequence of nowhere dense trees. -/
def IsMeagre (A : V) : Prop :=
  ∃ f ∈ (℘ (binarySequences V)) ^ (ω : V), (∀ n ∈ (ω : V), IsNowhereDenseTree (f ‘ n)) ∧
    ∀ x ∈ A, ∃ n ∈ (ω : V), x ∈ treeBody (f ‘ n)

instance isMeagreFormula_defined : ℒₛₑₜ-predicate[V] IsMeagre via isMeagreFormula :=
  ⟨fun v ↦ by simp [isMeagreFormula, IsMeagre]⟩

instance isMeagre_definable : ℒₛₑₜ-predicate[V] IsMeagre := isMeagreFormula_defined.to_definable

def IsOpen (U : V) : Prop := ∃ S, S ⊆ binarySequences V ∧ U = openFrom S

instance isOpenFormula_defined : ℒₛₑₜ-predicate[V] IsOpen via isOpenFormula :=
  ⟨fun v ↦ by simp [isOpenFormula, IsOpen]⟩

instance isOpen_definable : ℒₛₑₜ-predicate[V] IsOpen := isOpenFormula_defined.to_definable

/-- `A` differs from an open set by a meagre set. -/
def BaireProperty (A : V) : Prop := ∃ U, IsOpen U ∧ IsMeagre ((A \ U) ∪ (U \ A))

instance bairePropertyFormula_defined : ℒₛₑₜ-predicate[V] BaireProperty via bairePropertyFormula :=
  ⟨fun v ↦ by simp [bairePropertyFormula, BaireProperty]⟩

instance baireProperty_definable : ℒₛₑₜ-predicate[V] BaireProperty :=
  bairePropertyFormula_defined.to_definable

def AllPerfectSetProperty (V : Type*) [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙] : Prop :=
  ∀ A : V, A ⊆ cantorSpace V → PerfectSetProperty A

def AllBaireProperty (V : Type*) [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙] : Prop :=
  ∀ A : V, A ⊆ cantorSpace V → BaireProperty A

instance perfectSetPropertySentence_defined :
    Defined (fun _ : Fin 0 → V ↦ AllPerfectSetProperty V) perfectSetPropertySentence :=
  ⟨fun v ↦ by simp [perfectSetPropertySentence, AllPerfectSetProperty]⟩

instance bairePropertySentence_defined :
    Defined (fun _ : Fin 0 → V ↦ AllBaireProperty V) bairePropertySentence :=
  ⟨fun v ↦ by simp [bairePropertySentence, AllBaireProperty]⟩

end ZFVP
