import ZFVP.SetTheory.CohenAutomorphisms
import ZFVP.SetTheory.FiniteStabilizerFilter
import ZFVP.SetTheory.FiniteSetUnions

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

noncomputable def cohenFilter (I : V) : V := finiteStabilizerFilter (cohenConditions I) (cohenGroup I)

instance cohenFilter_definable : ℒₛₑₜ-function₁[V] cohenFilter := by
  unfold cohenFilter
  definability

theorem cohenFilter_normal (I : V) :
    IsNormalSubgroupFilter (cohenConditions I) (cohenGroup I) (cohenFilter I) :=
  finiteStabilizerFilter_normal (cohenGroup_group I)

theorem cohen_symmetricSystem (I : V) :
    IsSymmetricSystem (cohenConditions I) (cohenOrder I) (cohenGroup I) (cohenFilter I) :=
  ⟨cohen_poset I, ⟨∅, cohen_top I⟩, cohenGroup_group I, cohenFilter_normal I⟩

noncomputable def cohenFamilySupport (E : V) : V := ⋃ˢ (repl cohenSupport (by definability) E)

instance cohenFamilySupport_definable : ℒₛₑₜ-function₁[V] cohenFamilySupport := by
  unfold cohenFamilySupport
  definability

theorem mem_cohenFamilySupport (E i : V) :
    i ∈ cohenFamilySupport E ↔ ∃ p ∈ E, i ∈ cohenSupport p := by
  simp only [cohenFamilySupport, mem_sUnion_iff, repl_spec]
  constructor
  · rintro ⟨S, ⟨p, hp, rfl⟩, hi⟩
    exact ⟨p, hp, hi⟩
  · rintro ⟨p, hp, hi⟩
    exact ⟨cohenSupport p, ⟨p, hp, rfl⟩, hi⟩

theorem cohenFamilySupport_finite {I E : V} (hEP : E ⊆ cohenConditions I)
    (hEf : IsInternallyFinite E) : IsInternallyFinite (cohenFamilySupport E) := by
  apply internallyFinite_sUnion (internallyFinite_repl _ _ hEf)
  intro S hS
  obtain ⟨p, hp, rfl⟩ := (repl_spec (by definability)).mp hS
  exact cohenSupport_finite (hEP p hp)

theorem cohenFamilySupport_subset {I E : V} (hEP : E ⊆ cohenConditions I) : cohenFamilySupport E ⊆ I := by
  intro i hi
  obtain ⟨p, hp, hip⟩ := (mem_cohenFamilySupport E i).mp hi
  exact cohenSupport_subset (hEP p hp) i hip

noncomputable def cohenRowMarker (i : V) : V := {⟨⟨i, (0 : V)⟩ₖ, (0 : V)⟩ₖ}

instance cohenRowMarker_definable : ℒₛₑₜ-function₁[V] cohenRowMarker := by
  unfold cohenRowMarker
  definability

theorem cohenRowMarker_condition {I i : V} (hi : i ∈ I) : cohenRowMarker i ∈ cohenConditions I := by
  have h := cohen_insert (cohen_top I).1 hi (show (0 : V) ∈ ω by simp)
    (show (0 : V) ∈ 2 by simp) (show ⟨i, (0 : V)⟩ₖ ∉ domain (∅ : V) by simp)
  simpa [cohenRowMarker] using h

theorem cohenRowMarker_fix_iff {I π i : V} (hi : i ∈ I) :
    (cohenPermutation I π) ‘ (cohenRowMarker i) = cohenRowMarker i ↔ π ‘ i = i := by
  have hp := cohenRowMarker_condition hi
  rw [cohenPermutation_value hp]
  constructor
  · intro he
    have hm := cohenConditionAction_pair (π := π) hp
      (show ⟨⟨i, (0 : V)⟩ₖ, (0 : V)⟩ₖ ∈ cohenRowMarker i by simp [cohenRowMarker])
    rw [he] at hm
    simpa only [cohenRowMarker, mem_singleton_iff, kpair_iff, and_true] using hm
  · intro he
    apply cohenConditionAction_fix hp
    intro j hj
    obtain ⟨n, b, hb⟩ := (mem_cohenSupport _ _).mp hj
    have hji : j = i := (kpair_iff.mp (kpair_iff.mp (mem_singleton_iff.mp hb)).1).1
    simpa only [hji] using he

/-- This is precisely the normal filter generated by stabilizers of finite sets of rows. -/
theorem mem_cohenFilter_iff (I H : V) : H ∈ cohenFilter I ↔
    IsForcingSubgroup (cohenConditions I) (cohenGroup I) H ∧
      ∃ E, E ⊆ I ∧ IsInternallyFinite E ∧
        ∀ π, IsInternalPermutation I π → (∀ i ∈ E, π ‘ i = i) → cohenPermutation I π ∈ H := by
  rw [show cohenFilter I = finiteStabilizerFilter (cohenConditions I) (cohenGroup I) from rfl,
    mem_finiteStabilizerFilter]
  constructor
  · rintro ⟨hHs, E, hEP, hEf, hEH⟩
    refine ⟨hHs, cohenFamilySupport E, cohenFamilySupport_subset hEP,
      cohenFamilySupport_finite hEP hEf, ?_⟩
    intro π hπ hfix
    apply hEH
    refine (mem_pointwiseStabilizer _ _ _).mpr
      ⟨(mem_cohenGroup I _).mpr ⟨π, hπ, rfl⟩, ?_⟩
    intro p hp
    rw [cohenPermutation_value (hEP p hp)]
    exact cohenConditionAction_fix (hEP p hp)
      (fun i hi ↦ hfix i ((mem_cohenFamilySupport E i).mpr ⟨p, hp, hi⟩))
  · rintro ⟨hHs, E, hEI, hEf, hEH⟩
    refine ⟨hHs, repl cohenRowMarker (by definability) E, ?_, internallyFinite_repl _ _ hEf, ?_⟩
    · intro p hp
      obtain ⟨i, hi, rfl⟩ := (repl_spec (by definability)).mp hp
      exact cohenRowMarker_condition (hEI i hi)
    · intro σ hσ
      obtain ⟨hσG, hσE⟩ := (mem_pointwiseStabilizer _ _ _).mp hσ
      obtain ⟨π, hπ, rfl⟩ := (mem_cohenGroup I σ).mp hσG
      apply hEH π hπ
      intro i hi
      exact (cohenRowMarker_fix_iff (hEI i hi)).mp
        (hσE _ ((repl_spec (by definability)).mpr ⟨i, hi, rfl⟩))

end ZFVP
