import ZFVP.SetTheory.FiniteStabilizerFilter
import ZFVP.SetTheory.CountableSets

/-! The normal filter generated by pointwise stabilizers of internal countable sets.
Under countable choice it is closed under countable intersections. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

noncomputable def countableStabilizerFilter (P Γ : V) : V :=
  {H ∈ ℘ Γ ; IsForcingSubgroup P Γ H ∧
    ∃ E ∈ ℘ P, IsInternallyCountable E ∧ pointwiseStabilizer Γ E ⊆ H}

theorem mem_countableStabilizerFilter (P Γ H : V) :
    H ∈ countableStabilizerFilter P Γ ↔ IsForcingSubgroup P Γ H ∧
      ∃ E, E ⊆ P ∧ IsInternallyCountable E ∧ pointwiseStabilizer Γ E ⊆ H := by
  simp only [countableStabilizerFilter, mem_sep_iff, mem_power_iff]
  exact ⟨fun h ↦ h.2, fun h ↦ ⟨h.1.1, h⟩⟩

instance countableStabilizerFilter_definable : ℒₛₑₜ-function₂[V] countableStabilizerFilter := by
  have h : ℒₛₑₜ-relation₃[V] (fun F P Γ ↦ ∀ H, H ∈ F ↔ IsForcingSubgroup P Γ H ∧
      ∃ E, E ⊆ P ∧ IsInternallyCountable E ∧ pointwiseStabilizer Γ E ⊆ H) := by definability
  apply Language.Definable.of_iff h
  intro v
  change v 0 = countableStabilizerFilter (v 1) (v 2) ↔ _
  rw [mem_ext_iff]
  simp only [mem_countableStabilizerFilter]

theorem countableStabilizerFilter_normal {P R Γ : V} (hΓ : IsForcingAutomorphismGroup P R Γ) :
    IsNormalSubgroupFilter P Γ (countableStabilizerFilter P Γ) := by
  refine ⟨fun H hH ↦ ((mem_countableStabilizerFilter P Γ H).mp hH).1, ?_, ?_, ?_, ?_⟩
  · exact (mem_countableStabilizerFilter P Γ Γ).mpr
      ⟨forcingGroup_subgroup_self hΓ, ∅, by simp, internallyCountable_empty,
        fun π hπ ↦ ((mem_pointwiseStabilizer _ _ _).mp hπ).1⟩
  · intro H hH K hK hHK
    obtain ⟨_, E, hEP, hEc, hEH⟩ := (mem_countableStabilizerFilter P Γ H).mp hH
    exact (mem_countableStabilizerFilter P Γ K).mpr ⟨hK, E, hEP, hEc, subset_trans hEH hHK⟩
  · intro H hH K hK
    obtain ⟨hHs, E, hEP, hEc, hEH⟩ := (mem_countableStabilizerFilter P Γ H).mp hH
    obtain ⟨hKs, D, hDP, hDc, hDK⟩ := (mem_countableStabilizerFilter P Γ K).mp hK
    refine (mem_countableStabilizerFilter P Γ _).mpr
      ⟨forcingSubgroup_inter hHs hKs, E ∪ D, ?_, internallyCountable_union hEc hDc, ?_⟩
    · intro p hp
      exact (mem_union_iff.mp hp).elim (hEP p) (hDP p)
    · rw [pointwiseStabilizer_union]
      intro π hπ
      exact mem_inter_iff.mpr ⟨hEH _ (mem_inter_iff.mp hπ).1, hDK _ (mem_inter_iff.mp hπ).2⟩
  · intro π hπ H hH
    obtain ⟨hHs, E, hEP, hEc, hEH⟩ := (mem_countableStabilizerFilter P Γ H).mp hH
    refine (mem_countableStabilizerFilter P Γ _).mpr
      ⟨conjugateSubgroup_subgroup hΓ hπ hHs, repl (fun p ↦ π ‘ p) (by definability) E,
        ?_, internallyCountable_repl _ _ hEc, pointwiseStabilizer_conjugate_subset hΓ hπ hEP hEH⟩
    intro q hq
    obtain ⟨p, hp, rfl⟩ := (repl_spec (by definability)).mp hq
    exact function_value_mem (hΓ.1 _ hπ).1 (hEP p hp)

/-- Countably many members of the filter have their intersection in the filter: choose a
countable support for each member and take the countable union. -/
theorem countableStabilizerFilter_countable_inter {P Γ : V} (hCC : InternalCountableChoice V)
    {H : V} [IsFunction H] (hd : domain H = (ω : V))
    (hH : ∀ n ∈ (ω : V), H ‘ n ∈ countableStabilizerFilter P Γ) :
    ⋂ˢ range H ∈ countableStabilizerFilter P Γ := by
  have h0 : (0 : V) ∈ domain H := by rw [hd]; simp
  have hne : IsNonempty (range H) := ⟨H ‘ 0, mem_range_of_kpair_mem (kpair_value_mem h0)⟩
  have hmem (n : V) (hn : n ∈ (ω : V)) : H ‘ n ∈ range H :=
    mem_range_of_kpair_mem (kpair_value_mem (show n ∈ domain H from hd.symm ▸ hn))
  have hsub (K : V) (hK : K ∈ range H) : IsForcingSubgroup P Γ K ∧
      ∃ E, E ⊆ P ∧ IsInternallyCountable E ∧ pointwiseStabilizer Γ E ⊆ K := by
    obtain ⟨n, hnK⟩ := mem_range_iff.mp hK
    have hn : n ∈ (ω : V) := hd ▸ mem_domain_of_kpair_mem hnK
    rw [← value_eq_of_kpair_mem hnK]
    exact (mem_countableStabilizerFilter P Γ _).mp (hH n hn)
  -- the intersection is a subgroup
  have hgroup : IsForcingSubgroup P Γ (⋂ˢ range H) := by
    refine ⟨?_, ?_, ?_, ?_⟩
    · intro π hπ
      exact (hsub _ (hmem 0 (by simp))).1.1 π
        ((mem_sInter_iff_of_nonempty).mp hπ _ (hmem 0 (by simp)))
    · exact mem_sInter_iff_of_nonempty.mpr fun K hK ↦ (hsub K hK).1.2.1
    · intro π hπ ρ hρ
      exact mem_sInter_iff_of_nonempty.mpr fun K hK ↦ (hsub K hK).1.2.2.1 π
        (mem_sInter_iff_of_nonempty.mp hπ K hK) ρ (mem_sInter_iff_of_nonempty.mp hρ K hK)
    · intro π hπ
      exact mem_sInter_iff_of_nonempty.mpr fun K hK ↦ (hsub K hK).1.2.2.2 π
        (mem_sInter_iff_of_nonempty.mp hπ K hK)
  -- choose supports
  let B : V → V := fun n ↦ {E ∈ ℘ P ; IsInternallyCountable E ∧ pointwiseStabilizer Γ E ⊆ H ‘ n}
  have hB : ℒₛₑₜ-function₁ B := by
    have h : ℒₛₑₜ-relation (fun S n : V ↦ ∀ E, E ∈ S ↔
        E ⊆ P ∧ IsInternallyCountable E ∧ pointwiseStabilizer Γ E ⊆ H ‘ n) := by
      definability
    apply Language.Definable.of_iff h
    intro v
    rw [mem_ext_iff]
    simp [B]
  let b := definableGraph (ω : V) B hB
  have hb (n : V) (hn : n ∈ (ω : V)) : b ‘ n = B n := value_definableGraph _ _ _ hn
  have hnB : ∀ n ∈ (ω : V), IsNonempty (b ‘ n) := by
    intro n hn
    obtain ⟨_, E, hEP, hEc, hEH⟩ := (mem_countableStabilizerFilter P Γ _).mp (hH n hn)
    rw [hb n hn]
    exact ⟨E, mem_sep_iff.mpr ⟨mem_power_iff.mpr hEP, hEc, hEH⟩⟩
  obtain ⟨g, hg, hval⟩ := hCC b (definableGraph_isFunction _ _ _) (domain_definableGraph _ _ _) hnB
  let := IsFunction.of_mem hg
  have hdg : domain g = (ω : V) := domain_eq_of_mem_function hg
  have hgn (n : V) (hn : n ∈ (ω : V)) : g ‘ n ⊆ P ∧ IsInternallyCountable (g ‘ n) ∧
      pointwiseStabilizer Γ (g ‘ n) ⊆ H ‘ n := by
    have hm := hval n hn
    rw [hb n hn] at hm
    obtain ⟨hP, hc, hs⟩ := mem_sep_iff.mp hm
    exact ⟨mem_power_iff.mp hP, hc, hs⟩
  refine (mem_countableStabilizerFilter P Γ _).mpr ⟨hgroup, ⋃ˢ range g, ?_, ?_, ?_⟩
  · intro p hp
    obtain ⟨E, hE, hpE⟩ := mem_sUnion_iff.mp hp
    obtain ⟨n, hnE⟩ := mem_range_iff.mp hE
    have hn : n ∈ (ω : V) := hdg ▸ mem_domain_of_kpair_mem hnE
    rw [← value_eq_of_kpair_mem hnE] at hpE
    exact (hgn n hn).1 p hpE
  · exact countable_union_of_countableChoice hCC hdg fun n hn ↦ (hgn n hn).2.1
  · intro π hπ
    obtain ⟨hπΓ, hπE⟩ := (mem_pointwiseStabilizer _ _ _).mp hπ
    apply mem_sInter_iff_of_nonempty.mpr
    intro K hK
    obtain ⟨n, hnK⟩ := mem_range_iff.mp hK
    have hn : n ∈ (ω : V) := hd ▸ mem_domain_of_kpair_mem hnK
    rw [← value_eq_of_kpair_mem hnK]
    apply (hgn n hn).2.2
    refine (mem_pointwiseStabilizer _ _ _).mpr ⟨hπΓ, ?_⟩
    intro p hp
    exact hπE p (mem_sUnion_iff.mpr ⟨g ‘ n, mem_range_of_kpair_mem
      (kpair_value_mem (show n ∈ domain g from hdg.symm ▸ hn)), hp⟩)

end ZFVP
