import ZFVP.SetTheory.CountableCohenForcing
import ZFVP.SetTheory.CountableStabilizerFilter
import ZFVP.SetTheory.CohenSymmetricSystem

/-! The countable-support Cohen symmetric system: the normal filter generated by
pointwise stabilizers of countable sets of conditions, and its description through
countable sets of rows. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-- Under countable choice a countable family of countable sets has countable union. -/
theorem internallyCountable_sUnion_of_countable (hCC : InternalCountableChoice V) {A : V}
    (hA : IsInternallyCountable A) (h : ∀ x ∈ A, IsInternallyCountable x) :
    IsInternallyCountable (⋃ˢ A) := by
  classical
  by_cases hne : IsNonempty A
  · obtain ⟨a₀, ha₀⟩ := hne
    obtain ⟨e, he, hei⟩ := hA
    let := IsFunction.of_mem he
    let F : V → V := fun n ↦ if n ∈ range e then (converseGraph e) ‘ n else a₀
    have hF : ℒₛₑₜ-function₁ F := by
      have hr : ℒₛₑₜ-relation (fun x n : V ↦
          (n ∈ range e ∧ x = (converseGraph e) ‘ n) ∨ (n ∉ range e ∧ x = a₀)) := by definability
      apply Language.Definable.of_iff hr
      intro v
      change v 0 = F (v 1) ↔ _
      unfold F
      split <;> simp_all
    let C := definableGraph (ω : V) F hF
    have hdC : domain C = (ω : V) := domain_definableGraph _ _ _
    have hce := converseGraph_mem_function he hei
    have hCval (n : V) (hn : n ∈ (ω : V)) : C ‘ n ∈ A := by
      rw [value_definableGraph _ _ _ hn]
      dsimp only [F]
      split_ifs with hnr
      · exact function_value_mem hce hnr
      · exact ha₀
    have hCsurj (x : V) (hx : x ∈ A) : ∃ n ∈ (ω : V), C ‘ n = x := by
      have hex : e ‘ x ∈ range e := value_mem_range he hx
      refine ⟨e ‘ x, function_value_mem he hx, ?_⟩
      rw [value_definableGraph _ _ _ (function_value_mem he hx)]
      dsimp only [F]
      rw [if_pos hex]
      exact converseGraph_value_value he hei hx
    have hre : ⋃ˢ range C = ⋃ˢ A := by
      apply mem_ext
      intro z
      simp only [mem_sUnion_iff]
      constructor
      · rintro ⟨X, hX, hz⟩
        obtain ⟨n, hnX⟩ := mem_range_iff.mp hX
        have hn : n ∈ (ω : V) := hdC ▸ mem_domain_of_kpair_mem hnX
        rw [← value_eq_of_kpair_mem hnX] at hz
        exact ⟨C ‘ n, hCval n hn, hz⟩
      · rintro ⟨X, hX, hz⟩
        obtain ⟨n, hn, rfl⟩ := hCsurj X hX
        exact ⟨C ‘ n, mem_range_of_kpair_mem (kpair_value_mem
          (show n ∈ domain C from hdC.symm ▸ hn)), hz⟩
    let := IsFunction.of_mem (definableGraph_mem_function (ω : V) F hF)
    rw [← hre]
    exact countable_union_of_countableChoice hCC hdC fun n hn ↦ h _ (hCval n hn)
  · have hA0 : A = ∅ := by
      ext x
      constructor
      · intro hx
        exact absurd ⟨x, hx⟩ hne
      · intro hx
        exact (not_mem_empty hx).elim
    rw [hA0]
    simpa using (internallyCountable_empty (V := V))

noncomputable def countableCohenFilter (I J : V) : V :=
  countableStabilizerFilter (countableCohenConditions I J) (countableCohenGroup I J)

instance countableCohenFilter_definable : ℒₛₑₜ-function₂[V] countableCohenFilter := by
  unfold countableCohenFilter
  definability

theorem countableCohenFilter_normal (I J : V) :
    IsNormalSubgroupFilter (countableCohenConditions I J) (countableCohenGroup I J)
      (countableCohenFilter I J) :=
  countableStabilizerFilter_normal (countableCohenGroup_group I J)

theorem countableCohen_symmetricSystem (I J : V) :
    IsSymmetricSystem (countableCohenConditions I J) (countableCohenOrder I J)
      (countableCohenGroup I J) (countableCohenFilter I J) :=
  ⟨countableCohen_poset I J, ⟨∅, countableCohen_top I J⟩, countableCohenGroup_group I J,
    countableCohenFilter_normal I J⟩

theorem countableCohenFamilySupport_countable (hCC : InternalCountableChoice V) {I J E : V}
    (hEP : E ⊆ countableCohenConditions I J) (hEc : IsInternallyCountable E) :
    IsInternallyCountable (cohenFamilySupport E) := by
  apply internallyCountable_sUnion_of_countable hCC (internallyCountable_repl _ _ hEc)
  intro S hS
  obtain ⟨p, hp, rfl⟩ := (repl_spec (by definability)).mp hS
  exact countableCohenSupport_countable (hEP p hp)

theorem countableCohenFamilySupport_subset {I J E : V} (hEP : E ⊆ countableCohenConditions I J) :
    cohenFamilySupport E ⊆ I := by
  intro i hi
  obtain ⟨p, hp, hip⟩ := (mem_cohenFamilySupport E i).mp hi
  exact countableCohenSupport_subset (hEP p hp) i hip

theorem countableCohenRowMarker_condition {I J i : V} (hi : i ∈ I) (h0 : (0 : V) ∈ J) :
    cohenRowMarker i ∈ countableCohenConditions I J := by
  have h := countableCohen_insert (empty_mem_countablePartialFunctions (I ×ˢ J) 2) hi h0
    (show (0 : V) ∈ 2 by simp) (show ⟨i, (0 : V)⟩ₖ ∉ domain (∅ : V) by simp)
  simpa [cohenRowMarker] using h

theorem countableCohenRowMarker_fix_iff {I J π i : V} (hi : i ∈ I) (h0 : (0 : V) ∈ J) :
    (countableCohenPermutation I J π) ‘ (cohenRowMarker i) = cohenRowMarker i ↔ π ‘ i = i := by
  have hp := countableCohenRowMarker_condition (J := J) hi h0
  rw [countableCohenPermutation_value hp]
  constructor
  · intro he
    have hm := countableCohenConditionAction_pair (π := π) hp
      (show ⟨⟨i, (0 : V)⟩ₖ, (0 : V)⟩ₖ ∈ cohenRowMarker i by simp [cohenRowMarker])
    rw [he] at hm
    simpa only [cohenRowMarker, mem_singleton_iff, kpair_iff, and_true] using hm
  · intro he
    apply countableCohenConditionAction_fix hp
    intro j hj
    obtain ⟨n, b, hb⟩ := (mem_cohenSupport _ _).mp hj
    have hji : j = i := (kpair_iff.mp (kpair_iff.mp (mem_singleton_iff.mp hb)).1).1
    simpa only [hji] using he

/-- A subgroup containing every permutation fixing a countable set of rows is in the filter. -/
theorem countableCohenFilter_of_rows {I J H E : V} (h0 : (0 : V) ∈ J)
    (hHs : IsForcingSubgroup (countableCohenConditions I J) (countableCohenGroup I J) H)
    (hEI : E ⊆ I) (hEc : IsInternallyCountable E)
    (hEH : ∀ π, IsInternalPermutation I π → (∀ i ∈ E, π ‘ i = i) →
      countableCohenPermutation I J π ∈ H) :
    H ∈ countableCohenFilter I J := by
  rw [show countableCohenFilter I J =
    countableStabilizerFilter (countableCohenConditions I J) (countableCohenGroup I J) from rfl,
    mem_countableStabilizerFilter]
  refine ⟨hHs, repl cohenRowMarker (by definability) E, ?_, internallyCountable_repl _ _ hEc, ?_⟩
  · intro p hp
    obtain ⟨i, hi, rfl⟩ := (repl_spec (by definability)).mp hp
    exact countableCohenRowMarker_condition (hEI i hi) h0
  · intro σ hσ
    obtain ⟨hσG, hσE⟩ := (mem_pointwiseStabilizer _ _ _).mp hσ
    obtain ⟨π, hπ, rfl⟩ := (mem_countableCohenGroup I J σ).mp hσG
    apply hEH π hπ
    intro i hi
    exact (countableCohenRowMarker_fix_iff (hEI i hi) h0).mp
      (hσE _ ((repl_spec (by definability)).mpr ⟨i, hi, rfl⟩))

/-- Every member of the filter contains all permutations fixing some countable set of rows. -/
theorem countableCohenFilter_rows (hCC : InternalCountableChoice V) {I J H : V}
    (hH : H ∈ countableCohenFilter I J) :
    ∃ E, E ⊆ I ∧ IsInternallyCountable E ∧
      ∀ π, IsInternalPermutation I π → (∀ i ∈ E, π ‘ i = i) →
        countableCohenPermutation I J π ∈ H := by
  rw [show countableCohenFilter I J =
    countableStabilizerFilter (countableCohenConditions I J) (countableCohenGroup I J) from rfl,
    mem_countableStabilizerFilter] at hH
  obtain ⟨_, E, hEP, hEc, hEH⟩ := hH
  refine ⟨cohenFamilySupport E, countableCohenFamilySupport_subset hEP,
    countableCohenFamilySupport_countable hCC hEP hEc, ?_⟩
  intro π hπ hfix
  apply hEH
  refine (mem_pointwiseStabilizer _ _ _).mpr
    ⟨(mem_countableCohenGroup I J _).mpr ⟨π, hπ, rfl⟩, ?_⟩
  intro p hp
  rw [countableCohenPermutation_value (hEP p hp)]
  exact countableCohenConditionAction_fix (hEP p hp)
    (fun i hi ↦ hfix i ((mem_cohenFamilySupport E i).mpr ⟨p, hp, hi⟩))

end ZFVP
