import ZFVP.SetTheory.FefermanLevyAutomorphisms
import ZFVP.SetTheory.FiniteStabilizerFilter

/-! The normal filter generated by the pointwise stabilizers of the stages: a subgroup is
in the filter when it contains every automorphism fixing all conditions of some stage. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

noncomputable def flFilter (V : Type*) [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙] : V :=
  {H ∈ ℘ (flGroup V) ; IsForcingSubgroup (flConditions V) (flGroup V) H ∧
    ∃ n ∈ (ω : V), pointwiseStabilizer (flGroup V) (flStage n) ⊆ H}

theorem mem_flFilter (H : V) : H ∈ flFilter V ↔ IsForcingSubgroup (flConditions V) (flGroup V) H ∧
    ∃ n ∈ (ω : V), pointwiseStabilizer (flGroup V) (flStage n) ⊆ H := by
  simp only [flFilter, mem_sep_iff, mem_power_iff]
  exact ⟨fun h ↦ h.2, fun h ↦ ⟨h.1.1, h⟩⟩

theorem flPermutation_mem_stabilizer {n π : V} (hn : n ∈ (ω : V)) (hπ : IsColumnPermutation π)
    (hfix : FixesColumnsBelow n π) :
    flPermutation π ∈ pointwiseStabilizer (flGroup V) (flStage n) :=
  (mem_pointwiseStabilizer _ _ _).mpr ⟨(mem_flGroup _).mpr ⟨π, hπ, rfl⟩,
    fun _ hp ↦ flPermutation_fixed_of_columns (IsOrdinal.toIsTransitive.transitive n hn) hfix hp⟩

theorem stabilizer_antitone {n n' : V} (h : n ⊆ n') :
    pointwiseStabilizer (flGroup V) (flStage n') ⊆ pointwiseStabilizer (flGroup V) (flStage n) := by
  intro σ hσ
  obtain ⟨hσG, hσfix⟩ := (mem_pointwiseStabilizer _ _ _).mp hσ
  exact (mem_pointwiseStabilizer _ _ _).mpr ⟨hσG, fun p hp ↦ hσfix p (flStage_mono h p hp)⟩

theorem flFilter_normal : IsNormalSubgroupFilter (flConditions V) (flGroup V) (flFilter V) := by
  have hΓ := flGroup_group (V := V)
  refine ⟨fun H hH ↦ ((mem_flFilter H).mp hH).1, ?_, ?_, ?_, ?_⟩
  · exact (mem_flFilter _).mpr ⟨forcingGroup_subgroup_self hΓ, 0, by simp,
      fun σ hσ ↦ ((mem_pointwiseStabilizer _ _ _).mp hσ).1⟩
  · intro H hH K hK hHK
    obtain ⟨_, n, hn, hnH⟩ := (mem_flFilter H).mp hH
    exact (mem_flFilter K).mpr ⟨hK, n, hn, subset_trans hnH hHK⟩
  · intro H hH K hK
    obtain ⟨hHs, n, hn, hnH⟩ := (mem_flFilter H).mp hH
    obtain ⟨hKs, n', hn', hnK⟩ := (mem_flFilter K).mp hK
    have hno : IsOrdinal n := IsOrdinal.of_mem hn
    have hn'o : IsOrdinal n' := IsOrdinal.of_mem hn'
    refine (mem_flFilter _).mpr ⟨forcingSubgroup_inter hHs hKs, n ∪ n', ?_, ?_⟩
    · rcases IsOrdinal.mem_trichotomy (α := n) (β := n') with h | h | h
      · rw [show n ∪ n' = n' from SetTheory.subset_antisymm
          (fun x hx ↦ (mem_union_iff.mp hx).elim (fun hx ↦ IsOrdinal.toIsTransitive.mem_trans hx h) id)
          (fun x hx ↦ mem_union_iff.mpr (Or.inr hx))]
        exact hn'
      · rw [h, show n' ∪ n' = n' from SetTheory.subset_antisymm
          (fun x hx ↦ (mem_union_iff.mp hx).elim id id) (fun x hx ↦ mem_union_iff.mpr (Or.inl hx))]
        exact hn'
      · rw [show n ∪ n' = n from SetTheory.subset_antisymm
          (fun x hx ↦ (mem_union_iff.mp hx).elim id (fun hx ↦ IsOrdinal.toIsTransitive.mem_trans hx h))
          (fun x hx ↦ mem_union_iff.mpr (Or.inl hx))]
        exact hn
    · intro σ hσ
      exact mem_inter_iff.mpr ⟨hnH _ (stabilizer_antitone (fun x hx ↦ mem_union_iff.mpr (Or.inl hx)) _ hσ),
        hnK _ (stabilizer_antitone (fun x hx ↦ mem_union_iff.mpr (Or.inr hx)) _ hσ)⟩
  · intro σ hσ H hH
    obtain ⟨hHs, n, hn, hnH⟩ := (mem_flFilter H).mp hH
    refine (mem_flFilter _).mpr ⟨conjugateSubgroup_subgroup hΓ hσ hHs, n, hn, ?_⟩
    have hsub := pointwiseStabilizer_conjugate_subset hΓ hσ
      (flStage_subset hn) hnH
    rwa [flGroup_stage_image (IsOrdinal.toIsTransitive.transitive n hn) hσ] at hsub

theorem fl_symmetricSystem :
    IsSymmetricSystem (flConditions V) (flOrder V) (flGroup V) (flFilter V) :=
  ⟨fl_poset, ⟨∅, fl_top⟩, flGroup_group, flFilter_normal⟩

/-- Every member of the filter contains all column permutations fixing some stage. -/
theorem flFilter_support {H : V} (hH : H ∈ flFilter V) :
    ∃ n ∈ (ω : V), ∀ π, IsColumnPermutation π → FixesColumnsBelow n π → flPermutation π ∈ H := by
  obtain ⟨_, n, hn, hnH⟩ := (mem_flFilter H).mp hH
  exact ⟨n, hn, fun π hπ hfix ↦ hnH _ (flPermutation_mem_stabilizer hn hπ hfix)⟩

end ZFVP
