import ZFVP.SetTheory.ForcingConjugation
import ZFVP.SetTheory.FiniteSets

/-! The normal filter generated by pointwise stabilizers of internal finite sets. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

noncomputable def pointwiseStabilizer (Γ E : V) : V := {π ∈ Γ ; ∀ p ∈ E, π ‘ p = p}

theorem mem_pointwiseStabilizer (Γ E π : V) :
    π ∈ pointwiseStabilizer Γ E ↔ π ∈ Γ ∧ ∀ p ∈ E, π ‘ p = p := mem_sep_iff

instance pointwiseStabilizer_definable : ℒₛₑₜ-function₂[V] pointwiseStabilizer := by
  have h : ℒₛₑₜ-relation₃[V] (fun H Γ E ↦ ∀ π, π ∈ H ↔ π ∈ Γ ∧ ∀ p ∈ E, π ‘ p = p) := by definability
  apply Language.Definable.of_iff h
  intro v
  change v 0 = pointwiseStabilizer (v 1) (v 2) ↔ _
  rw [mem_ext_iff]
  simp only [mem_pointwiseStabilizer]

theorem pointwiseStabilizer_subgroup {P R Γ E : V}
    (hΓ : IsForcingAutomorphismGroup P R Γ) (hE : E ⊆ P) :
    IsForcingSubgroup P Γ (pointwiseStabilizer Γ E) := by
  refine ⟨fun π hπ ↦ (mem_pointwiseStabilizer Γ E π).mp hπ |>.1,
    (mem_pointwiseStabilizer Γ E _).mpr ⟨hΓ.2.1, fun p hp ↦ identity_value (hE p hp)⟩, ?_, ?_⟩
  · intro π hπ ρ hρ
    obtain ⟨hπΓ, hπE⟩ := (mem_pointwiseStabilizer Γ E π).mp hπ
    obtain ⟨hρΓ, hρE⟩ := (mem_pointwiseStabilizer Γ E ρ).mp hρ
    refine (mem_pointwiseStabilizer Γ E _).mpr ⟨hΓ.2.2.1 _ hπΓ _ hρΓ, ?_⟩
    intro p hp
    rw [value_compose_of_mem_function (hΓ.1 _ hπΓ).1 (hΓ.1 _ hρΓ).1 (hE p hp), hπE p hp, hρE p hp]
  · intro π hπ
    obtain ⟨hπΓ, hπE⟩ := (mem_pointwiseStabilizer Γ E π).mp hπ
    refine (mem_pointwiseStabilizer Γ E _).mpr ⟨hΓ.2.2.2 _ hπΓ, ?_⟩
    intro p hp
    calc
      (converseGraph π) ‘ p = (converseGraph π) ‘ (π ‘ p) := congrArg _ (hπE p hp).symm
      _ = p := converseGraph_value_value (hΓ.1 _ hπΓ).1 (hΓ.1 _ hπΓ).2.1 (hE p hp)

theorem pointwiseStabilizer_union (Γ E K : V) :
    pointwiseStabilizer Γ (E ∪ K) = pointwiseStabilizer Γ E ∩ pointwiseStabilizer Γ K := by
  ext π
  simp only [mem_pointwiseStabilizer, mem_union_iff, mem_inter_iff]
  constructor
  · rintro ⟨hg, hf⟩
    exact ⟨⟨hg, fun p hp ↦ hf p (Or.inl hp)⟩, hg, fun p hp ↦ hf p (Or.inr hp)⟩
  · rintro ⟨⟨hg, he⟩, _, hk⟩
    exact ⟨hg, fun p hp ↦ hp.elim (he p) (hk p)⟩

theorem pointwiseStabilizer_conjugate_subset {P R Γ E π H : V}
    (hΓ : IsForcingAutomorphismGroup P R Γ) (hπ : π ∈ Γ) (hE : E ⊆ P)
    (hEH : pointwiseStabilizer Γ E ⊆ H) :
    pointwiseStabilizer Γ (repl (fun p ↦ π ‘ p) (by definability) E) ⊆ conjugateSubgroup π H := by
  intro θ hθ
  obtain ⟨hθΓ, hθE⟩ := (mem_pointwiseStabilizer _ _ _).mp hθ
  have ha := hΓ.1 _ hπ
  have hb := hΓ.1 _ hθΓ
  have hi := forcingAutomorphism_inverse ha
  have : IsFunction π := IsFunction.of_mem ha.1
  let ρ := conjugatePermutation (converseGraph π) θ
  have hρΓ : ρ ∈ Γ := by
    unfold ρ conjugatePermutation
    exact hΓ.2.2.1 _ (hΓ.2.2.1 _ (hΓ.2.2.2 _ (hΓ.2.2.2 _ hπ)) _ hθΓ) _ (hΓ.2.2.2 _ hπ)
  have hρE : ∀ p ∈ E, ρ ‘ p = p := by
    intro p hp
    have hp' : π ‘ p ∈ repl (fun p ↦ π ‘ p) (by definability) E :=
      (repl_spec (by definability)).mpr ⟨p, hp, rfl⟩
    rw [show ρ = conjugatePermutation (converseGraph π) θ from rfl,
      conjugatePermutation_value hi hb (hE p hp), converseGraph_involutive, hθE _ hp',
      converseGraph_value_value ha.1 ha.2.1 (hE p hp)]
  exact (mem_conjugateSubgroup π H θ).mpr
    ⟨ρ, hEH _ ((mem_pointwiseStabilizer _ _ _).mpr ⟨hρΓ, hρE⟩),
      (conjugatePermutation_cancel_inverse ha hb).symm⟩

noncomputable def finiteStabilizerFilter (P Γ : V) : V :=
  {H ∈ ℘ Γ ; IsForcingSubgroup P Γ H ∧
    ∃ E ∈ ℘ P, IsInternallyFinite E ∧ pointwiseStabilizer Γ E ⊆ H}

theorem mem_finiteStabilizerFilter (P Γ H : V) :
    H ∈ finiteStabilizerFilter P Γ ↔ IsForcingSubgroup P Γ H ∧
      ∃ E, E ⊆ P ∧ IsInternallyFinite E ∧ pointwiseStabilizer Γ E ⊆ H := by
  simp only [finiteStabilizerFilter, mem_sep_iff, mem_power_iff]
  exact ⟨fun h ↦ h.2, fun h ↦ ⟨h.1.1, h⟩⟩

instance finiteStabilizerFilter_definable : ℒₛₑₜ-function₂[V] finiteStabilizerFilter := by
  have h : ℒₛₑₜ-relation₃[V] (fun F P Γ ↦ ∀ H, H ∈ F ↔ IsForcingSubgroup P Γ H ∧
      ∃ E, E ⊆ P ∧ IsInternallyFinite E ∧ pointwiseStabilizer Γ E ⊆ H) := by definability
  apply Language.Definable.of_iff h
  intro v
  change v 0 = finiteStabilizerFilter (v 1) (v 2) ↔ _
  rw [mem_ext_iff]
  simp only [mem_finiteStabilizerFilter]

theorem finiteStabilizerFilter_normal {P R Γ : V} (hΓ : IsForcingAutomorphismGroup P R Γ) :
    IsNormalSubgroupFilter P Γ (finiteStabilizerFilter P Γ) := by
  refine ⟨fun H hH ↦ ((mem_finiteStabilizerFilter P Γ H).mp hH).1, ?_, ?_, ?_, ?_⟩
  · exact (mem_finiteStabilizerFilter P Γ Γ).mpr
      ⟨forcingGroup_subgroup_self hΓ, ∅, by simp, internallyFinite_empty,
        fun π hπ ↦ ((mem_pointwiseStabilizer _ _ _).mp hπ).1⟩
  · intro H hH K hK hHK
    obtain ⟨_, E, hEP, hEf, hEH⟩ := (mem_finiteStabilizerFilter P Γ H).mp hH
    exact (mem_finiteStabilizerFilter P Γ K).mpr ⟨hK, E, hEP, hEf, subset_trans hEH hHK⟩
  · intro H hH K hK
    obtain ⟨hHs, E, hEP, hEf, hEH⟩ := (mem_finiteStabilizerFilter P Γ H).mp hH
    obtain ⟨hKs, D, hDP, hDf, hDK⟩ := (mem_finiteStabilizerFilter P Γ K).mp hK
    refine (mem_finiteStabilizerFilter P Γ _).mpr
      ⟨forcingSubgroup_inter hHs hKs, E ∪ D, ?_, internallyFinite_union hEf hDf, ?_⟩
    · intro p hp
      exact (mem_union_iff.mp hp).elim (hEP p) (hDP p)
    · rw [pointwiseStabilizer_union]
      intro π hπ
      exact mem_inter_iff.mpr ⟨hEH _ (mem_inter_iff.mp hπ).1, hDK _ (mem_inter_iff.mp hπ).2⟩
  · intro π hπ H hH
    obtain ⟨hHs, E, hEP, hEf, hEH⟩ := (mem_finiteStabilizerFilter P Γ H).mp hH
    refine (mem_finiteStabilizerFilter P Γ _).mpr
      ⟨conjugateSubgroup_subgroup hΓ hπ hHs, repl (fun p ↦ π ‘ p) (by definability) E,
        ?_, internallyFinite_repl _ _ hEf, pointwiseStabilizer_conjugate_subset hΓ hπ hEP hEH⟩
    intro q hq
    obtain ⟨p, hp, rfl⟩ := (repl_spec (by definability)).mp hq
    exact function_value_mem (hΓ.1 _ hπ).1 (hEP p hp)

end ZFVP
