import ZFVP.SetTheory.ForcingInverseLimit

namespace ZFVP
open LO LO.FirstOrder LO.FirstOrder.SetTheory
variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-- A thread is generated by its coordinate at `k` using the system sections. -/
def IsThreadSupport (θ E f k : V) : Prop :=
  k ∈ θ ∧ ∀ j ∈ θ, k ⊆ j → f ‘ j = (E ‘ ⟨k, j⟩ₖ) ‘ (f ‘ k)

instance isThreadSupport_definable : ℒₛₑₜ-relation₄[V] IsThreadSupport := by
  unfold IsThreadSupport
  definability

/-- The direct limit consists of coherent threads eventually given by sections. -/
noncomputable def forcingDirectLimit (θ P π E U : V) : V :=
  {f ∈ forcingInverseLimit θ P π U ; ∃ k, IsThreadSupport θ E f k}

theorem mem_forcingDirectLimit_iff (θ P π E U f : V) :
    f ∈ forcingDirectLimit θ P π E U ↔
      f ∈ forcingInverseLimit θ P π U ∧ ∃ k, IsThreadSupport θ E f k := mem_sep_iff

theorem forcingDirectLimit_subset (θ P π E U : V) :
    forcingDirectLimit θ P π E U ⊆ forcingInverseLimit θ P π U := sep_subset

theorem forcingDirectLimit_preorder {θ P R π E U : V}
    (hR : ∀ i ∈ θ, IsForcingPreorder (P ‘ i) (R ‘ i)) :
    IsForcingPreorder (forcingDirectLimit θ P π E U)
      (forcingThreadOrder θ R (forcingDirectLimit θ P π E U)) :=
  forcingThreadOrder_preorder hR (fun _ hf ↦
    ((mem_forcingInverseLimit_iff _ _ _ _ _).mp
      (forcingDirectLimit_subset _ _ _ _ _ _ hf)).2.1)

theorem IsThreadSupport.raise {θ P E f k l : V}
    (hf : ∀ i ∈ θ, f ‘ i ∈ P ‘ i)
    (hk : IsThreadSupport θ E f k) (hl : l ∈ θ) (hkl : k ⊆ l)
    (hcomp : ∀ j ∈ θ, l ⊆ j → ∀ p ∈ P ‘ k,
      (E ‘ ⟨l, j⟩ₖ) ‘ ((E ‘ ⟨k, l⟩ₖ) ‘ p) = (E ‘ ⟨k, j⟩ₖ) ‘ p) :
    IsThreadSupport θ E f l := by
  refine ⟨hl, ?_⟩
  intro j hj hlj
  rw [hk.2 j hj (fun x hx ↦ hlj x (hkl x hx)), hk.2 l hl hkl]
  exact (hcomp j hj hlj _ (hf k hk.1)).symm

theorem forcingDirectLimit_restrict_of_support {θ η P π E U f k : V}
    (hη : η ⊆ θ) (hkη : k ∈ η)
    (hf : f ∈ forcingInverseLimit θ P π U) (hk : IsThreadSupport θ E f k) :
    f ↾ η ∈ forcingDirectLimit η P π E U := by
  have hfun := ((mem_forcingInverseLimit_iff _ _ _ _ _).mp hf).1
  let := IsFunction.of_mem hfun
  have hv : ∀ i ∈ η, (f ↾ η) ‘ i = f ‘ i := fun i hi ↦
    value_restrict ((domain_eq_of_mem_function hfun).symm ▸ hη i hi) hi
  apply (mem_forcingDirectLimit_iff _ _ _ _ _ _).mpr
  refine ⟨forcingInverseLimit_restrict hη hf, k, hkη, ?_⟩
  intro j hj hkj
  rw [hv j hj, hv k hkη]
  exact hk.2 j (hη j hj) hkj

/-- At a shared support, one coordinate determines the order of two threads. -/
theorem forcingThreadOrder_of_support {θ P R π E U f g k : V} [IsOrdinal θ]
    (hf : f ∈ forcingInverseLimit θ P π U)
    (hg : g ∈ forcingInverseLimit θ P π U)
    (hfk : IsThreadSupport θ E f k) (hgk : IsThreadSupport θ E g k)
    (hπ : ∀ i ∈ k, ∀ p ∈ P ‘ k, ∀ q ∈ P ‘ k, ⟨p, q⟩ₖ ∈ R ‘ k →
      ⟨(π ‘ ⟨i, k⟩ₖ) ‘ p, (π ‘ ⟨i, k⟩ₖ) ‘ q⟩ₖ ∈ R ‘ i)
    (hE : ∀ i ∈ θ, k ⊆ i → ∀ p ∈ P ‘ k, ∀ q ∈ P ‘ k, ⟨p, q⟩ₖ ∈ R ‘ k →
      ⟨(E ‘ ⟨k, i⟩ₖ) ‘ p, (E ‘ ⟨k, i⟩ₖ) ‘ q⟩ₖ ∈ R ‘ i)
    (hle : ⟨f ‘ k, g ‘ k⟩ₖ ∈ R ‘ k) :
    ⟨f, g⟩ₖ ∈ forcingThreadOrder θ R (forcingDirectLimit θ P π E U) := by
  have hf' := (mem_forcingInverseLimit_iff _ _ _ _ _).mp hf
  have hg' := (mem_forcingInverseLimit_iff _ _ _ _ _).mp hg
  let := IsOrdinal.of_mem hfk.1
  apply (mem_forcingThreadOrder_iff _ _ _ _ _).mpr
  refine ⟨(mem_forcingDirectLimit_iff _ _ _ _ _ _).mpr ⟨hf, k, hfk⟩,
    (mem_forcingDirectLimit_iff _ _ _ _ _ _).mpr ⟨hg, k, hgk⟩, ?_⟩
  intro i hi
  let := IsOrdinal.of_mem hi
  rcases IsOrdinal.mem_trichotomy i k with hik | rfl | hki
  · rw [← hf'.2.2 k hfk.1 i hik hi, ← hg'.2.2 k hfk.1 i hik hi]
    exact hπ i hik _ (hf'.2.1 k hfk.1) _ (hg'.2.1 k hfk.1) hle
  · exact hle
  · have hsub : k ⊆ i := IsOrdinal.toIsTransitive.transitive _ hki
    rw [hfk.2 i hi hsub, hgk.2 i hi hsub]
    exact hE i hi hsub _ (hf'.2.1 k hfk.1) _ (hg'.2.1 k hfk.1) hle

end ZFVP
