import ZFVP.SetTheory.CantorSpace

/-! Lebesgue null sets and Lebesgue measurability on the Cantor space, without real
arithmetic: the measure of a finite union of basic open sets is compared with `2^{-m}` by
comparing the cardinalities of finite sets of sequences. A set is null if for every `m` it is
covered by a sequence of basic open sets each of whose finite initial unions has measure at
most `2^{-m}`; it is Lebesgue measurable if it lies in a `G_δ` set with null difference. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

def shadowFormula : SetTheorySemisentence 3 :=
  f“S F M. ∀ t, t ∈ S ↔ t ∈ !function.dfn (!(numeralFormula 2)) M ∧ ∃ s ∈ F, s ⊆ t”

def smallMeasureFormula : SetTheorySemisentence 2 :=
  f“F m. ∃ M ∈ !isω, (∀ s ∈ F, !domain.dfn s ⊆ M) ∧
    !CardLE.dfn (!prod.dfn (!shadowFormula F M) (!function.dfn (!(numeralFormula 2)) m))
      (!function.dfn (!(numeralFormula 2)) M)”

def isNullFormula : SetTheorySemisentence 1 :=
  f“A. ∀ m ∈ !isω, ∃ f ∈ !function.dfn (!binarySequencesFormula) (!isω),
    (∀ x ∈ A, ∃ i ∈ !isω, !restrict.dfn x (!domain.dfn (!value.dfn f i)) = !value.dfn f i) ∧
    ∀ k ∈ !isω, !smallMeasureFormula (!image.dfn f k) m”

def gDeltaFormula : SetTheorySemisentence 2 :=
  f“B g. ∀ x, x ∈ B ↔ x ∈ !cantorSpaceFormula ∧ ∀ n ∈ !isω, x ∈ !openFromFormula (!value.dfn g n)”

def isLebesgueMeasurableFormula : SetTheorySemisentence 1 :=
  f“A. ∃ g ∈ !function.dfn (!power.dfn (!binarySequencesFormula)) (!isω),
    A ⊆ !gDeltaFormula g ∧ !isNullFormula (!sdiff.dfn (!gDeltaFormula g) A)”

/-- Every set of reals is Lebesgue measurable. -/
def lebesgueMeasurableSentence : SetTheorySentence :=
  f“∀ A, A ⊆ !cantorSpaceFormula → !isLebesgueMeasurableFormula A”

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-- The sequences of length `M` extending a member of `F`. -/
noncomputable def shadow (F M : V) : V :=
  {t ∈ ((2 : ℕ) : V) ^ M ; ∃ s ∈ F, s ⊆ t}

theorem mem_shadow_iff (F M t : V) : t ∈ shadow F M ↔ t ∈ ((2 : ℕ) : V) ^ M ∧ ∃ s ∈ F, s ⊆ t := by
  simp [shadow]

instance shadowFormula_defined : ℒₛₑₜ-function₂[V] shadow via shadowFormula :=
  ⟨fun v ↦ by simp [shadowFormula, mem_ext_iff (y := shadow _ _), mem_shadow_iff]⟩

instance shadow_definable : ℒₛₑₜ-function₂[V] shadow := shadowFormula_defined.to_definable

/-- The union of the basic open sets of `F` has measure at most `2^{-m}`. -/
def SmallMeasure (F m : V) : Prop :=
  ∃ M ∈ (ω : V), (∀ s ∈ F, domain s ⊆ M) ∧
    (shadow F M ×ˢ (((2 : ℕ) : V) ^ m)) ≤# (((2 : ℕ) : V) ^ M)

instance smallMeasureFormula_defined : ℒₛₑₜ-relation[V] SmallMeasure via smallMeasureFormula :=
  ⟨fun v ↦ by simp [smallMeasureFormula, SmallMeasure]⟩

instance smallMeasure_definable : ℒₛₑₜ-relation[V] SmallMeasure :=
  smallMeasureFormula_defined.to_definable

/-- Lebesgue null: for every `m`, a cover by basic open sets whose finite initial unions all
have measure at most `2^{-m}`. -/
def IsNull (A : V) : Prop :=
  ∀ m ∈ (ω : V), ∃ f ∈ (binarySequences V) ^ (ω : V),
    (∀ x ∈ A, ∃ i ∈ (ω : V), x ↾ (domain (f ‘ i)) = f ‘ i) ∧
    ∀ k ∈ (ω : V), SmallMeasure (f “ k) m

instance isNullFormula_defined : ℒₛₑₜ-predicate[V] IsNull via isNullFormula :=
  ⟨fun v ↦ by simp [isNullFormula, IsNull]⟩

instance isNull_definable : ℒₛₑₜ-predicate[V] IsNull := isNullFormula_defined.to_definable

/-- The intersection of the open sets generated by the values of `g`. -/
noncomputable def gDelta (g : V) : V :=
  {x ∈ cantorSpace V ; ∀ n ∈ (ω : V), x ∈ openFrom (g ‘ n)}

theorem mem_gDelta_iff (g x : V) :
    x ∈ gDelta g ↔ x ∈ cantorSpace V ∧ ∀ n ∈ (ω : V), x ∈ openFrom (g ‘ n) := by
  simp [gDelta]

instance gDeltaFormula_defined : ℒₛₑₜ-function₁[V] gDelta via gDeltaFormula :=
  ⟨fun v ↦ by simp [gDeltaFormula, mem_ext_iff (y := gDelta _), mem_gDelta_iff]⟩

instance gDelta_definable : ℒₛₑₜ-function₁[V] gDelta := gDeltaFormula_defined.to_definable

/-- Lebesgue measurable: contained in a `G_δ` set with null difference. -/
def IsLebesgueMeasurable (A : V) : Prop :=
  ∃ g ∈ (℘ (binarySequences V)) ^ (ω : V), A ⊆ gDelta g ∧ IsNull (gDelta g \ A)

instance isLebesgueMeasurableFormula_defined :
    ℒₛₑₜ-predicate[V] IsLebesgueMeasurable via isLebesgueMeasurableFormula :=
  ⟨fun v ↦ by simp [isLebesgueMeasurableFormula, IsLebesgueMeasurable]⟩

instance isLebesgueMeasurable_definable : ℒₛₑₜ-predicate[V] IsLebesgueMeasurable :=
  isLebesgueMeasurableFormula_defined.to_definable

def AllLebesgueMeasurable (V : Type*) [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙] : Prop :=
  ∀ A : V, A ⊆ cantorSpace V → IsLebesgueMeasurable A

instance lebesgueMeasurableSentence_defined :
    Defined (fun _ : Fin 0 → V ↦ AllLebesgueMeasurable V) lebesgueMeasurableSentence :=
  ⟨fun v ↦ by simp [lebesgueMeasurableSentence, AllLebesgueMeasurable]⟩

end ZFVP
