import ZFVP.SetTheory.TreeBodies
import ZFVP.SetTheory.DisjointCounting

/-! Telescoping for trees: the drop sets `dropSet T M M'` (nodes at level `M'` above a level-`M`
node of `T` but outside `T`) are eventually small, since a long chain of large drops would give
too many pairwise disjoint large subsets of a level. Consequently the open set generated by a
level of `T` differs from the body of `T` by a set with a cover of any prescribed measure. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

theorem binarySequences_countable (hAC : InternalChoice V) : binarySequences V ≤# (ω : V) := by
  have hω : IsInitialOrdinal (ω : V) := ⟨IsOrdinal.ω, fun n hn ↦ omega_not_cardLE_natural hn⟩
  refine CardLE.trans (cardLE_of_subset ?_) (finiteSequences_cardLE_initial hAC hω (fun x hx ↦ hx))
  intro s hs
  obtain ⟨n, hn, hsn⟩ := (mem_binarySequences_iff s).mp hs
  exact (mem_finiteSequences_iff _ _).mpr ⟨n, hn, mem_function_of_mem_function_of_subset hsn
    (IsTransitive.ω.transitive _ (ofNat_mem_ω 2))⟩

theorem shadow_self {F L : V} (hF : F ⊆ ((2 : ℕ) : V) ^ L) : shadow F L = F := by
  apply mem_ext
  intro t
  rw [mem_shadow_iff]
  constructor
  · rintro ⟨ht, s, hs, hst⟩
    rw [sequence_eq_of_subset_of_domain_eq (hF s hs) ht hst] at hs
    exact hs
  · intro ht
    exact ⟨hF t ht, t, ht, fun x hx ↦ hx⟩

/-- Nodes at level `M'` above a level-`M` node of `T` but outside `T`. -/
noncomputable def dropSet (T M M' : V) : V := shadow (levelSet T M) M' \ levelSet T M'

theorem mem_dropSet_iff (T M M' t : V) :
    t ∈ dropSet T M M' ↔ t ∈ ((2 : ℕ) : V) ^ M' ∧ (∃ s ∈ levelSet T M, s ⊆ t) ∧ t ∉ T := by
  unfold dropSet
  rw [mem_sdiff_iff, mem_shadow_iff, mem_levelSet_iff]
  constructor
  · rintro ⟨⟨ht, hs⟩, hnot⟩
    exact ⟨ht, hs, fun h ↦ hnot ⟨h, ht⟩⟩
  · rintro ⟨ht, hs, hnot⟩
    exact ⟨⟨ht, hs⟩, fun h ↦ hnot h.1⟩

theorem dropSet_subset_power (T M M' : V) : dropSet T M M' ⊆ ((2 : ℕ) : V) ^ M' :=
  fun t ht ↦ ((mem_dropSet_iff _ _ _ _).mp ht).1

theorem dropSet_domain {T M M' t : V} (ht : t ∈ dropSet T M M') : domain t = M' :=
  domain_eq_of_mem_function (dropSet_subset_power T M M' t ht)

/-- The shadow of a drop set at a higher level. -/
theorem mem_shadow_dropSet_iff {T M M' L : V} (hT : IsTree T) (hMM' : M ⊆ M') (hM'L : M' ⊆ L) (t : V) :
    t ∈ shadow (dropSet T M M') L ↔ t ∈ ((2 : ℕ) : V) ^ L ∧ t ↾ M ∈ T ∧ t ↾ M' ∉ T := by
  rw [mem_shadow_iff]
  constructor
  · rintro ⟨ht, s, hs, hst⟩
    obtain ⟨hsM', ⟨s₀, hs₀, hs₀s⟩, hsT⟩ := (mem_dropSet_iff _ _ _ _).mp hs
    obtain ⟨hs₀T, hs₀M⟩ := (mem_levelSet_iff _ _ _).mp hs₀
    have hseq : s = t ↾ M' := sequence_eq_restrict_of_subset ht hsM' hst
    have hs₀eq : s₀ = t ↾ M := sequence_eq_restrict_of_subset ht hs₀M (fun p hp ↦ hst p (hs₀s p hp))
    refine ⟨ht, ?_, ?_⟩
    · rw [← hs₀eq]; exact hs₀T
    · rw [← hseq]; exact hsT
  · rintro ⟨ht, hM, hM'⟩
    refine ⟨ht, t ↾ M', (mem_dropSet_iff _ _ _ _).mpr ⟨function_restrict_mem ht hM'L, ⟨t ↾ M, ?_, ?_⟩, hM'⟩,
      restrict_subset t M'⟩
    · exact (mem_levelSet_iff _ _ _).mpr ⟨hM, function_restrict_mem ht (fun x hx ↦ hM'L x (hMM' x hx))⟩
    · rw [← restrict_restrict_of_subset hMM']
      exact restrict_subset _ _

theorem not_small_shadow_of_not_small {T M M' L m : V} (hL : L ∈ (ω : V)) (hM'L : M' ⊆ L)
    (h : ¬ SmallMeasure (dropSet T M M') m) :
    ¬ shadow (dropSet T M M') L ×ˢ (((2 : ℕ) : V) ^ m) ≤# ((2 : ℕ) : V) ^ L := by
  intro hle
  exact h ⟨L, hL, fun s hs ↦ by rw [dropSet_domain hs]; exact hM'L, hle⟩

/-- Chains of levels with large drops. -/
def DropChain (T m N : V) : Prop :=
  ∃ c ∈ (ω : V) ^ succ N, (∀ i ∈ succ N, ∀ j ∈ succ N, i ⊆ j → c ‘ i ⊆ c ‘ j) ∧
    ∀ j ∈ N, ¬ SmallMeasure (dropSet T (c ‘ j) (c ‘ (succ j))) m

instance dropChain_definable (T m : V) : ℒₛₑₜ-predicate[V] (DropChain T m) := by
  unfold DropChain dropSet levelSet
  definability

theorem empty_mem_power_empty (A : V) : (∅ : V) ∈ A ^ (∅ : V) := by
  rw [mem_function_iff]
  exact ⟨fun p hp ↦ (not_mem_empty hp).elim, fun x hx ↦ (not_mem_empty hx).elim⟩

theorem natural_subset_of_mem_succ {i N : V} (hN : N ∈ (ω : V)) (hi : i ∈ succ N) : i ⊆ N := by
  have : IsOrdinal N := IsOrdinal.nat hN
  rcases mem_succ_iff.mp hi with rfl | hi
  · exact fun x hx ↦ hx
  · exact IsOrdinal.toIsTransitive.transitive i hi

theorem natural_mem_trans {i j k : V} (hk : k ∈ (ω : V)) (hij : i ∈ j) (hjk : j ∈ k) : i ∈ k := by
  have : IsOrdinal k := IsOrdinal.nat hk
  exact IsOrdinal.toIsTransitive.mem_trans hij hjk

theorem dropChain_all {T m : V} (hm : m ∈ (ω : V))
    (hbad : ∀ M ∈ (ω : V), ∃ M' ∈ (ω : V), M ⊆ M' ∧ ¬ SmallMeasure (dropSet T M M') m) :
    ∀ N ∈ (ω : V), DropChain T m N := by
  apply naturalNumber_induction (DropChain T m) (by definability)
  · refine ⟨insert ⟨∅, ∅⟩ₖ ∅, function_append_mem (empty_mem_power_empty _) zero_mem_ω, ?_, ?_⟩
    · intro i hi j hj _
      have hi0 : i = ∅ := by
        rcases mem_succ_iff.mp hi with rfl | hi
        · rfl
        · exact (not_mem_empty hi).elim
      have hj0 : j = ∅ := by
        rcases mem_succ_iff.mp hj with rfl | hj
        · rfl
        · exact (not_mem_empty hj).elim
      rw [hi0, hj0]
    · intro j hj
      exact (not_mem_empty hj).elim
  · intro N hN ⟨c, hc, hmono, hdrop⟩
    have : IsOrdinal N := IsOrdinal.nat hN
    have hcf : IsFunction c := IsFunction.of_mem hc
    have hcN : c ‘ N ∈ (ω : V) := function_value_mem hc (mem_succ_self N)
    obtain ⟨M', hM', hcM', hnot⟩ := hbad (c ‘ N) hcN
    obtain ⟨c', hc'def⟩ : ∃ c' : V, c' = insert ⟨succ N, M'⟩ₖ c := ⟨_, rfl⟩
    have hc' : c' ∈ (ω : V) ^ succ (succ N) := by rw [hc'def]; exact function_append_mem hc hM'
    have hc'f : IsFunction c' := IsFunction.of_mem hc'
    have hrest : c' ↾ (succ N) = c := by rw [hc'def]; exact function_append_restrict hc
    have hval : ∀ j ∈ succ N, c' ‘ j = c ‘ j := by
      intro j hj
      have h1 : (c' ↾ (succ N)) ‘ j = c' ‘ j :=
        value_restrict (by rw [domain_eq_of_mem_function hc']; exact mem_succ_iff.mpr (Or.inr hj)) hj
      rw [hrest] at h1
      exact h1.symm
    have hvaltop : c' ‘ (succ N) = M' := by
      apply value_eq_of_kpair_mem
      rw [hc'def]
      exact mem_insert.mpr (Or.inl rfl)
    refine ⟨c', hc', ?_, ?_⟩
    · intro i hi j hj hij
      rcases mem_succ_iff.mp hj with rfl | hj'
      · rcases mem_succ_iff.mp hi with rfl | hi'
        · exact fun x hx ↦ hx
        · rw [hval i hi', hvaltop]
          exact fun x hx ↦ hcM' x (hmono i hi' N (mem_succ_self N) (natural_subset_of_mem_succ hN hi') x hx)
      · rcases mem_succ_iff.mp hi with rfl | hi'
        · exfalso
          have hjN : j ⊆ N := natural_subset_of_mem_succ hN hj'
          exact mem_irrefl N (hjN N (hij N (mem_succ_self N)))
        · rw [hval i hi', hval j hj']
          exact hmono i hi' j hj' hij
    · intro j hj
      rcases mem_succ_iff.mp hj with rfl | hj'
      · rw [hval j (mem_succ_self j), hvaltop]
        exact hnot
      · rw [hval j (mem_succ_iff.mpr (Or.inr hj')), hval (succ j) (succ_mem_succ_of_natural_mem hN hj')]
        exact hdrop j hj'

theorem dropShadow_definable (T c L : V) :
    ℒₛₑₜ-function₁ (fun j : V ↦ shadow (dropSet T (c ‘ j) (c ‘ (succ j))) L) := by
  unfold dropSet levelSet
  definability

/-- Beyond some level, all drops of `T` are small. -/
theorem exists_stable_level (hAC : InternalChoice V) {T m : V} (hT : IsTree T) (hm : m ∈ (ω : V)) :
    ∃ M ∈ (ω : V), ∀ M' ∈ (ω : V), M ⊆ M' → SmallMeasure (dropSet T M M') m := by
  by_contra hcon
  have hbad : ∀ M ∈ (ω : V), ∃ M' ∈ (ω : V), M ⊆ M' ∧ ¬ SmallMeasure (dropSet T M M') m := by
    intro M hM
    by_contra h
    exact hcon ⟨M, hM, fun M' hM' hMM' ↦ by_contra (fun h' ↦ h ⟨M', hM', hMM', h'⟩)⟩
  obtain ⟨n₂, hn₂, h2n⟩ := internallyFinite_two_pow (V := V) hm
  have hN : succ n₂ ∈ (ω : V) := ω_succ_closed hn₂
  obtain ⟨c, hc, hmono, hdrop⟩ := dropChain_all hm hbad (succ n₂) hN
  have hcf : IsFunction c := IsFunction.of_mem hc
  obtain ⟨L, hLdef⟩ : ∃ L : V, L = c ‘ (succ n₂) := ⟨_, rfl⟩
  have hL : L ∈ (ω : V) := by rw [hLdef]; exact function_value_mem hc (mem_succ_self _)
  have hcω : ∀ j ∈ succ (succ n₂), c ‘ j ∈ (ω : V) := fun j hj ↦ function_value_mem hc hj
  have hjω : ∀ j ∈ succ n₂, j ∈ (ω : V) := fun j hj ↦ IsTransitive.ω.transitive _ hN j hj
  have hjL : ∀ j ∈ succ n₂, c ‘ (succ j) ⊆ L := by
    intro j hj
    rw [hLdef]
    refine hmono (succ j) (succ_mem_succ_of_natural_mem hN hj) (succ n₂) (mem_succ_self _) ?_
    intro x hx
    rcases mem_succ_iff.mp hx with rfl | hx
    · exact hj
    · exact natural_mem_trans hN hx hj
  have hjj : ∀ j ∈ succ n₂, c ‘ j ⊆ c ‘ (succ j) := fun j hj ↦
    hmono j (mem_succ_iff.mpr (Or.inr hj)) (succ j) (succ_mem_succ_of_natural_mem hN hj)
      (fun x hx ↦ mem_succ_iff.mpr (Or.inr hx))
  have hjL' : ∀ j ∈ succ n₂, c ‘ j ⊆ L := fun j hj x hx ↦ hjL j hj x (hjj j hj x hx)
  obtain ⟨X, hXdef⟩ : ∃ X : V, X = definableGraph (succ n₂)
    (fun j ↦ shadow (dropSet T (c ‘ j) (c ‘ (succ j))) L) (dropShadow_definable T c L) := ⟨_, rfl⟩
  have hXval : ∀ j ∈ succ n₂, X ‘ j = shadow (dropSet T (c ‘ j) (c ‘ (succ j))) L := by
    intro j hj
    rw [hXdef]
    exact value_definableGraph _ _ _ hj
  have hX : X ∈ (℘ (((2 : ℕ) : V) ^ L)) ^ succ n₂ := by
    rw [hXdef]
    exact definableGraph_mem_function_of_mapsTo _ _ _ _ (fun j _ ↦ mem_power_iff.mpr (shadow_subset_power _ _))
  -- disjointness of the lifted drops
  have hdisj₀ : ∀ j ∈ succ n₂, ∀ j' ∈ succ n₂, j ∈ j' → ∀ x, x ∈ X ‘ j → x ∈ X ‘ j' → False := by
    intro j hj j' hj' hjj' x hx hx'
    rw [hXval j hj] at hx
    rw [hXval j' hj'] at hx'
    obtain ⟨hxL, -, hxnot⟩ := (mem_shadow_dropSet_iff hT (hjj j hj) (hjL j hj) x).mp hx
    obtain ⟨-, hxin, -⟩ := (mem_shadow_dropSet_iff hT (hjj j' hj') (hjL j' hj') x).mp hx'
    have hsub : c ‘ (succ j) ⊆ c ‘ j' :=
      hmono (succ j) (succ_mem_succ_of_natural_mem hN hj) j' (mem_succ_iff.mpr (Or.inr hj')) (by
        intro y hy
        rcases mem_succ_iff.mp hy with rfl | hy
        · exact hjj'
        · exact natural_mem_trans (hjω j' hj') hy hjj')
    apply hxnot
    have : IsFunction x := IsFunction.of_mem hxL
    rw [← restrict_restrict_of_subset hsub]
    exact tree_restrict_mem hT hxin (hcω (succ j) (succ_mem_succ_of_natural_mem hN hj))
      (by rw [domain_eq_of_mem_function (function_restrict_mem hxL (hjL' j' hj'))]; exact hsub)
  have hdisj : ∀ j ∈ succ n₂, ∀ j' ∈ succ n₂, j ≠ j' → ∀ x, x ∈ X ‘ j → x ∈ X ‘ j' → False := by
    intro j hj j' hj' hne x hx hx'
    have : IsOrdinal j := IsOrdinal.nat (hjω j hj)
    have : IsOrdinal j' := IsOrdinal.nat (hjω j' hj')
    rcases IsOrdinal.subset_or_supset (α := j) (β := j') with h | h
    · rcases (IsOrdinal.subset_iff (α := j) (β := j')).mp h with h' | h'
      · exact hne h'
      · exact hdisj₀ j hj j' hj' h' x hx hx'
    · rcases (IsOrdinal.subset_iff (α := j') (β := j)).mp h with h' | h'
      · exact hne h'.symm
      · exact hdisj₀ j' hj' j hj h' x hx' hx
  have hbig : ∀ j ∈ succ n₂, ¬ (X ‘ j) ×ˢ (((2 : ℕ) : V) ^ m) ≤# ((2 : ℕ) : V) ^ L := by
    intro j hj
    rw [hXval j hj]
    exact not_small_shadow_of_not_small hL (hjL j hj) (hdrop j hj)
  have hle := disjoint_family_cardLE hAC hN (internallyFinite_two_pow hL) hm hX hdisj hbig
  exact not_succ_cardLE_self hn₂ (hle.trans h2n.le)

/-- A cover from an enumerable family of sequences all of whose finite subfamilies are small. -/
theorem exists_cover_of_enumerable {D A m : V} (hm : m ∈ (ω : V)) (hD : D ⊆ binarySequences V)
    (hDω : D ≤# (ω : V)) (hcov : ∀ x ∈ A, Meets D x)
    (hsmall : ∀ F, F ⊆ D → IsInternallyFinite F → SmallMeasure F m) :
    ∃ f ∈ (binarySequences V) ^ (ω : V), IsCoverAt f A m ∧ ∀ s ∈ D, ∃ i ∈ (ω : V), f ‘ i = s := by
  by_cases hne : ∃ s, s ∈ D
  · obtain ⟨s₀, hs₀⟩ := hne
    obtain ⟨E, hE, hrange⟩ := exists_surjection_of_cardLE hDω hs₀
    have hEf : IsFunction E := IsFunction.of_mem hE
    have hsurj : ∀ s ∈ D, ∃ i ∈ (ω : V), E ‘ i = s := by
      intro s hs
      have hsr : s ∈ range E := by rw [hrange]; exact hs
      obtain ⟨i, hi⟩ := mem_range_iff.mp hsr
      exact ⟨i, by rw [← domain_eq_of_mem_function hE]; exact mem_domain_of_kpair_mem hi, value_eq_of_kpair_mem hi⟩
    refine ⟨E, mem_function_of_mem_function_of_subset hE hD, ⟨fun x hx ↦ ?_, fun k hk ↦ ?_⟩, hsurj⟩
    · obtain ⟨s, hs, hxs⟩ := hcov x hx
      have hsr : s ∈ range E := by rw [hrange]; exact hs
      obtain ⟨i, hi⟩ := mem_range_iff.mp hsr
      refine ⟨i, by rw [← domain_eq_of_mem_function hE]; exact mem_domain_of_kpair_mem hi, ?_⟩
      rw [value_eq_of_kpair_mem hi]
      exact hxs
    · refine hsmall _ (fun s hs ↦ ?_) ?_
      · obtain ⟨i, -, hi⟩ := (mem_image_iff' _ _ _).mp hs
        have : s ∈ range E := mem_range_iff.mpr ⟨i, hi⟩
        rw [hrange] at this
        exact this
      · have hrf : IsFunction (E ↾ k) := IsFunction.restrict E k
        have hdom : IsInternallyFinite (domain (E ↾ k)) := by
          rw [domain_restrict_eq, domain_eq_of_mem_function hE]
          exact internallyFinite_subset ⟨k, hk, CardEQ.refl k⟩ (fun x hx ↦ (mem_inter_iff.mp hx).2)
        exact internallyFinite_range (internallyFinite_function hdom)
  · have hAempty : ∀ x, x ∉ A := fun x hx ↦ by
      obtain ⟨s, hs, -⟩ := hcov x hx
      exact hne ⟨s, hs⟩
    obtain ⟨E, hEdef⟩ : ∃ E : V, E = definableGraph (ω : V) (fun _ ↦ zeroSequence m) (by definability) :=
      ⟨_, rfl⟩
    have hE : E ∈ (binarySequences V) ^ (ω : V) := by
      rw [hEdef]
      exact definableGraph_mem_function_of_mapsTo _ _ _ _ (fun _ _ ↦ zeroSequence_mem_binarySequences hm)
    refine ⟨E, hE, ⟨fun x hx ↦ (hAempty x hx).elim, fun k _ ↦ ?_⟩, fun s hs ↦ (hne ⟨s, hs⟩).elim⟩
    refine smallMeasure_mono_family (smallMeasure_singleton_zeroSequence hm) (fun s hs ↦ ?_)
    obtain ⟨i, hi, his⟩ := (mem_image_iff' _ _ _).mp hs
    have hiω : i ∈ (ω : V) := by
      have := mem_domain_of_kpair_mem his
      rw [domain_eq_of_mem_function hE] at this
      exact this
    have : IsFunction E := IsFunction.of_mem hE
    rw [mem_singleton_iff, ← value_eq_of_kpair_mem his, hEdef, value_definableGraph _ _ _ hiω]

/-- The sequences above level `M` leaving the tree. -/
def LeavesTree (T M s : V) : Prop := M ⊆ domain s ∧ s ∉ T ∧ s ↾ M ∈ T

instance leavesTree_definable (T M : V) : ℒₛₑₜ-predicate[V] (LeavesTree T M) := by
  unfold LeavesTree
  definability

/-- The open set generated by a suitable level of `T` differs from the body of `T` by a set with a
cover of measure at most `2^{-m}`. -/
theorem exists_level_cover (hAC : InternalChoice V) {T m : V} (hT : IsTree T) (hm : m ∈ (ω : V)) :
    ∃ M ∈ (ω : V), ∃ f ∈ (binarySequences V) ^ (ω : V),
      IsCoverAt f (openFrom (levelSet T M) \ treeBody T) m ∧
      ∀ s ∈ binarySequences V, LeavesTree T M s → ∃ i ∈ (ω : V), f ‘ i = s := by
  obtain ⟨M, hM, hstable⟩ := exists_stable_level hAC hT hm
  have : IsOrdinal M := IsOrdinal.nat hM
  obtain ⟨D, hDdef⟩ : ∃ D : V, D = sep (binarySequences V) (LeavesTree T M) (leavesTree_definable T M) := ⟨_, rfl⟩
  have hDmem : ∀ s, s ∈ D ↔ s ∈ binarySequences V ∧ M ⊆ domain s ∧ s ∉ T ∧ s ↾ M ∈ T := by
    intro s
    rw [hDdef, mem_sep_iff]
    rfl
  have hDsub : D ⊆ binarySequences V := fun s hs ↦ ((hDmem s).mp hs).1
  have hcov' : ∀ x ∈ openFrom (levelSet T M) \ treeBody T, Meets D x := by
    intro x hx
    obtain ⟨hxo, hxnot⟩ := mem_sdiff_iff.mp hx
    obtain ⟨hxc, s₀, hs₀, hxs₀⟩ := (mem_openFrom_iff _ _).mp hxo
    obtain ⟨hs₀T, hs₀M⟩ := (mem_levelSet_iff _ _ _).mp hs₀
    rw [domain_eq_of_mem_function hs₀M] at hxs₀
    have hxM : x ↾ M ∈ T := by rw [hxs₀]; exact hs₀T
    have hxf : IsFunction x := IsFunction.of_mem hxc
    obtain ⟨M', hM', hxM'⟩ : ∃ M' ∈ (ω : V), x ↾ M' ∉ T := by
      by_contra h
      push Not at h
      exact hxnot ((mem_treeBody_iff _ _).mpr ⟨hxc, h⟩)
    have : IsOrdinal M' := IsOrdinal.nat hM'
    have hMM' : M ⊆ M' := by
      rcases IsOrdinal.subset_or_supset (α := M) (β := M') with h | h
      · exact h
      · exfalso
        apply hxM'
        rw [← restrict_restrict_of_subset h]
        exact tree_restrict_mem hT hxM hM'
          (by rw [domain_eq_of_mem_function (function_restrict_mem hxc (IsTransitive.ω.transitive M hM))]; exact h)
    refine ⟨x ↾ M', (hDmem _).mpr ⟨restrict_mem_binarySequences hxc hM', ?_, hxM', ?_⟩, ?_⟩
    · rw [domain_eq_of_mem_function (function_restrict_mem hxc (IsTransitive.ω.transitive M' hM'))]
      exact hMM'
    · rw [restrict_restrict_of_subset hMM']
      exact hxM
    · rw [domain_eq_of_mem_function (function_restrict_mem hxc (IsTransitive.ω.transitive M' hM'))]
  have hsmall' : ∀ F, F ⊆ D → IsInternallyFinite F → SmallMeasure F m := by
    intro F hFD hFfin
    -- a level bounding the domains
    have hdoms : IsInternallyFinite (repl domain (by definability) F) := internallyFinite_repl _ _ hFfin
    obtain ⟨L', hL', hbound⟩ := internallyFinite_naturals_bounded hdoms (fun x hx ↦ by
      obtain ⟨s, hs, rfl⟩ := (repl_spec (by definability)).mp hx
      obtain ⟨n, hn, hsn⟩ := (mem_binarySequences_iff _).mp (hDsub s (hFD s hs))
      rw [domain_eq_of_mem_function hsn]
      exact hn)
    have : IsOrdinal L' := IsOrdinal.nat hL'
    obtain ⟨L, hL, hL'L, hML⟩ : ∃ L ∈ (ω : V), L' ⊆ L ∧ M ⊆ L := by
      rcases IsOrdinal.subset_or_supset (α := L') (β := M) with h | h
      · exact ⟨M, hM, h, fun x hx ↦ hx⟩
      · exact ⟨L', hL', fun x hx ↦ hx, h⟩
    have hFdom : ∀ s ∈ F, domain s ⊆ L := fun s hs x hx ↦
      hL'L x (IsOrdinal.toIsTransitive.transitive (domain s)
        (hbound _ ((repl_spec (by definability)).mpr ⟨s, hs, rfl⟩)) x hx)
    obtain ⟨Λ₀, hΛ₀, -, hlev⟩ := smallMeasure_levels (hstable L hL hML)
    have : IsOrdinal Λ₀ := IsOrdinal.nat hΛ₀
    have : IsOrdinal L := IsOrdinal.nat hL
    obtain ⟨Λ, hΛ, hΛ₀Λ, hLΛ⟩ : ∃ Λ ∈ (ω : V), Λ₀ ⊆ Λ ∧ L ⊆ Λ := by
      rcases IsOrdinal.subset_or_supset (α := Λ₀) (β := L) with h | h
      · exact ⟨L, hL, h, fun x hx ↦ hx⟩
      · exact ⟨Λ₀, hΛ₀, fun x hx ↦ hx, h⟩
    refine ⟨Λ, hΛ, fun s hs x hx ↦ hLΛ x (hFdom s hs x hx), ?_⟩
    refine CardLE.trans (prod_cardLE_prod (cardLE_of_subset ?_) (CardLE.refl _)) (hlev Λ hΛ hΛ₀Λ)
    intro t ht
    obtain ⟨htΛ, s, hs, hst⟩ := (mem_shadow_iff _ _ _).mp ht
    obtain ⟨hsB, hMs, hsT, hsM⟩ := (hDmem s).mp (hFD s hs)
    obtain ⟨n, hn, hsn⟩ := (mem_binarySequences_iff _).mp hsB
    have hdn : domain s = n := domain_eq_of_mem_function hsn
    have hnL : n ⊆ L := by rw [← hdn]; exact hFdom s hs
    have htf : IsFunction t := IsFunction.of_mem htΛ
    rw [mem_shadow_dropSet_iff hT hML hLΛ]
    have hstL : s ⊆ t ↾ L := by
      intro p hp
      obtain ⟨a, ha, b, -, rfl⟩ := mem_prod_iff.mp ((mem_function_iff.mp hsn).1 p hp)
      exact kpair_mem_restrict_iff.mpr ⟨hst _ hp, hnL a ha⟩
    have htL : t ↾ L ∈ ((2 : ℕ) : V) ^ L := function_restrict_mem htΛ hLΛ
    have hseq : s = (t ↾ L) ↾ n := sequence_eq_restrict_of_subset htL hsn hstL
    refine ⟨htΛ, ?_, ?_⟩
    · have h1 : (t ↾ L) ↾ M = t ↾ M := restrict_restrict_of_subset hML
      have h2 : s ↾ M = ((t ↾ L) ↾ n) ↾ M := by rw [← hseq]
      rw [restrict_restrict_of_subset (by rw [← hdn]; exact hMs)] at h2
      rw [← h1, ← h2]
      exact hsM
    · intro htLT
      apply hsT
      rw [hseq]
      exact tree_restrict_mem hT htLT hn (by rw [domain_eq_of_mem_function htL]; exact hnL)
  obtain ⟨f, hf, hcov, hsurj⟩ := exists_cover_of_enumerable hm hDsub
    ((cardLE_of_subset hDsub).trans (binarySequences_countable hAC)) hcov' hsmall'
  exact ⟨M, hM, f, hf, hcov, fun s hs hl ↦ hsurj s ((hDmem s).mpr ⟨hs, hl⟩)⟩

end ZFVP
