import ZFVP.SetTheory.NullSets
import ZFVP.SetTheory.SequenceTree

/-! Bodies of binary trees: level sets, the body as the intersection of the open sets generated by
the levels, intersections, and König's lemma: a tree with nodes at every level has a branch. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-- The nodes of `T` at level `M`. -/
noncomputable def levelSet (T M : V) : V := T ∩ (((2 : ℕ) : V) ^ M)

theorem mem_levelSet_iff (T M s : V) : s ∈ levelSet T M ↔ s ∈ T ∧ s ∈ ((2 : ℕ) : V) ^ M := mem_inter_iff

theorem levelSet_subset (T M : V) : levelSet T M ⊆ T := fun s hs ↦ ((mem_levelSet_iff _ _ _).mp hs).1

theorem levelSet_finite {T M : V} (hM : M ∈ (ω : V)) : IsInternallyFinite (levelSet T M) :=
  internallyFinite_subset (internallyFinite_two_pow hM) (fun s hs ↦ ((mem_levelSet_iff _ _ _).mp hs).2)

theorem levelSet_subset_binarySequences {T M : V} (hM : M ∈ (ω : V)) : levelSet T M ⊆ binarySequences V :=
  fun s hs ↦ (mem_binarySequences_iff _).mpr ⟨M, hM, ((mem_levelSet_iff _ _ _).mp hs).2⟩

theorem shadow_levelSet (T M : V) : shadow (levelSet T M) M = levelSet T M := by
  apply mem_ext
  intro t
  rw [mem_shadow_iff]
  constructor
  · rintro ⟨ht, s, hs, hst⟩
    obtain ⟨hsT, hsM⟩ := (mem_levelSet_iff _ _ _).mp hs
    rw [sequence_eq_of_subset_of_domain_eq hsM ht hst] at hsT
    exact (mem_levelSet_iff _ _ _).mpr ⟨hsT, ht⟩
  · intro ht
    exact ⟨((mem_levelSet_iff _ _ _).mp ht).2, t, ht, fun x hx ↦ hx⟩

theorem levelSet_mono {T T' : V} (h : T ⊆ T') (M : V) : levelSet T M ⊆ levelSet T' M := by
  intro s hs
  obtain ⟨hsT, hsM⟩ := (mem_levelSet_iff _ _ _).mp hs
  exact (mem_levelSet_iff _ _ _).mpr ⟨h s hsT, hsM⟩

theorem levelSet_inter (T T' M : V) : levelSet (T ∩ T') M = levelSet T M ∩ levelSet T' M := by
  apply mem_ext
  intro s
  simp only [mem_levelSet_iff, mem_inter_iff]
  tauto

theorem restrict_mem_levelSet {T x M : V} (hx : x ∈ treeBody T) (hM : M ∈ (ω : V)) :
    x ↾ M ∈ levelSet T M := by
  obtain ⟨hxc, hxT⟩ := (mem_treeBody_iff _ _).mp hx
  exact (mem_levelSet_iff _ _ _).mpr ⟨hxT M hM, function_restrict_mem hxc (IsTransitive.ω.transitive _ hM)⟩

theorem treeBody_subset_openFrom_levelSet {T M : V} (hM : M ∈ (ω : V)) :
    treeBody T ⊆ openFrom (levelSet T M) := by
  intro x hx
  have hxc := ((mem_treeBody_iff _ _).mp hx).1
  refine (mem_openFrom_iff _ _).mpr ⟨hxc, x ↾ M, restrict_mem_levelSet hx hM, ?_⟩
  have hd : domain (x ↾ M) = M :=
    domain_eq_of_mem_function (function_restrict_mem hxc (IsTransitive.ω.transitive _ hM))
  rw [hd]

theorem mem_treeBody_of_meets_levels {T x : V} (hx : x ∈ cantorSpace V)
    (h : ∀ M ∈ (ω : V), x ∈ openFrom (levelSet T M)) : x ∈ treeBody T := by
  refine (mem_treeBody_iff _ _).mpr ⟨hx, fun M hM ↦ ?_⟩
  obtain ⟨-, s, hs, hxs⟩ := (mem_openFrom_iff _ _).mp (h M hM)
  obtain ⟨hsT, hsM⟩ := (mem_levelSet_iff _ _ _).mp hs
  rw [domain_eq_of_mem_function hsM] at hxs
  rw [hxs]
  exact hsT

theorem treeBody_inter (T T' : V) : treeBody (T ∩ T') = treeBody T ∩ treeBody T' := by
  apply mem_ext
  intro x
  simp only [mem_treeBody_iff, mem_inter_iff]
  constructor
  · rintro ⟨hx, h⟩
    exact ⟨⟨hx, fun n hn ↦ (h n hn).1⟩, ⟨hx, fun n hn ↦ (h n hn).2⟩⟩
  · rintro ⟨⟨hx, h1⟩, ⟨-, h2⟩⟩
    exact ⟨hx, fun n hn ↦ ⟨h1 n hn, h2 n hn⟩⟩

theorem treeBody_mono {T T' : V} (h : T ⊆ T') : treeBody T ⊆ treeBody T' := by
  intro x hx
  obtain ⟨hxc, hxT⟩ := (mem_treeBody_iff _ _).mp hx
  exact (mem_treeBody_iff _ _).mpr ⟨hxc, fun n hn ↦ h _ (hxT n hn)⟩

theorem treeBody_subset_cantorSpace (T : V) : treeBody T ⊆ cantorSpace V :=
  fun x hx ↦ ((mem_treeBody_iff _ _).mp hx).1

/-- Restrictions of nodes of a tree to initial segments are nodes. -/
theorem tree_restrict_mem {T t M : V} (hT : IsTree T) (ht : t ∈ T) (hM : M ∈ (ω : V))
    (hMt : M ⊆ domain t) : t ↾ M ∈ T := by
  obtain ⟨n, hn, htn⟩ := (mem_binarySequences_iff _).mp (hT.1 t ht)
  have hd : domain t = n := domain_eq_of_mem_function htn
  have : IsOrdinal M := IsOrdinal.nat hM
  have : IsOrdinal n := IsOrdinal.nat hn
  rw [hd] at hMt
  rcases (IsOrdinal.subset_iff (α := M) (β := n)).mp hMt with rfl | hMn
  · have : IsFunction t := IsFunction.of_mem htn
    rw [IsFunction.restrict_eq_self t M (by rw [hd])]
    exact ht
  · exact hT.2 t ht M (by rw [hd]; exact hMn)

/-- Appending a value. -/
theorem append_value {s n i : V} (hs : s ∈ ((2 : ℕ) : V) ^ n) (hi : i ∈ ((2 : ℕ) : V)) :
    (insert ⟨n, i⟩ₖ s) ‘ n = i := by
  have : IsFunction (insert ⟨n, i⟩ₖ s) := IsFunction.of_mem (function_append_mem hs hi)
  exact value_eq_of_kpair_mem (mem_insert.mpr (Or.inl rfl))

theorem append_subset_iff {s t n i M : V} (hs : s ∈ ((2 : ℕ) : V) ^ n) (ht : t ∈ ((2 : ℕ) : V) ^ M)
    (hnM : n ∈ M) (hst : s ⊆ t) : insert ⟨n, i⟩ₖ s ⊆ t ↔ t ‘ n = i := by
  have : IsFunction t := IsFunction.of_mem ht
  constructor
  · intro h
    exact value_eq_of_kpair_mem (h _ (mem_insert.mpr (Or.inl rfl)))
  · intro h p hp
    rcases mem_insert.mp hp with rfl | hp
    · rw [← h]
      exact kpair_value_mem (by rw [domain_eq_of_mem_function ht]; exact hnM)
    · exact hst p hp

/-- `s` has extensions in `T` at every level. -/
def Extendible (T s : V) : Prop :=
  ∀ M ∈ (ω : V), domain s ⊆ M → ∃ t ∈ T, t ∈ ((2 : ℕ) : V) ^ M ∧ s ⊆ t

instance extendible_definable : ℒₛₑₜ-relation[V] Extendible := by
  unfold Extendible
  definability

theorem extendible_empty {T : V} (hlev : ∀ M ∈ (ω : V), ∃ s ∈ T, s ∈ ((2 : ℕ) : V) ^ M) :
    Extendible T (∅ : V) := by
  intro M hM _
  obtain ⟨s, hs, hsM⟩ := hlev M hM
  exact ⟨s, hs, hsM, fun x hx ↦ (not_mem_empty hx).elim⟩

theorem extendible_mem {T s n : V} (hT : IsTree T) (hs : s ∈ ((2 : ℕ) : V) ^ n) (hn : n ∈ (ω : V))
    (h : Extendible T s) : s ∈ T := by
  obtain ⟨t, ht, htn, hst⟩ := h n hn (by rw [domain_eq_of_mem_function hs])
  rw [sequence_eq_of_subset_of_domain_eq hs htn hst]
  exact ht

theorem extendible_restrict {T s M : V} (hT : IsTree T) {n : V} (hs : s ∈ ((2 : ℕ) : V) ^ n) (hn : n ∈ (ω : V))
    (h : Extendible T s) (hM : M ∈ (ω : V)) (hMn : M ⊆ n) : Extendible T (s ↾ M) := by
  intro M' hM' hMM'
  have : IsOrdinal M' := IsOrdinal.nat hM'
  have : IsOrdinal n := IsOrdinal.nat hn
  have hd : domain (s ↾ M) = M := domain_eq_of_mem_function (function_restrict_mem hs hMn)
  rw [hd] at hMM'
  rcases IsOrdinal.subset_or_supset (α := n) (β := M') with hnM' | hM'n
  · obtain ⟨t, ht, htM', hst⟩ := h M' hM' (by rw [domain_eq_of_mem_function hs]; exact hnM')
    exact ⟨t, ht, htM', fun p hp ↦ hst p (restrict_subset s M p hp)⟩
  · refine ⟨s ↾ M', tree_restrict_mem hT (extendible_mem hT hs hn h) hM'
      (by rw [domain_eq_of_mem_function hs]; exact hM'n), function_restrict_mem hs hM'n, ?_⟩
    intro p hp
    obtain ⟨hps, x, hx, y, rfl⟩ := mem_restrict_iff.mp hp
    exact kpair_mem_restrict_iff.mpr ⟨hps, hMM' x hx⟩

/-- An extendible node has an extendible child. -/
theorem extendible_child {T s n : V} (hT : IsTree T) (hs : s ∈ ((2 : ℕ) : V) ^ n) (hn : n ∈ (ω : V))
    (h : Extendible T s) :
    Extendible T (insert ⟨n, ∅⟩ₖ s) ∨ Extendible T (insert ⟨n, succ ∅⟩ₖ s) := by
  by_contra hcon
  have h0 : ¬ Extendible T (insert ⟨n, ∅⟩ₖ s) := fun h ↦ hcon (Or.inl h)
  have h1 : ¬ Extendible T (insert ⟨n, succ ∅⟩ₖ s) := fun h ↦ hcon (Or.inr h)
  unfold Extendible at h0 h1
  push Not at h0 h1
  obtain ⟨M₀, hM₀, hdom₀, hno₀⟩ := h0
  obtain ⟨M₁, hM₁, hdom₁, hno₁⟩ := h1
  have : IsOrdinal M₀ := IsOrdinal.nat hM₀
  have : IsOrdinal M₁ := IsOrdinal.nat hM₁
  have hd0 : domain (insert ⟨n, ∅⟩ₖ s) = succ n :=
    domain_eq_of_mem_function (function_append_mem hs ((mem_two_iff _).mpr (Or.inl rfl)))
  have hd1 : domain (insert ⟨n, succ ∅⟩ₖ s) = succ n :=
    domain_eq_of_mem_function (function_append_mem hs ((mem_two_iff _).mpr (Or.inr rfl)))
  rw [hd0] at hdom₀
  rw [hd1] at hdom₁
  obtain ⟨M, hM, hM₀M, hM₁M⟩ : ∃ M ∈ (ω : V), M₀ ⊆ M ∧ M₁ ⊆ M := by
    rcases IsOrdinal.subset_or_supset (α := M₀) (β := M₁) with h | h
    · exact ⟨M₁, hM₁, h, fun x hx ↦ hx⟩
    · exact ⟨M₀, hM₀, fun x hx ↦ hx, h⟩
  have hnM : n ∈ M := hM₀M n (hdom₀ n (mem_succ_self n))
  obtain ⟨t, ht, htM, hst⟩ := h M hM (by
    rw [domain_eq_of_mem_function hs]
    exact fun x hx ↦ hM₀M x (hdom₀ x (mem_succ_iff.mpr (Or.inr hx))))
  have : IsFunction t := IsFunction.of_mem htM
  have htn : t ‘ n ∈ ((2 : ℕ) : V) := function_value_mem htM hnM
  have hrestr : ∀ M' ∈ (ω : V), M' ⊆ M → succ n ⊆ M' → ∀ i, t ‘ n = i →
      ∃ t' ∈ T, t' ∈ ((2 : ℕ) : V) ^ M' ∧ insert ⟨n, i⟩ₖ s ⊆ t' := by
    intro M' hM' hM'M hnM' i hi
    have hnM'' : n ∈ M' := hnM' n (mem_succ_self n)
    refine ⟨t ↾ M', tree_restrict_mem hT ht hM' (by rw [domain_eq_of_mem_function htM]; exact hM'M),
      function_restrict_mem htM hM'M, ?_⟩
    have hst' : s ⊆ t ↾ M' := by
      intro p hp
      obtain ⟨a, ha, b, -, rfl⟩ := mem_prod_iff.mp ((mem_function_iff.mp hs).1 p hp)
      exact kpair_mem_restrict_iff.mpr ⟨hst _ hp, hnM' a (mem_succ_iff.mpr (Or.inr (by
        rw [← domain_eq_of_mem_function hs]; exact mem_domain_of_kpair_mem hp)))⟩
    rw [append_subset_iff hs (function_restrict_mem htM hM'M) hnM'' hst',
      value_restrict (by rw [domain_eq_of_mem_function htM]; exact hnM) hnM'']
    exact hi
  rcases (mem_two_iff _).mp htn with h0' | h1'
  · obtain ⟨t', ht', ht'M, hsub⟩ := hrestr M₀ hM₀ hM₀M hdom₀ ∅ h0'
    exact hno₀ t' ht' ht'M hsub
  · obtain ⟨t', ht', ht'M, hsub⟩ := hrestr M₁ hM₁ hM₁M hdom₁ (succ ∅) h1'
    exact hno₁ t' ht' ht'M hsub

/-- Leftmost extendible approximations. -/
def LeftmostApprox (T s : V) : Prop :=
  Extendible T s ∧ ∀ n ∈ domain s, Extendible T (insert ⟨n, ∅⟩ₖ (s ↾ n)) → s ‘ n = ∅

instance leftmostApprox_definable : ℒₛₑₜ-relation[V] LeftmostApprox := by
  unfold LeftmostApprox
  definability

/-- The unique leftmost approximation at each level. -/
def LeftmostLevel (T M : V) : Prop :=
  (∃ s ∈ ((2 : ℕ) : V) ^ M, LeftmostApprox T s) ∧
    ∀ s ∈ ((2 : ℕ) : V) ^ M, ∀ s' ∈ ((2 : ℕ) : V) ^ M, LeftmostApprox T s → LeftmostApprox T s' → s = s'

instance leftmostLevel_definable : ℒₛₑₜ-relation[V] LeftmostLevel := by
  unfold LeftmostLevel
  definability

theorem leftmostApprox_restrict {T s n M : V} (hT : IsTree T) (hs : s ∈ ((2 : ℕ) : V) ^ n) (hn : n ∈ (ω : V))
    (h : LeftmostApprox T s) (hM : M ∈ (ω : V)) (hMn : M ⊆ n) : LeftmostApprox T (s ↾ M) := by
  have : IsFunction s := IsFunction.of_mem hs
  have hd : domain (s ↾ M) = M := domain_eq_of_mem_function (function_restrict_mem hs hMn)
  refine ⟨extendible_restrict hT hs hn h.1 hM hMn, fun k hk hext ↦ ?_⟩
  rw [hd] at hk
  have hkn : k ∈ n := hMn k hk
  have hkd : k ∈ domain s := by rw [domain_eq_of_mem_function hs]; exact hkn
  have hMo : IsOrdinal M := IsOrdinal.nat hM
  have hkM : k ⊆ M := IsOrdinal.toIsTransitive.transitive k hk
  rw [restrict_restrict_of_subset hkM] at hext
  rw [value_restrict hkd hk]
  exact h.2 k hkd hext

theorem leftmostLevel_all {T : V} (hT : IsTree T) (hlev : ∀ M ∈ (ω : V), ∃ s ∈ T, s ∈ ((2 : ℕ) : V) ^ M) :
    ∀ M ∈ (ω : V), LeftmostLevel T M := by
  apply naturalNumber_induction (LeftmostLevel T) (by definability)
  · have hempty : (∅ : V) ∈ ((2 : ℕ) : V) ^ (0 : V) := by
      rw [mem_function_iff]
      refine ⟨fun p hp ↦ (not_mem_empty hp).elim, fun x hx ↦ (not_mem_empty hx).elim⟩
    refine ⟨⟨∅, hempty, extendible_empty hlev, fun n hn _ ↦ ?_⟩, ?_⟩
    · obtain ⟨y, hy⟩ := mem_domain_iff.mp hn
      exact (not_mem_empty hy).elim
    intro s hs s' hs' _ _
    have h1 : s = ∅ := by
      apply mem_ext
      intro p
      simp only [not_mem_empty, iff_false]
      intro hp
      obtain ⟨a, ha, -, -, -⟩ := mem_prod_iff.mp ((mem_function_iff.mp hs).1 p hp)
      exact not_mem_empty ha
    have h2 : s' = ∅ := by
      apply mem_ext
      intro p
      simp only [not_mem_empty, iff_false]
      intro hp
      obtain ⟨a, ha, -, -, -⟩ := mem_prod_iff.mp ((mem_function_iff.mp hs').1 p hp)
      exact not_mem_empty ha
    rw [h1, h2]
  · intro M hM ih
    obtain ⟨⟨u, hu, hul⟩, huniq⟩ := ih
    have h0mem : (∅ : V) ∈ ((2 : ℕ) : V) := (mem_two_iff _).mpr (Or.inl rfl)
    have h1mem : succ (∅ : V) ∈ ((2 : ℕ) : V) := (mem_two_iff _).mpr (Or.inr rfl)
    -- the extension: the leftmost extendible child
    have hchild : ∃ i ∈ ((2 : ℕ) : V), Extendible T (insert ⟨M, i⟩ₖ u) ∧
        (Extendible T (insert ⟨M, ∅⟩ₖ u) → i = ∅) := by
      by_cases h0 : Extendible T (insert ⟨M, ∅⟩ₖ u)
      · exact ⟨∅, h0mem, h0, fun _ ↦ rfl⟩
      · rcases extendible_child hT hu hM hul.1 with h | h
        · exact (h0 h).elim
        · exact ⟨succ ∅, h1mem, h, fun h' ↦ (h0 h').elim⟩
    obtain ⟨i, hi, hext, hleft⟩ := hchild
    have hsucc : insert ⟨M, i⟩ₖ u ∈ ((2 : ℕ) : V) ^ succ M := function_append_mem hu hi
    have hdsucc : domain (insert ⟨M, i⟩ₖ u) = succ M := domain_eq_of_mem_function hsucc
    have hrest : (insert ⟨M, i⟩ₖ u) ↾ M = u := function_append_restrict hu
    refine ⟨⟨insert ⟨M, i⟩ₖ u, hsucc, hext, fun n hn hextn ↦ ?_⟩, ?_⟩
    · rw [hdsucc] at hn
      rcases mem_succ_iff.mp hn with rfl | hnM
      · rw [hrest] at hextn
        rw [append_value hu hi]
        exact hleft hextn
      · have hMo : IsOrdinal M := IsOrdinal.nat hM
        have hnM' : n ⊆ M := IsOrdinal.toIsTransitive.transitive n hnM
        have hval : (insert ⟨M, i⟩ₖ u) ‘ n = u ‘ n := by
          have : IsFunction (insert ⟨M, i⟩ₖ u) := IsFunction.of_mem hsucc
          rw [← hrest, value_restrict (by rw [hdsucc]; exact mem_succ_iff.mpr (Or.inr hnM)) hnM]
          rw [hrest]
        have hrn : (insert ⟨M, i⟩ₖ u) ↾ n = u ↾ n := by
          have h1 : ((insert ⟨M, i⟩ₖ u) ↾ M) ↾ n = (insert ⟨M, i⟩ₖ u) ↾ n := restrict_restrict_of_subset hnM'
          rw [hrest] at h1
          exact h1.symm
        rw [hrn] at hextn
        rw [hval]
        exact hul.2 n (by rw [domain_eq_of_mem_function hu]; exact hnM) hextn
    · intro s hs s' hs' hl hl'
      -- both restrict to the unique leftmost approximation at level `M`
      have hsM : s ↾ M = u := huniq _ (function_restrict_mem hs (fun x hx ↦ mem_succ_iff.mpr (Or.inr hx)))
        u hu (leftmostApprox_restrict hT hs (ω_succ_closed hM) hl hM (fun x hx ↦ mem_succ_iff.mpr (Or.inr hx))) hul
      have hs'M : s' ↾ M = u := huniq _ (function_restrict_mem hs' (fun x hx ↦ mem_succ_iff.mpr (Or.inr hx)))
        u hu (leftmostApprox_restrict hT hs' (ω_succ_closed hM) hl' hM (fun x hx ↦ mem_succ_iff.mpr (Or.inr hx))) hul
      -- decompose both as appended sequences
      obtain ⟨t, j, ht, hj, rfl⟩ := function_succ_decompose hs
      obtain ⟨t', j', ht', hj', rfl⟩ := function_succ_decompose hs'
      rw [function_append_restrict ht] at hsM
      rw [function_append_restrict ht'] at hs'M
      rw [hsM] at hl
      rw [hs'M] at hl'
      rw [hsM, hs'M]
      -- the last values agree
      have hlast : ∀ {k : V}, k ∈ ((2 : ℕ) : V) → LeftmostApprox T (insert ⟨M, k⟩ₖ u) →
          (Extendible T (insert ⟨M, ∅⟩ₖ u) → k = ∅) ∧ (¬ Extendible T (insert ⟨M, ∅⟩ₖ u) → k = succ ∅) := by
        intro k hk hlk
        constructor
        · intro hext0
          have := hlk.2 M (by rw [domain_eq_of_mem_function (function_append_mem hu hk)]; exact mem_succ_self M)
          rw [function_append_restrict hu, append_value hu hk] at this
          exact this hext0
        · intro hnot
          rcases (mem_two_iff k).mp hk with rfl | rfl
          · exact (hnot hlk.1).elim
          · rfl
      by_cases hext0 : Extendible T (insert ⟨M, ∅⟩ₖ u)
      · rw [(hlast hj hl).1 hext0, (hlast hj' hl').1 hext0]
      · rw [(hlast hj hl).2 hext0, (hlast hj' hl').2 hext0]

/-- König's lemma for binary trees: a tree with nodes at every level has a branch. -/
theorem exists_branch_of_levels {T : V} (hT : IsTree T)
    (hlev : ∀ M ∈ (ω : V), ∃ s ∈ T, s ∈ ((2 : ℕ) : V) ^ M) : ∃ x, x ∈ treeBody T := by
  have hL := leftmostLevel_all hT hlev
  obtain ⟨B, hBdef⟩ : ∃ B : V, B = {s ∈ binarySequences V ; LeftmostApprox T s} := ⟨_, rfl⟩
  have hBmem : ∀ s, s ∈ B ↔ s ∈ binarySequences V ∧ LeftmostApprox T s := by
    intro s
    rw [hBdef]
    exact mem_sep_iff
  -- the approximations are compatible
  have hcompat : ∀ s ∈ B, ∀ s' ∈ B, s ⊆ s' ∨ s' ⊆ s := by
    intro s hs s' hs'
    obtain ⟨hsB, hsl⟩ := (hBmem s).mp hs
    obtain ⟨hs'B, hs'l⟩ := (hBmem s').mp hs'
    obtain ⟨n, hn, hsn⟩ := (mem_binarySequences_iff _).mp hsB
    obtain ⟨n', hn', hs'n⟩ := (mem_binarySequences_iff _).mp hs'B
    have : IsOrdinal n := IsOrdinal.nat hn
    have : IsOrdinal n' := IsOrdinal.nat hn'
    rcases IsOrdinal.subset_or_supset (α := n) (β := n') with h | h
    · left
      have := (hL n hn).2 s hsn (s' ↾ n) (function_restrict_mem hs'n h) hsl
        (leftmostApprox_restrict hT hs'n hn' hs'l hn h)
      rw [this]
      exact restrict_subset s' n
    · right
      have := (hL n' hn').2 s' hs'n (s ↾ n') (function_restrict_mem hsn h) hs'l
        (leftmostApprox_restrict hT hsn hn hsl hn' h)
      rw [this]
      exact restrict_subset s n'
  obtain ⟨x, hxdef⟩ : ∃ x : V, x = ⋃ˢ B := ⟨_, rfl⟩
  have hxmem : ∀ p, p ∈ x ↔ ∃ s ∈ B, p ∈ s := by
    intro p
    rw [hxdef]
    exact mem_sUnion_iff
  have hBsub : ∀ s ∈ B, s ⊆ x := fun s hs p hp ↦ (hxmem p).mpr ⟨s, hs, hp⟩
  -- `x` is a total binary function
  have hx : x ∈ ((2 : ℕ) : V) ^ (ω : V) := by
    rw [mem_function_iff]
    refine ⟨fun p hp ↦ ?_, fun k hk ↦ ?_⟩
    · obtain ⟨s, hs, hps⟩ := (hxmem p).mp hp
      obtain ⟨hsB, -⟩ := (hBmem s).mp hs
      obtain ⟨n, hn, hsn⟩ := (mem_binarySequences_iff _).mp hsB
      exact prod_subset_prod_of_subset (IsTransitive.ω.transitive n hn) (fun z hz ↦ hz) p
        ((mem_function_iff.mp hsn).1 p hps)
    · obtain ⟨⟨s, hs, hsl⟩, -⟩ := hL (succ k) (ω_succ_closed hk)
      have hsB : s ∈ B := (hBmem s).mpr ⟨(mem_binarySequences_iff _).mpr ⟨_, ω_succ_closed hk, hs⟩, hsl⟩
      have : IsFunction s := IsFunction.of_mem hs
      have hkd : k ∈ domain s := by rw [domain_eq_of_mem_function hs]; exact mem_succ_self k
      refine ⟨s ‘ k, hBsub s hsB _ (kpair_value_mem hkd), fun y hy ↦ ?_⟩
      obtain ⟨s', hs'B, hys'⟩ := (hxmem _).mp hy
      rcases hcompat s hsB s' hs'B with h | h
      · have : IsFunction s' := IsFunction.of_mem ((mem_finiteSequences_iff_domain _ _).mp ((hBmem s').mp hs'B).1).2
        exact (value_eq_of_kpair_mem hys').symm.trans (value_eq_of_kpair_mem (h _ (kpair_value_mem hkd)))
      · exact (value_eq_of_kpair_mem (h _ hys')).symm
  have hxf : IsFunction x := IsFunction.of_mem hx
  refine ⟨x, (mem_treeBody_iff _ _).mpr ⟨(mem_cantorSpace_iff x).mpr hx, fun M hM ↦ ?_⟩⟩
  obtain ⟨⟨s, hs, hsl⟩, -⟩ := hL M hM
  have hsB : s ∈ B := (hBmem s).mpr ⟨(mem_binarySequences_iff _).mpr ⟨_, hM, hs⟩, hsl⟩
  have hxM : x ↾ M = s := by
    have hxr : x ↾ M ∈ ((2 : ℕ) : V) ^ M := function_restrict_mem hx (IsTransitive.ω.transitive M hM)
    symm
    apply sequence_eq_of_subset_of_domain_eq hs hxr
    intro p hp
    obtain ⟨a, ha, b, -, rfl⟩ := mem_prod_iff.mp ((mem_function_iff.mp hs).1 p hp)
    exact kpair_mem_restrict_iff.mpr ⟨hBsub s hsB _ hp, ha⟩
  rw [hxM]
  exact extendible_mem hT hs hM hsl.1

/-- A tree with empty body has an empty level. -/
theorem exists_empty_level_of_treeBody_empty {T : V} (hT : IsTree T) (h : ∀ x, x ∉ treeBody T) :
    ∃ M ∈ (ω : V), ∀ s, s ∉ levelSet T M := by
  by_contra hcon
  push Not at hcon
  obtain ⟨x, hx⟩ := exists_branch_of_levels hT (fun M hM ↦ by
    obtain ⟨s, hs⟩ := hcon M hM
    exact ⟨s, ((mem_levelSet_iff _ _ _).mp hs).1, ((mem_levelSet_iff _ _ _).mp hs).2⟩)
  exact h x hx

end ZFVP
