"""Copy the independently defined vocabulary into Palomar's standalone statement.

Palomar forbids project imports from Challenge. The Solution imports Vocabulary
normally. Comparator checks that both environments contain the same definitions.
"""
import argparse
from pathlib import Path

root = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
vocabulary = (root / 'PalomarBridge/Vocabulary.lean').read_text(encoding='utf-8').rstrip()
statement = '''

namespace VopenkaWithoutChoice

/-- Theorem B. There is a set-sized model of ZFC plus the full parameterized
Vopěnka scheme if and only if there is such a model of ZF plus that scheme.
By first-order completeness this is the paper's equiconsistency assertion.
The domain may be externally ill-founded. No external countability assumption
is imposed. Every definition used here is given above or imported from mathlib.
-/
theorem palomar_equiconsistency :
    PalomarBridge.HasZFCVPModel ↔ PalomarBridge.HasZFVPModel := by
  sorry

end VopenkaWithoutChoice
'''
content = ('-- Generated by scripts/generate-palomar-challenge.py.\n'
           '-- Edit PalomarBridge/Vocabulary.lean and regenerate.\n' + vocabulary + '\n' + statement)
preservation = (root / 'PalomarPreservationBridge/Vocabulary.lean').read_text(encoding='utf-8')
preservation = preservation.removeprefix('import PalomarBridge.Vocabulary\n').strip()
preservation_statement = '''

namespace VopenkaWithoutChoice

/-- Theorem A. The specified symmetric quotient exists and every presentation
of it satisfies ZF and full VP. The generic is supplied; there is no external
countability, transitivity or well-foundedness assumption on the ground. -/
theorem palomar_preservation {M : Type u} (mem : M → M → Prop) [Nonempty M]
    (hZF : PalomarBridge.IsZF mem) (hVP : PalomarBridge.Coding.Vopenka mem)
    (d : PalomarPreservationBridge.SymmetricData mem) :
    (∃ (W : Type u) (wmem : W → W → Prop),
      PalomarPreservationBridge.Presentation mem d W wmem) ∧
    ∀ (W : Type u) (wmem : W → W → Prop),
      PalomarPreservationBridge.Presentation mem d W wmem →
        PalomarPreservationBridge.IsZFVPModel wmem := by
  sorry

end VopenkaWithoutChoice
'''
preservation_content = ('-- Generated by scripts/generate-palomar-challenge.py.\n'
    '-- Edit the two bridge Vocabulary.lean files and regenerate.\n'
    + vocabulary + '\n\n' + preservation + '\n' + preservation_statement)
for filename, generated in [('PalomarChallenge.lean', content),
                            ('PalomarPreservationChallenge.lean', preservation_content)]:
    output = root / filename
    if args.check:
        if not output.exists() or output.read_text(encoding='utf-8') != generated:
            raise SystemExit(f'{filename} differs from its vocabulary and statement recipe.')
        print(f'{filename} matches the shared vocabulary.')
    else:
        output.write_text(generated, encoding='utf-8', newline='\n')
        print(f'Wrote {filename}: {len(generated.splitlines())} lines, {len(generated.encode())} bytes')
