"""Copy the independently defined vocabulary into Palomar's standalone statement.

Palomar forbids project imports from Challenge. The Solution imports Vocabulary
normally. Comparator checks that both environments contain the same definitions.
"""
import argparse
from pathlib import Path

root = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser()
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
vocabulary = (root / 'PalomarBridge/Vocabulary.lean').read_text(encoding='utf-8').rstrip()
statement = '''

namespace VopenkaWithoutChoice

/-- Theorem B. There is a set-sized model of ZFC plus the full parameterized
Vopěnka scheme if and only if there is such a model of ZF plus that scheme.
By first-order completeness this is the paper's equiconsistency assertion.
The domain may be externally ill-founded. No external countability assumption
is imposed. Every definition used here is given above or imported from mathlib.
-/
theorem palomar_equiconsistency :
    PalomarBridge.HasZFCVPModel ↔ PalomarBridge.HasZFVPModel := by
  sorry

end VopenkaWithoutChoice
'''
content = ('-- Generated by scripts/generate-palomar-challenge.py.\n'
           '-- Edit PalomarBridge/Vocabulary.lean and regenerate.\n' + vocabulary + '\n' + statement)
output = root / 'PalomarChallenge.lean'
if args.check:
    if not output.exists() or output.read_text(encoding='utf-8') != content:
        raise SystemExit('PalomarChallenge.lean differs from the vocabulary and statement recipe.')
    print('Standalone Challenge matches the shared vocabulary.')
else:
    output.write_text(content, encoding='utf-8', newline='\n')
    print(f'Wrote {output.name}: {len(content.splitlines())} lines, {len(content.encode())} bytes')
