import ZFVP.SetTheory.BlockCohenNames
import ZFVP.ModelTheory.CohenModel

/-!
The symmetric model of Jech's first embedding theorem, packaged as a `SymmetricContext`: Cohen
forcing over `ω ×ˢ ω`, the group of Cohen automorphisms coming from a block permutation, and the
filter generated by pointwise stabilizers of finite sets of conditions.

The objects named here are the Cohen real of an index in `ω ×ˢ ω`, the block of `ω` reals with a
fixed first coordinate, and the set of all `ω` blocks, together with the membership descriptions
and the distinctness facts for reals and for blocks.
-/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-- The block Cohen symmetric system as a symmetric forcing context. -/
noncomputable def blockCohenContext (G : Set V)
    (hG : IsExternalForcingGeneric (cohenConditions ((ω : V) ×ˢ (ω : V)))
      (cohenOrder ((ω : V) ×ˢ (ω : V))) G) : SymmetricContext V where
  P := cohenConditions ((ω : V) ×ˢ (ω : V))
  R := cohenOrder ((ω : V) ×ˢ (ω : V))
  G := G
  order := (cohen_poset ((ω : V) ×ˢ (ω : V))).1
  generic := hG
  one := ∅
  top := cohen_top ((ω : V) ×ˢ (ω : V))
  Γ := blockCohenGroup
  F := blockCohenFilter
  poset := cohen_poset ((ω : V) ×ˢ (ω : V))
  group := blockCohenGroup_group
  normal := blockCohenFilter_normal

namespace BlockCohenModel

variable {G : Set V} (hG : IsExternalForcingGeneric (cohenConditions ((ω : V) ×ˢ (ω : V)))
  (cohenOrder ((ω : V) ×ˢ (ω : V))) G)

/-- The Cohen real of an index `i ∈ ω ×ˢ ω`, as an element of the symmetric model. -/
noncomputable def real (i : V) (hi : i ∈ (ω : V) ×ˢ (ω : V)) : (blockCohenContext G hG).Model :=
  (blockCohenContext G hG).ofName
    ⟨cohenRealName ((ω : V) ×ˢ (ω : V)) i, cohenRealName_blockHereditarilySymmetric hi⟩

/-- The block of the `ω` Cohen reals whose index has first coordinate `a`. -/
noncomputable def block (a : V) (ha : a ∈ (ω : V)) : (blockCohenContext G hG).Model :=
  (blockCohenContext G hG).ofName ⟨blockName a, blockName_hereditarilySymmetric ha⟩

/-- The set of all `ω` blocks. -/
noncomputable def blocks : (blockCohenContext G hG).Model :=
  (blockCohenContext G hG).ofName ⟨blockSetName, blockSetName_hereditarilySymmetric⟩

theorem mem_real_iff (i : V) (hi : i ∈ (ω : V) ×ˢ (ω : V)) (x : (blockCohenContext G hG).Model) :
    x ∈ real hG i hi ↔ ∃ n ∈ (ω : V), ∃ p ∈ G,
      ⟨⟨i, n⟩ₖ, (1 : V)⟩ₖ ∈ p ∧ x = (blockCohenContext G hG).check n := by
  let S := blockCohenContext G hG
  rw [real, S.mem_ofName_iff]
  constructor
  · rintro ⟨σ, p, hp, hσp, hx⟩
    obtain ⟨_, n, hn, hσ, hb⟩ :=
      (pair_mem_cohenRealName ((ω : V) ×ˢ (ω : V)) i σ.val p).mp hσp
    have he : S.ofName σ = S.check n := congrArg S.ofName (Subtype.ext hσ)
    exact ⟨n, hn, p, hp, hb, hx.trans he⟩
  · rintro ⟨n, hn, p, hp, hb, rfl⟩
    refine ⟨⟨checkName ∅ n, hereditarilySymmetric_checkName (cohen_poset ((ω : V) ×ˢ (ω : V)))
      blockCohenGroup_group blockCohenFilter_normal (cohen_top ((ω : V) ×ˢ (ω : V))) n⟩,
      p, hp, ?_, rfl⟩
    exact (pair_mem_cohenRealName ((ω : V) ×ˢ (ω : V)) i _ p).mpr ⟨hG.1.1 p hp, n, hn, rfl, hb⟩

theorem check_mem_real_iff {i n : V} (hi : i ∈ (ω : V) ×ˢ (ω : V)) :
    (blockCohenContext G hG).check n ∈ real hG i hi ↔
      n ∈ (ω : V) ∧ ∃ p ∈ G, ⟨⟨i, n⟩ₖ, (1 : V)⟩ₖ ∈ p := by
  rw [mem_real_iff]
  constructor
  · rintro ⟨m, hm, p, hp, hb, he⟩
    obtain rfl := ((blockCohenContext G hG).check_eq_iff n m).mp he
    exact ⟨hm, p, hp, hb⟩
  · rintro ⟨hn, p, hp, hb⟩
    exact ⟨n, hn, p, hp, hb, rfl⟩

theorem check_not_mem_real_of_zero {i n p : V} (hi : i ∈ (ω : V) ×ˢ (ω : V)) (hp : p ∈ G)
    (hb : ⟨⟨i, n⟩ₖ, (0 : V)⟩ₖ ∈ p) : (blockCohenContext G hG).check n ∉ real hG i hi := by
  intro hm
  obtain ⟨_, q, hq, hqbit⟩ := (check_mem_real_iff hG hi).mp hm
  have hc := (finitePartialFunctions_compatible_iff (hG.1.1 p hp) (hG.1.1 q hq)).mp
    (externalForcingFilter_compatible hG.1 hp hq)
  have h01 := hc ⟨i, n⟩ₖ 0 1 hb hqbit
  simp at h01

theorem real_ne {i j : V} (hi : i ∈ (ω : V) ×ˢ (ω : V)) (hj : j ∈ (ω : V) ×ˢ (ω : V))
    (hij : i ≠ j) : real hG i hi ≠ real hG j hj := by
  obtain ⟨p, hp, hpd⟩ := hG.2 _ (cohen_separate_rows_dense hi hj hij)
  obtain ⟨_, n, hn, hb0, hb1⟩ := mem_sep_iff.mp hpd
  intro he
  have hnmem := (check_mem_real_iff hG hj).mpr ⟨hn, p, hp, hb1⟩
  exact check_not_mem_real_of_zero hG hi hp hb0 (he.symm ▸ hnmem)

theorem real_eq_iff {i j : V} (hi : i ∈ (ω : V) ×ˢ (ω : V)) (hj : j ∈ (ω : V) ×ˢ (ω : V)) :
    real hG i hi = real hG j hj ↔ i = j := by
  constructor
  · intro he
    by_contra hn
    exact real_ne hG hi hj hn he
  · rintro rfl
    rfl

theorem mem_block_iff (a : V) (ha : a ∈ (ω : V)) (x : (blockCohenContext G hG).Model) :
    x ∈ block hG a ha ↔ ∃ ξ, ∃ hξ : ξ ∈ (ω : V),
      x = real hG ⟨a, ξ⟩ₖ (kpair_mem_iff.mpr ⟨ha, hξ⟩) := by
  let S := blockCohenContext G hG
  rw [block, S.mem_ofName_iff]
  constructor
  · rintro ⟨σ, p, hp, hσp, hx⟩
    obtain ⟨ξ, hξ, he⟩ := (mem_blockName a _).mp hσp
    obtain ⟨hσv, rfl⟩ := kpair_iff.mp he
    refine ⟨ξ, hξ, hx.trans (congrArg S.ofName (Subtype.ext hσv))⟩
  · rintro ⟨ξ, hξ, rfl⟩
    exact ⟨⟨cohenRealName ((ω : V) ×ˢ (ω : V)) ⟨a, ξ⟩ₖ,
      cohenRealName_blockHereditarilySymmetric (kpair_mem_iff.mpr ⟨ha, hξ⟩)⟩, ∅,
      externalForcingFilter_top hG.1 (cohen_top ((ω : V) ×ˢ (ω : V))),
      (mem_blockName a _).mpr ⟨ξ, hξ, rfl⟩, rfl⟩

theorem mem_blocks_iff (x : (blockCohenContext G hG).Model) :
    x ∈ blocks hG ↔ ∃ a, ∃ ha : a ∈ (ω : V), x = block hG a ha := by
  let S := blockCohenContext G hG
  rw [blocks, S.mem_ofName_iff]
  constructor
  · rintro ⟨σ, p, hp, hσp, hx⟩
    obtain ⟨a, ha, he⟩ := (mem_blockSetName _).mp hσp
    obtain ⟨hσv, rfl⟩ := kpair_iff.mp he
    exact ⟨a, ha, hx.trans (congrArg S.ofName (Subtype.ext hσv))⟩
  · rintro ⟨a, ha, rfl⟩
    exact ⟨⟨blockName a, blockName_hereditarilySymmetric ha⟩, ∅,
      externalForcingFilter_top hG.1 (cohen_top ((ω : V) ×ˢ (ω : V))),
      (mem_blockSetName _).mpr ⟨a, ha, rfl⟩, rfl⟩

theorem block_mem_blocks (a : V) (ha : a ∈ (ω : V)) : block hG a ha ∈ blocks hG :=
  (mem_blocks_iff hG _).mpr ⟨a, ha, rfl⟩

theorem block_ne {a b : V} (ha : a ∈ (ω : V)) (hb : b ∈ (ω : V)) (hab : a ≠ b) :
    block hG a ha ≠ block hG b hb := by
  have h0 : (0 : V) ∈ (ω : V) := by simp
  intro he
  have hmem : real hG ⟨a, (0 : V)⟩ₖ (kpair_mem_iff.mpr ⟨ha, h0⟩) ∈ block hG a ha :=
    (mem_block_iff hG a ha _).mpr ⟨0, h0, rfl⟩
  rw [he] at hmem
  obtain ⟨η, hη, heq⟩ := (mem_block_iff hG b hb _).mp hmem
  have := (real_eq_iff hG (kpair_mem_iff.mpr ⟨ha, h0⟩)
    (kpair_mem_iff.mpr ⟨hb, hη⟩)).mp heq
  exact hab (kpair_iff.mp this).1

theorem block_eq_iff {a b : V} (ha : a ∈ (ω : V)) (hb : b ∈ (ω : V)) :
    block hG a ha = block hG b hb ↔ a = b := by
  constructor
  · intro he
    by_contra hn
    exact block_ne hG ha hb hn he
  · rintro rfl
    rfl

end BlockCohenModel
end ZFVP
