import ZFVP.ModelTheory.GeneratedSubalgebraTrace
import ZFVP.ModelTheory.GroundRealsHODClosure

/-! For a Boolean name `τ` of a real, the ground sequence `n ↦ ‖ň ∈ τ‖` of Boolean values is met
by the generic exactly at the members of the real; hence the trace of the generic on the complete
subalgebra generated by these Boolean values is definable in `V[G]` from the real and ground
parameters (KS-style identification of the generic on the subalgebra generated by a real). -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

theorem standardTuple_two (a b : V) :
    standardTuple ![a, b] = assignmentPrepend (succ ∅) (assignmentPrepend ∅ ∅ b) a := by
  simp only [standardTuple, Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons]
  have h1 : ((1 : ℕ) : V) = succ ∅ := by
    rw [num_succ_def 0]
    rfl
  have h0 : ((0 : ℕ) : V) = ∅ := rfl
  rw [h1, h0]
  rfl

namespace ForcingContext

variable (A : ForcingContext V)

/-- The Boolean value of `ň ∈ τ` as a function of `n`. -/
noncomputable def booleanMemValue (τ : V) (n : V) : V :=
  A.booleanValue memAtom ![checkName A.booleanContext.one n, τ]

theorem booleanMemValue_definable (τ : V) : ℒₛₑₜ-function₁[V] (A.booleanMemValue τ) := by
  have h : ℒₛₑₜ-relation (fun d n : V ↦ d = regularJoin A.P A.R
      (forcingFormula (booleanConditions A.P A.R) (booleanOrder A.P A.R) memAtom
        (assignmentPrepend (succ ∅) (assignmentPrepend ∅ ∅ τ) (checkName A.booleanContext.one n)))) := by
    have := regularJoin_definable_one A.P A.R
    have := forcingFormula_definable (booleanConditions A.P A.R) (booleanOrder A.P A.R) memAtom
    definability
  apply Language.Definable.of_iff h
  intro v
  change v 0 = A.booleanMemValue τ (v 1) ↔ _
  unfold booleanMemValue booleanValue
  rw [standardTuple_two]

/-- The ground sequence of Boolean values of `ň ∈ τ`. -/
noncomputable def booleanValueSequence (τ : V) : V :=
  definableGraph (ω : V) (A.booleanMemValue τ) (A.booleanMemValue_definable τ)

theorem booleanValueSequence_mem_function (τ : V) :
    A.booleanValueSequence τ ∈ regularSets A.P A.R ^ (ω : V) :=
  definableGraph_mem_function_of_mapsTo _ _ _ _
    (fun n _ ↦ (mem_regularSets_iff _ _ _).mpr (A.booleanValue_regular memAtom _))

theorem booleanValueSequence_value {τ n : V} (hn : n ∈ (ω : V)) :
    (A.booleanValueSequence τ) ‘ n = A.booleanMemValue τ n :=
  value_definableGraph _ _ _ hn

/-- The Boolean value of `ň ∈ τ` is met by the generic exactly when `ň ∈ τ` holds. -/
theorem booleanMemValue_meets (τ : ForcingName A.booleanContext.P) (n : V) :
    (∃ p ∈ A.G, p ∈ A.booleanMemValue τ.val n) ↔ A.booleanContext.check n ∈ A.booleanContext.ofName τ := by
  let B := A.booleanContext
  let v : Fin 2 → ForcingName B.P := ![⟨checkName B.one n, checkName_isName B.top.1 n⟩, τ]
  have hv : (fun i ↦ (v i).val) = ![checkName B.one n, τ.val] := by
    funext i
    refine Fin.cases rfl (fun j ↦ Fin.cases rfl (fun k ↦ k.elim0) j) i
  have h := A.booleanValue_truth_meets memAtom v
  rw [hv] at h
  change (∃ p ∈ A.G, p ∈ A.booleanValue memAtom ![checkName B.one n, τ.val]) ↔ _
  change GenericMeets A.G (A.booleanValue memAtom ![checkName B.one n, τ.val]) ↔ _
  rw [← h]
  simp only [memAtom]
  simp
  rfl

/-- The real named by `τ`, transported into `V[G]`. -/
noncomputable def booleanReal (τ : ForcingName A.booleanContext.P) : A.Model :=
  A.booleanEquiv.symm (A.booleanContext.ofName τ)

theorem check_mem_booleanReal_iff (τ : ForcingName A.booleanContext.P) (n : V) :
    A.check n ∈ A.booleanReal τ ↔ A.booleanContext.check n ∈ A.booleanContext.ofName τ := by
  unfold booleanReal
  rw [← A.booleanEquiv_mem_iff, A.booleanEquiv_check, Equiv.apply_symm_apply]

theorem booleanReal_subset (τ : ForcingName A.booleanContext.P)
    (hτ : A.booleanContext.ofName τ ⊆ A.booleanContext.check (ω : V)) :
    A.booleanReal τ ⊆ A.check (ω : V) := by
  intro z hz
  unfold booleanReal at hz
  rw [← A.booleanEquiv_mem_iff, Equiv.apply_symm_apply] at hz
  rw [← A.booleanEquiv_mem_iff, A.booleanEquiv_check]
  exact hτ _ hz

/-- The trace of the generic on the subalgebra generated by the Boolean values of a real name is
definable from the real and ground parameters. -/
theorem booleanReal_trace_groundRealDefinable (hAC : InternalChoice V)
    (τ : ForcingName A.booleanContext.P)
    (hτ : A.booleanContext.ofName τ ⊆ A.booleanContext.check (ω : V)) :
    A.IsGroundRealDefinable
      (A.genericTrace (generatedSubalgebra A.P A.R (range (A.booleanValueSequence τ.val)))) := by
  apply A.genericTrace_groundRealDefinable hAC (A.booleanReal_subset τ hτ) (A.booleanValueSequence_mem_function τ.val)
  intro n hn
  rw [A.booleanValueSequence_value hn, A.booleanMemValue_meets τ n, A.check_mem_booleanReal_iff]

end ForcingContext

end ZFVP
