import ZFVP.ModelTheory.GeneratedSubalgebraGeneric
import ZFVP.ModelTheory.GroundRealsHOD

/-! The trace of the generic on the subalgebra generated by a real is definable from the real:
if a ground sequence `s : ω → RO(P)` of regular sets is met by the generic exactly at the members
of a real `x`, then `G ∩ D` for `D` generated by the range of `s` is the unique antichain-generic
ultrafilter of the checked completion agreeing with `x` along `s`, hence ground-real definable. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

/-- `d ∈ D` and some antichain-generic ultrafilter `U` on `Reg` (relative to `MA`) with
`val n ∈ U ↔ n ∈ x` for `n ∈ w` contains `d`. -/
def traceFormula : SetTheorySemisentence 7 :=
  f“d D Reg MA val w x. d ∈ D ∧ ∃ U, (∀ u ∈ U, u ∈ Reg) ∧
    (∀ u ∈ U, ∀ u' ∈ Reg, u ⊆ u' → u' ∈ U) ∧ (∀ u ∈ U, ∀ u' ∈ U, !inter.dfn u u' ∈ U) ∧
    (∀ u ∈ U, ∃ z, z ∈ u) ∧ (∀ A ∈ MA, ∃ a ∈ A, a ∈ U) ∧
    (∀ n ∈ w, (!value.dfn val n ∈ U ↔ n ∈ x)) ∧ d ∈ U”

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

theorem eval_traceFormula (d D Reg MA val w x : V) :
    traceFormula.Evalb ![d, D, Reg, MA, val, w, x] ↔
      d ∈ D ∧ ∃ U : V, (∀ u ∈ U, u ∈ Reg) ∧
        (∀ u ∈ U, ∀ u' ∈ Reg, u ⊆ u' → u' ∈ U) ∧ (∀ u ∈ U, ∀ u' ∈ U, u ∩ u' ∈ U) ∧
        (∀ u ∈ U, ∃ z, z ∈ u) ∧ (∀ A ∈ MA, ∃ a ∈ A, a ∈ U) ∧
        (∀ n ∈ w, (val ‘ n ∈ U ↔ n ∈ x)) ∧ d ∈ U := by
  simp [traceFormula]

namespace ForcingContext

variable (A : ForcingContext V)

/-- The trace of the generic on a checked set of regular sets. -/
noncomputable def genericTrace (D : V) : A.Model :=
  {d ∈ A.check D ; d ∈ A.boolGenericSet}

theorem antichainGeneric_of_clauses {Reg MA U : V}
    (h1 : ∀ u ∈ U, u ∈ Reg) (h2 : ∀ u ∈ U, ∀ u' ∈ Reg, u ⊆ u' → u' ∈ U)
    (h3 : ∀ u ∈ U, ∀ u' ∈ U, u ∩ u' ∈ U) (h4 : ∀ u ∈ U, ∃ z, z ∈ u)
    (h5 : ∀ M ∈ MA, ∃ a ∈ M, a ∈ U) : IsAntichainGeneric Reg MA U :=
  ⟨h1, h2, h3, fun h ↦ by obtain ⟨z, hz⟩ := h4 ∅ h; exact not_mem_empty hz, h5⟩

/-- The trace of the generic on the subalgebra generated by a Boolean-value sequence of a real is
definable from the real and ground parameters. -/
theorem genericTrace_groundRealDefinable (hAC : InternalChoice V) {x : A.Model}
    (hx : x ⊆ A.check (ω : V)) {s : V} (hs : s ∈ regularSets A.P A.R ^ (ω : V))
    (hval : ∀ n ∈ (ω : V), ((∃ p ∈ A.G, p ∈ s ‘ n) ↔ A.check n ∈ x)) :
    A.IsGroundRealDefinable (A.genericTrace (generatedSubalgebra A.P A.R (range s))) := by
  have hsfun : IsFunction s := IsFunction.of_mem hs
  have hsdom : domain s = (ω : V) := domain_eq_of_mem_function hs
  have hS : range s ⊆ regularSets A.P A.R := range_subset_of_mem_function hs
  refine ⟨6, traceFormula, ![A.check (generatedSubalgebra A.P A.R (range s)), A.check (regularSets A.P A.R),
    A.check (boolMaximalAntichains A.P A.R), A.check s, A.check (ω : V), x], ?_, fun b ↦ ?_⟩
  · intro i
    match i with
    | 0 => exact Or.inl ⟨_, rfl⟩
    | 1 => exact Or.inl ⟨_, rfl⟩
    | 2 => exact Or.inl ⟨_, rfl⟩
    | 3 => exact Or.inl ⟨_, rfl⟩
    | 4 => exact Or.inl ⟨_, rfl⟩
    | 5 => exact Or.inr (Or.inl hx)
  · have he := eval_traceFormula b (A.check (generatedSubalgebra A.P A.R (range s)))
      (A.check (regularSets A.P A.R)) (A.check (boolMaximalAntichains A.P A.R)) (A.check s)
      (A.check (ω : V)) x
    change b ∈ A.genericTrace _ ↔ traceFormula.Evalb ![b, _, _, _, _, _, _]
    rw [he]
    unfold genericTrace
    rw [mem_sep_iff]
    -- values of the checked sequence
    have hcheckval : ∀ n₀ ∈ (ω : V), (A.check s) ‘ (A.check n₀) = A.check (s ‘ n₀) :=
      fun n₀ hn₀ ↦ A.check_value (by rw [hsdom]; exact hn₀)
    have hgen := A.boolGenericSet_antichainGeneric
    constructor
    · rintro ⟨hbD, hbU⟩
      refine ⟨hbD, A.boolGenericSet, hgen.subset, hgen.upward, hgen.inter, ?_, hgen.meets, ?_, hbU⟩
      · intro u hu
        obtain ⟨_, p, _, hp⟩ := mem_sep_iff.mp hu
        exact ⟨p, hp⟩
      · intro n hn
        obtain ⟨n₀, hn₀, rfl⟩ := (A.mem_check_iff _ _).mp hn
        rw [hcheckval n₀ hn₀, A.check_mem_boolGenericSet_iff, ← hval n₀ hn₀]
        constructor
        · rintro ⟨_, h⟩
          exact h
        · intro h
          exact ⟨range_subset_of_mem_function hs _ (value_mem_range hs hn₀), h⟩
    · rintro ⟨hbD, U, h1, h2, h3, h4, h5, hvalU, hbU⟩
      refine ⟨hbD, ?_⟩
      have hU := antichainGeneric_of_clauses h1 h2 h3 h4 h5
      have hagree : ∀ t ∈ A.check (range s), (t ∈ A.boolGenericSet ↔ t ∈ U) := by
        intro t ht
        obtain ⟨t₀, ht₀, rfl⟩ := (A.mem_check_iff _ _).mp ht
        obtain ⟨n₀, hn₀⟩ := mem_range_iff.mp ht₀
        have hn₀ω : n₀ ∈ (ω : V) := hsdom ▸ mem_domain_of_kpair_mem hn₀
        have ht₀eq : t₀ = s ‘ n₀ := (value_eq_of_kpair_mem hn₀).symm
        have hU' := hvalU (A.check n₀) ((A.check_mem_iff _ _).mpr hn₀ω)
        rw [hcheckval n₀ hn₀ω] at hU'
        rw [ht₀eq, A.check_mem_boolGenericSet_iff, hU', ← hval n₀ hn₀ω]
        constructor
        · rintro ⟨_, h⟩
          exact h
        · intro h
          exact ⟨range_subset_of_mem_function hs _ (value_mem_range hs hn₀ω), h⟩
      exact (A.generatedSubalgebra_generic_unique hAC hS hU hagree b hbD).mpr hbU

end ForcingContext

end ZFVP
