import ZFVP.ModelTheory.GenericFilterTrace
import ZFVP.SetTheory.TraceStagesTransport
import ZFVP.ModelTheory.ForcingRealizationGeneration

/-! The intermediate model of a generic filter: a filter `H` of the extension on a checked ground
poset `Q` that meets every ground dense set determines a forcing context over the ground with
poset `Q`, and its extension is isomorphic to the extension by the complete subalgebra generated
by the Boolean values `‖q̌ ∈ Ḣ‖`, compatibly with checks; the generic of the `Q`-context corresponds
to `H`. The isomorphism is the value map of a realization; it is onto because the generic of the
subalgebra extension is the trace recursion, transported along the realization. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

theorem MembershipEndExtension.map_image {W : Type*} [SetStructure W] [Nonempty W] [W↓[ℒₛₑₜ] ⊧* 𝗭𝗙]
    (j : MembershipEndExtension V W) (f X : V) : j (image f X) = image (j f) (j X) := by
  unfold image
  rw [j.map_range, j.map_restrict]

namespace ForcingContext

variable (A : ForcingContext V)

theorem genericSet_subset_check_P : A.genericSet ⊆ A.check A.P := by
  intro x hx
  obtain ⟨p, hp, rfl⟩ := (A.mem_genericSet_iff x).mp hx
  exact (A.check_mem_iff _ _).mpr (A.generic.1.1 p hp)

theorem booleanEquiv_eq_value (x : A.Model) : A.booleanEquiv x = A.recoveredRealization.value x := rfl

/-- The Boolean generic set of the poset extension corresponds to the generic set of the Boolean
extension. -/
theorem booleanEquiv_boolGenericSet : A.booleanEquiv A.boolGenericSet = A.booleanContext.genericSet := by
  apply mem_ext
  intro y
  obtain ⟨x, rfl⟩ := A.booleanEquiv.surjective y
  rw [A.booleanEquiv_mem_iff, A.booleanContext.mem_genericSet_iff]
  constructor
  · intro hx
    have hx' := (mem_sep_iff.mp hx).1
    obtain ⟨d₀, hd₀, rfl⟩ := (A.mem_check_iff _ _).mp hx'
    obtain ⟨hreg, p, hp, hpd⟩ := (A.check_mem_boolGenericSet_iff d₀).mp hx
    refine ⟨d₀, ?_, A.booleanEquiv_check d₀⟩
    change d₀ ∈ booleanGeneric A.P A.R A.G
    exact (mem_booleanGeneric_iff _ _ _ _).mpr
      ⟨(mem_booleanConditions_iff _ _ _).mpr ⟨(mem_regularSets_iff _ _ _).mp hreg, p, hpd⟩, p, hp, hpd⟩
  · rintro ⟨d₀, hd₀, he⟩
    rw [← A.booleanEquiv_check d₀] at he
    rw [A.booleanEquiv.injective he]
    change d₀ ∈ booleanGeneric A.P A.R A.G at hd₀
    obtain ⟨hcond, p, hp, hpd⟩ := (mem_booleanGeneric_iff _ _ _ _).mp hd₀
    exact (A.check_mem_boolGenericSet_iff d₀).mpr
      ⟨(mem_regularSets_iff _ _ _).mpr ((mem_booleanConditions_iff _ _ _).mp hcond).1, p, hp, hpd⟩

section

variable {Q S one : V} (hQ : IsForcingPreorder Q S) (htop : IsForcingTop Q S one)
  {H : A.Model} (hHQ : H ⊆ A.check Q) (hfilter : IsForcingFilter (A.check Q) (A.check S) H)
  (hgen : ∀ D : V, ForcingDense Q S D → ∃ q ∈ D, A.check q ∈ H)

/-- The external filter read off `H`. -/
def filterTrace : Set V := {q | A.check q ∈ H}

include hHQ hfilter hgen in
theorem filterTrace_generic : IsExternalForcingGeneric Q S (A.filterTrace (H := H)) := by
  refine ⟨⟨?_, ?_, ?_, ?_⟩, fun D hD ↦ ?_⟩
  · intro p hp
    exact (A.check_mem_iff _ _).mp (hHQ _ hp)
  · obtain ⟨p, hp⟩ := hfilter.2.1
    obtain ⟨p₀, _, rfl⟩ := (A.mem_check_iff _ _).mp (hHQ p hp)
    exact ⟨p₀, hp⟩
  · intro p hp q hq hpq
    have := hfilter.2.2.1 (A.check p) hp (A.check q) ((A.check_mem_iff _ _).mpr hq)
      (by rw [← A.check_kpair]; exact (A.check_mem_iff _ _).mpr hpq)
    exact this
  · intro p hp q hq
    obtain ⟨r, hr, hrp, hrq⟩ := hfilter.2.2.2 (A.check p) hp (A.check q) hq
    obtain ⟨r₀, _, rfl⟩ := (A.mem_check_iff _ _).mp (hHQ r hr)
    rw [← A.check_kpair, A.check_mem_iff] at hrp hrq
    exact ⟨r₀, hr, hrp, hrq⟩
  · obtain ⟨q, hq, hqH⟩ := hgen D hD
    exact ⟨q, hqH, hq⟩

/-- The forcing context of `Q` with the generic read off `H`. -/
noncomputable def filterContext : ForcingContext V where
  P := Q
  R := S
  one := one
  G := A.filterTrace (H := H)
  order := hQ
  top := htop
  generic := A.filterTrace_generic hHQ hfilter hgen

theorem filterContext_P : (A.filterContext hQ htop hHQ hfilter hgen).P = Q := rfl
theorem filterContext_R : (A.filterContext hQ htop hHQ hfilter hgen).R = S := rfl
theorem filterContext_one : (A.filterContext hQ htop hHQ hfilter hgen).one = one := rfl
theorem mem_filterContext_G (q : V) : q ∈ (A.filterContext hQ htop hHQ hfilter hgen).G ↔ A.check q ∈ H :=
  Iff.rfl

include hQ htop hHQ hfilter hgen in
/-- The extension by `Q` with generic `H` is the extension by the complete subalgebra generated by
the Boolean values of membership in `H`, compatibly with checks, the generic corresponding to
`H`. -/
theorem exists_intermediate_equiv (hAC : InternalChoice V) :
    ∃ (D : V) (hD : IsCompleteSubalgebra A.P A.R D)
      (f : (A.filterContext hQ htop hHQ hfilter hgen).Model ≃ (A.subalgebraContext hD).Model),
      (∀ x y, f x ∈ f y ↔ x ∈ y) ∧
      (∀ a : V, f ((A.filterContext hQ htop hHQ hfilter hgen).check a) = (A.subalgebraContext hD).check a) ∧
      (A.subalgebraRealization hD).value (f (A.filterContext hQ htop hHQ hfilter hgen).genericSet) =
        A.booleanEquiv H := by
  obtain ⟨C, hC⟩ : ∃ C : ForcingContext V, C = A.filterContext hQ htop hHQ hfilter hgen := ⟨_, rfl⟩
  have hCP : C.P = Q := by rw [hC]; rfl
  have hCG : ∀ q, q ∈ C.G ↔ A.check q ∈ H := by rw [hC]; exact fun q ↦ Iff.rfl
  let B := A.booleanContext
  obtain ⟨τ, hτ⟩ := B.ofName_surjective (A.booleanEquiv H)
  have hτQ : B.ofName τ ⊆ B.check Q := by
    intro y hy
    rw [hτ] at hy
    obtain ⟨y', rfl⟩ := A.booleanEquiv.surjective y
    rw [A.booleanEquiv_mem_iff] at hy
    rw [← A.booleanEquiv_check, A.booleanEquiv_mem_iff]
    exact hHQ y' hy
  have hH : ∀ q ∈ Q, A.check q ∈ H ↔ B.check q ∈ B.ofName τ := by
    intro q _
    rw [hτ, ← A.booleanEquiv_check, A.booleanEquiv_mem_iff]
  obtain ⟨s, hs⟩ : ∃ s : V, s = A.booleanValueFamily τ.val Q := ⟨_, rfl⟩
  have hsf : s ∈ regularSets A.P A.R ^ Q := by
    rw [hs]
    exact A.booleanValueFamily_mem_function τ.val Q
  have hsfun : IsFunction s := IsFunction.of_mem hsf
  have hsdom : domain s = Q := domain_eq_of_mem_function hsf
  have hS : range s ⊆ regularSets A.P A.R := range_subset_of_mem_function hsf
  obtain ⟨D, hDdef⟩ : ∃ D : V, D = generatedSubalgebra A.P A.R (range s) := ⟨_, rfl⟩
  have hD : IsCompleteSubalgebra A.P A.R D := by
    rw [hDdef]
    exact generatedSubalgebra_complete A.order hS
  have hrange : range s ⊆ D := by
    rw [hDdef]
    exact subset_generatedSubalgebra _ _ _
  let M := A.subalgebraContext hD
  have hMG : ∀ d, d ∈ M.G ↔ d ∈ B.G ∧ d ∈ subalgebraConditions A.P A.R D := fun d ↦ Iff.rfl
  have hMone : M.one = B.one := rfl
  have hMP : M.P = subalgebraConditions A.P A.R D := rfl
  -- the copy of `H` inside the subalgebra extension
  let ν : ForcingName M.P := ⟨decisionName M.one s Q M.P, decisionName_isName M.top.1⟩
  have hνmem : ∀ q, M.check q ∈ M.ofName ν ↔ A.check q ∈ H := by
    intro q
    rw [M.mem_ofName_decisionName]
    constructor
    · rintro ⟨q', hq', hq'G, he⟩
      rw [M.check_eq_iff] at he
      subst he
      have hval : s ‘ q = A.booleanMemValue τ.val q := by
        rw [hs]
        exact A.booleanValueFamily_value hq'
      rw [hH q hq', ← A.booleanMemValue_mem_generic_iff, ← hval]
      exact ((hMG _).mp hq'G).1
    · intro hq
      have hqQ : q ∈ Q := (A.check_mem_iff _ _).mp (hHQ _ hq)
      refine ⟨q, hqQ, ?_, rfl⟩
      have hval : s ‘ q = A.booleanMemValue τ.val q := by
        rw [hs]
        exact A.booleanValueFamily_value hqQ
      have hBG : s ‘ q ∈ B.G := by
        rw [hval, A.booleanMemValue_mem_generic_iff]
        exact (hH q hqQ).mp hq
      refine (hMG _).mpr ⟨hBG, (mem_subalgebraConditions_iff _ _ _ _).mpr
        ⟨hrange _ (value_mem_range hsf hqQ), B.generic.1.1 _ hBG⟩⟩
  have hνsub : M.ofName ν ⊆ M.check Q := by
    intro x hx
    obtain ⟨q, hq, _, rfl⟩ := (M.mem_ofName_decisionName _ _ _).mp hx
    exact (M.check_mem_iff _ _).mpr hq
  -- the realization of the `Q`-extension inside the subalgebra extension
  let L : ForcingRealization C M.Model :=
    { ground := M.checkEmbedding
      genericSet := M.ofName ν
      generic_subset := by rw [hCP]; exact hνsub
      generic_mem := fun q ↦ by rw [hCG]; exact hνmem q }
  have hLground : ∀ x : V, L.ground x = M.check x := fun _ ↦ rfl
  have hLgen : L.genericSet = M.ofName ν := rfl
  -- the copy of `H` in the Boolean extension
  have hL'ν : (A.subalgebraRealization hD).value (M.ofName ν) = A.booleanEquiv H := by
    have h := A.subalgebraRealization_value_decisionName hD τ hτQ (by rw [← hs]; exact hrange)
    rw [← hs] at h
    rw [← hτ]
    exact h
  -- the generic of the subalgebra extension is the value of the trace recursion
  have hsurj : Function.Surjective L.value := by
    apply ForcingRealization.value_surjective_of_generators M L (fun x ↦ ⟨C.check x, L.value_check x⟩)
    refine ⟨traceSet (C.check A.P) (C.check A.R) (C.check (℘ (regularSets A.P A.R)))
      (C.check (insert A.P (range s))) (C.generatorDecisions A.P s C.genericSet)
      (C.check (closureStages A.P A.R (insert A.P (range s)) (stageBound A.P A.R)))
      (C.check (stageBound A.P A.R)), ?_⟩
    have hmap := L.embedding.map_traceSet (C.check A.P) (C.check A.R) (C.check (℘ (regularSets A.P A.R)))
      (C.check (insert A.P (range s))) (C.generatorDecisions A.P s C.genericSet)
      (C.check (closureStages A.P A.R (insert A.P (range s)) (stageBound A.P A.R)))
      (C.check (stageBound A.P A.R))
    change L.value _ = _ at hmap
    rw [hmap]
    have hvc : ∀ x : V, L.value (C.check x) = M.check x := fun x ↦ L.value_check x
    have hdec : L.value (C.generatorDecisions A.P s C.genericSet) = M.generatorDecisions A.P s (M.ofName ν) := by
      unfold generatorDecisions
      have h1 : L.value (insert (C.check A.P) (image (C.check s) C.genericSet)) =
          insert (L.value (C.check A.P)) (L.value (image (C.check s) C.genericSet)) :=
        L.embedding.map_insert _ _
      have h2 : L.value (image (C.check s) C.genericSet) =
          image (L.value (C.check s)) (L.value C.genericSet) := L.embedding.map_image _ _
      rw [h1, h2, hvc, hvc, L.value_genericSet, hLgen]
    change traceSet (L.value (C.check A.P)) (L.value (C.check A.R)) (L.value (C.check (℘ (regularSets A.P A.R))))
      (L.value (C.check (insert A.P (range s)))) (L.value (C.generatorDecisions A.P s C.genericSet))
      (L.value (C.check (closureStages A.P A.R (insert A.P (range s)) (stageBound A.P A.R))))
      (L.value (C.check (stageBound A.P A.R))) = M.genericSet
    rw [hvc, hvc, hvc, hvc, hvc, hvc, hdec]
    -- compare inside the Boolean extension through the subalgebra realization
    apply (A.subalgebraRealization hD).value_injective
    have hmap' := (A.subalgebraRealization hD).embedding.map_traceSet (M.check A.P) (M.check A.R)
      (M.check (℘ (regularSets A.P A.R))) (M.check (insert A.P (range s)))
      (M.generatorDecisions A.P s (M.ofName ν))
      (M.check (closureStages A.P A.R (insert A.P (range s)) (stageBound A.P A.R)))
      (M.check (stageBound A.P A.R))
    change (A.subalgebraRealization hD).value _ = _ at hmap'
    rw [hmap']
    have hvc' : ∀ x : V, (A.subalgebraRealization hD).value (M.check x) = B.check x :=
      fun x ↦ (A.subalgebraRealization hD).value_check x
    have hdec' : (A.subalgebraRealization hD).value (M.generatorDecisions A.P s (M.ofName ν)) =
        B.generatorDecisions A.P s (A.booleanEquiv H) := by
      unfold generatorDecisions
      have h1 : (A.subalgebraRealization hD).value (insert (M.check A.P) (image (M.check s) (M.ofName ν))) =
          insert ((A.subalgebraRealization hD).value (M.check A.P))
            ((A.subalgebraRealization hD).value (image (M.check s) (M.ofName ν))) :=
        (A.subalgebraRealization hD).embedding.map_insert _ _
      have h2 : (A.subalgebraRealization hD).value (image (M.check s) (M.ofName ν)) =
          image ((A.subalgebraRealization hD).value (M.check s)) ((A.subalgebraRealization hD).value (M.ofName ν)) :=
        (A.subalgebraRealization hD).embedding.map_image _ _
      rw [h1, h2, hvc', hvc', hL'ν]
    change traceSet ((A.subalgebraRealization hD).value (M.check A.P))
      ((A.subalgebraRealization hD).value (M.check A.R))
      ((A.subalgebraRealization hD).value (M.check (℘ (regularSets A.P A.R))))
      ((A.subalgebraRealization hD).value (M.check (insert A.P (range s))))
      ((A.subalgebraRealization hD).value (M.generatorDecisions A.P s (M.ofName ν)))
      ((A.subalgebraRealization hD).value (M.check (closureStages A.P A.R (insert A.P (range s)) (stageBound A.P A.R))))
      ((A.subalgebraRealization hD).value (M.check (stageBound A.P A.R))) =
      (A.subalgebraRealization hD).value M.genericSet
    rw [hvc', hvc', hvc', hvc', hvc', hvc', hdec', (A.subalgebraRealization hD).value_genericSet]
    -- the trace on the poset side, transported to the Boolean extension
    have htrace := A.traceSet_generatorDecisions hAC τ hHQ hH
    rw [← hs] at htrace
    have hmapA := A.recoveredRealization.embedding.map_traceSet (A.check A.P) (A.check A.R)
      (A.check (℘ (regularSets A.P A.R))) (A.check (insert A.P (range s)))
      (A.generatorDecisions A.P s H)
      (A.check (closureStages A.P A.R (insert A.P (range s)) (stageBound A.P A.R)))
      (A.check (stageBound A.P A.R))
    change A.booleanEquiv _ = _ at hmapA
    rw [htrace] at hmapA
    have hvcA : ∀ x : V, A.booleanEquiv (A.check x) = B.check x := fun x ↦ A.booleanEquiv_check x
    have hdecA : A.booleanEquiv (A.generatorDecisions A.P s H) = B.generatorDecisions A.P s (A.booleanEquiv H) := by
      unfold generatorDecisions
      have h1 : A.booleanEquiv (insert (A.check A.P) (image (A.check s) H)) =
          insert (A.booleanEquiv (A.check A.P)) (A.booleanEquiv (image (A.check s) H)) :=
        A.recoveredRealization.embedding.map_insert _ _
      have h2 : A.booleanEquiv (image (A.check s) H) =
          image (A.booleanEquiv (A.check s)) (A.booleanEquiv H) :=
        A.recoveredRealization.embedding.map_image _ _
      rw [h1, h2, hvcA, hvcA]
    have hmapA' : A.booleanEquiv (A.boolGenericSet ∩ A.check D) =
        traceSet (A.booleanEquiv (A.check A.P)) (A.booleanEquiv (A.check A.R))
          (A.booleanEquiv (A.check (℘ (regularSets A.P A.R))))
          (A.booleanEquiv (A.check (insert A.P (range s)))) (A.booleanEquiv (A.generatorDecisions A.P s H))
          (A.booleanEquiv (A.check (closureStages A.P A.R (insert A.P (range s)) (stageBound A.P A.R))))
          (A.booleanEquiv (A.check (stageBound A.P A.R))) := by
      rw [← hDdef] at hmapA
      exact hmapA
    rw [hvcA, hvcA, hvcA, hvcA, hvcA, hvcA, hdecA] at hmapA'
    rw [← hmapA']
    have hinter : A.booleanEquiv (A.boolGenericSet ∩ A.check D) =
        A.booleanEquiv A.boolGenericSet ∩ A.booleanEquiv (A.check D) :=
      A.recoveredRealization.embedding.map_inter _ _
    rw [hinter, A.booleanEquiv_boolGenericSet, hvcA]
    -- the generic of the subalgebra realization
    change _ = B.genericSet ∩ B.check (subalgebraConditions A.P A.R D)
    apply mem_ext
    intro y
    rw [mem_inter_iff, mem_inter_iff]
    constructor
    · rintro ⟨hy, hyD⟩
      refine ⟨hy, ?_⟩
      obtain ⟨d₀, hd₀, rfl⟩ := (B.mem_check_iff _ _).mp (B.genericSet_subset_check_P y hy)
      rw [B.check_mem_iff] at hyD
      exact (B.check_mem_iff _ _).mpr ((mem_subalgebraConditions_iff _ _ _ _).mpr ⟨hyD, hd₀⟩)
    · rintro ⟨hy, hyD⟩
      refine ⟨hy, ?_⟩
      obtain ⟨d₀, hd₀, rfl⟩ := (B.mem_check_iff _ _).mp hyD
      exact (B.check_mem_iff _ _).mpr ((mem_subalgebraConditions_iff _ _ _ _).mp hd₀).1
  refine ⟨D, hD, ?_⟩
  rw [← hC]
  refine ⟨Equiv.ofBijective L.value ⟨L.value_injective, hsurj⟩, fun x y ↦ L.value_mem_iff x y,
    fun a ↦ L.value_check a, ?_⟩
  change (A.subalgebraRealization hD).value (L.value C.genericSet) = A.booleanEquiv H
  rw [L.value_genericSet, hLgen, hL'ν]

end

end ForcingContext

end ZFVP
