import ZFVP.ModelTheory.CompleteSubalgebra
import ZFVP.SetTheory.WellFoundedRecursion
import ZFVP.SetTheory.UniformCollapse
import ZFVP.SetTheory.PulledWellOrder
import ZFVP.SetTheory.Hessenberg

/-! The complete subalgebra of `RO(P)` generated by a set `S` of regular sets, built as the union
of transfinite closure stages `Cl α = step (S ∪ ⋃_{β<α} Cl β)`, where one step adds complements
and joins of subsets. The stages stabilize below the Hartogs number of `ω × ℘(RO(P))`; the
stable stage is the least complete subalgebra containing `S`. The stage structure is what makes
the generated subalgebra amenable to induction in extensions. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

theorem regularJoin_definable_one (P R : V) : ℒₛₑₜ-function₁[V] (regularJoin P R) := by
  have h : ℒₛₑₜ-relation (fun J X : V ↦ ∀ p, p ∈ J ↔
      p ∈ P ∧ ∀ q ∈ P, ⟨q, p⟩ₖ ∈ R → ∃ r ∈ ⋃ˢ X, ⟨r, q⟩ₖ ∈ R) := by definability
  apply Language.Definable.of_iff h
  intro v
  change v 0 = regularJoin P R (v 1) ↔ _
  rw [mem_ext_iff]
  simp only [regularJoin, mem_forcingClosure_iff]

/-- One closure step: add complements and joins of subsets. -/
noncomputable def subalgebraStep (P R X : V) : V :=
  X ∪ repl (fun A ↦ forcingNegation P R A) (by definability) X ∪
    repl (fun Y ↦ regularJoin P R Y) (regularJoin_definable_one P R) (℘ X)

theorem mem_subalgebraStep_iff (P R X d : V) :
    d ∈ subalgebraStep P R X ↔ d ∈ X ∨ (∃ A ∈ X, d = forcingNegation P R A) ∨
      ∃ Y, Y ⊆ X ∧ d = regularJoin P R Y := by
  unfold subalgebraStep
  rw [mem_union_iff, mem_union_iff, repl_spec, repl_spec]
  simp only [mem_power_iff, or_assoc]

theorem subalgebraStep_definable (P R : V) : ℒₛₑₜ-function₁[V] (subalgebraStep P R) := by
  have := regularJoin_definable_one P R
  have h : ℒₛₑₜ-relation (fun D X : V ↦ ∀ d, d ∈ D ↔ d ∈ X ∨ (∃ A ∈ X, d = forcingNegation P R A) ∨
      ∃ Y, Y ⊆ X ∧ d = regularJoin P R Y) := by definability
  apply Language.Definable.of_iff h
  intro v
  change v 0 = subalgebraStep P R (v 1) ↔ _
  rw [mem_ext_iff]
  simp only [mem_subalgebraStep_iff]

theorem subset_subalgebraStep (P R X : V) : X ⊆ subalgebraStep P R X :=
  fun d hd ↦ (mem_subalgebraStep_iff P R X d).mpr (Or.inl hd)

theorem subalgebraStep_regular {P R X : V} (hR : IsForcingPreorder P R) (hX : X ⊆ regularSets P R) :
    subalgebraStep P R X ⊆ regularSets P R := by
  intro d hd
  rcases (mem_subalgebraStep_iff P R X d).mp hd with hd | ⟨A, hA, rfl⟩ | ⟨Y, hY, rfl⟩
  · exact hX d hd
  · exact (mem_regularSets_iff _ _ _).mpr
      (forcingNegation_regular hR ((mem_regularSets_iff _ _ _).mp (hX A hA)).2.1)
  · exact (mem_regularSets_iff _ _ _).mpr
      (regularJoin_regular hR (fun A hA ↦ ((mem_regularSets_iff _ _ _).mp (hX A (hY A hA))).1))

theorem subalgebraStep_subset_of_complete {P R D X : V} (hD : IsCompleteSubalgebra P R D) (hX : X ⊆ D) :
    subalgebraStep P R X ⊆ D := by
  intro d hd
  rcases (mem_subalgebraStep_iff P R X d).mp hd with hd | ⟨A, hA, rfl⟩ | ⟨Y, hY, rfl⟩
  · exact hX d hd
  · exact hD.2.2.1 A (hX A hA)
  · exact hD.2.2.2 Y (fun A hA ↦ hX A (hY A hA))

theorem predecessors_membershipRelation {θ α : V} [IsOrdinal θ] (hα : α ∈ θ) :
    predecessors (membershipRelation θ) θ α = α := by
  apply mem_ext
  intro β
  rw [mem_predecessors_iff, pair_mem_membershipRelation]
  constructor
  · rintro ⟨_, _, _, h⟩
    exact h
  · intro h
    exact ⟨IsOrdinal.toIsTransitive.mem_trans h hα, IsOrdinal.toIsTransitive.mem_trans h hα, hα, h⟩

/-- The closure stages, as a function on the ordinal `θ`. -/
noncomputable def closureStages (P R S θ : V) : V :=
  wellFoundedRecursion (membershipRelation_wellFounded θ)
    (fun _ g ↦ subalgebraStep P R (S ∪ ⋃ˢ range g))
    (by have := subalgebraStep_definable P R; definability)

instance closureStages_isFunction (P R S θ : V) : IsFunction (closureStages P R S θ) :=
  wellFoundedRecursion_isFunction _ _ _

theorem closureStages_domain (P R S θ : V) : domain (closureStages P R S θ) = θ :=
  domain_wellFoundedRecursion _ _ _

/-- The recursion equation `Cl α = step (S ∪ ⋃_{β<α} Cl β)`. -/
theorem closureStages_value {P R S θ α : V} [IsOrdinal θ] (hα : α ∈ θ) :
    (closureStages P R S θ) ‘ α =
      subalgebraStep P R (S ∪ ⋃ˢ range ((closureStages P R S θ) ↾ α)) := by
  unfold closureStages
  rw [wellFoundedRecursion_value _ _ _ hα, predecessors_membershipRelation hα]

theorem generators_subset_closureStage {P R S θ α : V} [IsOrdinal θ] (hα : α ∈ θ) :
    S ⊆ (closureStages P R S θ) ‘ α := by
  rw [closureStages_value hα]
  exact fun d hd ↦ subset_subalgebraStep _ _ _ d (mem_union_iff.mpr (Or.inl hd))

theorem closureStage_mono {P R S θ α β : V} [IsOrdinal θ] (hα : α ∈ θ) (hβα : β ∈ α) :
    (closureStages P R S θ) ‘ β ⊆ (closureStages P R S θ) ‘ α := by
  have hfun := closureStages_isFunction P R S θ
  have hβ : β ∈ θ := IsOrdinal.toIsTransitive.mem_trans hβα hα
  rw [closureStages_value hα]
  intro d hd
  apply subset_subalgebraStep _ _ _ d
  apply mem_union_iff.mpr
  refine Or.inr (mem_sUnion_iff.mpr ⟨(closureStages P R S θ) ‘ β, ?_, hd⟩)
  apply mem_range_of_kpair_mem
  exact kpair_mem_restrict_iff.mpr ⟨kpair_value_mem (by rw [closureStages_domain]; exact hβ), hβα⟩

theorem closureStage_regular {P R S θ : V} [IsOrdinal θ] (hR : IsForcingPreorder P R)
    (hS : S ⊆ regularSets P R) : ∀ α ∈ θ, (closureStages P R S θ) ‘ α ⊆ regularSets P R := by
  apply internalWellFounded_induction (membershipRelation_wellFounded θ)
    (fun α ↦ (closureStages P R S θ) ‘ α ⊆ regularSets P R) (by definability)
  intro α hα ih
  rw [closureStages_value hα]
  apply subalgebraStep_regular hR
  intro d hd
  rcases mem_union_iff.mp hd with hd | hd
  · exact hS d hd
  · obtain ⟨X, hX, hdX⟩ := mem_sUnion_iff.mp hd
    obtain ⟨β, hβ⟩ := mem_range_iff.mp hX
    obtain ⟨hβ, hβα⟩ := kpair_mem_restrict_iff.mp hβ
    have hβθ : β ∈ θ := IsOrdinal.toIsTransitive.mem_trans hβα hα
    have := ih β hβθ ((pair_mem_membershipRelation _ _ _).mpr ⟨hβθ, hα, hβα⟩)
    rw [value_eq_of_kpair_mem hβ] at this
    exact this d hdX

theorem closureStage_subset_of_complete {P R S θ D : V} [IsOrdinal θ] (hD : IsCompleteSubalgebra P R D)
    (hS : S ⊆ D) : ∀ α ∈ θ, (closureStages P R S θ) ‘ α ⊆ D := by
  apply internalWellFounded_induction (membershipRelation_wellFounded θ)
    (fun α ↦ (closureStages P R S θ) ‘ α ⊆ D) (by definability)
  intro α hα ih
  rw [closureStages_value hα]
  apply subalgebraStep_subset_of_complete hD
  intro d hd
  rcases mem_union_iff.mp hd with hd | hd
  · exact hS d hd
  · obtain ⟨X, hX, hdX⟩ := mem_sUnion_iff.mp hd
    obtain ⟨β, hβ⟩ := mem_range_iff.mp hX
    obtain ⟨hβ, hβα⟩ := kpair_mem_restrict_iff.mp hβ
    have hβθ : β ∈ θ := IsOrdinal.toIsTransitive.mem_trans hβα hα
    have := ih β hβθ ((pair_mem_membershipRelation _ _ _).mpr ⟨hβθ, hα, hβα⟩)
    rw [value_eq_of_kpair_mem hβ] at this
    exact this d hdX

/-- The stage bound: the Hartogs number of `ω × ℘(RO(P))`. -/
noncomputable def stageBound (P R : V) : V := hartogsNumber ((ω : V) ×ˢ ℘ (regularSets P R))

theorem stageBound_initial (P R : V) : IsInitialOrdinal (stageBound P R) := hartogsNumber_initial _

instance stageBound_ordinal (P R : V) : IsOrdinal (stageBound P R) := (hartogsNumber_initial _).1

theorem omega_subset_stageBound (P R : V) : (ω : V) ⊆ stageBound P R := by
  have hω : (ω : V) ∈ stageBound P R := by
    apply ordinal_cardLE_iff_mem_hartogsNumber.mp
    obtain ⟨A, hA⟩ : ∃ A, A ∈ ℘ (regularSets P R) := ⟨∅, mem_power_iff.mpr (fun z hz ↦ (not_mem_empty hz).elim)⟩
    let F : V → V := fun n ↦ ⟨n, A⟩ₖ
    have hF : ℒₛₑₜ-function₁ F := by unfold F; definability
    refine ⟨definableGraph (ω : V) F hF, definableGraph_mem_function_of_mapsTo _ _ F hF
      (fun n hn ↦ kpair_mem_iff.mpr ⟨hn, hA⟩), ?_⟩
    intro n m z hn hm
    obtain ⟨_, rfl⟩ := (pair_mem_definableGraph_iff _ _ _ _ _).mp hn
    obtain ⟨_, hz⟩ := (pair_mem_definableGraph_iff _ _ _ _ _).mp hm
    exact (kpair_iff.mp hz).1
  exact IsOrdinal.toIsTransitive.transitive _ hω

/-- The stages stabilize below the stage bound. -/
theorem exists_stable_stage {P R S : V} (hR : IsForcingPreorder P R) (hS : S ⊆ regularSets P R) :
    ∃ α ∈ stageBound P R, (closureStages P R S (stageBound P R)) ‘ (succ α) =
      (closureStages P R S (stageBound P R)) ‘ α := by
  by_contra hne
  push Not at hne
  have hsucc : ∀ α ∈ stageBound P R, succ α ∈ stageBound P R :=
    fun α hα ↦ initial_succ_mem (stageBound_initial P R) (omega_subset_stageBound P R) hα
  apply not_hartogsNumber_cardLE ((ω : V) ×ˢ ℘ (regularSets P R))
  -- the stages inject the bound into `℘(RO(P))`
  have hreg := closureStage_regular (θ := stageBound P R) hR hS
  let F : V → V := fun α ↦ ⟨∅, (closureStages P R S (stageBound P R)) ‘ α⟩ₖ
  have hF : ℒₛₑₜ-function₁ F := by unfold F; definability
  refine ⟨definableGraph (stageBound P R) F hF, definableGraph_mem_function_of_mapsTo _ _ F hF
    (fun α hα ↦ kpair_mem_iff.mpr ⟨empty_mem_ω, mem_power_iff.mpr (hreg α hα)⟩), ?_⟩
  intro α β z hα hβ
  obtain ⟨hαθ, rfl⟩ := (pair_mem_definableGraph_iff _ _ _ _ _).mp hα
  obtain ⟨hβθ, hz⟩ := (pair_mem_definableGraph_iff _ _ _ _ _).mp hβ
  have heq := (kpair_iff.mp hz).2
  have : IsOrdinal α := IsOrdinal.of_mem hαθ
  have : IsOrdinal β := IsOrdinal.of_mem hβθ
  by_contra hαβ
  -- strict growth between distinct stages contradicts equality
  have hgrow : ∀ γ δ : V, γ ∈ stageBound P R → δ ∈ γ →
      (closureStages P R S (stageBound P R)) ‘ δ ≠ (closureStages P R S (stageBound P R)) ‘ γ := by
    intro γ δ hγ hδγ h
    have hδ : δ ∈ stageBound P R := IsOrdinal.toIsTransitive.mem_trans hδγ hγ
    have : IsOrdinal δ := IsOrdinal.of_mem hδ
    have : IsOrdinal γ := IsOrdinal.of_mem hγ
    apply hne δ hδ
    apply SetTheory.subset_antisymm
    · rw [h]
      have hsδγ : succ δ ⊆ γ := by
        intro x hx
        rcases mem_succ_iff.mp hx with rfl | hx
        · exact hδγ
        · exact IsOrdinal.toIsTransitive.mem_trans hx hδγ
      rcases IsOrdinal.subset_iff.mp hsδγ with h' | h'
      · rw [h']
      · exact closureStage_mono hγ h'
    · exact closureStage_mono (hsucc δ hδ) (mem_succ_self δ)
  rcases IsOrdinal.mem_trichotomy (α := α) (β := β) with h | h | h
  · exact hgrow β α hβθ h heq
  · exact hαβ h
  · exact hgrow α β hαθ h heq.symm

/-- The complete subalgebra generated by `S` (together with the top `P`). -/
noncomputable def generatedSubalgebra (P R S : V) : V :=
  ⋃ˢ range (closureStages P R (insert P S) (stageBound P R))

theorem mem_generatedSubalgebra_iff (P R S d : V) :
    d ∈ generatedSubalgebra P R S ↔ ∃ α ∈ stageBound P R, d ∈ (closureStages P R (insert P S) (stageBound P R)) ‘ α := by
  unfold generatedSubalgebra
  rw [mem_sUnion_iff]
  constructor
  · rintro ⟨X, hX, hdX⟩
    obtain ⟨α, hα⟩ := mem_range_iff.mp hX
    have hαθ : α ∈ stageBound P R := by
      have := mem_domain_of_kpair_mem hα
      rwa [closureStages_domain] at this
    rw [← value_eq_of_kpair_mem hα] at hdX
    exact ⟨α, hαθ, hdX⟩
  · rintro ⟨α, hα, hd⟩
    have hfun := closureStages_isFunction P R (insert P S) (stageBound P R)
    exact ⟨_, mem_range_of_kpair_mem (kpair_value_mem (by rw [closureStages_domain]; exact hα)), hd⟩

theorem generatedSubalgebra_eq_stage {P R S : V} (hR : IsForcingPreorder P R) (hS : S ⊆ regularSets P R)
    {α : V} (hα : α ∈ stageBound P R)
    (hstable : (closureStages P R (insert P S) (stageBound P R)) ‘ (succ α) =
      (closureStages P R (insert P S) (stageBound P R)) ‘ α) :
    generatedSubalgebra P R S = (closureStages P R (insert P S) (stageBound P R)) ‘ α := by
  have hsucc : succ α ∈ stageBound P R :=
    initial_succ_mem (stageBound_initial P R) (omega_subset_stageBound P R) hα
  have : IsOrdinal α := IsOrdinal.of_mem hα
  apply mem_ext
  intro d
  rw [mem_generatedSubalgebra_iff]
  constructor
  · rintro ⟨β, hβ, hd⟩
    have : IsOrdinal β := IsOrdinal.of_mem hβ
    rcases IsOrdinal.subset_or_supset (α := β) (β := α) with h | h
    · rcases IsOrdinal.subset_iff.mp h with h | h
      · rw [← h]
        exact hd
      · exact closureStage_mono hα h d hd
    · -- all stages above `α` equal the stage `α`
      have hstage : ∀ γ ∈ stageBound P R, α ⊆ γ →
          (closureStages P R (insert P S) (stageBound P R)) ‘ γ =
            (closureStages P R (insert P S) (stageBound P R)) ‘ α := by
        apply internalWellFounded_induction (membershipRelation_wellFounded (stageBound P R))
          (fun γ ↦ α ⊆ γ → (closureStages P R (insert P S) (stageBound P R)) ‘ γ =
            (closureStages P R (insert P S) (stageBound P R)) ‘ α) (by definability)
        intro γ hγ ih hαγ
        have : IsOrdinal γ := IsOrdinal.of_mem hγ
        rcases IsOrdinal.subset_iff.mp hαγ with h | h
        · rw [h]
        · apply SetTheory.subset_antisymm
          · rw [closureStages_value hγ]
            intro d hd
            rcases (mem_subalgebraStep_iff _ _ _ _).mp hd with hd | ⟨A, hA, rfl⟩ | ⟨Y, hY, rfl⟩
            · rcases mem_union_iff.mp hd with hd | hd
              · exact generators_subset_closureStage hα d hd
              · obtain ⟨X, hX, hdX⟩ := mem_sUnion_iff.mp hd
                obtain ⟨δ, hδ⟩ := mem_range_iff.mp hX
                obtain ⟨hδ, hδγ⟩ := kpair_mem_restrict_iff.mp hδ
                have hδθ : δ ∈ stageBound P R := IsOrdinal.toIsTransitive.mem_trans hδγ hγ
                have : IsOrdinal δ := IsOrdinal.of_mem hδθ
                rw [← value_eq_of_kpair_mem hδ] at hdX
                rcases IsOrdinal.subset_or_supset (α := δ) (β := α) with h' | h'
                · rcases IsOrdinal.subset_iff.mp h' with h' | h'
                  · rw [← h']; exact hdX
                  · exact closureStage_mono hα h' d hdX
                · rw [ih δ hδθ ((pair_mem_membershipRelation _ _ _).mpr ⟨hδθ, hγ, hδγ⟩) h'] at hdX
                  exact hdX
            · -- complements of elements of the stage lie in the next stage, which is the stage
              have hAα : A ∈ (closureStages P R (insert P S) (stageBound P R)) ‘ α := by
                rcases mem_union_iff.mp hA with hA | hA
                · exact generators_subset_closureStage hα A hA
                · obtain ⟨X, hX, hAX⟩ := mem_sUnion_iff.mp hA
                  obtain ⟨δ, hδ⟩ := mem_range_iff.mp hX
                  obtain ⟨hδ, hδγ⟩ := kpair_mem_restrict_iff.mp hδ
                  have hδθ : δ ∈ stageBound P R := IsOrdinal.toIsTransitive.mem_trans hδγ hγ
                  have : IsOrdinal δ := IsOrdinal.of_mem hδθ
                  rw [← value_eq_of_kpair_mem hδ] at hAX
                  rcases IsOrdinal.subset_or_supset (α := δ) (β := α) with h' | h'
                  · rcases IsOrdinal.subset_iff.mp h' with h' | h'
                    · rw [← h']; exact hAX
                    · exact closureStage_mono hα h' A hAX
                  · rw [ih δ hδθ ((pair_mem_membershipRelation _ _ _).mpr ⟨hδθ, hγ, hδγ⟩) h'] at hAX
                    exact hAX
              rw [← hstable, closureStages_value hsucc]
              apply (mem_subalgebraStep_iff _ _ _ _).mpr
              refine Or.inr (Or.inl ⟨A, mem_union_iff.mpr (Or.inr (mem_sUnion_iff.mpr ⟨_, ?_, hAα⟩)), rfl⟩)
              have hfun := closureStages_isFunction P R (insert P S) (stageBound P R)
              exact mem_range_of_kpair_mem (kpair_mem_restrict_iff.mpr
                ⟨kpair_value_mem (by rw [closureStages_domain]; exact hα), mem_succ_self α⟩)
            · have hYα : Y ⊆ (closureStages P R (insert P S) (stageBound P R)) ‘ α := by
                intro A hA
                rcases mem_union_iff.mp (hY A hA) with hA | hA
                · exact generators_subset_closureStage hα A hA
                · obtain ⟨X, hX, hAX⟩ := mem_sUnion_iff.mp hA
                  obtain ⟨δ, hδ⟩ := mem_range_iff.mp hX
                  obtain ⟨hδ, hδγ⟩ := kpair_mem_restrict_iff.mp hδ
                  have hδθ : δ ∈ stageBound P R := IsOrdinal.toIsTransitive.mem_trans hδγ hγ
                  have : IsOrdinal δ := IsOrdinal.of_mem hδθ
                  rw [← value_eq_of_kpair_mem hδ] at hAX
                  rcases IsOrdinal.subset_or_supset (α := δ) (β := α) with h' | h'
                  · rcases IsOrdinal.subset_iff.mp h' with h' | h'
                    · rw [← h']; exact hAX
                    · exact closureStage_mono hα h' A hAX
                  · rw [ih δ hδθ ((pair_mem_membershipRelation _ _ _).mpr ⟨hδθ, hγ, hδγ⟩) h'] at hAX
                    exact hAX
              rw [← hstable, closureStages_value hsucc]
              apply (mem_subalgebraStep_iff _ _ _ _).mpr
              refine Or.inr (Or.inr ⟨Y, fun A hA ↦ mem_union_iff.mpr (Or.inr (mem_sUnion_iff.mpr ⟨_, ?_, hYα A hA⟩)), rfl⟩)
              have hfun := closureStages_isFunction P R (insert P S) (stageBound P R)
              exact mem_range_of_kpair_mem (kpair_mem_restrict_iff.mpr
                ⟨kpair_value_mem (by rw [closureStages_domain]; exact hα), mem_succ_self α⟩)
          · exact closureStage_mono hγ h
      rw [hstage β hβ h] at hd
      exact hd
  · intro hd
    exact ⟨α, hα, hd⟩

/-- The generated subalgebra is a complete subalgebra containing the generators. -/
theorem generatedSubalgebra_complete {P R S : V} (hR : IsForcingPreorder P R) (hS : S ⊆ regularSets P R) :
    IsCompleteSubalgebra P R (generatedSubalgebra P R S) := by
  have hS' : insert P S ⊆ regularSets P R := by
    intro d hd
    rcases mem_insert.mp hd with h | hd
    · rw [h]
      exact (mem_regularSets_iff _ _ _).mpr (forcingRegular_top P R)
    · exact hS d hd
  obtain ⟨α, hα, hstable⟩ := exists_stable_stage hR hS'
  have heq := generatedSubalgebra_eq_stage hR hS hα hstable
  have hsucc : succ α ∈ stageBound P R :=
    initial_succ_mem (stageBound_initial P R) (omega_subset_stageBound P R) hα
  have hfun := closureStages_isFunction P R (insert P S) (stageBound P R)
  have hin : (closureStages P R (insert P S) (stageBound P R)) ‘ α ∈
      range ((closureStages P R (insert P S) (stageBound P R)) ↾ (succ α)) :=
    mem_range_of_kpair_mem (kpair_mem_restrict_iff.mpr
      ⟨kpair_value_mem (by rw [closureStages_domain]; exact hα), mem_succ_self α⟩)
  rw [heq]
  refine ⟨closureStage_regular hR hS' α hα, generators_subset_closureStage hα P (mem_insert.mpr (Or.inl rfl)), ?_, ?_⟩
  · intro A hA
    rw [← hstable, closureStages_value hsucc]
    exact (mem_subalgebraStep_iff _ _ _ _).mpr (Or.inr (Or.inl ⟨A,
      mem_union_iff.mpr (Or.inr (mem_sUnion_iff.mpr ⟨_, hin, hA⟩)), rfl⟩))
  · intro Y hY
    rw [← hstable, closureStages_value hsucc]
    exact (mem_subalgebraStep_iff _ _ _ _).mpr (Or.inr (Or.inr ⟨Y,
      fun A hA ↦ mem_union_iff.mpr (Or.inr (mem_sUnion_iff.mpr ⟨_, hin, hY A hA⟩)), rfl⟩))

theorem subset_generatedSubalgebra (P R S : V) : S ⊆ generatedSubalgebra P R S := by
  intro d hd
  have h0 : (∅ : V) ∈ stageBound P R := omega_subset_stageBound P R ∅ empty_mem_ω
  exact (mem_generatedSubalgebra_iff _ _ _ _).mpr
    ⟨∅, h0, generators_subset_closureStage h0 d (mem_insert.mpr (Or.inr hd))⟩

/-- The generated subalgebra is the least complete subalgebra containing the generators. -/
theorem generatedSubalgebra_minimal {P R S D : V} (hD : IsCompleteSubalgebra P R D) (hS : S ⊆ D) :
    generatedSubalgebra P R S ⊆ D := by
  intro d hd
  obtain ⟨α, hα, hd⟩ := (mem_generatedSubalgebra_iff _ _ _ _).mp hd
  have hS' : insert P S ⊆ D := by
    intro x hx
    rcases mem_insert.mp hx with h | hx
    · rw [h]
      exact hD.2.1
    · exact hS x hx
  exact closureStage_subset_of_complete hD hS' α hα d hd

end ZFVP
