import ZFVP.ModelTheory.GenericFilterName
import ZFVP.ModelTheory.GeneratedSubalgebraGeneric
import ZFVP.SetTheory.TraceStages
import ZFVP.SetTheory.PerfectSetCore

/-! The trace recursion inside the extension: for the subalgebra generated by the Boolean values
`‖q̌ ∈ τ‖`, the recursion started from the decisions read off the value of `τ` computes the Boolean
generic restricted to the checked subalgebra. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

namespace ForcingContext

variable (A : ForcingContext V)

theorem check_union (x y : V) : A.check (x ∪ y) = A.check x ∪ A.check y :=
  A.checkEmbedding.map_union x y

theorem check_sUnion (x : V) : A.check (⋃ˢ x) = ⋃ˢ (A.check x) :=
  A.checkEmbedding.map_sUnion x

theorem check_range (f : V) : A.check (range f) = range (A.check f) :=
  A.checkEmbedding.map_range f

theorem check_restrict (f x : V) : A.check (f ↾ x) = (A.check f) ↾ (A.check x) :=
  A.checkEmbedding.map_restrict f x

theorem check_forcingNegation (P R x : V) :
    A.check (forcingNegation P R x) = forcingNegation (A.check P) (A.check R) (A.check x) :=
  A.checkEmbedding.map_forcingNegation P R x

theorem check_regularJoin (P R x : V) :
    A.check (regularJoin P R x) = regularJoin (A.check P) (A.check R) (A.check x) :=
  A.checkEmbedding.map_regularJoin P R x

/-- The decisions on the generators: the top together with the values at the members of `H`. -/
noncomputable def generatorDecisions (P₀ s : V) (H : A.Model) : A.Model :=
  insert (A.check P₀) (image (A.check s) H)

/-- The closure stages of the checked generated subalgebra satisfy the closure properties of the
trace recursion. -/
theorem check_closureStages_closure {S : V} :
    ∀ α ∈ A.check (stageBound A.P A.R),
      A.check (insert A.P S) ⊆ (A.check (closureStages A.P A.R (insert A.P S) (stageBound A.P A.R))) ‘ α ∧
      (∀ β ∈ α, (A.check (closureStages A.P A.R (insert A.P S) (stageBound A.P A.R))) ‘ β ⊆
        (A.check (closureStages A.P A.R (insert A.P S) (stageBound A.P A.R))) ‘ α) ∧
      (∀ B ∈ A.check (insert A.P S) ∪
          ⋃ˢ range ((A.check (closureStages A.P A.R (insert A.P S) (stageBound A.P A.R))) ↾ α),
        forcingNegation (A.check A.P) (A.check A.R) B ∈
          (A.check (closureStages A.P A.R (insert A.P S) (stageBound A.P A.R))) ‘ α) ∧
      ∀ Y ∈ A.check (℘ (regularSets A.P A.R)), Y ⊆ A.check (insert A.P S) ∪
          ⋃ˢ range ((A.check (closureStages A.P A.R (insert A.P S) (stageBound A.P A.R))) ↾ α) →
        regularJoin (A.check A.P) (A.check A.R) Y ∈
          (A.check (closureStages A.P A.R (insert A.P S) (stageBound A.P A.R))) ‘ α := by
  let j := A.checkEmbedding
  have : IsOrdinal (stageBound A.P A.R) := (stageBound_initial A.P A.R).1
  obtain ⟨Cl, hCl⟩ : ∃ Cl : V, Cl = closureStages A.P A.R (insert A.P S) (stageBound A.P A.R) := ⟨_, rfl⟩
  have hClf : IsFunction Cl := hCl ▸ closureStages_isFunction _ _ _ _
  have hdom : domain Cl = stageBound A.P A.R := by rw [hCl, closureStages_domain]
  have hstage : ∀ α₀ ∈ stageBound A.P A.R, (A.check Cl) ‘ (A.check α₀) = A.check (Cl ‘ α₀) :=
    fun α₀ hα₀ ↦ A.check_value (by rw [hdom]; exact hα₀)
  have hval : ∀ α₀ ∈ stageBound A.P A.R,
      Cl ‘ α₀ = subalgebraStep A.P A.R (insert A.P S ∪ ⋃ˢ range (Cl ↾ α₀)) := by
    intro α₀ hα₀
    rw [hCl]
    exact closureStages_value hα₀
  have hprev : ∀ α₀ : V, A.check (insert A.P S) ∪ ⋃ˢ range ((A.check Cl) ↾ (A.check α₀)) =
      A.check (insert A.P S ∪ ⋃ˢ range (Cl ↾ α₀)) := by
    intro α₀
    rw [A.check_union, A.check_sUnion, A.check_range, A.check_restrict]
  rw [← hCl]
  intro α hα
  obtain ⟨α₀, hα₀, rfl⟩ := (A.mem_check_iff _ _).mp hα
  rw [hstage α₀ hα₀, hprev α₀]
  refine ⟨?_, ?_, ?_, ?_⟩
  · rw [hval α₀ hα₀]
    exact (j.subset_iff _ _).mpr (fun d hd ↦ subset_subalgebraStep _ _ _ d (mem_union_iff.mpr (Or.inl hd)))
  · intro β hβ
    obtain ⟨β₀, hβ₀, rfl⟩ := (A.mem_check_iff _ _).mp hβ
    have hβθ : β₀ ∈ stageBound A.P A.R := IsOrdinal.toIsTransitive.mem_trans hβ₀ hα₀
    rw [hstage β₀ hβθ, hval α₀ hα₀]
    refine (j.subset_iff _ _).mpr (fun d hd ↦ subset_subalgebraStep _ _ _ d (mem_union_iff.mpr (Or.inr ?_)))
    refine mem_sUnion_iff.mpr ⟨Cl ‘ β₀, ?_, hd⟩
    exact mem_range_of_kpair_mem (kpair_mem_restrict_iff.mpr ⟨kpair_value_mem (by rw [hdom]; exact hβθ), hβ₀⟩)
  · intro B hB
    obtain ⟨B₀, hB₀, rfl⟩ := (A.mem_check_iff _ _).mp hB
    rw [← A.check_forcingNegation, hval α₀ hα₀]
    exact (A.check_mem_iff _ _).mpr ((mem_subalgebraStep_iff _ _ _ _).mpr (Or.inr (Or.inl ⟨B₀, hB₀, rfl⟩)))
  · intro Y hY hYsub
    obtain ⟨Y₀, _, rfl⟩ := (A.mem_check_iff _ _).mp hY
    rw [← A.check_regularJoin, hval α₀ hα₀]
    exact (A.check_mem_iff _ _).mpr ((mem_subalgebraStep_iff _ _ _ _).mpr
      (Or.inr (Or.inr ⟨Y₀, (j.subset_iff _ _).mp hYsub, rfl⟩)))

theorem mem_generatorDecisions_iff (P₀ s : V) (H d : A.Model) :
    d ∈ A.generatorDecisions P₀ s H ↔ d = A.check P₀ ∨ ∃ h ∈ H, ⟨h, d⟩ₖ ∈ A.check s := by
  unfold generatorDecisions
  rw [mem_insert, mem_image_iff']

/-- The trace recursion started from the decisions of `H` computes the Boolean generic on the
checked subalgebra generated by the Boolean values `‖q̌ ∈ τ‖`. -/
theorem traceSet_generatorDecisions (hAC : InternalChoice V) (τ : ForcingName A.booleanContext.P)
    {Q : V} {H : A.Model} (hHQ : H ⊆ A.check Q)
    (hH : ∀ q ∈ Q, A.check q ∈ H ↔ A.booleanContext.check q ∈ A.booleanContext.ofName τ) :
    traceSet (A.check A.P) (A.check A.R) (A.check (℘ (regularSets A.P A.R)))
      (A.check (insert A.P (range (A.booleanValueFamily τ.val Q))))
      (A.generatorDecisions A.P (A.booleanValueFamily τ.val Q) H)
      (A.check (closureStages A.P A.R (insert A.P (range (A.booleanValueFamily τ.val Q)))
        (stageBound A.P A.R)))
      (A.check (stageBound A.P A.R)) =
      A.boolGenericSet ∩ A.check (generatedSubalgebra A.P A.R (range (A.booleanValueFamily τ.val Q))) := by
  let j := A.checkEmbedding
  obtain ⟨s, hs⟩ : ∃ s : V, s = A.booleanValueFamily τ.val Q := ⟨_, rfl⟩
  have hsf : s ∈ regularSets A.P A.R ^ Q := hs ▸ A.booleanValueFamily_mem_function τ.val Q
  have hsfun : IsFunction s := IsFunction.of_mem hsf
  have hsdom : domain s = Q := domain_eq_of_mem_function hsf
  have hsval : ∀ q ∈ Q, s ‘ q = A.booleanMemValue τ.val q := fun q hq ↦ hs ▸ A.booleanValueFamily_value hq
  have hS : range s ⊆ regularSets A.P A.R := range_subset_of_mem_function hsf
  have hcheckf : IsFunction (A.check s) := j.map_function s
  rw [← hs]
  have hH₀ : A.generatorDecisions A.P s H ⊆ A.check (insert A.P (range s)) := by
    intro d hd
    rw [A.check_insert]
    rcases (A.mem_generatorDecisions_iff A.P s H d).mp hd with rfl | ⟨h, hh, hhd⟩
    · exact mem_insert.mpr (Or.inl rfl)
    · refine mem_insert.mpr (Or.inr ?_)
      rw [A.check_range]
      exact mem_range_of_kpair_mem hhd
  have hagree : ∀ d ∈ A.check (insert A.P (range s)),
      d ∈ A.boolGenericSet ↔ d ∈ A.generatorDecisions A.P s H := by
    intro d hd
    rw [A.check_insert] at hd
    rw [A.mem_generatorDecisions_iff A.P]
    rcases mem_insert.mp hd with rfl | hd
    · exact ⟨fun _ ↦ Or.inl rfl, fun _ ↦ A.check_top_mem_boolGenericSet⟩
    · obtain ⟨d₀, hd₀, rfl⟩ := (A.mem_check_iff _ _).mp hd
      obtain ⟨q, hq⟩ := mem_range_iff.mp hd₀
      have hqQ : q ∈ Q := by rw [← hsdom]; exact mem_domain_of_kpair_mem hq
      have hqv : s ‘ q = d₀ := value_eq_of_kpair_mem hq
      -- membership of a generator value in the Boolean generic set is the decision at `q`
      have hgen : ∀ q' ∈ Q, A.check (s ‘ q') ∈ A.boolGenericSet ↔ A.check q' ∈ H := by
        intro q' hq'
        rw [A.check_mem_boolGenericSet_iff, hH q' hq', hsval q' hq', ← A.booleanMemValue_mem_generic_iff]
        change _ ↔ _ ∈ booleanGeneric A.P A.R A.G
        rw [mem_booleanGeneric_iff, mem_regularSets_iff, mem_booleanConditions_iff]
        constructor
        · rintro ⟨hreg, p, hp, hpv⟩
          exact ⟨⟨hreg, p, hpv⟩, p, hp, hpv⟩
        · rintro ⟨⟨hreg, _⟩, p, hp, hpv⟩
          exact ⟨hreg, p, hp, hpv⟩
      rw [← hqv]
      constructor
      · intro hG
        refine Or.inr ⟨A.check q, (hgen q hqQ).mp hG, ?_⟩
        rw [← A.check_kpair]
        exact (A.check_mem_iff _ _).mpr (kpair_value_mem (by rw [hsdom]; exact hqQ))
      · rintro (he | ⟨h, hh, hhd⟩)
        · rw [he]
          exact A.check_top_mem_boolGenericSet
        · obtain ⟨q', hq'Q, rfl⟩ := (A.mem_check_iff _ _).mp (hHQ h hh)
          rw [← A.check_kpair] at hhd
          have hq's := (A.check_mem_iff _ _).mp hhd
          have : s ‘ q' = s ‘ q := by rw [value_eq_of_kpair_mem hq's, hqv]
          rw [← this]
          exact (hgen q' hq'Q).mpr hh
  have hsys := A.checkStageSystem hAC hS
  have hclos := A.check_closureStages_closure (S := range s)
  have hR : IsForcingPreorder (A.check A.P) (A.check A.R) := j.map_forcingPreorder A.order
  rw [traceSet_eq hR hsys A.boolGenericSet_antichainGeneric hclos hH₀ hagree]
  unfold generatedSubalgebra
  rw [A.check_sUnion, A.check_range]

end ForcingContext

end ZFVP
