import ZFVP.ModelTheory.InfinitaryAdequateOldEmbedding

namespace ZFVP.Infinitary
open LO LO.FirstOrder
universe u v
namespace WeakModel.AdequateGenericChain
variable {L : Language.{u}} [L.Eq] [L.Encodable]
  {M : WeakModel.{u,v} L} {S : Set (TaggedFormula L)}
  {p₀ : AdequateFiniteCondition M S} (C : AdequateGenericChain M S p₀)

theorem eval_q_liftRename {n m} (φ : ParameterInstance M S (n + 1))
    (ρ : Fin n → Fin m) (ts : Fin m → ℕ) :
    C.Eval (φ.rename (liftRenaming ρ)).q ts ↔ C.Eval φ.q (ts ∘ ρ) := by
  have he : C.Eval (φ.rename (liftRenaming ρ)).q ts ↔ C.Eval (φ.q.rename ρ) ts := by
    apply C.eval_congr
    intro b
    simp only [ParameterInstance.eval_q, ParameterInstance.eval_rename, compose_liftRenaming]
  exact he.trans (C.eval_rename φ.q ρ ts)

theorem eval_q_monotone {n} (φ ψ : ParameterInstance M S (n + 1)) (ts : Fin n → ℕ)
    (hi : C.Eval (φ.and ψ.neg).neg.all ts) (hq : C.Eval φ.q ts) : C.Eval ψ.q ts := by
  apply C.eval_mono (φ := (φ.and ψ.neg).neg.all.and φ.q) ?_
    ((C.eval_and _ _ ts).mpr ⟨hi, hq⟩)
  intro b hb
  obtain ⟨hb, hq⟩ := (ParameterInstance.eval_and _ _ b).mp hb
  apply (ParameterInstance.eval_q _ _).mpr
  apply M.mono ?_ ((ParameterInstance.eval_q _ _).mp hq)
  intro x hx
  have ht := (ParameterInstance.eval_all _ _).mp hb x
  by_contra hy
  exact (ParameterInstance.eval_neg _ _).mp ht ((ParameterInstance.eval_and _ _ _).mpr ⟨hx, hy⟩)

def genericFiber {n} (φ : ParameterInstance M S (n + 1)) (ts : Fin n → ℕ) : Set C.Domain :=
  {x | C.QuotientEval φ (x :> C.classOf ∘ ts)}

theorem classOf_mem_genericFiber {n} (φ : ParameterInstance M S (n + 1))
    (ts : Fin n → ℕ) (t : ℕ) : C.classOf t ∈ C.genericFiber φ ts ↔ C.Eval φ (t :> ts) := by
  change C.QuotientEval φ (C.classOf t :> C.classOf ∘ ts) ↔ _
  rw [← C.classOf_cons]
  exact C.quotientEval_classOf φ _

/-- Fiber inclusion with any two finite parameter contexts controls the Q labels. -/
theorem q_label_of_fiber_subset {n m} (φ : ParameterInstance M S (n + 1))
    (ψ : ParameterInstance M S (m + 1)) (ts : Fin n → ℕ) (us : Fin m → ℕ)
    (hsub : C.genericFiber φ ts ⊆ C.genericFiber ψ us) (hq : C.Eval φ.q ts) : C.Eval ψ.q us := by
  let v := Fin.append ts us
  let ρ : Fin n → Fin (n + m) := Fin.castAdd m
  let σ : Fin m → Fin (n + m) := Fin.natAdd n
  have hvρ : v ∘ ρ = ts := by funext i; exact Fin.append_left ts us i
  have hvσ : v ∘ σ = us := by funext i; exact Fin.append_right ts us i
  let φ' := φ.rename (liftRenaming ρ)
  let ψ' := ψ.rename (liftRenaming σ)
  have hall : C.Eval (φ'.and ψ'.neg).neg.all v := by
    apply (C.eval_all _ _).mpr
    intro t
    rw [C.eval_neg, C.eval_and, C.eval_neg]
    rintro ⟨hp, hn⟩
    have hp' : C.Eval φ (t :> ts) := by
      simpa only [compose_liftRenaming, hvρ] using (C.eval_rename φ (liftRenaming ρ) _).mp hp
    have hψ := hsub ((C.classOf_mem_genericFiber φ ts t).mpr hp')
    have hψ' := (C.classOf_mem_genericFiber ψ us t).mp hψ
    apply hn
    apply (C.eval_rename ψ (liftRenaming σ) _).mpr
    simpa only [compose_liftRenaming, hvσ] using hψ'
  have hq' : C.Eval φ'.q v := (C.eval_q_liftRename φ ρ v).mpr (hvρ.symm ▸ hq)
  have hψ := C.eval_q_monotone φ' ψ' v hall hq'
  simpa only [hvσ] using (C.eval_q_liftRename ψ σ v).mp hψ

/-- An actual monotone quantifier generated by positive generic definable fibers. -/
def extensionQuantifier (A : Set C.Domain) : Prop :=
  ∃ n, ∃ φ : ParameterInstance M S (n + 1), ∃ ts : Fin n → ℕ,
    C.Eval φ.q ts ∧ C.genericFiber φ ts ⊆ A

theorem extensionQuantifier_mono : Monotone C.extensionQuantifier := by
  rintro A B hAB ⟨n, φ, ts, hq, hs⟩
  exact ⟨n, φ, ts, hq, hs.trans hAB⟩

theorem extensionQuantifier_fiber {n} (φ : ParameterInstance M S (n + 1)) (ts : Fin n → ℕ) :
    C.extensionQuantifier (C.genericFiber φ ts) ↔ C.Eval φ.q ts := by
  constructor
  · rintro ⟨m, ψ, us, hq, hs⟩
    exact C.q_label_of_fiber_subset ψ φ us ts hs hq
  · exact fun hq ↦ ⟨n, φ, ts, hq, Set.Subset.rfl⟩

end WeakModel.AdequateGenericChain
end ZFVP.Infinitary

