import ZFVP.ModelTheory.LevySupportAlgebraClosure
import ZFVP.ModelTheory.SolovaySupportAlgebraBase

/-! The Galois step of Karagila-Schilhan Lemma 9.3 for the Levy collapse, reduced to a statement
about automorphisms of the collapse itself.

`GaloisStep P R one K E` lives two levels up: it speaks about a condition `b` of the Boolean
completion `B = RO(P)` and about the complete subalgebra of `RO(B)` generated by the Boolean
values `‖ǩ ∈ σ‖`, `σ ∈ E`. Both levels are redundant. `B` is separative, so `RO(B)` is `B` again
through regular cones, and `supportAlgebraBase` is the support algebra read back inside `RO(P)`.
`galoisStep_iff_base` says the two readings of the Galois step are the same statement, so one may
work entirely inside `RO(P)`.

Inside `RO(P)` the step is a Galois closure claim: the fixed algebra of the pointwise stabilizer
of `supportAlgebraBase` is that algebra again. `galoisStepBase_iff_moved` states it in the form
one actually proves, namely that every regular set outside the algebra is moved by some
automorphism of `B` fixing the algebra.

The automorphisms of `B` one can build are the lifts of automorphisms of `P`, and a lift lands in
the forced stabilizer of `E` as soon as the base automorphism fixes each Boolean value `‖ǩ ∈ σ‖`
read as a regular set of `P` (`booleanLift_mem_forcedStabilizer_of_fixes_supportValuesBase`). Note
that this asks much less than the earlier `booleanLift_mem_forcedStabilizer`, which asks the base
automorphism to fix every condition occurring in the names of `E`; the support values, not the
conditions of the names, are what the forced stabilizer sees. Feeding this in, the whole Galois
step for the Levy collapse reduces to

  for every regular set `b` of `Coll(ω, <κ)` outside the base support algebra of `E` there is an
  automorphism of `Coll(ω, <κ)` fixing the base support values and moving `b`,

and, using the localization of `ZFVP/ModelTheory/LevyGaloisStep.lean`, only those `b` that are
determined below the `ξ < κ` where the conditions of the names of `E` live have to be moved
(`levy_galoisStepBase_of_base_separates_determined`).

What is not proved here is that such automorphisms exist. The support algebra is generated by
countably many values and so is small, but it need not be the algebra of a subcollapse; the
refutation in `ZFVP/ModelTheory/LevySupportAlgebraClosure.lean` shows that replacing "fixed by the
forced stabilizer" by "determined below ξ" is false, so no argument that only uses the row
permutations can close the gap. The classical proof factors `RO(Coll(ω, <κ))` as `A * (B/A)` over
the support algebra `A`, uses that `Coll(ω, <κ)` absorbs the small quotient so that `B/A` is
forced to be a collapse again, and converts a name for an automorphism of `B/A` into an
automorphism of `B` fixing `A` elementwise. The repository has the factoring only at the level of
models (`solovay_factor`, `factorContext_homogeneous`): it produces a context over the
intermediate model with a homogeneous poset, but no transport of the automorphism group of the
collapse into that context, and no correspondence between names for automorphisms of the quotient
and automorphisms of `B` over `A`. That correspondence is the one missing ingredient.

Unconditionally settled here is the case where all the Boolean values of `E` are the zero or the
top (`levy_galoisStep_of_supportValuesBase_trivial`), which contains the empty support
(`levy_galoisStep_empty`): then every automorphism of the collapse lifts into the forced
stabilizer, and weak homogeneity forces `b` to be the top. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-! ### The Galois step read inside `RO(P)` -/

/-- The base-level Galois step: a condition of the Boolean completion fixed by the whole forced
stabilizer of `E` lies in the support algebra of `E` read as a complete subalgebra of `RO(P)`. -/
def GaloisStepBase (P R one K E : V) : Prop :=
  ∀ b ∈ booleanConditions P R,
    (∀ Θ ∈ forcedStabilizer (booleanConditions P R) (booleanOrder P R)
        (forcingAutomorphisms (booleanConditions P R) (booleanOrder P R)) E, Θ ‘ b = b) →
      b ∈ supportAlgebraBase P R one K E

/-- The base-level form and the original form of the Galois step are the same statement: the cone
map identifies `RO(RO(P))` with `RO(P)` and carries the base support algebra onto the support
algebra. -/
theorem galoisStep_iff_base (P R one K E : V) :
    GaloisStep P R one K E ↔ GaloisStepBase P R one K E := by
  constructor
  · intro h b hb hfix
    exact (mem_algebraPreimage_iff _ _ _ _).mpr ⟨booleanConditions_regular hb, h b hb hfix⟩
  · intro h b hb hfix
    exact ((mem_algebraPreimage_iff _ _ _ _).mp (h b hb hfix)).2

/-- The Galois step in the form one proves it: every condition of the completion outside the base
support algebra is moved by some automorphism in the forced stabilizer of `E`. -/
theorem galoisStepBase_iff_moved (P R one K E : V) :
    GaloisStepBase P R one K E ↔
      ∀ b ∈ booleanConditions P R, b ∉ supportAlgebraBase P R one K E →
        ∃ Θ ∈ forcedStabilizer (booleanConditions P R) (booleanOrder P R)
          (forcingAutomorphisms (booleanConditions P R) (booleanOrder P R)) E, Θ ‘ b ≠ b := by
  constructor
  · intro h b hb hno
    by_contra hcon
    refine hno (h b hb (fun Θ hΘ ↦ ?_))
    by_contra hne
    exact hcon ⟨Θ, hΘ, hne⟩
  · intro h b hb hfix
    by_contra hno
    obtain ⟨Θ, hΘ, hne⟩ := h b hb hno
    exact hne (hfix Θ hΘ)

theorem galoisStep_iff_moved (P R one K E : V) :
    GaloisStep P R one K E ↔
      ∀ b ∈ booleanConditions P R, b ∉ supportAlgebraBase P R one K E →
        ∃ Θ ∈ forcedStabilizer (booleanConditions P R) (booleanOrder P R)
          (forcingAutomorphisms (booleanConditions P R) (booleanOrder P R)) E, Θ ‘ b ≠ b :=
  (galoisStep_iff_base P R one K E).trans (galoisStepBase_iff_moved P R one K E)

/-! ### Lifts of base automorphisms that fix the support algebra -/

/-- The image action of any map on the empty set is empty. -/
theorem imageAction_empty (π : V) : imageAction π (∅ : V) = (∅ : V) := by
  apply mem_ext
  intro z
  rw [mem_imageAction_iff]
  constructor
  · rintro ⟨p, hp, -⟩
    exact (not_mem_empty hp).elim
  · intro hz
    exact (not_mem_empty hz).elim

/-- An automorphism of the base poset fixing every condition of the base support algebra of `E`
lifts to an automorphism of the completion lying in the forced stabilizer of `E`. Only the support
values have to be fixed; the conditions occurring in the names of `E` may be moved. -/
theorem booleanLift_mem_forcedStabilizer_of_fixes_supportAlgebraBase {P R K E π : V}
    (hP : ∃ p, p ∈ P) (hR : IsForcingPreorder P R) (hπ : IsForcingAutomorphism P R π)
    (hE : ∀ σ ∈ E, IsSaturatedNiceName (booleanConditions P R) (booleanOrder P R) P K σ)
    (hfix : ∀ a ∈ supportAlgebraBase P R P K E, a ∈ booleanConditions P R →
      imageAction π a = a) :
    booleanLift P R π ∈ forcedStabilizer (booleanConditions P R) (booleanOrder P R)
      (forcingAutomorphisms (booleanConditions P R) (booleanOrder P R)) E := by
  rw [forcedStabilizer_eq_imageStabilizer (booleanOrder_poset P R)
    (forcingAutomorphisms_group _ _) (booleanOrder_top hP) hE]
  refine (mem_imageStabilizer_iff _ _ _).mpr
    ⟨booleanLift_mem_forcingAutomorphisms hπ, fun A hA ↦ ?_⟩
  have hΘ := booleanLift_isForcingAutomorphism hπ
  by_cases hne : ∃ C, C ∈ A
  · obtain ⟨C₀, hC₀⟩ := hne
    have hAreg : IsForcingRegular (booleanConditions P R) (booleanOrder P R) A :=
      (mem_regularSets_iff _ _ _).mp
        (supportValues_subset_regularSets (booleanOrder_poset P R).1 P K E A hA)
    have hAB : A ∈ booleanConditions (booleanConditions P R) (booleanOrder P R) :=
      (mem_booleanConditions_iff _ _ A).mpr ⟨hAreg, C₀, hC₀⟩
    have ha : regularJoin P R A ∈ booleanConditions P R :=
      regularJoin_mem_booleanConditions hR hAreg.1 hC₀
    have hcone : coneRegular (booleanConditions P R) (booleanOrder P R) (regularJoin P R A) = A :=
      coneRegular_regularJoin hR hAB
    have haD : regularJoin P R A ∈ supportAlgebraBase P R P K E := by
      refine (mem_algebraPreimage_iff _ _ _ _).mpr ⟨booleanConditions_regular ha, ?_⟩
      rw [hcone]
      exact supportValues_subset_supportAlgebra _ _ _ _ _ _ hA
    have hval : (booleanLift P R π) ‘ (regularJoin P R A) = regularJoin P R A := by
      rw [booleanLift_value ha]
      exact hfix _ haD ha
    conv_lhs => rw [← hcone]
    rw [imageAction_coneRegular hΘ ha, hval, hcone]
  · have hA0 : A = (∅ : V) :=
      mem_ext (fun z ↦ ⟨fun hz ↦ absurd ⟨z, hz⟩ hne, fun hz ↦ absurd hz not_mem_empty⟩)
    rw [hA0, imageAction_empty]

/-- An automorphism of the base poset fixing the base support values fixes the whole base support
algebra, since that algebra is the complete subalgebra of `RO(P)` they generate. -/
theorem fixes_supportAlgebraBase_of_fixes_supportValuesBase {P R one K E π : V}
    (hP : ∃ p, p ∈ P) (hR : IsForcingPreorder P R) (hπ : IsForcingAutomorphism P R π)
    (hfix : ∀ b ∈ supportValuesBase P R one K E, imageAction π b = b) :
    ∀ a ∈ supportAlgebraBase P R one K E, imageAction π a = a := by
  rw [supportAlgebraBase_eq_generatedSubalgebra hR hP]
  exact imageStabilizer_fixes_generatedSubalgebra hR (forcingAutomorphisms_group P R)
    (supportValuesBase_subset_regularSets hR one K E)
    ((mem_imageStabilizer_iff _ _ _).mpr
      ⟨(mem_forcingAutomorphisms_iff _ _ _).mpr hπ, hfix⟩)

/-- The generator form of the lifting lemma: an automorphism of the base poset fixing each Boolean
value `‖ǩ ∈ σ‖`, read as a regular set of `P`, lifts into the forced stabilizer of `E`. -/
theorem booleanLift_mem_forcedStabilizer_of_fixes_supportValuesBase {P R K E π : V}
    (hP : ∃ p, p ∈ P) (hR : IsForcingPreorder P R) (hπ : IsForcingAutomorphism P R π)
    (hE : ∀ σ ∈ E, IsSaturatedNiceName (booleanConditions P R) (booleanOrder P R) P K σ)
    (hfix : ∀ b ∈ supportValuesBase P R P K E, imageAction π b = b) :
    booleanLift P R π ∈ forcedStabilizer (booleanConditions P R) (booleanOrder P R)
      (forcingAutomorphisms (booleanConditions P R) (booleanOrder P R)) E :=
  booleanLift_mem_forcedStabilizer_of_fixes_supportAlgebraBase hP hR hπ hE
    (fun a ha _ ↦ fixes_supportAlgebraBase_of_fixes_supportValuesBase hP hR hπ hfix a ha)

/-- The Galois step follows from the existence of automorphisms of the base poset that fix the
base support values and move any prescribed condition outside the base support algebra. -/
theorem galoisStepBase_of_base_separates {P R K E : V} (hP : ∃ p, p ∈ P)
    (hR : IsForcingPreorder P R)
    (hE : ∀ σ ∈ E, IsSaturatedNiceName (booleanConditions P R) (booleanOrder P R) P K σ)
    (hsep : ∀ b ∈ booleanConditions P R, b ∉ supportAlgebraBase P R P K E →
      ∃ π, IsForcingAutomorphism P R π ∧
        (∀ a ∈ supportValuesBase P R P K E, imageAction π a = a) ∧ imageAction π b ≠ b) :
    GaloisStepBase P R P K E := by
  intro b hb hfix
  by_contra hno
  obtain ⟨π, hπ, hfixa, hmove⟩ := hsep b hb hno
  refine hmove ?_
  rw [← booleanLift_value (P := P) (R := R) (π := π) hb]
  exact hfix _ (booleanLift_mem_forcedStabilizer_of_fixes_supportValuesBase hP hR hπ hE hfixa)

/-- The Galois step holds unconditionally when every Boolean value `‖ǩ ∈ σ‖` of `E` is the zero or
the top of `RO(P)`: then every automorphism of the base poset lifts into the forced stabilizer of
`E`, so a condition fixed by the stabilizer is fixed by every automorphism, hence is the top by
weak homogeneity. Taking `E` empty is the special case where there are no support values. -/
theorem galoisStep_of_supportValuesBase_trivial {P R one K E : V} (hP : ∃ p, p ∈ P)
    (hR : IsForcingPreorder P R) (hhom : IsWeaklyHomogeneous P R one)
    (hE : ∀ σ ∈ E, IsSaturatedNiceName (booleanConditions P R) (booleanOrder P R) P K σ)
    (htriv : ∀ a ∈ supportValuesBase P R P K E, a = (∅ : V) ∨ a = P) :
    GaloisStep P R P K E := by
  intro b hb hfix
  have hbtop : b = P := by
    refine eq_top_of_imageAction_fixed hhom hb (fun π hπ _ ↦ ?_)
    have hlift : booleanLift P R π ∈ forcedStabilizer (booleanConditions P R) (booleanOrder P R)
        (forcingAutomorphisms (booleanConditions P R) (booleanOrder P R)) E := by
      refine booleanLift_mem_forcedStabilizer_of_fixes_supportValuesBase hP hR hπ hE
        (fun a ha ↦ ?_)
      rcases htriv a ha with rfl | rfl
      · exact imageAction_empty π
      · exact imageAction_eq_of_iff hπ (fun _ h ↦ h) (fun _ h ↦ h)
          (fun q hq ↦ ⟨fun _ ↦ hq, fun _ ↦ function_value_mem hπ.1 hq⟩)
    rw [← booleanLift_value (P := P) (R := R) (π := π) hb]
    exact hfix _ hlift
  rw [hbtop, coneRegular_top_boolean hR]
  exact top_mem_supportAlgebra _ _ _ _ _

/-! ### The Levy collapse -/

/-- For the Levy collapse it is enough to move the conditions that are determined below `ξ`: a
condition fixed by the forced stabilizer of `E` is determined below any `ξ` at which the
conditions of the names of `E` are determined, so the separating automorphisms only have to be
built for those. -/
theorem levy_galoisStepBase_of_base_separates_determined {κ ξ K E : V} [IsOrdinal ξ]
    (hξ : ξ ⊆ κ)
    (hE : ∀ σ ∈ E, IsSaturatedNiceName (booleanConditions (levyCollapse κ) (levyOrder κ))
      (booleanOrder (levyCollapse κ) (levyOrder κ)) (levyCollapse κ) K σ)
    (hdet : ∀ d ∈ nameConditions E, IsLevyDeterminedBelow κ ξ d)
    (hsep : ∀ b ∈ booleanConditions (levyCollapse κ) (levyOrder κ),
      IsLevyDeterminedBelow κ ξ b →
      b ∉ supportAlgebraBase (levyCollapse κ) (levyOrder κ) (levyCollapse κ) K E →
      ∃ π, IsForcingAutomorphism (levyCollapse κ) (levyOrder κ) π ∧
        (∀ a ∈ supportValuesBase (levyCollapse κ) (levyOrder κ) (levyCollapse κ) K E,
          imageAction π a = a) ∧
        imageAction π b ≠ b) :
    GaloisStepBase (levyCollapse κ) (levyOrder κ) (levyCollapse κ) K E := by
  intro b hb hfix
  have hbdet : IsLevyDeterminedBelow κ ξ b :=
    levy_determined_below_of_forcedStabilizer_fixed_of_names hξ
      (fun σ hσ ↦ (hE σ hσ).nice) hdet hb hfix
  by_contra hno
  obtain ⟨π, hπ, hfixa, hmove⟩ := hsep b hb hbdet hno
  refine hmove ?_
  rw [← booleanLift_value (P := levyCollapse κ) (R := levyOrder κ) (π := π) hb]
  exact hfix _ (booleanLift_mem_forcedStabilizer_of_fixes_supportValuesBase
    ⟨∅, empty_mem_levyCollapse κ⟩ (levyCollapse_poset κ).1 hπ hE hfixa)

/-- The same in the original two-level form. -/
theorem levy_galoisStep_of_base_separates_determined {κ ξ K E : V} [IsOrdinal ξ]
    (hξ : ξ ⊆ κ)
    (hE : ∀ σ ∈ E, IsSaturatedNiceName (booleanConditions (levyCollapse κ) (levyOrder κ))
      (booleanOrder (levyCollapse κ) (levyOrder κ)) (levyCollapse κ) K σ)
    (hdet : ∀ d ∈ nameConditions E, IsLevyDeterminedBelow κ ξ d)
    (hsep : ∀ b ∈ booleanConditions (levyCollapse κ) (levyOrder κ),
      IsLevyDeterminedBelow κ ξ b →
      b ∉ supportAlgebraBase (levyCollapse κ) (levyOrder κ) (levyCollapse κ) K E →
      ∃ π, IsForcingAutomorphism (levyCollapse κ) (levyOrder κ) π ∧
        (∀ a ∈ supportValuesBase (levyCollapse κ) (levyOrder κ) (levyCollapse κ) K E,
          imageAction π a = a) ∧
        imageAction π b ≠ b) :
    GaloisStep (levyCollapse κ) (levyOrder κ) (levyCollapse κ) K E :=
  (galoisStep_iff_base _ _ _ _ _).mpr
    (levy_galoisStepBase_of_base_separates_determined hξ hE hdet hsep)

/-- The Levy instance of the trivial-value case. -/
theorem levy_galoisStep_of_supportValuesBase_trivial {κ K E : V}
    (hE : ∀ σ ∈ E, IsSaturatedNiceName (booleanConditions (levyCollapse κ) (levyOrder κ))
      (booleanOrder (levyCollapse κ) (levyOrder κ)) (levyCollapse κ) K σ)
    (htriv : ∀ a ∈ supportValuesBase (levyCollapse κ) (levyOrder κ) (levyCollapse κ) K E,
      a = (∅ : V) ∨ a = levyCollapse κ) :
    GaloisStep (levyCollapse κ) (levyOrder κ) (levyCollapse κ) K E :=
  galoisStep_of_supportValuesBase_trivial ⟨∅, empty_mem_levyCollapse κ⟩ (levyCollapse_poset κ).1
    (levyCollapse_homogeneous κ) hE htriv

/-- The Galois step for the Levy collapse and the empty support, with no hypotheses: a condition
fixed by every automorphism of the completion is the top, by weak homogeneity of the collapse. -/
theorem levy_galoisStep_empty (κ K : V) :
    GaloisStep (levyCollapse κ) (levyOrder κ) (levyCollapse κ) K (∅ : V) := by
  refine galoisStep_of_rigid ⟨∅, empty_mem_levyCollapse κ⟩ (levyCollapse_homogeneous κ)
    (fun σ hσ ↦ (not_mem_empty hσ).elim) (fun d hd ↦ ?_)
  obtain ⟨σ, hσ, -⟩ := (mem_nameConditions_iff _ d).mp hd
  exact (not_mem_empty hσ).elim

end ZFVP
