import ZFVP.ModelTheory.LevySupportGalois
import ZFVP.ModelTheory.LevyBooleanAntichainSupport

/-! The Galois step of Karagila-Schilhan Lemma 9.3 for the Levy collapse, without a rigidity
hypothesis on the conditions of the names.

The rigid version in `ZFVP/ModelTheory/LevySupportGalois.lean` assumes that every condition of
every name in `E` is fixed by every automorphism of the base poset fixing the top, and then weak
homogeneity forces the condition `b` to be the top. Here we replace that by the localization
argument.

A regular set `d` of `Coll(ω, <κ)` contains a maximal antichain `A`, and `A` is an antichain of
the poset, so its supports are bounded below `κ`: there is `ξ < κ` with `A ⊆ Coll(ω, <ξ)`. Any
automorphism of the collapse fixing `Coll(ω, <ξ)` pointwise then fixes `d`
(`levy_regular_fixed_of_fixes_subcollapse`).

Conversely, a regular set fixed by all the row permutations above `ξ` is determined below `ξ`:
`p ∈ d` iff the part of `p` below `ξ` is in `d` (`IsLevyDeterminedBelow`). This is the tail
homogeneity step; the proof moves the rows of `p` above `ξ` off the rows of a given `q` extending
the part of `p` below `ξ`, which makes the moved condition compatible with `q`.

Putting the two together, every regular set of the Levy collapse is determined below some `ξ < κ`
(`levy_regular_exists_determined_below`), and a condition `b` fixed by the whole forced stabilizer
of `E` is determined below any `ξ` at which the row permutations lift into that stabilizer
(`levy_determined_below_of_forcedStabilizer_fixed`). What is still missing for the full Galois
step is the last move, from "b is determined below ξ" to "the cone of b lies in the algebra
generated by the support values of E". That move is a Galois closure statement about the
subcollapse `Coll(ω, <ξ)`: the algebra generated by the support values need not be the algebra of
a subcollapse, so the row permutations no longer suffice and one needs automorphisms of
`Coll(ω, <ξ)` fixing the support values and moving a prescribed regular set. Nothing in this file
assumes it. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-! ### Automorphisms fixing a maximal antichain of a regular set -/

/-- An automorphism fixing every element of a maximal antichain of `d` maps `d` into `d`. -/
theorem imageAction_subset_of_maximalAntichain_fixed {P R d A π : V}
    (hd : IsForcingRegular P R d) (hA : IsMaximalAntichainIn P R d A)
    (hπ : IsForcingAutomorphism P R π) (hfix : ∀ a ∈ A, π ‘ a = a) :
    imageAction π d ⊆ d := by
  intro x hx
  obtain ⟨q, hq, rfl⟩ := (mem_imageAction_iff _ _ _).mp hx
  have hqP : q ∈ P := hd.1 q hq
  have hπq : π ‘ q ∈ P := function_value_mem hπ.1 hqP
  refine hd.2.2 _ hπq (fun r hr hrq ↦ ?_)
  obtain ⟨r', hr', rfl⟩ := forcingAutomorphism_surjective hπ r hr
  have hr'q : ⟨r', q⟩ₖ ∈ R := (hπ.2.2.2 r' hr' q hqP).mpr hrq
  have hr'd : r' ∈ d := hd.2.1 q hq r' hr' hr'q
  obtain ⟨a, haA, t, htP, hta, htr'⟩ := hA.2.2 r' hr'd
  have haP : a ∈ P := hd.1 a (hA.2.1 a haA)
  refine ⟨π ‘ t, ?_, (hπ.2.2.2 t htP r' hr').mp htr'⟩
  have h1 : ⟨π ‘ t, π ‘ a⟩ₖ ∈ R := (hπ.2.2.2 t htP a haP).mp hta
  rw [hfix a haA] at h1
  exact hd.2.1 a (hA.2.1 a haA) _ (function_value_mem hπ.1 htP) h1

/-- An automorphism fixing every element of a maximal antichain of `d` fixes `d`. -/
theorem imageAction_eq_self_of_maximalAntichain_fixed {P R d A π : V}
    (hd : IsForcingRegular P R d) (hA : IsMaximalAntichainIn P R d A)
    (hπ : IsForcingAutomorphism P R π) (hfix : ∀ a ∈ A, π ‘ a = a) :
    imageAction π d = d := by
  have hinv := forcingAutomorphism_inverse hπ
  have hfixinv : ∀ a ∈ A, (converseGraph π) ‘ a = a := by
    intro a ha
    have haP : a ∈ P := hd.1 a (hA.2.1 a ha)
    conv_lhs => rw [← hfix a ha]
    exact converseGraph_value_value hπ.1 hπ.2.1 haP
  apply SetTheory.subset_antisymm (imageAction_subset_of_maximalAntichain_fixed hd hA hπ hfix)
  intro x hx
  have hxP : x ∈ P := hd.1 x hx
  have hxr : x ∈ range π := hπ.2.2.1.symm ▸ hxP
  have hinvx : (converseGraph π) ‘ x ∈ d :=
    imageAction_subset_of_maximalAntichain_fixed hd hA hinv hfixinv _
      ((mem_imageAction_iff _ _ _).mpr ⟨x, hx, rfl⟩)
  exact (mem_imageAction_iff _ _ _).mpr
    ⟨(converseGraph π) ‘ x, hinvx, (value_converseGraph_value hπ.1 hπ.2.1 hxr).symm⟩

/-! ### Localizing a regular set of the Levy collapse -/

section

variable {κ U : V} [IsOrdinal κ] (hAC : InternalChoice V)
  (hU : IsNonprincipalSetUltrafilter κ U) (hc : IsOrdinalComplete κ U)
  (hω : (ω : V) ∈ κ) (hκ : IsInitialOrdinal κ)

include hAC hU hc hω hκ in
/-- A regular set of the Levy collapse contains a maximal antichain all of whose conditions lie
in one subcollapse `Coll(ω, <ξ)` with `ξ < κ`. -/
theorem levy_exists_localized_maximalAntichain {d : V}
    (hd : IsForcingRegular (levyCollapse κ) (levyOrder κ) d) :
    ∃ ξ ∈ κ, ∃ A, IsMaximalAntichainIn (levyCollapse κ) (levyOrder κ) d A ∧
      A ⊆ levyCollapse ξ := by
  obtain ⟨A, hA⟩ := exists_maximalAntichain (levyCollapse_poset κ).1 hd.1
    (wellOrderable_of_internalChoice hAC d)
  obtain ⟨ξ, hξ, hsupp⟩ := levyAntichain_supports_bounded hAC hU hc hω hκ hA.1
  have : IsOrdinal ξ := IsOrdinal.of_mem hξ
  refine ⟨ξ, hξ, A, hA, fun p hp ↦ ?_⟩
  have hpP : p ∈ levyCollapse κ := hA.1.1 p hp
  rw [← levyCut_eq_of_support hpP (hsupp p hp)]
  exact levyCut_mem hpP

include hAC hU hc hω hκ in
/-- Every regular set of the Levy collapse is fixed by every automorphism that fixes one
subcollapse `Coll(ω, <ξ)` pointwise, for some `ξ < κ`. -/
theorem levy_regular_fixed_of_fixes_subcollapse {d : V}
    (hd : IsForcingRegular (levyCollapse κ) (levyOrder κ) d) :
    ∃ ξ ∈ κ, ∀ π, IsForcingAutomorphism (levyCollapse κ) (levyOrder κ) π →
      (∀ p ∈ levyCollapse ξ, π ‘ p = p) → imageAction π d = d := by
  obtain ⟨ξ, hξ, A, hA, hAξ⟩ := levy_exists_localized_maximalAntichain hAC hU hc hω hκ hd
  exact ⟨ξ, hξ, fun π hπ hfix ↦
    imageAction_eq_self_of_maximalAntichain_fixed hd hA hπ (fun a ha ↦ hfix a (hAξ a ha))⟩

end

/-! ### Being determined below an ordinal -/

/-- A set of conditions of `Coll(ω, <κ)` is determined below `ξ` when membership in it depends
only on the part of a condition below `ξ`. -/
def IsLevyDeterminedBelow (κ ξ d : V) : Prop :=
  ∀ p ∈ levyCollapse κ, (p ∈ d ↔ levyCut ξ p ∈ d)

/-- A row permutation above `ξ` does not change the part of a condition below `ξ`. -/
theorem levyCut_levyPermutation_value {κ ξ s p : V} (hs : IsInternalPermutation (ω : V) s)
    (hp : p ∈ levyCollapse κ) :
    levyCut ξ ((levyPermutation κ ξ s) ‘ p) = levyCut ξ p := by
  have hpfun : IsFunction p := ((mem_finitePartialFunctions _ _ p).mp
    (levyCollapse_finitePartialFunction hp)).2.1
  have hsub := ((mem_finitePartialFunctions _ _ p).mp (levyCollapse_finitePartialFunction hp)).1
  rw [levyPermutation_value hp]
  apply mem_ext
  intro z
  simp only [levyCut, mem_restrict_iff]
  constructor
  · rintro ⟨hz, x, hx, y, rfl⟩
    obtain ⟨u, hu, hxu⟩ := (pair_mem_permutedGraph _ p x y).mp hz
    obtain ⟨n, hn, α, hα, rfl⟩ := mem_prod_iff.mp (kpair_mem_iff.mp (hsub _ hu)).1
    by_cases hαξ : α ∈ ξ
    · rw [levyRowPermutation_value_below hs hn hα hαξ] at hxu
      subst hxu
      exact ⟨hu, _, hx, y, rfl⟩
    · rw [levyRowPermutation_value_above hs hn hα hαξ] at hxu
      subst hxu
      exact absurd (kpair_mem_iff.mp hx).2 hαξ
  · rintro ⟨hz, x, hx, y, rfl⟩
    obtain ⟨n, hn, α, hαξ, rfl⟩ := mem_prod_iff.mp hx
    obtain ⟨-, hα⟩ := kpair_mem_iff.mp (kpair_mem_iff.mp (hsub _ hz)).1
    refine ⟨(pair_mem_permutedGraph _ p _ y).mpr ⟨⟨n, α⟩ₖ, hz, ?_⟩, _, hx, y, rfl⟩
    exact (levyRowPermutation_value_below hs hn hα hαξ).symm

/-- A set of conditions determined below `ξ` is fixed by the row permutations above `ξ`. -/
theorem levyPermutation_imageAction_eq_self_of_determined {κ ξ s d : V}
    (hs : IsInternalPermutation (ω : V) s) (hd : d ⊆ levyCollapse κ)
    (hdet : IsLevyDeterminedBelow κ ξ d) :
    imageAction (levyPermutation κ ξ s) d = d := by
  have hπ := levyPermutation_automorphism (κ := κ) (β := ξ) hs
  refine imageAction_eq_of_iff hπ hd hd (fun q hq ↦ ?_)
  rw [hdet _ (function_value_mem hπ.1 hq), levyCut_levyPermutation_value hs hq, ← hdet q hq]

/-! ### Tail homogeneity: a set fixed by the row permutations is determined below `ξ` -/

/-- If a regular set is fixed by every row permutation above `ξ`, then the part below `ξ` of each
of its conditions is again in it. -/
theorem levyCut_mem_of_rowPermutations_fixed {κ ξ d : V} [IsOrdinal ξ] (hξ : ξ ⊆ κ)
    (hd : IsForcingRegular (levyCollapse κ) (levyOrder κ) d)
    (hfix : ∀ s, IsInternalPermutation (ω : V) s → imageAction (levyPermutation κ ξ s) d = d)
    {p : V} (hp : p ∈ d) : levyCut ξ p ∈ d := by
  have hpP : p ∈ levyCollapse κ := hd.1 p hp
  have hcutP : levyCut ξ p ∈ levyCollapse κ := levyCollapse_mono hξ _ (levyCut_mem hpP)
  refine hd.2.2 _ hcutP (fun q hq hqcut ↦ ?_)
  have hqsub : levyCut ξ p ⊆ q := ((pair_mem_reverseInclusionOrder _ _ _).mp hqcut).2.2
  obtain ⟨s, hs, hmove⟩ := exists_permutation_moving (levyRows_finite (β := ξ) hpP)
    (levyRows_subset ξ p) (levyRows_finite (β := ξ) hq) (levyRows_subset ξ q)
  have hπ := levyPermutation_automorphism (κ := κ) (β := ξ) hs
  have hπp : (levyPermutation κ ξ s) ‘ p ∈ levyCollapse κ := function_value_mem hπ.1 hpP
  have hcompat : ∀ x y z, ⟨x, y⟩ₖ ∈ (levyPermutation κ ξ s) ‘ p → ⟨x, z⟩ₖ ∈ q → y = z := by
    rw [levyPermutation_value hpP]
    exact levyPermutation_compatible hs hpP hq hqsub hmove
  have hu : (levyPermutation κ ξ s) ‘ p ∪ q ∈ levyCollapse κ :=
    levyCollapse_union hπp hq hcompat
  have hπpd : (levyPermutation κ ξ s) ‘ p ∈ d := by
    rw [← hfix s hs]
    exact (mem_imageAction_iff _ _ _).mpr ⟨p, hp, rfl⟩
  refine ⟨(levyPermutation κ ξ s) ‘ p ∪ q, hd.2.1 _ hπpd _ hu ?_, ?_⟩
  · exact (pair_mem_reverseInclusionOrder _ _ _).mpr ⟨hu, hπp, subset_union_left _ _⟩
  · exact (pair_mem_reverseInclusionOrder _ _ _).mpr ⟨hu, hq, subset_union_right _ _⟩

/-- Tail homogeneity: a regular set fixed by every row permutation above `ξ` is determined
below `ξ`. -/
theorem levy_determinedBelow_of_rowPermutations_fixed {κ ξ d : V} [IsOrdinal ξ] (hξ : ξ ⊆ κ)
    (hd : IsForcingRegular (levyCollapse κ) (levyOrder κ) d)
    (hfix : ∀ s, IsInternalPermutation (ω : V) s → imageAction (levyPermutation κ ξ s) d = d) :
    IsLevyDeterminedBelow κ ξ d := by
  intro p hp
  refine ⟨fun h ↦ levyCut_mem_of_rowPermutations_fixed hξ hd hfix h, fun h ↦ ?_⟩
  have hcutP : levyCut ξ p ∈ levyCollapse κ := levyCollapse_subset hp (levyCut_subset ξ p)
  exact hd.2.1 _ h p hp
    ((pair_mem_reverseInclusionOrder _ _ _).mpr ⟨hp, hcutP, levyCut_subset ξ p⟩)

/-! ### Every regular set is determined below some `ξ < κ` -/

section

variable {κ U : V} [IsOrdinal κ] (hAC : InternalChoice V)
  (hU : IsNonprincipalSetUltrafilter κ U) (hc : IsOrdinalComplete κ U)
  (hω : (ω : V) ∈ κ) (hκ : IsInitialOrdinal κ)

include hAC hU hc hω hκ in
/-- Every regular set of the Levy collapse at a measurable is determined below some `ξ < κ`. -/
theorem levy_regular_exists_determined_below {d : V}
    (hd : IsForcingRegular (levyCollapse κ) (levyOrder κ) d) :
    ∃ ξ ∈ κ, IsLevyDeterminedBelow κ ξ d := by
  obtain ⟨ξ, hξ, hfix⟩ := levy_regular_fixed_of_fixes_subcollapse hAC hU hc hω hκ hd
  have : IsOrdinal ξ := IsOrdinal.of_mem hξ
  have hξκ : ξ ⊆ κ := IsOrdinal.toIsTransitive.transitive _ hξ
  refine ⟨ξ, hξ, levy_determinedBelow_of_rowPermutations_fixed hξκ hd (fun s hs ↦ ?_)⟩
  exact hfix _ (levyPermutation_automorphism hs) (fun p hp ↦ levyPermutation_fixed hs hp hξκ)

end

/-! ### Feeding the row permutations into the forced stabilizer -/

/-- The conditions occurring in a set of nice names are conditions of the poset the names live
over. -/
theorem nameConditions_subset {Q one K E : V} (hE : ∀ σ ∈ E, IsNiceName Q one K σ) :
    nameConditions E ⊆ Q := by
  intro d hd
  obtain ⟨σ, hσ, z, hz, rfl⟩ := (mem_nameConditions_iff E d).mp hd
  obtain ⟨k, -, p, hp, rfl⟩ := hE σ hσ z hz
  rw [kpair.π₂_kpair]
  exact hp

/-- If every condition of every name in `E` is determined below `ξ`, then the lift of a row
permutation above `ξ` lies in the forced stabilizer of `E`. -/
theorem levy_booleanLift_mem_forcedStabilizer_of_determined {κ ξ s K E : V}
    (hs : IsInternalPermutation (ω : V) s)
    (hE : ∀ σ ∈ E, IsNiceName (booleanConditions (levyCollapse κ) (levyOrder κ))
      (levyCollapse κ) K σ)
    (hdet : ∀ d ∈ nameConditions E, IsLevyDeterminedBelow κ ξ d) :
    booleanLift (levyCollapse κ) (levyOrder κ) (levyPermutation κ ξ s) ∈
      forcedStabilizer (booleanConditions (levyCollapse κ) (levyOrder κ))
        (booleanOrder (levyCollapse κ) (levyOrder κ))
        (forcingAutomorphisms (booleanConditions (levyCollapse κ) (levyOrder κ))
          (booleanOrder (levyCollapse κ) (levyOrder κ))) E := by
  refine booleanLift_mem_forcedStabilizer ⟨∅, empty_mem_levyCollapse κ⟩
    (levyPermutation_automorphism hs) hE (fun d hd ↦ ?_)
  have hdB : d ∈ booleanConditions (levyCollapse κ) (levyOrder κ) := nameConditions_subset hE d hd
  exact levyPermutation_imageAction_eq_self_of_determined hs
    (booleanConditions_regular hdB).1 (hdet d hd)

/-! ### The Galois step, as far as it goes -/

/-- If the row permutations above `ξ` lift into the forced stabilizer of `E`, then a condition of
the completion fixed by the whole forced stabilizer of `E` is determined below `ξ`. This is the
localization half of the Galois step of Karagila-Schilhan Lemma 9.3, with no rigidity assumption
on the conditions of the names. -/
theorem levy_determined_below_of_forcedStabilizer_fixed {κ ξ E b : V} [IsOrdinal ξ]
    (hξ : ξ ⊆ κ)
    (hsupp : ∀ s, IsInternalPermutation (ω : V) s →
      booleanLift (levyCollapse κ) (levyOrder κ) (levyPermutation κ ξ s) ∈
        forcedStabilizer (booleanConditions (levyCollapse κ) (levyOrder κ))
          (booleanOrder (levyCollapse κ) (levyOrder κ))
          (forcingAutomorphisms (booleanConditions (levyCollapse κ) (levyOrder κ))
            (booleanOrder (levyCollapse κ) (levyOrder κ))) E)
    (hb : b ∈ booleanConditions (levyCollapse κ) (levyOrder κ))
    (hfix : ∀ Θ ∈ forcedStabilizer (booleanConditions (levyCollapse κ) (levyOrder κ))
      (booleanOrder (levyCollapse κ) (levyOrder κ))
      (forcingAutomorphisms (booleanConditions (levyCollapse κ) (levyOrder κ))
        (booleanOrder (levyCollapse κ) (levyOrder κ))) E, Θ ‘ b = b) :
    IsLevyDeterminedBelow κ ξ b := by
  refine levy_determinedBelow_of_rowPermutations_fixed hξ (booleanConditions_regular hb)
    (fun s hs ↦ ?_)
  rw [← booleanLift_value (P := levyCollapse κ) (R := levyOrder κ)
    (π := levyPermutation κ ξ s) hb]
  exact hfix _ (hsupp s hs)

/-- The combined form: if every condition of every name in `E` is determined below `ξ`, then a
condition fixed by the forced stabilizer of `E` is determined below `ξ` as well. -/
theorem levy_determined_below_of_forcedStabilizer_fixed_of_names {κ ξ K E b : V} [IsOrdinal ξ]
    (hξ : ξ ⊆ κ)
    (hE : ∀ σ ∈ E, IsNiceName (booleanConditions (levyCollapse κ) (levyOrder κ))
      (levyCollapse κ) K σ)
    (hdet : ∀ d ∈ nameConditions E, IsLevyDeterminedBelow κ ξ d)
    (hb : b ∈ booleanConditions (levyCollapse κ) (levyOrder κ))
    (hfix : ∀ Θ ∈ forcedStabilizer (booleanConditions (levyCollapse κ) (levyOrder κ))
      (booleanOrder (levyCollapse κ) (levyOrder κ))
      (forcingAutomorphisms (booleanConditions (levyCollapse κ) (levyOrder κ))
        (booleanOrder (levyCollapse κ) (levyOrder κ))) E, Θ ‘ b = b) :
    IsLevyDeterminedBelow κ ξ b :=
  levy_determined_below_of_forcedStabilizer_fixed hξ
    (fun _ hs ↦ levy_booleanLift_mem_forcedStabilizer_of_determined hs hE hdet) hb hfix

end ZFVP
