import ZFVP.ModelTheory.LevyOrbitTransferCone

/-! The cone hypothesis of the Solovay corollary from a homogeneity statement about the Boolean
completion alone.

`ForcingContext.IsConeAligned` (`ZFVP/ModelTheory/LevyOrbitTransferCone.lean`) is the open
hypothesis of the wave-4 chain. It still speaks about the generic filter, about an orbit filter
`H`, and about which conditions are regular cones of conditions of the base poset. The hypothesis
introduced here, `ForcingContext.ComplementConeIsomorphic`, mentions none of that. It says: an
isomorphism of two cones of the Boolean completion that fixes the base support values relatively
extends to an isomorphism of the two complementary cones fixing them relatively as well. That is
relative homogeneity of the completion over the subalgebra generated by the support values.

`coneOrbitTransfer_of_complementConeIsomorphic` derives `ForcingContext.ConeOrbitTransfer` from it.
The positive half of the cone data comes from `exists_orbit_cone_isomorphism_support`, which
already produces a condition `q₀` of `H`, a condition `r` of the generic filter, an isomorphism
`ψ` of the cone below `q₀` onto the cone below `coneRegular r`, the filter clause and the support
clause. Only the complementary isomorphism is missing, and that is what the new hypothesis
supplies, applied to the inverse of `ψ`.

Two points of bookkeeping.

* The support clause of `exists_orbit_cone_isomorphism_support` has the form
  `ψ ‘ (d ∩ q₀) = d ∩ coneRegular r` for `d` of the base support algebra with `d ∩ q₀` a
  condition. `coneImage_inverse` needs it in `coneImage` form for every base support value,
  including the case `d ∩ q₀ = ∅`. That case is settled inside the support algebra: it is a
  complete subalgebra of `RO(P)`, so it contains `¬d`, and `d ∩ q₀ = ∅` says `q₀ ⊆ ¬d`. The
  support clause at `¬d` then reads `ψ ‘ q₀ = ¬d ∩ coneRegular r`, and `ψ ‘ q₀ = coneRegular r`,
  so `coneRegular r ⊆ ¬d` and `d ∩ coneRegular r = ∅`.

* `exists_orbit_cone_isomorphism_support` asks for the support sequence to be a function with
  domain `k`, while `ConeOrbitTransfer` supplies only that the members of `range s` are saturated
  nice names. Those two clauses are carried here as explicit hypotheses. They are exactly what the
  agreement of an orbit filter with the generic on the support algebra needs
  (`orbitFilter_agree_supportValuesBase` uses them to write each member of `range s` as `s ‘ i`
  for an `i ∈ k`), and they hold at the one place where the cone hypothesis is consumed, where the
  support sequence is the finite enumeration of a support of a hereditarily symmetric name. So
  `groundRealDefinable_booleanReal_of_complement` repeats the argument of
  `groundRealDefinable_booleanReal_of_cone` with the cone hypothesis asked for only of the
  well-formed support sequences, and `solovay_corollary_of_complement` is the paper's `cor:Solovay`
  with `ComplementConeIsomorphic` as its only open assumption, with no side condition left. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

namespace ForcingContext

/-! ### The homogeneity hypothesis -/

/-- Relative homogeneity of the Boolean completion over the subalgebra generated by the base
support values of `E`: every isomorphism `f` of the cone below a condition `b0` onto the cone below
a condition `c0` that fixes the base support values relatively, in the sense
`f (a ∩ b0) = a ∩ c0`, is matched by an isomorphism `g` of the cone below `¬b0` onto the cone below
`¬c0` fixing them relatively as well.

Nothing here refers to the generic filter, to an orbit filter, or to the base poset: the statement
is about the Boolean completion, its cones and the support values alone. Both support clauses are
in `coneImage` form, so they also say that an empty relative trace on one side is an empty relative
trace on the other. -/
def ComplementConeIsomorphic (A : ForcingContext V) (E : V) : Prop :=
  ∀ b0 ∈ booleanConditions A.P A.R, ∀ c0 ∈ booleanConditions A.P A.R, ∀ f : V,
    IsForcingIsomorphism
        (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R) b0)
        (restrictedOrder (booleanOrder A.P A.R)
          (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R) b0))
        (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R) c0)
        (restrictedOrder (booleanOrder A.P A.R)
          (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R) c0)) f →
    (∀ a ∈ supportValuesBase A.P A.R A.P ((ω : V) ×ˢ (ω : V)) E,
      coneImage A.P A.R b0 f (a ∩ b0) = a ∩ c0) →
    ∃ g : V,
      IsForcingIsomorphism
          (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R)
            (forcingNegation A.P A.R b0))
          (restrictedOrder (booleanOrder A.P A.R)
            (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R)
              (forcingNegation A.P A.R b0)))
          (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R)
            (forcingNegation A.P A.R c0))
          (restrictedOrder (booleanOrder A.P A.R)
            (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R)
              (forcingNegation A.P A.R c0))) g ∧
      ∀ a ∈ supportValuesBase A.P A.R A.P ((ω : V) ×ˢ (ω : V)) E,
        coneImage A.P A.R (forcingNegation A.P A.R b0) g
            (a ∩ forcingNegation A.P A.R b0) =
          a ∩ forcingNegation A.P A.R c0

/-! ### The support clause in `coneImage` form -/

variable {A : ForcingContext V}

/-- The support clause of `exists_orbit_cone_isomorphism_support`, rewritten in `coneImage` form
for the base support values. The case of an empty relative trace is settled by passing to the
negation inside the support algebra. -/
theorem coneImage_of_support_clause {q0 p0 ψ E : V} (hq0 : q0 ∈ booleanConditions A.P A.R)
    (hp0 : p0 ∈ booleanConditions A.P A.R)
    (hψ : IsForcingIsomorphism
      (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R) q0)
      (restrictedOrder (booleanOrder A.P A.R)
        (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R) q0))
      (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R) p0)
      (restrictedOrder (booleanOrder A.P A.R)
        (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R) p0)) ψ)
    (hsupp : ∀ d ∈ supportAlgebraBase A.P A.R A.P ((ω : V) ×ˢ (ω : V)) E,
      d ∩ q0 ∈ booleanConditions A.P A.R → ψ ‘ (d ∩ q0) = d ∩ p0)
    {a : V} (ha : a ∈ supportValuesBase A.P A.R A.P ((ω : V) ×ˢ (ω : V)) E) :
    coneImage A.P A.R q0 ψ (a ∩ q0) = a ∩ p0 := by
  have haS : a ∈ supportAlgebraBase A.P A.R A.P ((ω : V) ×ˢ (ω : V)) E :=
    supportValuesBase_subset_supportAlgebraBase A.order _ _ _ a ha
  have hareg : IsForcingRegular A.P A.R a :=
    (mem_regularSets_iff _ _ _).mp (supportValuesBase_subset_regularSets A.order _ _ _ a ha)
  rcases inter_mem_forcingCone_or_empty hareg hq0 with hc | hc
  · rw [coneImage_value hψ hc]
    exact hsupp a haS ((mem_forcingCone_iff _ _ _ _).mp hc).1
  · -- the relative trace on `q0` is empty, so the relative trace on `p0` is empty too
    rw [hc, coneImage_empty]
    have hD := isCompleteSubalgebra_supportAlgebraBase A.order ⟨A.one, A.top.1⟩ A.P
      ((ω : V) ×ˢ (ω : V)) E
    have hnS : forcingNegation A.P A.R a ∈ supportAlgebraBase A.P A.R A.P ((ω : V) ×ˢ (ω : V)) E :=
      hD.2.2.1 a haS
    have hq0a : q0 ∩ a = (∅ : V) := by rw [inter_comm_set]; exact hc
    have hq0n : q0 ⊆ forcingNegation A.P A.R a :=
      (subset_forcingNegation_iff A.order (booleanConditions_regular hq0) hareg.1).mpr hq0a
    have hnq : forcingNegation A.P A.R a ∩ q0 = q0 := by
      rw [inter_comm_set]; exact inter_eq_left_of_subset hq0n
    have hval := hsupp _ hnS (by rw [hnq]; exact hq0)
    rw [hnq, coneIsomorphism_value_top hq0 hp0 hψ] at hval
    have hp0n : p0 ⊆ forcingNegation A.P A.R a := by
      intro z hz
      have : z ∈ forcingNegation A.P A.R a ∩ p0 := by rw [← hval]; exact hz
      exact (mem_inter_iff.mp this).1
    have hzero : a ∩ p0 = (∅ : V) := by
      apply mem_ext
      intro z
      simp only [not_mem_empty, iff_false]
      intro hz
      obtain ⟨hza, hzp⟩ := mem_inter_iff.mp hz
      have hzn : z ∈ a ∩ forcingNegation A.P A.R a :=
        mem_inter_iff.mpr ⟨hza, hp0n z hzp⟩
      rw [inter_forcingNegation_eq_empty A.order hareg.1] at hzn
      exact not_mem_empty hzn
    rw [hzero]

/-! ### The cone hypothesis -/

/-- The cone hypothesis from relative homogeneity of the Boolean completion. The two conditions are
the condition `q₀` of the orbit filter and the regular cone of a condition of the generic filter
produced by `exists_orbit_cone_isomorphism_support`, the isomorphism of the positive cones is the
inverse of the one produced there, and the isomorphism of the complementary cones is the one the
homogeneity hypothesis returns for it.

The support sequence is asked to be a function with domain `k`. That is what
`exists_orbit_cone_isomorphism_support` needs in order to identify `range s` with the values
`s ‘ i` for `i ∈ k`, and it is available where the cone hypothesis is used. -/
theorem coneOrbitTransfer_of_complementConeIsomorphic (hAC : InternalChoice V)
    {Pf : SetTheorySemisentence 2} {s k : V} [IsFunction s] (hsdom : domain s = k) {p : A.Model}
    (hPf : ∀ y : A.Model, Pf.Evalb ![y, p] → ∃ a : V, y = A.check a)
    (hcomp : A.ComplementConeIsomorphic (range s)) :
    A.ConeOrbitTransfer Pf s k p := by
  intro hE H hH
  have hs : ∀ i ∈ k, IsSaturatedNiceName (booleanConditions A.P A.R) (booleanOrder A.P A.R) A.P
      ((ω : V) ×ˢ (ω : V)) (s ‘ i) := by
    intro i hi
    exact hE _ (mem_range_of_kpair_mem (kpair_value_mem (by rw [hsdom]; exact hi)))
  obtain ⟨r, hrG, q₀, hq₀B, ψ, hq₀H, hψ, hfilter, hsupp⟩ :=
    exists_orbit_cone_isomorphism_support hAC hsdom hs hH hPf
  have hrP : r ∈ A.P := A.generic.1.1 r hrG
  have hp0 : coneRegular A.P A.R r ∈ booleanConditions A.P A.R :=
    coneRegular_mem_booleanConditions A.order hrP
  have hcone : ∀ a ∈ supportValuesBase A.P A.R A.P ((ω : V) ×ˢ (ω : V)) (range s),
      coneImage A.P A.R q₀ ψ (a ∩ q₀) = a ∩ coneRegular A.P A.R r :=
    fun a ha ↦ coneImage_of_support_clause hq₀B hp0 hψ hsupp ha
  have hinv : ∀ a ∈ supportValuesBase A.P A.R A.P ((ω : V) ×ˢ (ω : V)) (range s),
      coneImage A.P A.R (coneRegular A.P A.R r) (converseGraph ψ)
        (a ∩ coneRegular A.P A.R r) = a ∩ q₀ := by
    intro a ha
    have hareg : IsForcingRegular A.P A.R a :=
      (mem_regularSets_iff _ _ _).mp (supportValuesBase_subset_regularSets A.order _ _ _ a ha)
    exact coneImage_inverse hψ hq₀B hareg (hcone a ha)
  obtain ⟨g, hg, hgsupp⟩ := hcomp _ hp0 _ hq₀B (converseGraph ψ)
    (isForcingIsomorphism_inverse hψ) hinv
  exact ⟨coneRegular A.P A.R r, hp0, q₀, hq₀B, converseGraph ψ, g,
    isForcingIsomorphism_inverse hψ, hg, ⟨r, hrG, self_mem_coneRegular A.order hrP⟩, hq₀H,
    filterTransfer_inverse hp0 hψ hfilter, fun a ha ↦ ⟨hinv a ha, hgsupp a ha⟩⟩

/-! ### The value of a symmetric name -/

/-- The value of a hereditarily symmetric name of the Solovay system is definable in the extension
from ground sets, reals and ordinals, given the cone hypothesis for the well-formed support
sequences. This is `groundRealDefinable_booleanReal_of_cone` with the cone hypothesis asked for
only of the sequences that are functions with domain the index set: the support of a name is
enumerated by such a sequence, and that is the only sequence the argument feeds to the
hypothesis. -/
theorem groundRealDefinable_booleanReal_of_complement (A : ForcingContext V)
    (Pf : SetTheorySemisentence 2) {p : A.Model} (hp : A.IsGroundRealDefinable p)
    (hground : ∀ a : V, Pf.Evalb ![A.check a, p])
    (hcone : ∀ s k : V, IsFunction s → domain s = k → A.ConeOrbitTransfer Pf s k p)
    (τ : A.solovayContext.Name) :
    A.IsGroundRealDefinable (A.booleanReal ⟨τ.val, τ.property.1⟩) := by
  obtain ⟨E, hEf, hE, hEs⟩ := A.solovay_exists_support τ
  obtain ⟨s, hsfin, hsrange⟩ := exists_finiteSequence_range hEf
  obtain ⟨n, hn, hsn⟩ := (mem_finiteSequences_iff E s).mp hsfin
  have hfun : IsFunction s := IsFunction.of_mem hsn
  have : IsFunction s := hfun
  have hsdom : domain s = n := domain_eq_of_mem_function hsn
  have hnω : n ⊆ (ω : V) := IsOrdinal.toIsTransitive.transitive n hn
  have hsval : ∀ i ∈ n, s ‘ i ∈ E := by
    intro i hi
    rw [← hsrange]
    exact mem_range_of_kpair_mem (kpair_value_mem (by rw [hsdom]; exact hi))
  have hs : ∀ i ∈ n, IsNiceName (booleanConditions A.P A.R) A.P ((ω : V) ×ˢ (ω : V)) (s ‘ i) :=
    fun i hi ↦ (hE _ (hsval i hi)).nice
  have hErange : ∀ σ ∈ range s, IsSaturatedNiceName (booleanConditions A.P A.R)
      (booleanOrder A.P A.R) A.P ((ω : V) ×ˢ (ω : V)) σ := by
    rw [hsrange]
    exact hE
  have hsym : forcedStabilizer (booleanConditions A.P A.R) (booleanOrder A.P A.R)
      (forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R)) (range s) ⊆
      nameStabilizer (forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R))
        τ.val := by
    rw [hsrange]
    exact hEs
  set τ' : ForcingName A.booleanContext.P := ⟨τ.val, τ.property.1⟩ with hτ'
  have hsub1 : A.booleanReal τ' ⊆ A.solovayOrbitUnion Pf s n τ.val p :=
    A.booleanReal_subset_solovayOrbitUnion hsdom τ' hs Pf hground
  have hsub2 : A.solovayOrbitUnion Pf s n τ.val p ⊆ A.booleanReal τ' :=
    A.solovayOrbitUnion_subset_booleanReal Pf hsdom τ' hsym
      (orbitTransfer_of_coneOrbitTransfer Pf hErange (hcone s n hfun hsdom))
  have heq : A.booleanReal τ' = A.solovayOrbitUnion Pf s n τ.val p :=
    mem_ext (fun z ↦ ⟨fun h ↦ hsub1 z h, fun h ↦ hsub2 z h⟩)
  rw [heq]
  exact A.groundRealDefinable_solovayOrbitUnion Pf s τ.val hnω hp

end ForcingContext

/-! ### The Levy exports -/

section

variable {κ U : V} [IsOrdinal κ] (hAC : InternalChoice V)
  (hU : IsNonprincipalSetUltrafilter κ U) (hc : IsOrdinalComplete κ U)
  (hω : (ω : V) ∈ κ) (hκ : IsInitialOrdinal κ)
  {G : Set V} (hG : IsExternalForcingGeneric (levyCollapse κ) (levyOrder κ) G)

include hAC hU hc hω hκ in
/-- The ground predicate at the Solovay parameter holds only of the checks. This is the side
condition `hPf` of `exists_orbit_cone_isomorphism_support` for the Levy collapse. -/
theorem levy_check_of_evalb_groundFormula (y : (levyContext κ hG).Model)
    (hy : groundFormula.Evalb ![y, solovayParam κ hG]) :
    ∃ a : V, y = (levyContext κ hG).check a :=
  (levy_isGround_iff hAC hU hc hω hκ hG y).mp ((eval_groundFormula _ _).mp hy)

include hAC hU hc hω hκ in
/-- The cone hypothesis for the Levy collapse from relative homogeneity of the Boolean completion,
for a support sequence that is a function with domain the index set. -/
theorem levy_coneOrbitTransfer_of_complement {s k : V} (hfun : IsFunction s) (hsdom : domain s = k)
    (hcomp : (levyContext κ hG).ComplementConeIsomorphic (range s)) :
    (levyContext κ hG).ConeOrbitTransfer groundFormula s k (solovayParam κ hG) :=
  haveI := hfun
  ForcingContext.coneOrbitTransfer_of_complementConeIsomorphic hAC hsdom
    (levy_check_of_evalb_groundFormula hAC hU hc hω hκ hG) hcomp

include hAC hU hc hω hκ in
/-- The transfer statement of Karagila and Schilhan, Lemma 9.3, for the Levy collapse, from
relative homogeneity of the Boolean completion. -/
theorem levy_orbitTransfer_of_complement
    (hcomp : ∀ s : V, (levyContext κ hG).ComplementConeIsomorphic (range s)) :
    ∀ s k : V, IsFunction s → domain s = k →
      (∀ σ ∈ range s, IsSaturatedNiceName
        (booleanConditions (levyCollapse κ) (levyOrder κ))
        (booleanOrder (levyCollapse κ) (levyOrder κ)) (levyCollapse κ) ((ω : V) ×ˢ (ω : V)) σ) →
      (levyContext κ hG).OrbitTransfer groundFormula s k (solovayParam κ hG) :=
  fun s _k hfun hsdom hE ↦ ForcingContext.orbitTransfer_of_coneOrbitTransfer groundFormula hE
    (levy_coneOrbitTransfer_of_complement hAC hU hc hω hκ hG hfun hsdom (hcomp s))

include hAC hU hc hω hκ in
/-- The hypothesis `hpt` of `solovay_corollary_final`, from relative homogeneity of the Boolean
completion. -/
theorem groundRealDefinable_solovayInclusion_of_complement
    (hcomp : ∀ s : V, (levyContext κ hG).ComplementConeIsomorphic (range s))
    (x : (levySolovayContext κ hG).Model) :
    (levyContext κ hG).IsGroundRealDefinable (solovaySymmetricInclusion hG x) := by
  obtain ⟨τ, rfl⟩ := (levySolovayContext κ hG).ofName_surjective x
  refine ForcingContext.groundRealDefinable_booleanReal_of_complement (levyContext κ hG)
    groundFormula ?_ ?_ (fun s k hfun hsdom ↦
      levy_coneOrbitTransfer_of_complement hAC hU hc hω hκ hG hfun hsdom (hcomp s)) τ
  · rw [solovayParam_eq_check]
    exact ForcingContext.groundRealDefinable_of_parameter (Or.inl ⟨_, rfl⟩)
  · intro a
    exact (eval_groundFormula _ _).mpr (levy_isGround_check hAC hU hc hω hκ hG a)

include hAC hU hc hω hκ in
/-- `cor:Solovay` with relative homogeneity of the Boolean completion over the support algebra as
its only open assumption. The clauses are those of `solovay_corollary_of_cone_transfer`. -/
theorem solovay_corollary_of_complement [Countable V]
    (hVP : ∀ ψ : SetTheorySemisentence 2, VopenkaInstance (V := V) ψ)
    (hcomp : ∀ s : V, (levyContext κ hG).ComplementConeIsomorphic (range s)) :
    haveI := solovay_models_zf hAC hU hc hω hκ hG
    (SolovayHOD κ hG)↓[ℒₛₑₜ] ⊧* 𝗭𝗙 ∧
    (∀ φ : SetTheorySemisentence 2, VopenkaInstance (V := SolovayHOD κ hG) φ) ∧
    InternalDependentChoice (SolovayHOD κ hG) ∧
    (∀ X : SolovayHOD κ hG, X ⊆ cantorSpace (SolovayHOD κ hG) → IsLebesgueMeasurable X) ∧
    (∀ X : SolovayHOD κ hG, X ⊆ cantorSpace (SolovayHOD κ hG) → BaireProperty X) ∧
    (∀ X : SolovayHOD κ hG, X ⊆ cantorSpace (SolovayHOD κ hG) → PerfectSetProperty X) ∧
    ¬ InternalChoice (SolovayHOD κ hG) ∧
    hartogsNumber (ω : SolovayHOD κ hG) = solovayCheck hAC hU hc hω hκ hG κ ∧
    IsNonprincipalSetUltrafilter (solovayCheck hAC hU hc hω hκ hG κ)
      (solovayUltrafilter hAC hU hc hω hκ hG) ∧
    IsOrdinalComplete (solovayCheck hAC hU hc hω hκ hG κ)
      (solovayUltrafilter hAC hU hc hω hκ hG) :=
  solovay_corollary_final hAC hU hc hω hκ hG hVP
    (groundRealDefinable_solovayInclusion_of_complement hAC hU hc hω hκ hG hcomp)

end

end ZFVP
