import ZFVP.ModelTheory.LevyConeComplementHomogeneity

/-! The cone hypothesis of the Solovay corollary split into two hypotheses that the empty-support
counterexample does not refute.

`cor:Solovay` is now proved with no open hypothesis at all, as
`ZFVP.Unconditional.solovay_corollary` in `ZFVP/ModelTheory/SolovayCorollaryUnconditional.lean`,
which closes the cone hypothesis by a different route (`levy_coneOrbitTransfer_finite`); the
conditional exports here are kept as the record of the reduction.

`ForcingContext.ComplementConeIsomorphic` (`ZFVP/ModelTheory/LevyConeComplementHomogeneity.lean`)
quantifies over every pair of cones carrying an isomorphism that fixes the base support values
relatively. As stated it is false. Take the empty support, `b0` the top of the completion and `c0`
a proper regular cone. The identity-like isomorphism of the cone below `b0` onto the cone below
`c0` exists and the support clause is vacuous, but the complementary cones are the cone below `∅`
and the cone below a nonempty condition, and no isomorphism matches them.

The repair is forced by the lifting step. The automorphism that step builds must fix each base
support value `a`, so it must carry `a ∩ ¬b0` onto `a ∩ ¬c0`. Two side conditions are therefore
available for free wherever the hypothesis is really used:

* `(N1)` `forcingNegation A.P A.R b0 = ∅ ↔ forcingNegation A.P A.R c0 = ∅`;
* `(N2)` for every base support value `a`, `a ∩ forcingNegation A.P A.R b0 = ∅ ↔
  a ∩ forcingNegation A.P A.R c0 = ∅`.

This module adds them on both sides of the cut.

`ForcingContext.ComplementConeAligned` is `ComplementConeIsomorphic` with `(N1)` and `(N2)` in the
antecedent. `ForcingContext.ConeTraceAligned` is `ForcingContext.ConeOrbitTransfer` with the
complementary isomorphism dropped and `(N1)` and `(N2)` demanded of the pair it produces.
`coneOrbitTransfer_of_traceAligned` puts them back together: feed the positive isomorphism and the
two trace conditions to `ComplementConeAligned` and keep the isomorphism it returns.

Neither half is refuted by the counterexample above. On the pair (top, proper cone) the antecedent
of `ComplementConeAligned` fails at `(N1)`, since `¬b0 = ∅` while `¬c0 ≠ ∅`, so that pair no longer
makes a demand. And `ConeTraceAligned` is existential in the pair: it is free to pick a pair whose
complements have matching traces, which is what the Jech lifting argument produces anyway, so the
counterexample says nothing about it.

The Levy exports at the end mirror those of `LevyConeComplementHomogeneity.lean`. Unlike there, no
side condition on the support sequence is left over: `ConeTraceAligned` carries the cone data
itself instead of calling `exists_orbit_cone_isomorphism_support`, which is what asked for the
sequence to be a function with domain the index set. So `solovay_corollary_of_traceAligned` goes
straight through `solovay_corollary_of_cone_transfer`. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

namespace ForcingContext

/-! ### The homogeneity hypothesis, restricted to pairs with matching complement traces -/

/-- Relative homogeneity of the Boolean completion over the subalgebra generated by the base
support values of `E`, restricted to pairs of cones whose complements have matching traces: if `f`
is an isomorphism of the cone below `b0` onto the cone below `c0` that fixes the base support
values relatively, and if in addition

* `(N1)` `¬b0` is empty exactly when `¬c0` is, and
* `(N2)` each base support value meets `¬b0` exactly when it meets `¬c0`,

then some isomorphism `g` of the cone below `¬b0` onto the cone below `¬c0` fixes the base support
values relatively as well.

`(N1)` and `(N2)` are necessary, not a convenience: the automorphism the lifting step builds from
`f` and `g` fixes each base support value `a`, so it carries `a ∩ ¬b0` onto `a ∩ ¬c0`, and it
carries `¬b0` onto `¬c0`. Both conditions hold at every pair that step meets.

They also block the counterexample to the unrestricted statement
`ForcingContext.ComplementConeIsomorphic`. With an empty support, `b0` the top of the completion
and `c0` a proper regular cone, an isomorphism of the two cones exists and the support clause is
vacuous, but `¬b0` is empty while `¬c0` is not, so `(N1)` fails and the antecedent here is not
met. -/
def ComplementConeAligned (A : ForcingContext V) (E : V) : Prop :=
  ∀ b0 ∈ booleanConditions A.P A.R, ∀ c0 ∈ booleanConditions A.P A.R, ∀ f : V,
    IsForcingIsomorphism
        (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R) b0)
        (restrictedOrder (booleanOrder A.P A.R)
          (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R) b0))
        (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R) c0)
        (restrictedOrder (booleanOrder A.P A.R)
          (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R) c0)) f →
    (∀ a ∈ supportValuesBase A.P A.R A.P ((ω : V) ×ˢ (ω : V)) E,
      coneImage A.P A.R b0 f (a ∩ b0) = a ∩ c0) →
    (forcingNegation A.P A.R b0 = (∅ : V) ↔ forcingNegation A.P A.R c0 = (∅ : V)) →
    (∀ a ∈ supportValuesBase A.P A.R A.P ((ω : V) ×ˢ (ω : V)) E,
      a ∩ forcingNegation A.P A.R b0 = (∅ : V) ↔
        a ∩ forcingNegation A.P A.R c0 = (∅ : V)) →
    ∃ g : V,
      IsForcingIsomorphism
          (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R)
            (forcingNegation A.P A.R b0))
          (restrictedOrder (booleanOrder A.P A.R)
            (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R)
              (forcingNegation A.P A.R b0)))
          (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R)
            (forcingNegation A.P A.R c0))
          (restrictedOrder (booleanOrder A.P A.R)
            (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R)
              (forcingNegation A.P A.R c0))) g ∧
      ∀ a ∈ supportValuesBase A.P A.R A.P ((ω : V) ×ˢ (ω : V)) E,
        coneImage A.P A.R (forcingNegation A.P A.R b0) g
            (a ∩ forcingNegation A.P A.R b0) =
          a ∩ forcingNegation A.P A.R c0

/-! ### The cone hypothesis with the complementary isomorphism dropped -/

/-- `ForcingContext.ConeOrbitTransfer` with the isomorphism of the complementary cones dropped and
the two trace conditions of `ComplementConeAligned` demanded of the pair instead. For every orbit
filter `H` there are a condition `b0` met by the generic, a condition `c0` in `H`, and an
isomorphism `f` of the cone below `b0` onto the cone below `c0` that carries the generic to `H`
pointwise below `b0` and fixes the base support values of `range s` relatively, such that

* `(N1)` `¬b0` is empty exactly when `¬c0` is, and
* `(N2)` each base support value meets `¬b0` exactly when it meets `¬c0`.

The antecedent is that of `ConeOrbitTransfer`, saturated nice name clause included.

The empty-support counterexample to `ComplementConeIsomorphic` does not refute this: the pair is
existentially quantified here, so the statement is free to pick a pair whose complements have
matching traces, and the pair (top, proper cone) that breaks the unrestricted homogeneity
statement is simply not the pair to pick. The pair the Jech lifting argument produces satisfies
`(N1)` and `(N2)` because the automorphism it comes from fixes the base support values. -/
def ConeTraceAligned (A : ForcingContext V) (Pf : SetTheorySemisentence 2) (s k : V)
    (p : A.Model) : Prop :=
  (∀ σ ∈ range s, IsSaturatedNiceName (booleanConditions A.P A.R) (booleanOrder A.P A.R) A.P
      ((ω : V) ×ˢ (ω : V)) σ) →
  ∀ H : A.Model, IsOrbitFilter Pf (A.check (regularSets A.P A.R))
      (A.check (boolMaximalAntichains A.P A.R)) (A.check A.P) (A.check s) (A.check k)
      (A.orbitSupportReal s k) p H →
    ∃ b0 ∈ booleanConditions A.P A.R, ∃ c0 ∈ booleanConditions A.P A.R, ∃ f : V,
      IsForcingIsomorphism
          (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R) b0)
          (restrictedOrder (booleanOrder A.P A.R)
            (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R) b0))
          (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R) c0)
          (restrictedOrder (booleanOrder A.P A.R)
            (forcingCone (booleanConditions A.P A.R) (booleanOrder A.P A.R) c0)) f ∧
      (∃ r ∈ A.G, r ∈ b0) ∧ A.check c0 ∈ H ∧
      (∀ b ∈ booleanConditions A.P A.R, b ⊆ b0 →
        (A.check (f ‘ b) ∈ H ↔ A.check b ∈ A.boolGenericSet)) ∧
      (∀ a ∈ supportValuesBase A.P A.R A.P ((ω : V) ×ˢ (ω : V)) (range s),
        coneImage A.P A.R b0 f (a ∩ b0) = a ∩ c0) ∧
      (forcingNegation A.P A.R b0 = (∅ : V) ↔ forcingNegation A.P A.R c0 = (∅ : V)) ∧
      (∀ a ∈ supportValuesBase A.P A.R A.P ((ω : V) ×ˢ (ω : V)) (range s),
        a ∩ forcingNegation A.P A.R b0 = (∅ : V) ↔
          a ∩ forcingNegation A.P A.R c0 = (∅ : V))

/-! ### Putting the two halves back together -/

variable {A : ForcingContext V}

/-- The cone hypothesis from the two aligned hypotheses. `ConeTraceAligned` supplies the pair, the
positive isomorphism and the two trace conditions; `ComplementConeAligned` turns those into the
missing isomorphism of the complementary cones. -/
theorem coneOrbitTransfer_of_traceAligned {Pf : SetTheorySemisentence 2} {s k : V} {p : A.Model}
    (halign : A.ConeTraceAligned Pf s k p) (hcomp : A.ComplementConeAligned (range s)) :
    A.ConeOrbitTransfer Pf s k p := by
  intro hE H hH
  obtain ⟨b0, hb0, c0, hc0, f, hf, hmeet, hc0H, hfilter, hsupp, hN1, hN2⟩ := halign hE H hH
  obtain ⟨g, hg, hgsupp⟩ := hcomp b0 hb0 c0 hc0 f hf hsupp hN1 hN2
  exact ⟨b0, hb0, c0, hc0, f, g, hf, hg, hmeet, hc0H, hfilter,
    fun a ha ↦ ⟨hsupp a ha, hgsupp a ha⟩⟩

end ForcingContext

/-! ### The Levy exports -/

section

variable {κ U : V} [IsOrdinal κ] (hAC : InternalChoice V)
  (hU : IsNonprincipalSetUltrafilter κ U) (hc : IsOrdinalComplete κ U)
  (hω : (ω : V) ∈ κ) (hκ : IsInitialOrdinal κ)
  {G : Set V} (hG : IsExternalForcingGeneric (levyCollapse κ) (levyOrder κ) G)

omit [IsOrdinal κ] in
/-- The transfer statement of Karagila and Schilhan, Lemma 9.3, for the Levy collapse, from the two
aligned hypotheses. -/
theorem levy_orbitTransfer_of_traceAligned
    (halign : ∀ s k : V,
      (levyContext κ hG).ConeTraceAligned groundFormula s k (solovayParam κ hG))
    (hcomp : ∀ s : V, (levyContext κ hG).ComplementConeAligned (range s)) :
    ∀ s k : V, (∀ σ ∈ range s, IsSaturatedNiceName
        (booleanConditions (levyCollapse κ) (levyOrder κ))
        (booleanOrder (levyCollapse κ) (levyOrder κ)) (levyCollapse κ) ((ω : V) ×ˢ (ω : V)) σ) →
      (levyContext κ hG).OrbitTransfer groundFormula s k (solovayParam κ hG) :=
  levy_orbitTransfer_of_cone hG
    (fun s k ↦ ForcingContext.coneOrbitTransfer_of_traceAligned (halign s k) (hcomp s))

include hAC hU hc hω hκ in
/-- `cor:Solovay` with the two aligned hypotheses as its only open assumptions. The clauses are
those of `solovay_corollary_of_cone_transfer`. -/
theorem solovay_corollary_of_traceAligned [Countable V]
    (hVP : ∀ ψ : SetTheorySemisentence 2, VopenkaInstance (V := V) ψ)
    (halign : ∀ s k : V,
      (levyContext κ hG).ConeTraceAligned groundFormula s k (solovayParam κ hG))
    (hcomp : ∀ s : V, (levyContext κ hG).ComplementConeAligned (range s)) :
    haveI := solovay_models_zf hAC hU hc hω hκ hG
    (SolovayHOD κ hG)↓[ℒₛₑₜ] ⊧* 𝗭𝗙 ∧
    (∀ φ : SetTheorySemisentence 2, VopenkaInstance (V := SolovayHOD κ hG) φ) ∧
    InternalDependentChoice (SolovayHOD κ hG) ∧
    (∀ X : SolovayHOD κ hG, X ⊆ cantorSpace (SolovayHOD κ hG) → IsLebesgueMeasurable X) ∧
    (∀ X : SolovayHOD κ hG, X ⊆ cantorSpace (SolovayHOD κ hG) → BaireProperty X) ∧
    (∀ X : SolovayHOD κ hG, X ⊆ cantorSpace (SolovayHOD κ hG) → PerfectSetProperty X) ∧
    ¬ InternalChoice (SolovayHOD κ hG) ∧
    hartogsNumber (ω : SolovayHOD κ hG) = solovayCheck hAC hU hc hω hκ hG κ ∧
    IsNonprincipalSetUltrafilter (solovayCheck hAC hU hc hω hκ hG κ)
      (solovayUltrafilter hAC hU hc hω hκ hG) ∧
    IsOrdinalComplete (solovayCheck hAC hU hc hω hκ hG κ)
      (solovayUltrafilter hAC hU hc hω hκ hG) :=
  solovay_corollary_of_cone_transfer hAC hU hc hω hκ hG hVP
    (fun s k ↦ ForcingContext.coneOrbitTransfer_of_traceAligned (halign s k) (hcomp s))

end

end ZFVP
