import ZFVP.ModelTheory.LevyGaloisStep
import ZFVP.ModelTheory.SolovayPointwiseDefinable

/-! The Galois closure of a support algebra of the Levy collapse.

`ZFVP/ModelTheory/LevyGaloisStep.lean` proves that a condition `b` of the Boolean completion fixed
by the forced stabilizer of a set `E` of nice names is determined below some `ξ < κ`, and asks
whether that is enough to put the cone of `b` in the algebra generated by the support values of
`E`. It is not. Membership in the support algebra is a Galois condition: every automorphism in the
forced stabilizer of `E` fixes every element of the algebra as a set
(`supportAlgebra_fixed_of_forcedStabilizer`), hence fixes every condition whose cone is in the
algebra (`coneRegular_not_mem_supportAlgebra_of_moved`). Being determined below `ξ` only says that
the condition is fixed by the row permutations above `ξ`; the row permutations below `ξ`, which are
also in the forced stabilizer, can still move it.

`not_levy_coneRegular_mem_supportAlgebra_of_determined` turns this into a refutation. Take `E`
empty, so that the support algebra is the two-element algebra, `κ = ω`, `ξ = 3`, and `b` the cone
of the condition sending column `0` of row `2` to `0`. That `b` is determined below `3`, since a
condition lies in the cone exactly when it extends the one-point condition, and the one point lies
below `3`. A permutation of the columns moving `0` gives an automorphism of the whole collapse, so
its lift is in the forced stabilizer of the empty set, and it moves `b`. So the cone of `b` is not
in the support algebra. The same argument works for any `E` whose names only mention conditions
fixed by the permutation, so the failure is not an artifact of `E` being empty: the algebra
generated by the support values of `E` is in general a proper subalgebra of the algebra of the
subcollapse below `ξ`, and only the second one is what determinacy below `ξ` gives.

What survives for the downstream use is the value of a membership statement rather than an
arbitrary condition. If the forced stabilizer of `E` fixes two names, then it fixes the Boolean
value of the membership statement between them as a set, hence fixes the condition of the
completion whose cone that value is, hence that condition is determined below `ξ`
(`levy_atomicMembership_regularJoin_determinedBelow`). Getting from there to membership in the
support algebra is still the Galois closure of the support algebra inside the algebra of the
subcollapse, which is where Solovay's factoring of the collapse over the algebra of a real would
be used and which is not available here. The one case that the homogeneity argument settles on its
own is a support whose forced stabilizer is the whole automorphism group: then the value is the
zero or the top, and both are in every support algebra
(`atomicMembership_mem_supportAlgebra_of_invariant`). -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-! ### Elements of a support algebra are fixed by the forced stabilizer -/

/-- If some automorphism in the forced stabilizer of `E` moves a condition `b` of the completion,
then the regular cone of `b` is not in the support algebra of `E`. -/
theorem coneRegular_not_mem_supportAlgebra_of_moved {P R K E b Θ : V} (hP : ∃ p, p ∈ P)
    (hR : IsForcingPreorder P R)
    (hE : ∀ σ ∈ E, IsSaturatedNiceName (booleanConditions P R) (booleanOrder P R) P K σ)
    (hb : b ∈ booleanConditions P R)
    (hΘ : Θ ∈ forcedStabilizer (booleanConditions P R) (booleanOrder P R)
      (forcingAutomorphisms (booleanConditions P R) (booleanOrder P R)) E)
    (hmove : Θ ‘ b ≠ b) :
    coneRegular (booleanConditions P R) (booleanOrder P R) b ∉
      supportAlgebra (booleanConditions P R) (booleanOrder P R) P K E := by
  intro hmem
  have hΘa : IsForcingAutomorphism (booleanConditions P R) (booleanOrder P R) Θ :=
    (mem_forcingAutomorphisms_iff _ _ _).mp ((mem_forcedStabilizer _ _ _ _ _).mp hΘ).1
  have h := supportAlgebra_fixed_of_forcedStabilizer (booleanOrder_poset P R)
    (forcingAutomorphisms_group _ _) (booleanOrder_top hP) hE hΘ _ hmem
  rw [imageAction_coneRegular hΘa hb] at h
  exact hmove (coneRegular_injective_of_separative (booleanOrder_poset P R)
    (booleanOrder_separative hR) (function_value_mem hΘa.1 hb) hb h)

/-! ### Cones of conditions of the Levy collapse -/

/-- If every value of `p` can be replaced by another value at the same place, the regular cone of
`p` in the Levy collapse is the set of conditions extending `p`. -/
theorem levy_mem_coneRegular_iff_subset {κ p q : V} [IsOrdinal κ] (hp : p ∈ levyCollapse κ)
    (hq : q ∈ levyCollapse κ)
    (hrepl : ∀ n α y, (⟨⟨n, α⟩ₖ, y⟩ₖ : V) ∈ p → ∃ z ∈ α, z ≠ y) :
    q ∈ coneRegular (levyCollapse κ) (levyOrder κ) p ↔ p ⊆ q := by
  constructor
  · intro hmem z hz
    obtain ⟨-, hh⟩ := mem_coneRegular_iff.mp hmem
    have hsub := ((mem_finitePartialFunctions _ _ p).mp (levyCollapse_finitePartialFunction hp)).1
    obtain ⟨x, hx, y, -, rfl⟩ := mem_prod_iff.mp (hsub _ hz)
    obtain ⟨n, hn, α, hα, rfl⟩ := mem_prod_iff.mp hx
    by_cases hdom : ∃ w, (⟨⟨n, α⟩ₖ, w⟩ₖ : V) ∈ q
    · obtain ⟨w, hw⟩ := hdom
      obtain ⟨s, hsP, hsp, hsq⟩ := hh q hq
        ((pair_mem_reverseInclusionOrder _ _ _).mpr ⟨hq, hq, subset_refl q⟩)
      have : IsFunction s := ((mem_finitePartialFunctions _ _ s).mp
        (levyCollapse_finitePartialFunction hsP)).2.1
      have h1 : (⟨⟨n, α⟩ₖ, y⟩ₖ : V) ∈ s := ((pair_mem_reverseInclusionOrder _ _ _).mp hsp).2.2 _ hz
      have h2 : (⟨⟨n, α⟩ₖ, w⟩ₖ : V) ∈ s := ((pair_mem_reverseInclusionOrder _ _ _).mp hsq).2.2 _ hw
      exact (IsFunction.unique h1 h2 : y = w) ▸ hw
    · exfalso
      obtain ⟨z', hz'α, hz'y⟩ := hrepl n α y hz
      have hz'κ : z' ∈ κ := IsOrdinal.toIsTransitive.mem_trans hz'α hα
      have hfresh : (⟨n, α⟩ₖ : V) ∉ domain q := fun hd ↦ hdom (mem_domain_iff.mp hd)
      have hr : insert (⟨⟨n, α⟩ₖ, z'⟩ₖ : V) q ∈ levyCollapse κ := by
        refine (mem_levyCollapse_iff κ _).mpr
          ⟨finitePartialFunction_insert (levyCollapse_finitePartialFunction hq) hx hz'κ hfresh,
            fun m β γ hmem' ↦ ?_⟩
        rcases mem_insert.mp hmem' with he | hmem'
        · obtain ⟨he1, he2⟩ := kpair_iff.mp he.symm
          obtain ⟨he3, he4⟩ := kpair_iff.mp he1
          exact he4 ▸ he2 ▸ hz'α
        · exact levyCollapse_value hq hmem'
      obtain ⟨s, hsP, hsp, hsr⟩ := hh _ hr ((pair_mem_reverseInclusionOrder _ _ _).mpr
        ⟨hr, hq, fun z hz' ↦ mem_insert.mpr (Or.inr hz')⟩)
      have : IsFunction s := ((mem_finitePartialFunctions _ _ s).mp
        (levyCollapse_finitePartialFunction hsP)).2.1
      have h1 : (⟨⟨n, α⟩ₖ, y⟩ₖ : V) ∈ s := ((pair_mem_reverseInclusionOrder _ _ _).mp hsp).2.2 _ hz
      have h2 : (⟨⟨n, α⟩ₖ, z'⟩ₖ : V) ∈ s := ((pair_mem_reverseInclusionOrder _ _ _).mp hsr).2.2 _
        (mem_insert.mpr (Or.inl rfl))
      exact hz'y (IsFunction.unique h2 h1)
  · intro hsub
    refine mem_coneRegular_iff.mpr ⟨hq, fun r hr hrq ↦ ⟨r, hr, ?_, (levyCollapse_poset κ).1.2.1 r hr⟩⟩
    exact (pair_mem_reverseInclusionOrder _ _ _).mpr ⟨hr, hp,
      subset_trans hsub ((pair_mem_reverseInclusionOrder _ _ _).mp hrq).2.2⟩

/-! ### One-point conditions -/

/-- The condition of the Levy collapse sending the first column of the row `α` to `γ`. -/
noncomputable def levyPoint (α γ : V) : V := insert (⟨⟨(∅ : V), α⟩ₖ, γ⟩ₖ : V) (∅ : V)

theorem mem_levyPoint_iff (α γ z : V) : z ∈ levyPoint α γ ↔ z = ⟨⟨(∅ : V), α⟩ₖ, γ⟩ₖ := by
  unfold levyPoint
  rw [mem_insert]
  exact ⟨fun h ↦ h.elim id (fun h ↦ (not_mem_empty h).elim), fun h ↦ Or.inl h⟩

theorem levyPoint_mem_levyCollapse {κ α γ : V} (hα : α ∈ κ) (hγ : γ ∈ α) (hγκ : γ ∈ κ) :
    levyPoint α γ ∈ levyCollapse κ := by
  have hfresh : (⟨(∅ : V), α⟩ₖ : V) ∉ domain (∅ : V) := by
    intro h
    obtain ⟨y, hy⟩ := mem_domain_iff.mp h
    exact not_mem_empty hy
  refine (mem_levyCollapse_iff κ _).mpr ⟨finitePartialFunction_insert
    (empty_mem_finitePartialFunctions _ _) (kpair_mem_iff.mpr ⟨empty_mem_ω, hα⟩) hγκ hfresh,
    fun n β y hz ↦ ?_⟩
  obtain ⟨h1, h2⟩ := kpair_iff.mp ((mem_levyPoint_iff α γ _).mp hz)
  obtain ⟨-, h3⟩ := kpair_iff.mp h1
  exact h3 ▸ h2 ▸ hγ

theorem levyPoint_replaceable {α γ δ : V} (hδ : δ ∈ α) (hne : δ ≠ γ) :
    ∀ n β y, (⟨⟨n, β⟩ₖ, y⟩ₖ : V) ∈ levyPoint α γ → ∃ z ∈ β, z ≠ y := by
  intro n β y hz
  obtain ⟨h1, h2⟩ := kpair_iff.mp ((mem_levyPoint_iff α γ _).mp hz)
  obtain ⟨-, h3⟩ := kpair_iff.mp h1
  exact ⟨δ, h3 ▸ hδ, h2 ▸ hne⟩

/-- The cone of a one-point condition below `ξ` is determined below `ξ`. -/
theorem levyPoint_coneRegular_determinedBelow {κ ξ α γ δ : V} [IsOrdinal κ] [IsOrdinal ξ]
    (hξ : ξ ⊆ κ) (hαξ : α ∈ ξ) (hγ : γ ∈ α) (hδ : δ ∈ α) (hne : δ ≠ γ) :
    IsLevyDeterminedBelow κ ξ (coneRegular (levyCollapse κ) (levyOrder κ) (levyPoint α γ)) := by
  have hακ : α ∈ κ := hξ _ hαξ
  have hγξ : γ ∈ ξ := IsOrdinal.toIsTransitive.mem_trans hγ hαξ
  have hp : levyPoint α γ ∈ levyCollapse κ :=
    levyPoint_mem_levyCollapse hακ hγ (hξ _ hγξ)
  intro q hq
  have hcut : levyCut ξ q ∈ levyCollapse κ := levyCollapse_mono hξ _ (levyCut_mem hq)
  rw [levy_mem_coneRegular_iff_subset hp hq (levyPoint_replaceable hδ hne),
    levy_mem_coneRegular_iff_subset hp hcut (levyPoint_replaceable hδ hne)]
  constructor
  · intro h z hz
    have hz' := (mem_levyPoint_iff α γ z).mp hz
    subst hz'
    exact (kpair_mem_levyCut_iff ξ q _ _).mpr ⟨h _ hz, kpair_mem_iff.mpr ⟨empty_mem_ω, hαξ⟩⟩
  · exact fun h ↦ subset_trans h (levyCut_subset ξ q)

/-- A row permutation moving the first column moves a one-point condition off itself. -/
theorem levyPoint_not_subset_levyPermutation {κ α γ s : V} (hs : IsInternalPermutation (ω : V) s)
    (hs0 : s ‘ (∅ : V) ≠ ∅) (hα : α ∈ κ) (hγ : γ ∈ α) (hγκ : γ ∈ κ) :
    ¬ levyPoint α γ ⊆ (levyPermutation κ (∅ : V) s) ‘ (levyPoint α γ) := by
  intro hsub
  have hp : levyPoint α γ ∈ levyCollapse κ := levyPoint_mem_levyCollapse hα hγ hγκ
  have hz : (⟨⟨(∅ : V), α⟩ₖ, γ⟩ₖ : V) ∈ (levyPermutation κ (∅ : V) s) ‘ (levyPoint α γ) :=
    hsub _ ((mem_levyPoint_iff α γ _).mpr rfl)
  rw [levyPermutation_value hp, mem_permutedGraph] at hz
  obtain ⟨u, hu, heq⟩ := hz
  rw [(mem_levyPoint_iff α γ u).mp hu] at heq
  unfold permutedGraphEntry at heq
  rw [kpair.π₁_kpair, kpair.π₂_kpair,
    levyRowPermutation_value_above hs empty_mem_ω hα not_mem_empty] at heq
  exact hs0 ((kpair_iff.mp (kpair_iff.mp heq).1).1).symm

/-! ### The counterexample -/

/-- The cone of a one-point condition is not in the support algebra of the empty set of names:
the lift of a row permutation moving the first column lies in the forced stabilizer and moves the
condition. -/
theorem levyPoint_coneRegular_not_mem_supportAlgebra {κ α γ δ K s : V} [IsOrdinal κ]
    (hs : IsInternalPermutation (ω : V) s) (hs0 : s ‘ (∅ : V) ≠ ∅)
    (hα : α ∈ κ) (hγ : γ ∈ α) (hγκ : γ ∈ κ) (hδ : δ ∈ α) (hne : δ ≠ γ) :
    coneRegular (booleanConditions (levyCollapse κ) (levyOrder κ))
        (booleanOrder (levyCollapse κ) (levyOrder κ))
        (coneRegular (levyCollapse κ) (levyOrder κ) (levyPoint α γ)) ∉
      supportAlgebra (booleanConditions (levyCollapse κ) (levyOrder κ))
        (booleanOrder (levyCollapse κ) (levyOrder κ)) (levyCollapse κ) K (∅ : V) := by
  have hπ : IsForcingAutomorphism (levyCollapse κ) (levyOrder κ) (levyPermutation κ (∅ : V) s) :=
    levyPermutation_automorphism hs
  have hp : levyPoint α γ ∈ levyCollapse κ := levyPoint_mem_levyCollapse hα hγ hγκ
  have hb : coneRegular (levyCollapse κ) (levyOrder κ) (levyPoint α γ) ∈
      booleanConditions (levyCollapse κ) (levyOrder κ) :=
    coneRegular_mem_booleanConditions (levyCollapse_poset κ).1 hp
  refine coneRegular_not_mem_supportAlgebra_of_moved
    (Θ := booleanLift (levyCollapse κ) (levyOrder κ) (levyPermutation κ (∅ : V) s))
    ⟨∅, empty_mem_levyCollapse κ⟩
    (levyCollapse_poset κ).1 (fun σ hσ ↦ (not_mem_empty hσ).elim) hb ?_ ?_
  · refine booleanLift_mem_forcedStabilizer (K := K) ⟨∅, empty_mem_levyCollapse κ⟩ hπ
      (fun σ hσ ↦ (not_mem_empty hσ).elim) (fun d hd ↦ ?_)
    obtain ⟨σ, hσ, -⟩ := (mem_nameConditions_iff _ d).mp hd
    exact (not_mem_empty hσ).elim
  · intro heq
    rw [booleanLift_value hb, imageAction_coneRegular hπ hp] at heq
    have hπp : (levyPermutation κ (∅ : V) s) ‘ (levyPoint α γ) ∈ levyCollapse κ :=
      function_value_mem hπ.1 hp
    have h1 : (levyPermutation κ (∅ : V) s) ‘ (levyPoint α γ) ∈
        coneRegular (levyCollapse κ) (levyOrder κ) (levyPoint α γ) := by
      rw [← heq]
      exact self_mem_coneRegular (levyCollapse_poset κ).1 hπp
    exact levyPoint_not_subset_levyPermutation hs hs0 hα hγ hγκ
      ((levy_mem_coneRegular_iff_subset hp hπp (levyPoint_replaceable hδ hne)).mp h1)

/-- The Galois closure statement for the Levy collapse is false as stated: a condition of the
completion that is determined below `ξ` need not have its cone in the support algebra, because
being determined below `ξ` says nothing about being fixed by the forced stabilizer of `E`. The
witness takes `E` empty, `κ = ω`, `ξ = 3`, and `b` the cone of the condition sending the first
column of row `2` to `0`. -/
theorem not_levy_coneRegular_mem_supportAlgebra_of_determined :
    ¬ ∀ κ ξ K E b : V, IsOrdinal ξ → ξ ∈ κ → IsInternallyFinite E →
      (∀ σ ∈ E, IsSaturatedNiceName (booleanConditions (levyCollapse κ) (levyOrder κ))
        (booleanOrder (levyCollapse κ) (levyOrder κ)) (levyCollapse κ) K σ) →
      (∀ d ∈ nameConditions E, IsLevyDeterminedBelow κ ξ d) →
      (∀ d ∈ supportValues (booleanConditions (levyCollapse κ) (levyOrder κ))
        (booleanOrder (levyCollapse κ) (levyOrder κ)) (levyCollapse κ) K E,
          IsLevyDeterminedBelow κ ξ d) →
      b ∈ booleanConditions (levyCollapse κ) (levyOrder κ) →
      IsLevyDeterminedBelow κ ξ b →
      coneRegular (booleanConditions (levyCollapse κ) (levyOrder κ))
          (booleanOrder (levyCollapse κ) (levyOrder κ)) b ∈
        supportAlgebra (booleanConditions (levyCollapse κ) (levyOrder κ))
          (booleanOrder (levyCollapse κ) (levyOrder κ)) (levyCollapse κ) K E := by
  intro h
  obtain ⟨s, hs, hmove⟩ := exists_permutation_moving (X := insert (∅ : V) (∅ : V))
    (Y := insert (∅ : V) (∅ : V)) (internallyFinite_insert internallyFinite_empty ∅)
    (fun z hz ↦ by rcases mem_insert.mp hz with rfl | hz; exacts [empty_mem_ω, (not_mem_empty hz).elim])
    (internallyFinite_insert internallyFinite_empty ∅)
    (fun z hz ↦ by rcases mem_insert.mp hz with rfl | hz; exacts [empty_mem_ω, (not_mem_empty hz).elim])
  have hs0 : s ‘ (∅ : V) ≠ ∅ := by
    intro he
    refine hmove ∅ (mem_insert.mpr (Or.inl rfl)) ?_
    rw [he]
    exact mem_insert.mpr (Or.inl rfl)
  -- `α = 2`, `γ = 0`, `δ = 1`, `ξ = 3`
  have hαω : (succ (succ (∅ : V)) : V) ∈ (ω : V) :=
    ω_succ_closed (ω_succ_closed empty_mem_ω)
  have hξω : (succ (succ (succ (∅ : V))) : V) ∈ (ω : V) := ω_succ_closed hαω
  have hγ : (∅ : V) ∈ succ (succ (∅ : V)) := mem_succ_iff.mpr (Or.inr (mem_succ_self ∅))
  have hδ : (succ (∅ : V) : V) ∈ succ (succ (∅ : V)) := mem_succ_self _
  have hne : (succ (∅ : V) : V) ≠ ∅ := fun he ↦ not_mem_empty (he ▸ mem_succ_self (∅ : V))
  have hαξ : (succ (succ (∅ : V)) : V) ∈ succ (succ (succ (∅ : V))) := mem_succ_self _
  have hξκ : (succ (succ (succ (∅ : V))) : V) ⊆ (ω : V) :=
    IsOrdinal.toIsTransitive.transitive _ hξω
  refine levyPoint_coneRegular_not_mem_supportAlgebra (K := (∅ : V)) hs hs0 hαω hγ
    (IsOrdinal.toIsTransitive.mem_trans hγ hαω) hδ hne ?_
  refine h (ω : V) (succ (succ (succ (∅ : V)))) (∅ : V) (∅ : V) _ inferInstance hξω
    internallyFinite_empty (fun σ hσ ↦ (not_mem_empty hσ).elim) ?_ ?_
    (coneRegular_mem_booleanConditions (levyCollapse_poset _).1
      (levyPoint_mem_levyCollapse hαω hγ (IsOrdinal.toIsTransitive.mem_trans hγ hαω)))
    (levyPoint_coneRegular_determinedBelow hξκ hαξ hγ hδ hne)
  · intro d hd
    obtain ⟨σ, hσ, -⟩ := (mem_nameConditions_iff _ d).mp hd
    exact (not_mem_empty hσ).elim
  · intro d hd
    obtain ⟨k, -, σ, hσ, -⟩ := (mem_supportValues_iff _ _ _ _ _ _).mp hd
    exact (not_mem_empty hσ).elim

/-! ### What survives: the Boolean value of a membership statement is localized -/

/-- The image action of an automorphism fixing two names fixes the Boolean value of the membership
statement between them. -/
theorem imageAction_atomicMembership_eq_self {P R Θ σ τ : V}
    (hΘ : IsForcingAutomorphism (booleanConditions P R) (booleanOrder P R) Θ)
    (hσ : IsForcingName (booleanConditions P R) σ) (hτ : IsForcingName (booleanConditions P R) τ)
    (hsσ : nameAction Θ σ = σ) (hsτ : nameAction Θ τ = τ) :
    imageAction Θ (atomicMembership (booleanConditions P R) (booleanOrder P R) σ τ) =
      atomicMembership (booleanConditions P R) (booleanOrder P R) σ τ := by
  refine imageAction_eq_of_iff hΘ (atomicMembership_subset _ _ _ _)
    (atomicMembership_subset _ _ _ _) (fun q hq ↦ ?_)
  conv_lhs => rw [← hsσ, ← hsτ]
  exact atomicMembership_nameAction_iff hΘ hσ hτ hq

/-- An automorphism of the completion fixing an element of `RO(B)` as a set fixes the join of that
element, which is the condition of `B` with that cone. -/
theorem regularJoin_value_eq_self_of_imageAction {P R Θ A : V} (hR : IsForcingPreorder P R)
    (hΘ : IsForcingAutomorphism (booleanConditions P R) (booleanOrder P R) Θ)
    (hA : A ∈ booleanConditions (booleanConditions P R) (booleanOrder P R))
    (hfix : imageAction Θ A = A) : Θ ‘ (regularJoin P R A) = regularJoin P R A := by
  obtain ⟨C₀, hC₀⟩ := ((mem_booleanConditions_iff _ _ A).mp hA).2
  have hAsub : A ⊆ booleanConditions P R := ((mem_booleanConditions_iff _ _ A).mp hA).1.1
  have hb : regularJoin P R A ∈ booleanConditions P R :=
    regularJoin_mem_booleanConditions hR hAsub hC₀
  have hcone := coneRegular_regularJoin hR hA
  have himg := imageAction_coneRegular hΘ hb
  rw [hcone, hfix] at himg
  refine coneRegular_injective_of_separative (booleanOrder_poset P R)
    (booleanOrder_separative hR) (function_value_mem hΘ.1 hb) hb ?_
  rw [← himg, hcone]

/-- What the Galois step is really needed for, in the form that is provable. For two names of the
Levy symmetric system whose forced stabilizer of `E` fixes both, the Boolean value of the
membership statement between them, read as a condition of the Boolean completion, is determined
below any `ξ` at which the conditions of the names of `E` are determined. So the value lives in the
subcollapse `Coll(ω, <ξ)`; what is not proved is that it lives in the subalgebra generated by the
support values of `E`. -/
theorem levy_atomicMembership_regularJoin_determinedBelow {κ ξ K E σ τ : V} [IsOrdinal ξ]
    (hξ : ξ ⊆ κ)
    (hE : ∀ ρ ∈ E, IsNiceName (booleanConditions (levyCollapse κ) (levyOrder κ))
      (levyCollapse κ) K ρ)
    (hdet : ∀ d ∈ nameConditions E, IsLevyDeterminedBelow κ ξ d)
    (hσ : IsForcingName (booleanConditions (levyCollapse κ) (levyOrder κ)) σ)
    (hτ : IsForcingName (booleanConditions (levyCollapse κ) (levyOrder κ)) τ)
    (hfix : ∀ Θ ∈ forcedStabilizer (booleanConditions (levyCollapse κ) (levyOrder κ))
      (booleanOrder (levyCollapse κ) (levyOrder κ))
      (forcingAutomorphisms (booleanConditions (levyCollapse κ) (levyOrder κ))
        (booleanOrder (levyCollapse κ) (levyOrder κ))) E,
      nameAction Θ σ = σ ∧ nameAction Θ τ = τ) :
    IsLevyDeterminedBelow κ ξ (regularJoin (levyCollapse κ) (levyOrder κ)
      (atomicMembership (booleanConditions (levyCollapse κ) (levyOrder κ))
        (booleanOrder (levyCollapse κ) (levyOrder κ)) σ τ)) := by
  have hR : IsForcingPreorder (levyCollapse κ) (levyOrder κ) := (levyCollapse_poset κ).1
  by_cases hne : ∃ C, C ∈ atomicMembership (booleanConditions (levyCollapse κ) (levyOrder κ))
      (booleanOrder (levyCollapse κ) (levyOrder κ)) σ τ
  · have hA : atomicMembership (booleanConditions (levyCollapse κ) (levyOrder κ))
        (booleanOrder (levyCollapse κ) (levyOrder κ)) σ τ ∈
        booleanConditions (booleanConditions (levyCollapse κ) (levyOrder κ))
          (booleanOrder (levyCollapse κ) (levyOrder κ)) :=
      (mem_booleanConditions_iff _ _ _).mpr
        ⟨atomicMembership_regular (booleanOrder_poset _ _).1 σ τ, hne⟩
    obtain ⟨C₀, hC₀⟩ := hne
    have hb : regularJoin (levyCollapse κ) (levyOrder κ)
        (atomicMembership (booleanConditions (levyCollapse κ) (levyOrder κ))
          (booleanOrder (levyCollapse κ) (levyOrder κ)) σ τ) ∈
        booleanConditions (levyCollapse κ) (levyOrder κ) :=
      regularJoin_mem_booleanConditions hR (atomicMembership_subset _ _ _ _) hC₀
    refine levy_determined_below_of_forcedStabilizer_fixed_of_names hξ hE hdet hb
      (fun Θ hΘ ↦ ?_)
    have hΘa : IsForcingAutomorphism (booleanConditions (levyCollapse κ) (levyOrder κ))
        (booleanOrder (levyCollapse κ) (levyOrder κ)) Θ :=
      (mem_forcingAutomorphisms_iff _ _ _).mp ((mem_forcedStabilizer _ _ _ _ _).mp hΘ).1
    obtain ⟨hsσ, hsτ⟩ := hfix Θ hΘ
    exact regularJoin_value_eq_self_of_imageAction hR hΘa hA
      (imageAction_atomicMembership_eq_self hΘa hσ hτ hsσ hsτ)
  · have h0 : atomicMembership (booleanConditions (levyCollapse κ) (levyOrder κ))
        (booleanOrder (levyCollapse κ) (levyOrder κ)) σ τ = (∅ : V) := by
      apply mem_ext
      exact fun z ↦ ⟨fun hz ↦ absurd ⟨z, hz⟩ hne, fun hz ↦ absurd hz not_mem_empty⟩
    rw [h0, regularJoin_empty hR]
    exact fun p _ ↦ ⟨fun h ↦ (not_mem_empty h).elim, fun h ↦ (not_mem_empty h).elim⟩

/-! ### The homogeneous case of the Galois step for Boolean values -/

/-- The Boolean completion of a weakly homogeneous poset is weakly homogeneous. -/
theorem booleanOrder_weaklyHomogeneous {P R one : V} (hP : ∃ p, p ∈ P) (hR : IsForcingPreorder P R)
    (hhom : IsWeaklyHomogeneous P R one) :
    IsWeaklyHomogeneous (booleanConditions P R) (booleanOrder P R) P := by
  intro A hA C hC
  have hAr := booleanConditions_regular hA
  have hCr := booleanConditions_regular hC
  obtain ⟨p, hp⟩ := booleanConditions_nonempty hA
  obtain ⟨q, hq⟩ := booleanConditions_nonempty hC
  obtain ⟨π, hπ, -, r, hr, hrπ, hrq⟩ := hhom p (hAr.1 p hp) q (hCr.1 q hq)
  have hPB : P ∈ booleanConditions P R := top_mem_booleanConditions hP
  have htop : (booleanLift P R π) ‘ P = P := by
    rw [booleanLift_value hPB]
    exact imageAction_eq_of_iff hπ (fun _ h ↦ h) (fun _ h ↦ h)
      (fun z hz ↦ ⟨fun _ ↦ hz, fun _ ↦ function_value_mem hπ.1 hz⟩)
  refine ⟨booleanLift P R π, booleanLift_isForcingAutomorphism hπ, htop, ?_⟩
  have hcone : coneRegular P R r ∈ booleanConditions P R := coneRegular_mem_booleanConditions hR hr
  have hrA : r ∈ imageAction π A :=
    (imageAction_regular hπ hAr).2.1 (π ‘ p)
      ((mem_imageAction_iff _ _ _).mpr ⟨p, hp, rfl⟩) r hr hrπ
  refine ⟨coneRegular P R r, hcone, ?_, ?_⟩
  · rw [booleanLift_value hA]
    exact (kpair_mem_booleanOrder_iff _ _ _ _).mpr ⟨hcone, imageAction_mem_booleanConditions hπ hA,
      coneRegular_subset_of_mem hR (imageAction_regular hπ hAr) hrA⟩
  · exact (kpair_mem_booleanOrder_iff _ _ _ _).mpr ⟨hcone, hC,
      coneRegular_subset_of_mem hR hCr (hCr.2.1 q hq r hr hrq)⟩

/-- The Galois step for a Boolean value, in the case where the names are fixed by every
automorphism of the completion: then the value is the zero or the top of `RO(B)`, and both lie in
every support algebra. This is the whole of Karagila-Schilhan Lemma 9.3 for a support whose forced
stabilizer is the full automorphism group, and it is as far as the homogeneity argument alone
reaches. -/
theorem atomicMembership_mem_supportAlgebra_of_invariant {P R one K E σ τ : V} (hP : ∃ p, p ∈ P)
    (hR : IsForcingPreorder P R) (hhom : IsWeaklyHomogeneous P R one)
    (hσ : IsForcingName (booleanConditions P R) σ) (hτ : IsForcingName (booleanConditions P R) τ)
    (hfix : ∀ Θ, IsForcingAutomorphism (booleanConditions P R) (booleanOrder P R) Θ →
      Θ ‘ P = P → nameAction Θ σ = σ ∧ nameAction Θ τ = τ) :
    atomicMembership (booleanConditions P R) (booleanOrder P R) σ τ ∈
      supportAlgebra (booleanConditions P R) (booleanOrder P R) P K E := by
  by_cases hne : ∃ C, C ∈ atomicMembership (booleanConditions P R) (booleanOrder P R) σ τ
  · have hA : atomicMembership (booleanConditions P R) (booleanOrder P R) σ τ ∈
        booleanConditions (booleanConditions P R) (booleanOrder P R) :=
      (mem_booleanConditions_iff _ _ _).mpr
        ⟨atomicMembership_regular (booleanOrder_poset P R).1 σ τ, hne⟩
    have htop := eq_top_of_imageAction_fixed (booleanOrder_weaklyHomogeneous hP hR hhom) hA
      (fun Θ hΘ hone ↦ imageAction_atomicMembership_eq_self hΘ hσ hτ (hfix Θ hΘ hone).1
        (hfix Θ hΘ hone).2)
    rw [htop]
    exact top_mem_supportAlgebra _ _ _ _ _
  · have h0 : atomicMembership (booleanConditions P R) (booleanOrder P R) σ τ = (∅ : V) := by
      apply mem_ext
      exact fun z ↦ ⟨fun hz ↦ absurd ⟨z, hz⟩ hne, fun hz ↦ absurd hz not_mem_empty⟩
    rw [h0]
    exact empty_mem_supportAlgebra P R P K E

end ZFVP
