import ZFVP.ModelTheory.SchmerlInfinitaryFiniteSmall
import ZFVP.ModelTheory.MaximallyCompatibleFilters

/-! Countability of old finite sets supplies whole-domain coverage for every
maximal finite-function filter with an omega-one cofinal chain. -/

namespace ZFVP.Schmerl

open LO LO.FirstOrder LO.FirstOrder.SetTheory Set Order

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

theorem maximal_function_filter_downward {s : V} {F : V → Prop}
    (hF : IsMaximalInternalFilter (finitePartialFunctions s ((2 : ℕ) : V)) F)
    {p q : V} (hp : F p) (hqp : q ⊆ p) : F q := by
  apply (isMaximallyCompatibleOn_of_isMaximalInternalFilter s F hF).2 q
    (finitePartialFunction_subset (hF.1.1 p hp) hqp)
  intro r hr
  obtain ⟨u, hu, hru, hpu⟩ := hF.1.2 r p hr hp
  exact ⟨u, hF.1.1 u hu, hru, SetTheory.subset_trans hqp hpu⟩

/-- Maximal compatibility forces coverage of each individual old element. -/
theorem maximal_function_filter_covers_point {s : V} {F : V → Prop}
    (hF : IsMaximalInternalFilter (finitePartialFunctions s ((2 : ℕ) : V)) F)
    {x : V} (hx : x ∈ s) : ∃ p, F p ∧ x ∈ domain p := by
  classical
  by_contra hno
  have hnot (p : V) (hp : F p) : x ∉ domain p := fun hd ↦ hno ⟨p, hp, hd⟩
  let q : V := insert ⟨x, ((0 : ℕ) : V)⟩ₖ ∅
  have hq : q ∈ finitePartialFunctions s ((2 : ℕ) : V) :=
    finitePartialFunction_insert (empty_mem_finitePartialFunctions _ _) hx (by simp) (by simp)
  have hqF : F q := by
    apply (isMaximallyCompatibleOn_of_isMaximalInternalFilter s F hF).2 q hq
    intro p hp
    refine ⟨insert ⟨x, ((0 : ℕ) : V)⟩ₖ p,
      finitePartialFunction_insert (hF.1.1 p hp) hx (by simp) (hnot p hp),
      fun z hz ↦ mem_insert.mpr (Or.inr hz), ?_⟩
    intro z hz
    rcases mem_insert.mp hz with rfl | he
    · exact mem_insert.mpr (Or.inl rfl)
    · exact False.elim (not_mem_empty he)
  exact hnot q hqF (mem_domain_of_kpair_mem
    (show ⟨x, ((0 : ℕ) : V)⟩ₖ ∈ q from mem_insert.mpr (Or.inl rfl)))

/-- A countable domain is covered at one stage of any cofinal omega-one chain. -/
theorem maximal_function_filter_covers_countable {s c : V} {F : V → Prop}
    (hF : IsMaximalInternalFilter (finitePartialFunctions s ((2 : ℕ) : V)) F)
    (hchain : HasCofinalOmegaOneChain F) (hc : ({x : V | x ∈ c} : Set V).Countable)
    (hcs : c ⊆ s) : ∃ p, F p ∧ c ⊆ domain p := by
  classical
  obtain ⟨p, hp, hmono, hcof⟩ := hchain
  let Ω := Ordinal.ToType (Ordinal.omega.{0} 1)
  have hx (x : {x : V // x ∈ c}) : ∃ i : Ω, x.val ∈ domain (p i) := by
    obtain ⟨q, hq, hxq⟩ := maximal_function_filter_covers_point hF (hcs _ x.property)
    obtain ⟨i, hqi⟩ := hcof q hq
    obtain ⟨y, hxy⟩ := mem_domain_iff.mp hxq
    exact ⟨i, mem_domain_of_kpair_mem (hqi _ hxy)⟩
  choose index hindex using hx
  let : Countable {x : V // x ∈ c} := hc.to_subtype
  have hΩ : Cardinal.aleph0 < Order.cof Ω := by
    rw [Ordinal.cof_toType, Cardinal.cof_omega_one]
    exact Cardinal.aleph0_lt_aleph_one
  obtain ⟨β, hβ⟩ := exists_bound_of_countable hΩ (Set.countable_range index)
  refine ⟨p β, hp β, fun x hx ↦ ?_⟩
  let a : {x : V // x ∈ c} := ⟨x, hx⟩
  obtain ⟨y, hxy⟩ := mem_domain_iff.mp (hindex a)
  exact mem_domain_of_kpair_mem ((hmono (index a) β (hβ _ (Set.mem_range_self a))).1 _ hxy)

theorem maximal_function_filter_isFunctionFilter {s : V} {F : V → Prop}
    (hF : IsMaximalInternalFilter (finitePartialFunctions s ((2 : ℕ) : V)) F)
    (hchain : HasCofinalOmegaOneChain F) : IsFunctionFilter (s := s) F := by
  let Ω := Ordinal.ToType (Ordinal.omega.{0} 1)
  let : Nonempty Ω := Ordinal.nonempty_toType_iff.mpr (Ordinal.omega_pos 1).ne'
  obtain ⟨p, hp, _⟩ := hchain
  exact ⟨hF.1.1, ⟨p (Classical.arbitrary Ω), hp _⟩, hF.1.2,
    fun p q hp hqp ↦ maximal_function_filter_downward hF hp hqp⟩

/-- This is the missing whole selected-domain coverage implication. -/
theorem FinSmall.maximal_filter_covers {s : V} {F : V → Prop} (hsmall : FinSmall V)
    (hF : IsMaximalInternalFilter (finitePartialFunctions s ((2 : ℕ) : V)) F)
    (hchain : HasCofinalOmegaOneChain F)
    {I : Type*} [LinearOrder I] (C : FiniteDomainChain s I) :
    ∀ i, ∃ p, F p ∧ C.domain i ⊆ domain p :=
  fun i ↦ maximal_function_filter_covers_countable hF hchain
    (hsmall _ (C.finite i)) (C.subset i)

/-- Every maximal filter in the original weakly Rubin contract is exactly
the full filter generated by its selected branch. -/
theorem FinSmall.maximal_filter_is_branch_filter {s : V} {F : V → Prop} (hsmall : FinSmall V)
    (hF : IsMaximalInternalFilter (finitePartialFunctions s ((2 : ℕ) : V)) F)
    (hchain : HasCofinalOmegaOneChain F)
    {I : Type*} [LinearOrder I] (C : FiniteDomainChain s I) :
    ∃ B : Set (FunctionTreeNode C), (FunctionTreeNode.rankedTree (C := C)).IsBranch B ∧
      filterOfBranch C B = F := by
  have hff := maximal_function_filter_isFunctionFilter hF hchain
  have hcover := hsmall.maximal_filter_covers hF hchain C
  exact ⟨branchOfFilter C F, branchOfFilter_isBranch C hff hcover,
    filterOfBranch_branchOfFilter C hff hcover⟩

end ZFVP.Schmerl
