import ZFVP.ModelTheory.SchmerlFunctionTree
import ZFVP.ModelTheory.SchmerlCountableRanges

/-! First-order coding of the full filters generated by canonical function-tree
branches. The code clause does not demand definability of the selected domain
predicate in the original set-theoretic reduct.
-/

namespace ZFVP.Schmerl

open LO LO.FirstOrder LO.FirstOrder.SetTheory

universe u v w z

variable {V : Type u} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-- A full finite-function filter candidate, using selected domains and color equality. -/
def functionFilterCandidate (s : V) (D : V → Prop) (E : V → V → Prop) (b p : V) : Prop :=
  p ∈ finitePartialFunctions s ((2 : ℕ) : V) ∧
    ∃ y ∈ finitePartialFunctions s ((2 : ℕ) : V), D (domain y) ∧
      (y ⊆ b ∨ b ⊆ y ∧ E b y) ∧ p ⊆ y

variable {I : Type v} [LinearOrder I] {s : V} (C : FiniteDomainChain s I)
  {K : Type w} (f : V → K)

/-- Taking the full finite-function downward closure removes the intermediate
tree node in the branch-definition formula. -/
theorem filterOfBranch_branchDefinition_iff (b : FunctionTreeNode C) (p : V) :
    filterOfBranch C {a | branchDefinition (· ≤ ·) (fun x ↦ f x.graph) b a} p ↔
      functionFilterCandidate s (fun d ↦ d ∈ Set.range C.domain)
        (fun x y ↦ f x = f y) b.graph p := by
  constructor
  · rintro ⟨hp, a, ⟨y, hy, hay⟩, hpa⟩
    refine ⟨hp, y.graph, y.graph_mem_finitePartialFunctions,
      ⟨y.level, y.domain_graph.symm⟩, ?_, subset_trans hpa hay.2⟩
    simpa only [colorCone, FunctionTreeNode.le_iff_graph_subset] using hy
  · rintro ⟨hp, y, hy, hdom, hcone, hpy⟩
    obtain ⟨a, rfl⟩ := (FunctionTreeNode.mem_graph_range_iff y).mpr ⟨hy, hdom⟩
    refine ⟨hp, a, ⟨a, ?_, le_rfl⟩, hpy⟩
    simpa only [colorCone, FunctionTreeNode.le_iff_graph_subset] using hcone

/-- The rank-cofinality test is a first-order condition on the selected domains
and the full filter candidate, without quantifying over branches or subsets. -/
theorem functionFilterCandidate_cofinal_iff (b : FunctionTreeNode C) :
    IsCofinal ((FunctionTreeNode.rankedTree (C := C)).rank ''
      {x | branchDefinition (· ≤ ·) (fun x ↦ f x.graph) b x}) ↔
      ∀ d : V, d ∈ Set.range C.domain → ∃ p : V,
        functionFilterCandidate s (fun d ↦ d ∈ Set.range C.domain)
          (fun x y ↦ f x = f y) b.graph p ∧ d ⊆ domain p := by
  constructor
  · intro h d hd
    obtain ⟨i, rfl⟩ := hd
    obtain ⟨_, ⟨a, ha, rfl⟩, hia⟩ := h i
    refine ⟨a.graph, (filterOfBranch_branchDefinition_iff C f b a.graph).mp
      ⟨a.graph_mem_finitePartialFunctions, a, ha, subset_refl _⟩, ?_⟩
    rw [FunctionTreeNode.domain_graph]
    exact C.monotone hia
  · intro h i
    obtain ⟨p, hp, hip⟩ := h (C.domain i) (Set.mem_range_self i)
    obtain ⟨_, a, ha, hpa⟩ := (filterOfBranch_branchDefinition_iff C f b p).mpr hp
    have hdom : C.domain i ⊆ C.domain a.level := by
      rw [← FunctionTreeNode.domain_graph]
      intro x hx
      obtain ⟨y, hxy⟩ := mem_domain_iff.mp (hip x hx)
      exact mem_domain_of_kpair_mem (hpa _ hxy)
    exact ⟨a.level, ⟨a, ha, rfl⟩, (C.domain_subset_iff i a.level).mp hdom⟩

/-- Actual internal codes for all generated branch filters are equivalent to
codes for cofinal one-node candidates. The conclusion is stronger than an
expanded-language definition, since membership in the code uses only `∈`. -/
theorem forall_filter_codes_iff_candidates [Nonempty I]
    (hI : Cardinal.aleph0 < Order.cof I)
    (hf : WeaklySpecializes (· ≤ ·) (fun x : FunctionTreeNode C ↦ f x.graph))
    (hcolor : (Set.range (fun x : FunctionTreeNode C ↦ f x.graph)).Countable) :
    (∀ B : Set (FunctionTreeNode C), (FunctionTreeNode.rankedTree (C := C)).IsBranch B →
      ∃ m : V, ∀ p, p ∈ m ↔ filterOfBranch C B p) ↔
      ∀ b : FunctionTreeNode C,
        IsCofinal ((FunctionTreeNode.rankedTree (C := C)).rank ''
          {x | branchDefinition (· ≤ ·) (fun x ↦ f x.graph) b x}) →
        ∃ m : V, ∀ p, p ∈ m ↔ functionFilterCandidate s
          (fun d ↦ d ∈ Set.range C.domain) (fun x y ↦ f x = f y) b.graph p := by
  constructor
  · intro h b hb
    have hB := ((FunctionTreeNode.rankedTree (C := C)).branchDefinition_isBranch_iff hf b).mpr hb
    obtain ⟨m, hm⟩ := h _ hB
    exact ⟨m, fun p ↦ (hm p).trans (filterOfBranch_branchDefinition_iff C f b p)⟩
  · intro h B hB
    obtain ⟨b, _, hdef⟩ := hB.exists_branchDefinition_countable_range hI hf hcolor
    have heq : {x | branchDefinition (· ≤ ·) (fun x ↦ f x.graph) b x} = B := Set.ext hdef
    have hcof := ((FunctionTreeNode.rankedTree (C := C)).branchDefinition_isBranch_iff hf b).mp
      (heq.symm ▸ hB)
    obtain ⟨m, hm⟩ := h b hcof
    refine ⟨m, fun p ↦ ?_⟩
    rw [← heq]
    exact (hm p).trans (filterOfBranch_branchDefinition_iff C f b p).symm

/-- The full code requirement reduces to a first-order condition on individual
tree nodes once weak specialization and uncountable cofinality are available. -/
theorem forall_filter_codes_iff_firstOrder_candidates [Nonempty I]
    (hI : Cardinal.aleph0 < Order.cof I)
    (hf : WeaklySpecializes (· ≤ ·) (fun x : FunctionTreeNode C ↦ f x.graph))
    (hcolor : (Set.range (fun x : FunctionTreeNode C ↦ f x.graph)).Countable) :
    (∀ B : Set (FunctionTreeNode C), (FunctionTreeNode.rankedTree (C := C)).IsBranch B →
      ∃ m : V, ∀ p, p ∈ m ↔ filterOfBranch C B p) ↔
      ∀ b : FunctionTreeNode C,
        (∀ d : V, d ∈ Set.range C.domain → ∃ p : V,
          functionFilterCandidate s (fun d ↦ d ∈ Set.range C.domain)
            (fun x y ↦ f x = f y) b.graph p ∧ d ⊆ domain p) →
        ∃ m : V, ∀ p, p ∈ m ↔ functionFilterCandidate s
          (fun d ↦ d ∈ Set.range C.domain) (fun x y ↦ f x = f y) b.graph p := by
  rw [forall_filter_codes_iff_candidates C f hI hf hcolor]
  simp only [functionFilterCandidate_cofinal_iff]

/-- Since the full filter lies in an internal set, definability and having an
internal code are equivalent. No definability of `C` is required. -/
theorem filterOfBranch_definable_iff_coded (B : Set (FunctionTreeNode C)) :
    (ℒₛₑₜ-predicate[V] (filterOfBranch C B)) ↔
      ∃ m : V, ∀ p, p ∈ m ↔ filterOfBranch C B p := by
  constructor
  · intro hdef
    refine ⟨sep (finitePartialFunctions s ((2 : ℕ) : V)) (filterOfBranch C B) hdef, fun p ↦ ?_⟩
    rw [mem_sep_iff]
    exact ⟨fun h ↦ h.2, fun h ↦ ⟨h.1, h⟩⟩
  · rintro ⟨m, hm⟩
    exact Language.DefinablePred.of_iff (show ℒₛₑₜ-predicate[V] (fun p ↦ p ∈ m) by
      clear hm
      definability)
      (fun p ↦ (hm p).symm)

/-- This candidate is first order in any expansion defining the displayed
domain predicate, color relation, finite-function set, domain map and inclusion. -/
theorem functionFilterCandidate_definable {L : Language.{z}} [L.Eq] [Structure L V]
    [Structure.Eq L V] (s : V) (D : V → Prop) (E : V → V → Prop)
    [L-predicate[V] (fun p ↦ p ∈ finitePartialFunctions s ((2 : ℕ) : V))]
    [L-function₁[V] domain] [L-relation[V] (· ⊆ ·)]
    [L-predicate[V] D] [L-relation[V] E] (b : V) :
    L-predicate[V] (functionFilterCandidate s D E b) := by
  unfold functionFilterCandidate
  definability

end ZFVP.Schmerl
