import ZFVP.ModelTheory.ForcingSmallUltrafilter

/-! Levy-Solovay for small forcing (Banerjee, Theorem 2.5(2)): a nonprincipal `κ`-complete
ultrafilter `U` of the ground model generates a nonprincipal internally `κ`-complete
ultrafilter on `κ̌` in any extension by a poset of size below `κ`.

The generated object is the filter on `κ̌` whose members are the subsets of `κ̌` containing
`Y̌` for some `Y ∈ U`; it is `ForcingContext.derivedFilter` of
`ZFVP.ModelTheory.ForcingSmallUltrafilter`, named `liftedFilter` here. This file records the
lift under that name, splits the conclusion into its ultrafilter, nonprincipality and
completeness parts, and adds the generating fact that `Y̌` is in the lift for every `Y ∈ U`. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

namespace ForcingContext

/-- The filter on `κ̌` generated by the checks of the members of `U`, that is
`{X ∈ ℘ κ̌ ; ∃ Y ∈ Ǔ, Y ⊆ X}`. Same object as `ForcingContext.derivedFilter`. -/
noncomputable abbrev liftedFilter (S : ForcingContext V) (κ U : V) : S.Model :=
  S.derivedFilter κ U

theorem mem_liftedFilter_iff (S : ForcingContext V) (κ U : V) (X : S.Model) :
    X ∈ S.liftedFilter κ U ↔ X ⊆ S.check κ ∧ ∃ Y ∈ U, S.check Y ⊆ X :=
  S.mem_derivedFilter_iff κ U X

/-- The check of a member of `U` belongs to the generated filter. -/
theorem check_mem_liftedFilter (S : ForcingContext V) {κ U Y : V}
    (hU : IsSetUltrafilter κ U) (hY : Y ∈ U) : S.check Y ∈ S.liftedFilter κ U := by
  refine (S.mem_liftedFilter_iff κ U _).mpr ⟨?_, Y, hY, subset_refl _⟩
  intro z hz
  obtain ⟨y, hy, rfl⟩ := (S.mem_check_iff Y z).mp hz
  exact (S.check_mem_iff y κ).mpr (hU.subset_of_mem hY y hy)

/-- Levy-Solovay: a nonprincipal `κ`-complete ultrafilter of the ground model generates a
nonprincipal internally `κ̌`-complete ultrafilter on `κ̌` in an extension by a poset of size
below `κ`. -/
theorem liftedFilter_ultrafilter (S : ForcingContext V) (hAC : InternalChoice V) {κ U lam : V}
    [IsOrdinal κ] (hU : IsNonprincipalSetUltrafilter κ U) (hc : IsOrdinalComplete κ U)
    (hlam : lam ∈ κ) (hP : S.P ≤# lam) :
    IsNonprincipalSetUltrafilter (S.check κ) (S.liftedFilter κ U) ∧
      IsOrdinalComplete (S.check κ) (S.liftedFilter κ U) :=
  S.derivedFilter_ultrafilter hAC hU hc hlam hP

/-- The generated filter is an ultrafilter on `κ̌`. -/
theorem liftedFilter_isUltrafilter (S : ForcingContext V) (hAC : InternalChoice V) {κ U lam : V}
    [IsOrdinal κ] (hU : IsNonprincipalSetUltrafilter κ U) (hc : IsOrdinalComplete κ U)
    (hlam : lam ∈ κ) (hP : S.P ≤# lam) :
    IsSetUltrafilter (S.check κ) (S.liftedFilter κ U) :=
  (S.liftedFilter_ultrafilter hAC hU hc hlam hP).1.1

/-- No singleton of an element of `κ̌` lies in the generated filter. -/
theorem liftedFilter_nonprincipal (S : ForcingContext V) (hAC : InternalChoice V) {κ U lam : V}
    [IsOrdinal κ] (hU : IsNonprincipalSetUltrafilter κ U) (hc : IsOrdinalComplete κ U)
    (hlam : lam ∈ κ) (hP : S.P ≤# lam) :
    ∀ x ∈ S.check κ, ({x} : S.Model) ∉ S.liftedFilter κ U :=
  (S.liftedFilter_ultrafilter hAC hU hc hlam hP).1.2

/-- The generated filter is closed under intersections of internal families indexed by an
ordinal below `κ̌`. -/
theorem liftedFilter_complete (S : ForcingContext V) (hAC : InternalChoice V) {κ U lam : V}
    [IsOrdinal κ] (hU : IsNonprincipalSetUltrafilter κ U) (hc : IsOrdinalComplete κ U)
    (hlam : lam ∈ κ) (hP : S.P ≤# lam) :
    IsOrdinalComplete (S.check κ) (S.liftedFilter κ U) :=
  (S.liftedFilter_ultrafilter hAC hU hc hlam hP).2

/-- Every subset of `κ̌` in the extension, or its relative complement, contains the check of a
ground-model set in `U`. -/
theorem liftedFilter_dichotomy (S : ForcingContext V) (hAC : InternalChoice V) {κ U lam : V}
    [IsOrdinal κ] (hU : IsNonprincipalSetUltrafilter κ U) (hc : IsOrdinalComplete κ U)
    (hlam : lam ∈ κ) (hP : S.P ≤# lam) {X : S.Model} (hX : X ⊆ S.check κ) :
    (∃ Y ∈ U, S.check Y ⊆ X) ∨ ∃ Y ∈ U, S.check Y ⊆ relativeComplement (S.check κ) X := by
  rcases (S.liftedFilter_isUltrafilter hAC hU hc hlam hP).dichotomy hX with h | h
  · exact Or.inl ((S.mem_liftedFilter_iff κ U X).mp h).2
  · exact Or.inr ((S.mem_liftedFilter_iff κ U _).mp h).2

end ForcingContext
end ZFVP
