import ZFVP.ModelTheory.StabilizerFixedAlgebra
import ZFVP.ModelTheory.SolovaySymmetricContext
import ZFVP.ModelTheory.SolovayRealCoding
import ZFVP.ModelTheory.BooleanRealTrace

/-! Supports for the names of the Solovay symmetric extension. Every hereditarily symmetric name
of the system `O(B, Ṙ)` has a finite set `E` of saturated nice names whose forced stabilizer fixes
it, and that forced stabilizer is exactly the group of automorphisms fixing, as sets, the Boolean
values `‖ǩ ∈ σ‖` for `k ∈ K` and `σ ∈ E`. Combined with the fixed-algebra lemma this says that
every automorphism in the support group fixes the complete subalgebra generated by those values
elementwise. For a name that is itself a saturated nice name the value is read off from which of
its own support values the generic meets, so it is a subset of the checked `K` and hence, for
`K = ω × ω`, definable from ground sets, reals and ordinals. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-! ### Support extraction -/

namespace ForcingContext

/-- Every hereditarily symmetric name of the nice symmetric system has a finite set of saturated
nice names whose forced stabilizer is contained in its stabilizer. -/
theorem niceSymmetric_exists_support (A : ForcingContext V) (K : V)
    (τ : (A.niceSymmetricContext K).Name) :
    ∃ E : V, IsInternallyFinite E ∧
      (∀ σ ∈ E, IsSaturatedNiceName (booleanConditions A.P A.R) (booleanOrder A.P A.R) A.P K σ) ∧
      forcedStabilizer (booleanConditions A.P A.R) (booleanOrder A.P A.R)
          (forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R)) E ⊆
        nameStabilizer
          (forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R)) τ.val := by
  have h : nameStabilizer
      (forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R)) τ.val ∈
      forcedStabilizerFilter (booleanConditions A.P A.R) (booleanOrder A.P A.R)
        (forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R))
        (IsSaturatedNiceName (booleanConditions A.P A.R) (booleanOrder A.P A.R) A.P K)
        (isSaturatedNiceName_definable _ _ _ _) :=
    τ.property.2 τ.val (mem_nameClosure_self _)
  obtain ⟨-, E, hEf, hE, hEs⟩ := (mem_forcedStabilizerFilter _ _ _ _ _ _).mp h
  exact ⟨E, hEf, hE, hEs⟩

/-- The same for the Solovay system, where `K = ω × ω`. -/
theorem solovay_exists_support (A : ForcingContext V) (τ : A.solovayContext.Name) :
    ∃ E : V, IsInternallyFinite E ∧
      (∀ σ ∈ E, IsSaturatedNiceName (booleanConditions A.P A.R) (booleanOrder A.P A.R) A.P
        ((ω : V) ×ˢ (ω : V)) σ) ∧
      forcedStabilizer (booleanConditions A.P A.R) (booleanOrder A.P A.R)
          (forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R)) E ⊆
        nameStabilizer
          (forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R)) τ.val :=
  A.niceSymmetric_exists_support _ τ

end ForcingContext

/-! ### The support algebra -/

/-- The Boolean values `‖ǩ ∈ σ‖` for `k ∈ K` and `σ ∈ E`, as sets of conditions of the poset the
names live over. -/
noncomputable def supportValues (P R one K E : V) : V :=
  repl (fun z ↦ atomicMembership P R (checkName one (kpair.π₁ z)) (kpair.π₂ z))
    (by have := atomicMembership_definable P R; definability) (K ×ˢ E)

theorem mem_supportValues_iff (P R one K E b : V) :
    b ∈ supportValues P R one K E ↔
      ∃ k ∈ K, ∃ σ ∈ E, b = atomicMembership P R (checkName one k) σ := by
  unfold supportValues
  rw [repl_spec]
  constructor
  · rintro ⟨z, hz, rfl⟩
    obtain ⟨k, hk, σ, hσ, rfl⟩ := mem_prod_iff.mp hz
    exact ⟨k, hk, σ, hσ, by rw [kpair.π₁_kpair, kpair.π₂_kpair]⟩
  · rintro ⟨k, hk, σ, hσ, rfl⟩
    refine ⟨⟨k, σ⟩ₖ, mem_prod_iff.mpr ⟨k, hk, σ, hσ, rfl⟩, ?_⟩
    rw [kpair.π₁_kpair, kpair.π₂_kpair]

theorem atomicMembership_mem_supportValues {P R one K E k σ : V} (hk : k ∈ K) (hσ : σ ∈ E) :
    atomicMembership P R (checkName one k) σ ∈ supportValues P R one K E :=
  (mem_supportValues_iff _ _ _ _ _ _).mpr ⟨k, hk, σ, hσ, rfl⟩

theorem supportValues_subset_regularSets {P R : V} (hR : IsForcingPreorder P R) (one K E : V) :
    supportValues P R one K E ⊆ regularSets P R := by
  intro b hb
  obtain ⟨k, -, σ, -, rfl⟩ := (mem_supportValues_iff _ _ _ _ _ _).mp hb
  exact (mem_regularSets_iff _ _ _).mpr (atomicMembership_regular hR _ _)

/-- Every Boolean value `‖ǩ ∈ σ‖` with `k ∈ K` is a support value of `{σ}`. -/
theorem atomicMembership_mem_supportValues_singleton {P R one K k σ : V} (hk : k ∈ K) :
    atomicMembership P R (checkName one k) σ ∈ supportValues P R one K ({σ} : V) :=
  atomicMembership_mem_supportValues hk (mem_singleton_iff.mpr rfl)

/-- The complete subalgebra generated by the support values of `E`. -/
noncomputable def supportAlgebra (P R one K E : V) : V :=
  generatedSubalgebra P R (supportValues P R one K E)

theorem supportValues_subset_supportAlgebra (P R one K E : V) :
    supportValues P R one K E ⊆ supportAlgebra P R one K E :=
  subset_generatedSubalgebra _ _ _

/-- For a name over `K`, all the Boolean values `‖ǩ ∈ σ‖` that decide its value lie in the support
algebra of `{σ}` itself: the hypothesis that the values of a name lie in its own support algebra
is automatic for nice names. -/
theorem atomicMembership_mem_supportAlgebra_singleton {P R one K k σ : V} (hk : k ∈ K) :
    atomicMembership P R (checkName one k) σ ∈ supportAlgebra P R one K ({σ} : V) :=
  supportValues_subset_supportAlgebra _ _ _ _ _ _
    (atomicMembership_mem_supportValues_singleton hk)

/-- The image action of an automorphism on the Boolean value `‖ǩ ∈ σ‖` is the Boolean value of
`ǩ ∈ πσ`. -/
theorem imageAction_atomicMembership_checkName {P R one π k σ : V} (hR : IsForcingPoset P R)
    (hone : IsForcingTop P R one) (hπ : IsForcingAutomorphism P R π) (hσ : IsForcingName P σ) :
    imageAction π (atomicMembership P R (checkName one k) σ) =
      atomicMembership P R (checkName one k) (nameAction π σ) := by
  have hfix : π ‘ one = one := forcingAutomorphism_top hR hone hπ
  refine imageAction_eq_of_iff hπ (atomicMembership_subset _ _ _ _)
    (atomicMembership_subset _ _ _ _) (fun q hq ↦ ?_)
  conv_lhs => rw [← nameAction_checkName (P := P) hone.1 hfix k]
  exact atomicMembership_nameAction_iff hπ (checkName_isName hone.1 k) hσ hq

/-- Karagila-Schilhan Lemma 9.3 for nice names: the forced stabilizer of a set of saturated nice
names is exactly the group of automorphisms fixing all of their Boolean values as sets. -/
theorem forcedStabilizer_eq_imageStabilizer {P R Γ one K E : V} (hR : IsForcingPoset P R)
    (hΓ : IsForcingAutomorphismGroup P R Γ) (hone : IsForcingTop P R one)
    (hE : ∀ σ ∈ E, IsSaturatedNiceName P R one K σ) :
    forcedStabilizer P R Γ E = imageStabilizer Γ (supportValues P R one K E) := by
  ext π
  rw [mem_forcedStabilizer, mem_imageStabilizer_iff]
  constructor
  · rintro ⟨hπΓ, hfix⟩
    refine ⟨hπΓ, fun b hb ↦ ?_⟩
    obtain ⟨k, -, σ, hσ, rfl⟩ := (mem_supportValues_iff _ _ _ _ _ _).mp hb
    have hπ := hΓ.1 π hπΓ
    have hact : nameAction π σ = σ :=
      saturatedNiceName_fixed_of_forcedEqual hR hone hπ (hE σ hσ) (hfix σ hσ)
    rw [imageAction_atomicMembership_checkName hR hone hπ ((hE σ hσ).isName hone.1), hact]
  · rintro ⟨hπΓ, hfix⟩
    refine ⟨hπΓ, fun σ hσ ↦ ?_⟩
    have hπ := hΓ.1 π hπΓ
    have hsat := hE σ hσ
    have hσname : IsForcingName P σ := hsat.isName hone.1
    have hval : ∀ k ∈ K, atomicMembership P R (checkName one k) (nameAction π σ) =
        atomicMembership P R (checkName one k) σ := by
      intro k hk
      rw [← imageAction_atomicMembership_checkName hR hone hπ hσname]
      exact hfix _ (atomicMembership_mem_supportValues hk hσ)
    have hact : nameAction π σ = σ := by
      have h1 : nameAction π σ = niceName P R one K (nameAction π σ) := by
        conv_lhs => rw [hsat]
        rw [nameAction_niceName hR hone hπ hσname]
      rw [h1]
      conv_rhs => rw [hsat]
      ext z
      simp only [mem_niceName_iff]
      constructor
      · rintro ⟨k, hk, p, hp, rfl, hpm⟩
        exact ⟨k, hk, p, hp, rfl, by rw [← hval k hk]; exact hpm⟩
      · rintro ⟨k, hk, p, hp, rfl, hpm⟩
        exact ⟨k, hk, p, hp, rfl, by rw [hval k hk]; exact hpm⟩
    rw [hact]
    exact forcedEqual_refl hR.1 σ

/-- Every automorphism in the forced stabilizer of a set of saturated nice names fixes the
support algebra elementwise. -/
theorem supportAlgebra_fixed_of_forcedStabilizer {P R Γ one K E : V} (hR : IsForcingPoset P R)
    (hΓ : IsForcingAutomorphismGroup P R Γ) (hone : IsForcingTop P R one)
    (hE : ∀ σ ∈ E, IsSaturatedNiceName P R one K σ) {π : V}
    (hπ : π ∈ forcedStabilizer P R Γ E) :
    ∀ d ∈ supportAlgebra P R one K E, imageAction π d = d :=
  imageStabilizer_fixes_generatedSubalgebra hR.1 hΓ
    (supportValues_subset_regularSets hR.1 one K E)
    (by rw [← forcedStabilizer_eq_imageStabilizer hR hΓ hone hE]; exact hπ)

/-! ### Values of nice names -/

namespace ForcingContext

variable (A : ForcingContext V)

/-- A checked ground element belongs to the value of a Boolean name exactly when the generic of
the Boolean completion meets the Boolean value `‖ǩ ∈ τ‖`, which is a support value of `{τ}`. -/
theorem check_mem_booleanReal_iff_meets (τ : ForcingName A.booleanContext.P) (k : V) :
    A.check k ∈ A.booleanReal τ ↔
      ∃ b ∈ A.booleanContext.G,
        b ∈ atomicMembership (booleanConditions A.P A.R) (booleanOrder A.P A.R)
          (checkName A.P k) τ.val := by
  rw [A.check_mem_booleanReal_iff]
  exact forcingQuotientMk_mem_iff _ _ _ _ _ _ _

/-- The value of a nice name is a set of checked ground elements of `K`. -/
theorem booleanReal_subset_check_of_nice {K : V} (τ : ForcingName A.booleanContext.P)
    (hτ : IsNiceName (booleanConditions A.P A.R) A.P K τ.val) :
    A.booleanReal τ ⊆ A.check K := by
  intro z hz
  unfold booleanReal at hz
  rw [← A.booleanEquiv_mem_iff, Equiv.apply_symm_apply] at hz
  obtain ⟨ν, p, hpG, hνp, he⟩ := (A.booleanContext.mem_ofName_iff τ _).mp hz
  obtain ⟨k, hk, q, -, hz'⟩ := hτ _ hνp
  obtain ⟨hν, -⟩ := kpair_iff.mp hz'
  have hcheck : A.booleanContext.ofName ν = A.booleanContext.check k := by
    unfold ForcingContext.check forcingCheck ForcingContext.ofName
    exact congrArg _ (Subtype.ext hν)
  rw [hcheck, ← A.booleanEquiv_check] at he
  exact (A.mem_check_iff K z).mpr ⟨k, hk, A.booleanEquiv.injective he⟩

/-- The value of a nice name is completely determined by which of its support values the generic
of the Boolean completion meets. -/
theorem mem_booleanReal_iff_of_nice {K : V} (τ : ForcingName A.booleanContext.P)
    (hτ : IsNiceName (booleanConditions A.P A.R) A.P K τ.val) (z : A.Model) :
    z ∈ A.booleanReal τ ↔ ∃ k ∈ K, z = A.check k ∧
      ∃ b ∈ A.booleanContext.G,
        b ∈ atomicMembership (booleanConditions A.P A.R) (booleanOrder A.P A.R)
          (checkName A.P k) τ.val := by
  constructor
  · intro hz
    obtain ⟨k, hk, rfl⟩ := (A.mem_check_iff K z).mp (A.booleanReal_subset_check_of_nice τ hτ z hz)
    exact ⟨k, hk, rfl, (A.check_mem_booleanReal_iff_meets τ k).mp hz⟩
  · rintro ⟨k, -, rfl, hb⟩
    exact (A.check_mem_booleanReal_iff_meets τ k).mpr hb

/-- The value of a saturated nice name over `ω × ω` in the Solovay symmetric extension is
definable in the extension from ground sets, reals and ordinals. -/
theorem groundRealDefinable_of_saturatedNiceName (τ : A.solovayContext.Name)
    (hτ : IsSaturatedNiceName (booleanConditions A.P A.R) (booleanOrder A.P A.R) A.P
      ((ω : V) ×ˢ (ω : V)) τ.val) :
    A.IsGroundRealDefinable
      (A.booleanEquiv.symm (A.solovayContext.toOrdinary (A.solovayContext.ofName τ))) :=
  groundRealDefinable_of_subset_check_omega_prod _
    (A.booleanReal_subset_check_of_nice ⟨τ.val, τ.property.1⟩ hτ.nice)

end ForcingContext

end ZFVP
