import ZFVP.ModelTheory.SolovaySupportAlgebraBase
import ZFVP.ModelTheory.SubalgebraModelDefinable
import ZFVP.ModelTheory.SolovaySymmetricSupport

/-! The last link between the support algebra and ground-real definability.

`ForcingContext.groundRealDefinable_of_inSubalgebraModel_finite_of_real` needs a real `r` of the
extension whose bits record, for each generator `S ‘ ⟨i, n⟩ₖ` of the algebra, whether the generic
meets it. Here that real is built.

`supportTraceReal A S` is the set of natural numbers `m` of the extension such that `m` is the
pairing code of a pair `q` with `(Š) ‘ q` in the generic ultrafilter `boolGenericSet` on the
checked regular sets. It is a subset of `ω̌` by construction, and
`check_mem_supportTraceReal_iff` says that its bit at `naturalPairCode i n` is exactly the
statement that the generic meets `S ‘ ⟨i, n⟩ₖ`, which is the hypothesis `hval` wanted.

With `exists_supportAlgebraBase_eq_generatedSubalgebra_range` this closes the chain: the base
support algebra of an internally finite set of names over `ω × ω` is generated by the range of a
function with domain `k × ω` for a natural number `k`, that function is exactly the `S` above, and
so every element of the intermediate extension by the base support algebra is definable in `V[G]`
from ground sets, reals and ordinals.

Chained with `inSubalgebraModel_of_uniformSupport` this gives the pointwise statement for the
Levy collapse, conditional on the Galois step and on the name having a single support. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

namespace ForcingContext

variable (A : ForcingContext V)

/-! ### The real reading off the generic decisions of a ground family of regular sets -/

/-- The real of the extension recording which of the regular sets `S ‘ q` the generic meets, with
the pair `q` replaced by its ground pairing code. -/
noncomputable def supportTraceReal (S : V) : A.Model :=
  sep (A.check (ω : V))
    (fun m ↦ ∃ q ∈ A.check ((ω : V) ×ˢ (ω : V)),
      (⟨q, m⟩ₖ : A.Model) ∈ A.check (omegaPairGraph V) ∧ (A.check S) ‘ q ∈ A.boolGenericSet)
    (by definability)

theorem supportTraceReal_subset (S : V) : A.supportTraceReal S ⊆ A.check (ω : V) := sep_subset

/-- The bit of `supportTraceReal A S` at the pairing code of `⟨i, n⟩` says that the generic meets
`S ‘ ⟨i, n⟩ₖ`. -/
theorem check_mem_supportTraceReal_iff {k S : V} (hk : k ⊆ (ω : V))
    (hS : S ∈ regularSets A.P A.R ^ (k ×ˢ (ω : V))) {i n : V} (hi : i ∈ k) (hn : n ∈ (ω : V)) :
    A.check (naturalPairCode i n) ∈ A.supportTraceReal S ↔ ∃ p ∈ A.G, p ∈ S ‘ (⟨i, n⟩ₖ : V) := by
  have hSfun : IsFunction S := IsFunction.of_mem hS
  have hSdom : domain S = k ×ˢ (ω : V) := domain_eq_of_mem_function hS
  have hiω : i ∈ (ω : V) := hk i hi
  have hpair : (⟨i, n⟩ₖ : V) ∈ k ×ˢ (ω : V) := mem_prod_iff.mpr ⟨i, hi, n, hn, rfl⟩
  have hidom : (⟨i, n⟩ₖ : V) ∈ domain S := by rw [hSdom]; exact hpair
  have hvalue : (A.check S) ‘ (A.check (⟨i, n⟩ₖ : V)) = A.check (S ‘ (⟨i, n⟩ₖ : V)) :=
    A.check_value hidom
  have hreg : S ‘ (⟨i, n⟩ₖ : V) ∈ regularSets A.P A.R := function_value_mem hS hpair
  unfold supportTraceReal
  rw [mem_sep_iff]
  constructor
  · rintro ⟨-, q, hq, hqg, hgen⟩
    obtain ⟨q₀, hq₀, rfl⟩ := (A.mem_check_iff _ _).mp hq
    obtain ⟨u, hu, v, hv, rfl⟩ := mem_prod_iff.mp hq₀
    obtain ⟨-, -, he⟩ := (check_kpair_mem_check_omegaPairGraph_iff u v _).mp hqg
    obtain ⟨rfl, rfl⟩ := naturalPairCode_injective hiω hn hu hv he
    rw [hvalue] at hgen
    exact ((A.check_mem_boolGenericSet_iff _).mp hgen).2
  · intro h
    refine ⟨(A.check_mem_iff _ _).mpr (naturalPairCode_natural hiω hn),
      A.check (⟨i, n⟩ₖ : V), (A.check_mem_iff _ _).mpr (mem_prod_iff.mpr ⟨i, hiω, n, hn, rfl⟩),
      (check_kpair_mem_check_omegaPairGraph_iff i n _).mpr ⟨hiω, hn, rfl⟩, ?_⟩
    rw [hvalue]
    exact (A.check_mem_boolGenericSet_iff _).mpr ⟨hreg, h⟩

/-! ### Definability from the generated subalgebra alone -/

/-- If the complete subalgebra `D` is generated by the range of a ground function `S` with domain
`k × ω` for a set `k` of natural numbers, then every element of the intermediate extension by `D`
is definable in `V[G]` from ground sets, reals and ordinals. The real needed by
`groundRealDefinable_of_inSubalgebraModel_finite_of_real` is `supportTraceReal A S`. -/
theorem groundRealDefinable_of_inSubalgebraModel_range (hAC : InternalChoice V) {k S : V}
    (hk : k ⊆ (ω : V)) (hS : S ∈ regularSets A.P A.R ^ (k ×ˢ (ω : V)))
    {D : V} (hD : IsCompleteSubalgebra A.P A.R D)
    (hDgen : D = generatedSubalgebra A.P A.R (range S))
    {x : A.booleanContext.Model} (hx : A.InSubalgebraModel hD x) :
    A.IsGroundRealDefinable (A.booleanEquiv.symm x) :=
  A.groundRealDefinable_of_inSubalgebraModel_finite_of_real hAC hk hS
    (A.supportTraceReal_subset S)
    (fun _ hi _ hn ↦ (A.check_mem_supportTraceReal_iff hk hS hi hn).symm) hD hDgen hx

/-! ### The base support algebra -/

/-- Every element of the intermediate extension by the base support algebra of an internally
finite set of names over `ω × ω` is definable in `V[G]` from ground sets, reals and ordinals.
No hypothesis on the names in `E` beyond the finiteness of `E` is needed. -/
theorem groundRealDefinable_of_inSubalgebraModel_supportAlgebraBase_of_finite
    (hAC : InternalChoice V) {E : V} (hEf : IsInternallyFinite E)
    {x : A.booleanContext.Model}
    (hx : A.InSubalgebraModel (isCompleteSubalgebra_supportAlgebraBase A.order ⟨A.one, A.top.1⟩
      A.P ((ω : V) ×ˢ (ω : V)) E) x) :
    A.IsGroundRealDefinable (A.booleanEquiv.symm x) := by
  obtain ⟨k, S, hk, hS, hgen⟩ := exists_supportAlgebraBase_eq_generatedSubalgebra_range
    A.order ⟨A.one, A.top.1⟩ A.P E hEf
  exact A.groundRealDefinable_of_inSubalgebraModel_range hAC hk hS _ hgen hx

/-- The same with the hypothesis that the names of `E` are saturated nice names over `ω × ω`,
which the proof does not use. -/
theorem groundRealDefinable_of_inSubalgebraModel_supportAlgebraBase (hAC : InternalChoice V)
    {E : V} (hEf : IsInternallyFinite E)
    (hE : ∀ σ ∈ E, IsSaturatedNiceName (booleanConditions A.P A.R) (booleanOrder A.P A.R) A.P
      ((ω : V) ×ˢ (ω : V)) σ)
    {x : A.booleanContext.Model}
    (hx : A.InSubalgebraModel (isCompleteSubalgebra_supportAlgebraBase A.order ⟨A.one, A.top.1⟩
      A.P ((ω : V) ×ˢ (ω : V)) E) x) :
    A.IsGroundRealDefinable (A.booleanEquiv.symm x) :=
  A.groundRealDefinable_of_inSubalgebraModel_supportAlgebraBase_of_finite hAC hEf hx

end ForcingContext

/-! ### The Levy collapse -/

/-- Pointwise statement for the Solovay symmetric extension of the Levy collapse, conditional on
the Galois step for `E` and on every name in the closure of `τ` being fixed by the forced
stabilizer of `E`: the value of `τ`, seen in the Levy extension, is definable there from ground
sets, reals and ordinals. -/
theorem groundRealDefinable_solovayInclusion_of_uniformSupport {κ : V} [IsOrdinal κ] {G : Set V}
    (hAC : InternalChoice V)
    (hG : IsExternalForcingGeneric (levyCollapse κ) (levyOrder κ) G)
    (τ : (levySolovayContext κ hG).Name) (E : V) (hEf : IsInternallyFinite E)
    (hgal : GaloisStep (levyCollapse κ) (levyOrder κ) (levyCollapse κ) ((ω : V) ×ˢ (ω : V)) E)
    (hfix : ∀ μ ∈ nameClosure τ.val, ∀ Θ ∈ forcedStabilizer
      (booleanConditions (levyCollapse κ) (levyOrder κ))
      (booleanOrder (levyCollapse κ) (levyOrder κ))
      (forcingAutomorphisms (booleanConditions (levyCollapse κ) (levyOrder κ))
        (booleanOrder (levyCollapse κ) (levyOrder κ))) E, nameAction Θ μ = μ) :
    (levyContext κ hG).IsGroundRealDefinable
      (solovaySymmetricInclusion hG ((levySolovayContext κ hG).ofName τ)) := by
  obtain ⟨_, hx⟩ := inSubalgebraModel_of_uniformSupport hG τ E hgal hfix
  have h := (levyContext κ hG).groundRealDefinable_of_inSubalgebraModel_supportAlgebraBase_of_finite
    hAC hEf hx
  rwa [Equiv.symm_apply_apply] at h

/-- The same with the hypothesis that the names of `E` are saturated nice names over `ω × ω`,
which the proof does not use. -/
theorem groundRealDefinable_solovayInclusion_of_uniformSupport_of_nice {κ : V} [IsOrdinal κ]
    {G : Set V} (hAC : InternalChoice V)
    (hG : IsExternalForcingGeneric (levyCollapse κ) (levyOrder κ) G)
    (τ : (levySolovayContext κ hG).Name) (E : V) (hEf : IsInternallyFinite E)
    (hE : ∀ σ ∈ E, IsSaturatedNiceName (booleanConditions (levyCollapse κ) (levyOrder κ))
      (booleanOrder (levyCollapse κ) (levyOrder κ)) (levyCollapse κ) ((ω : V) ×ˢ (ω : V)) σ)
    (hgal : GaloisStep (levyCollapse κ) (levyOrder κ) (levyCollapse κ) ((ω : V) ×ˢ (ω : V)) E)
    (hfix : ∀ μ ∈ nameClosure τ.val, ∀ Θ ∈ forcedStabilizer
      (booleanConditions (levyCollapse κ) (levyOrder κ))
      (booleanOrder (levyCollapse κ) (levyOrder κ))
      (forcingAutomorphisms (booleanConditions (levyCollapse κ) (levyOrder κ))
        (booleanOrder (levyCollapse κ) (levyOrder κ))) E, nameAction Θ μ = μ) :
    (levyContext κ hG).IsGroundRealDefinable
      (solovaySymmetricInclusion hG ((levySolovayContext κ hG).ofName τ)) :=
  groundRealDefinable_solovayInclusion_of_uniformSupport hAC hG τ E hEf hgal hfix

end ZFVP
