import ZFVP.ModelTheory.SolovayLocalizationSequences
import ZFVP.ModelTheory.ForcingSmallUltrafilter
import ZFVP.SetTheory.LevyCollapseSmallSets

/-! Lemma Solovay-measure (external form): in the Levy collapse extension, the filter `U*`
generated by a nonprincipal `κ`-complete ultrafilter `U` of the ground model is a nonprincipal
filter on `κ` that decides every localized (in particular every definable) subset of `κ` and is
closed under intersections of localized (in particular definable) sequences of length `< κ`.
The localization lemma reduces each statement to a bounded-stage extension `V[G_ξ]`, where the
small-forcing theorem (Banerjee 2.5(2)) applies. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

section

variable {κ : V} [IsOrdinal κ] {G : Set V} (hG : IsExternalForcingGeneric (levyCollapse κ) (levyOrder κ) G)
  (β : V) [IsOrdinal β] (hβ : β ⊆ κ)

theorem levySubRealization_value_check' (x : V) :
    (levySubRealization β hβ hG).value ((levySubContext β hβ hG).check x) = (levyContext κ hG).check x :=
  ((levySubRealization β hβ hG).value_check x).trans (levySubRealization_ground β hβ hG x)

/-- Membership in the generated filter is reflected by the bounded-stage realization. -/
theorem value_mem_derivedFilter_iff (U : V) (X : (levySubContext β hβ hG).Model) :
    (levySubRealization β hβ hG).value X ∈ (levyContext κ hG).derivedFilter κ U ↔
      X ∈ (levySubContext β hβ hG).derivedFilter κ U := by
  let L := levySubRealization β hβ hG
  rw [(levyContext κ hG).mem_derivedFilter_iff, (levySubContext β hβ hG).mem_derivedFilter_iff]
  have h1 : L.embedding ((levySubContext β hβ hG).check κ) = (levyContext κ hG).check κ :=
    levySubRealization_value_check' hG β hβ κ
  constructor
  · rintro ⟨hsub, Y, hY, hYX⟩
    refine ⟨?_, Y, hY, ?_⟩
    · rw [← h1] at hsub
      exact (L.embedding.subset_iff _ _).mp hsub
    · rw [← levySubRealization_value_check' hG β hβ Y] at hYX
      exact (L.embedding.subset_iff _ _).mp hYX
  · rintro ⟨hsub, Y, hY, hYX⟩
    refine ⟨?_, Y, hY, ?_⟩
    · have := (L.embedding.subset_iff _ _).mpr hsub
      rwa [h1] at this
    · have hY' : L.embedding ((levySubContext β hβ hG).check Y) = (levyContext κ hG).check Y :=
        levySubRealization_value_check' hG β hβ Y
      have := (L.embedding.subset_iff _ _).mpr hYX
      rw [hY'] at this
      exact this

theorem value_relativeComplement (X : (levySubContext β hβ hG).Model) :
    (levySubRealization β hβ hG).value (relativeComplement ((levySubContext β hβ hG).check κ) X) =
      relativeComplement ((levyContext κ hG).check κ) ((levySubRealization β hβ hG).value X) := by
  let L := levySubRealization β hβ hG
  have h1 : L.embedding ((levySubContext β hβ hG).check κ) = (levyContext κ hG).check κ :=
    levySubRealization_value_check' hG β hβ κ
  unfold relativeComplement
  change L.embedding _ = _
  rw [L.embedding.map_separation _ (fun z ↦ z ∉ X) (fun z ↦ z ∉ L.embedding X) (by definability)
    (by definability) (fun z _ ↦ by rw [L.embedding.mem_iff]), h1]
  rfl

theorem value_indexedIntersection (δ : V) (g : (levySubContext β hβ hG).Model) [IsFunction g]
    (hdom : domain g = (levySubContext β hβ hG).check δ) :
    (levySubRealization β hβ hG).value
        (indexedIntersection ((levySubContext β hβ hG).check κ) ((levySubContext β hβ hG).check δ) g) =
      indexedIntersection ((levyContext κ hG).check κ) ((levyContext κ hG).check δ)
        ((levySubRealization β hβ hG).value g) := by
  let L := levySubRealization β hβ hG
  have h1 : L.embedding ((levySubContext β hβ hG).check κ) = (levyContext κ hG).check κ :=
    levySubRealization_value_check' hG β hβ κ
  have h2 : L.embedding ((levySubContext β hβ hG).check δ) = (levyContext κ hG).check δ :=
    levySubRealization_value_check' hG β hβ δ
  unfold indexedIntersection
  change L.embedding _ = _
  rw [L.embedding.map_separation _ (fun z ↦ ∀ i ∈ (levySubContext β hβ hG).check δ, z ∈ g ‘ i)
    (fun z ↦ ∀ i ∈ (levyContext κ hG).check δ, z ∈ (L.embedding g) ‘ i) (by definability)
    (by definability) ?_, h1]
  · rfl
  · intro z _
    rw [← h2, L.embedding.forall_mem_iff]
    constructor
    · intro h i hi
      rw [← L.embedding.map_value g i (by rw [hdom]; exact hi), L.embedding.mem_iff]
      exact h i hi
    · intro h i hi
      have := h i hi
      rwa [← L.embedding.map_value g i (by rw [hdom]; exact hi), L.embedding.mem_iff] at this

/-- A sequence of members of the generated filter realized from the bounded stage is a sequence of
members of the bounded-stage filter. -/
theorem value_function_derivedFilter (U δ : V) (g : (levySubContext β hβ hG).Model)
    (hg : (levySubRealization β hβ hG).value g ∈
      (levyContext κ hG).derivedFilter κ U ^ (levyContext κ hG).check δ) :
    g ∈ (levySubContext β hβ hG).derivedFilter κ U ^ (levySubContext β hβ hG).check δ := by
  let L := levySubRealization β hβ hG
  have h2 : L.embedding ((levySubContext β hβ hG).check δ) = (levyContext κ hG).check δ :=
    levySubRealization_value_check' hG β hβ δ
  haveI hLg : IsFunction (L.embedding g) := IsFunction.of_mem hg
  have hLdom : domain (L.embedding g) = L.embedding ((levySubContext β hβ hG).check δ) := by
    rw [h2]
    exact domain_eq_of_mem_function hg
  obtain ⟨hgf, hgdom⟩ := (L.embedding.function_on_iff g _).mp ⟨hLg, hLdom⟩
  haveI := hgf
  have hrange : range g ⊆ (levySubContext β hβ hG).derivedFilter κ U := by
    intro y hy
    obtain ⟨i, hiy⟩ := mem_range_iff.mp hy
    have hi : i ∈ domain g := mem_domain_of_kpair_mem hiy
    have hy' : y = g ‘ i := (value_eq_of_kpair_mem hiy).symm
    rw [hy', ← value_mem_derivedFilter_iff hG β hβ U]
    have hv : L.embedding (g ‘ i) = (L.embedding g) ‘ (L.embedding i) := L.embedding.map_value g i hi
    change L.embedding (g ‘ i) ∈ _
    rw [hv]
    apply function_value_mem hg
    rw [← h2]
    exact (L.embedding.mem_iff _ _).mpr (by rw [← hgdom]; exact hi)
  have hfun : g ∈ range g ^ domain g := isFunction_iff.mp hgf
  rw [hgdom] at hfun
  exact mem_function_of_mem_function_of_subset hfun hrange

end

section

variable {κ U : V} [IsOrdinal κ] (hAC : InternalChoice V)
  (hU : IsNonprincipalSetUltrafilter κ U) (hc : IsOrdinalComplete κ U)
  (hω : (ω : V) ∈ κ) (hκ : IsInitialOrdinal κ)
  {G : Set V} (hG : IsExternalForcingGeneric (levyCollapse κ) (levyOrder κ) G)

/-- The filter generated by `U` is a filter on `κ` in the extension. -/
theorem solovayFilter_filter (hU : IsNonprincipalSetUltrafilter κ U) :
    (levyContext κ hG).derivedFilter κ U ⊆ ℘ ((levyContext κ hG).check κ) ∧
    (levyContext κ hG).check κ ∈ (levyContext κ hG).derivedFilter κ U ∧
    (∅ : (levyContext κ hG).Model) ∉ (levyContext κ hG).derivedFilter κ U ∧
    (∀ X ∈ (levyContext κ hG).derivedFilter κ U, ∀ Y, Y ⊆ (levyContext κ hG).check κ → X ⊆ Y →
      Y ∈ (levyContext κ hG).derivedFilter κ U) ∧
    ∀ X ∈ (levyContext κ hG).derivedFilter κ U, ∀ Y ∈ (levyContext κ hG).derivedFilter κ U,
      X ∩ Y ∈ (levyContext κ hG).derivedFilter κ U := by
  let A := levyContext κ hG
  refine ⟨fun X hX ↦ mem_power_iff.mpr ((A.mem_derivedFilter_iff κ U X).mp hX).1, ?_, ?_, ?_, ?_⟩
  · exact (A.mem_derivedFilter_iff κ U _).mpr ⟨fun x hx ↦ hx, κ, hU.1.2.1, fun x hx ↦ hx⟩
  · intro h
    obtain ⟨_, Y, hY, hYsub⟩ := (A.mem_derivedFilter_iff κ U _).mp h
    have hYe : Y = ∅ := by
      apply mem_ext
      intro y
      simp only [not_mem_empty, iff_false]
      intro hy
      exact not_mem_empty (hYsub _ ((A.check_mem_iff y Y).mpr hy))
    rw [hYe] at hY
    exact hU.1.2.2.1 hY
  · intro X hX Y hY hXY
    obtain ⟨_, Z, hZ, hZX⟩ := (A.mem_derivedFilter_iff κ U X).mp hX
    exact (A.mem_derivedFilter_iff κ U Y).mpr ⟨hY, Z, hZ, subset_trans hZX hXY⟩
  · intro X hX Y hY
    obtain ⟨hXs, Z₁, hZ₁, hZ₁X⟩ := (A.mem_derivedFilter_iff κ U X).mp hX
    obtain ⟨_, Z₂, hZ₂, hZ₂Y⟩ := (A.mem_derivedFilter_iff κ U Y).mp hY
    refine (A.mem_derivedFilter_iff κ U _).mpr ⟨fun x hx ↦ hXs x (mem_inter_iff.mp hx).1,
      Z₁ ∩ Z₂, hU.1.2.2.2.2.1 Z₁ hZ₁ Z₂ hZ₂, fun x hx ↦ ?_⟩
    obtain ⟨z, hz, rfl⟩ := (A.mem_check_iff _ _).mp hx
    obtain ⟨hz₁, hz₂⟩ := mem_inter_iff.mp hz
    exact mem_inter_iff.mpr ⟨hZ₁X _ ((A.check_mem_iff z Z₁).mpr hz₁),
      hZ₂Y _ ((A.check_mem_iff z Z₂).mpr hz₂)⟩

/-- The generated filter is nonprincipal. -/
theorem solovayFilter_nonprincipal (hU : IsNonprincipalSetUltrafilter κ U) :
    ∀ x ∈ (levyContext κ hG).check κ, ({x} : (levyContext κ hG).Model) ∉
      (levyContext κ hG).derivedFilter κ U := by
  let A := levyContext κ hG
  intro x hx h
  obtain ⟨α, hα, rfl⟩ := (A.mem_check_iff κ x).mp hx
  obtain ⟨_, Y, hY, hYsub⟩ := (A.mem_derivedFilter_iff κ U _).mp h
  have hYα : Y ⊆ ({α} : V) := by
    intro y hy
    have := hYsub _ ((A.check_mem_iff y Y).mpr hy)
    rw [mem_singleton_iff, A.check_eq_iff] at this
    rw [mem_singleton_iff]
    exact this
  have hsing : ({α} : V) ∈ U :=
    hU.1.2.2.2.1 Y hY {α} (fun z hz ↦ by rw [mem_singleton_iff.mp hz]; exact hα) hYα
  exact hU.2 α hα hsing

include hAC hU hc hω hκ in
/-- Every localized subset of `κ` or its complement belongs to the generated filter. -/
theorem solovayFilter_dichotomy {X : (levyContext κ hG).Model} (hX : X ⊆ (levyContext κ hG).check κ)
    (hloc : IsLocalized hG X) :
    X ∈ (levyContext κ hG).derivedFilter κ U ∨
      relativeComplement ((levyContext κ hG).check κ) X ∈ (levyContext κ hG).derivedFilter κ U := by
  obtain ⟨ξ, hξ, X', rfl⟩ := hloc
  haveI : IsOrdinal ξ := IsOrdinal.of_mem hξ
  have hξsub : ξ ⊆ κ := IsOrdinal.toIsTransitive.transitive ξ hξ
  let C := levySubContext ξ hξsub hG
  let L := levySubRealization ξ hξsub hG
  obtain ⟨μ, hμ, hμP⟩ := levyCollapse_small hAC hU hc hω hκ hξ
  have huf := ForcingContext.derivedFilter_ultrafilter C hAC hU hc hμ hμP
  have hX'sub : X' ⊆ C.check κ := by
    have := hX
    rw [← levySubRealization_value_check' hG ξ hξsub κ] at this
    exact (L.embedding.subset_iff _ _).mp this
  rcases huf.1.1.2.2.2.2.2 X' hX'sub with h | h
  · exact Or.inl ((value_mem_derivedFilter_iff hG ξ hξsub U X').mpr h)
  · right
    rw [← value_relativeComplement hG ξ hξsub X']
    exact (value_mem_derivedFilter_iff hG ξ hξsub U _).mpr h

include hAC hU hc hω hκ in
/-- The generated filter is closed under intersections of localized sequences of length `< κ`. -/
theorem solovayFilter_complete {δ : V} (hδ : δ ∈ κ) {g : (levyContext κ hG).Model}
    (hg : g ∈ (levyContext κ hG).derivedFilter κ U ^ (levyContext κ hG).check δ)
    (hloc : IsLocalized hG g) :
    indexedIntersection ((levyContext κ hG).check κ) ((levyContext κ hG).check δ) g ∈
      (levyContext κ hG).derivedFilter κ U := by
  obtain ⟨ξ, hξ, g', rfl⟩ := hloc
  haveI : IsOrdinal ξ := IsOrdinal.of_mem hξ
  have hξsub : ξ ⊆ κ := IsOrdinal.toIsTransitive.transitive ξ hξ
  let C := levySubContext ξ hξsub hG
  obtain ⟨μ, hμ, hμP⟩ := levyCollapse_small hAC hU hc hω hκ hξ
  have huf := ForcingContext.derivedFilter_ultrafilter C hAC hU hc hμ hμP
  have hg' := value_function_derivedFilter hG ξ hξsub U δ g' hg
  haveI : IsFunction g' := IsFunction.of_mem hg'
  have hdom : domain g' = C.check δ := domain_eq_of_mem_function hg'
  have hδ' : C.check δ ∈ C.check κ := (C.check_mem_iff δ κ).mpr hδ
  have hint := huf.2 (C.check δ) hδ' g' hg'
  rw [← value_indexedIntersection hG ξ hξsub δ g' hdom]
  exact (value_mem_derivedFilter_iff hG ξ hξsub U _).mpr hint

include hAC hU hc hω hκ in
/-- Definable subsets of `κ` are decided by the generated filter. -/
theorem solovayFilter_dichotomy_of_definable {X : (levyContext κ hG).Model}
    (hX : X ⊆ (levyContext κ hG).check κ) (hXd : (levyContext κ hG).IsGroundRealDefinable X) :
    X ∈ (levyContext κ hG).derivedFilter κ U ∨
      relativeComplement ((levyContext κ hG).check κ) X ∈ (levyContext κ hG).derivedFilter κ U :=
  solovayFilter_dichotomy hAC hU hc hω hκ hG hX (groundRealDefinable_localized hAC hU hc hω hκ hG hXd hX)

include hAC hU hc hω hκ in
/-- The generated filter is closed under intersections of definable sequences of length `< κ`. -/
theorem solovayFilter_complete_of_definable {δ : V} (hδ : δ ∈ κ) {g : (levyContext κ hG).Model}
    (hg : g ∈ (levyContext κ hG).derivedFilter κ U ^ (levyContext κ hG).check δ)
    (hgd : (levyContext κ hG).IsGroundRealDefinable g) :
    indexedIntersection ((levyContext κ hG).check κ) ((levyContext κ hG).check δ) g ∈
      (levyContext κ hG).derivedFilter κ U := by
  have hg' : g ∈ ℘ ((levyContext κ hG).check κ) ^ (levyContext κ hG).check δ :=
    mem_function_of_mem_function_of_subset hg (solovayFilter_filter hG hU).1
  exact solovayFilter_complete hAC hU hc hω hκ hG hδ hg (sequence_localized hAC hU hc hω hκ hG hg' hgd)

end

end ZFVP
