import ZFVP.ModelTheory.LevySupportGalois
import ZFVP.ModelTheory.SolovaySymmetricRange
import ZFVP.SetTheory.GenericNameSeparative

/-! The Galois step of Karagila-Schilhan Lemma 9.3, taken as a named hypothesis, and what it gives
for the names of the Solovay symmetric system.

`GaloisStep P R one K E` is the conclusion of `coneRegular_mem_supportAlgebra_of_rigid` with its
rigidity hypothesis removed: a condition of the Boolean completion `B = booleanConditions P R`
fixed by every automorphism in the forced stabilizer of `E` has its regular cone inside the
complete subalgebra of `RO(B)` generated by the Boolean values `‖ǩ ∈ σ‖` for `σ ∈ E`.

The reduction proved here turns that into a statement about names. `B` is separative, so its
regular cones are exactly its principal cones and every element of `RO(B)` is the cone of a unique
element of `B`; that identification is proved below and is what lets the Galois step be applied to
a Boolean value rather than to a condition. Given two hereditarily symmetric names with supports
`E₁` and `E₂`, the value `‖σ ∈ τ‖` is fixed as a set by the forced stabilizer of `E₁ ∪ E₂`, hence
its cone is fixed, hence by the Galois step it lies in the support algebra of `E₁ ∪ E₂`. Since the
value decides `ofName σ ∈ ofName τ` through the generic, membership between values of hereditarily
symmetric names is decided inside a support algebra of a finite set of saturated nice names.

What is not proved here is the forward hypothesis `hpt` of `ZFVP.ModelTheory.SolovaySymmetricRange`,

  theorem groundRealDefinable_solovayInclusion_of_galois ... (x : (levySolovayContext κ hG).Model) :
      (levyContext κ hG).IsGroundRealDefinable (solovaySymmetricInclusion hG x)

The step from the projection lemma to that statement needs two things the library does not have.

First, the trace of the generic on a support algebra has to be a set of the extension definable
from a real. `ForcingContext.genericTrace_groundRealDefinable` does this for a subalgebra of
`RO(P)` generated by the range of a ground `ω`-sequence of regular sets whose meets are read off a
real. The support algebra lives one level up, inside `RO(RO(P))`, and its generators are indexed by
`(ω × ω) × E` rather than by `ω`, so what is missing is

  theorem genericTrace_supportAlgebra_groundRealDefinable
      (hE : ∀ σ ∈ E, IsSaturatedNiceName (booleanConditions A.P A.R) (booleanOrder A.P A.R) A.P
        ((ω : V) ×ˢ (ω : V)) σ) (hEf : IsInternallyFinite E) :
      A.IsGroundRealDefinable
        {d ∈ A.check (supportAlgebra (booleanConditions A.P A.R) (booleanOrder A.P A.R) A.P
          ((ω : V) ×ˢ (ω : V)) E) ; GenericMeets ... d}

the real in question being the tuple of the values of the names in `E`, each a subset of the
checked `ω × ω`.

Second, and this is the real obstruction, membership in `ofName τ` has to be reconstructed from
that trace. The projection lemma decides `ofName σ ∈ ofName τ` for one `σ` at a time, and the
support algebra it produces depends on `σ`; recovering `ofName τ` as a set of the extension needs a
valuation map `ν ↦ val_H ν` for a filter parameter `H`, defined by recursion on names inside the
extension, together with `val_{G ∩ D} τ = val_G τ` for names hereditarily supported by `D`. The
union of the supports of the names in the closure of `τ` is not finite, so the finite `E` of the
projection lemma does not suffice, and neither the internal valuation recursion nor a single
algebra covering a whole name closure is available. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-! ### The Galois step as a hypothesis -/

/-- The Galois step for the symmetric system over the Boolean completion of `(P, R)`: a condition
of the completion fixed by the whole forced stabilizer of `E` has its regular cone in the support
algebra of `E`. -/
def GaloisStep (P R one K E : V) : Prop :=
  ∀ b ∈ booleanConditions P R,
    (∀ Θ ∈ forcedStabilizer (booleanConditions P R) (booleanOrder P R)
        (forcingAutomorphisms (booleanConditions P R) (booleanOrder P R)) E, Θ ‘ b = b) →
      coneRegular (booleanConditions P R) (booleanOrder P R) b ∈
        supportAlgebra (booleanConditions P R) (booleanOrder P R) one K E

/-- The Galois step holds when the conditions occurring in the names of `E` are rigid: this is
`coneRegular_mem_supportAlgebra_of_rigid` read as a witness for `GaloisStep`. -/
theorem galoisStep_of_rigid {P R one K E : V} (hP : ∃ p, p ∈ P)
    (hhom : IsWeaklyHomogeneous P R one)
    (hE : ∀ σ ∈ E, IsNiceName (booleanConditions P R) P K σ)
    (hcond : ∀ d ∈ nameConditions E, ∀ π, IsForcingAutomorphism P R π →
      π ‘ one = one → imageAction π d = d) :
    GaloisStep P R P K E :=
  fun _ hb hfix ↦ coneRegular_mem_supportAlgebra_of_rigid hP hhom hE hcond hb hfix

/-! ### Regular cones in a separative poset -/

/-- In a separative preorder the regular cone of `p` is its set of extensions. -/
theorem mem_coneRegular_iff_of_separative {P R p q : V} (hR : IsForcingPreorder P R)
    (hsep : IsSeparative P R) (hp : p ∈ P) :
    q ∈ coneRegular P R p ↔ q ∈ P ∧ ⟨q, p⟩ₖ ∈ R := by
  rw [mem_coneRegular_iff]
  constructor
  · rintro ⟨hq, hh⟩
    refine ⟨hq, ?_⟩
    by_contra hno
    obtain ⟨r, hr, hrq, hinc⟩ := hsep q hq p hp hno
    obtain ⟨s, hs, hsp, hsr⟩ := hh r hr hrq
    exact hinc ⟨s, hs, hsr, hsp⟩
  · rintro ⟨hq, hqp⟩
    exact ⟨hq, fun r hr hrq ↦ ⟨r, hr, hR.2.2 r hr q hq p hp hrq hqp, hR.2.1 r hr⟩⟩

/-- In a separative poset a condition is determined by its regular cone. -/
theorem coneRegular_injective_of_separative {P R p q : V} (hR : IsForcingPoset P R)
    (hsep : IsSeparative P R) (hp : p ∈ P) (hq : q ∈ P)
    (h : coneRegular P R p = coneRegular P R q) : p = q := by
  have h1 : ⟨p, q⟩ₖ ∈ R := by
    have := self_mem_coneRegular hR.1 hp
    rw [h] at this
    exact ((mem_coneRegular_iff_of_separative hR.1 hsep hq).mp this).2
  have h2 : ⟨q, p⟩ₖ ∈ R := by
    have := self_mem_coneRegular hR.1 hq
    rw [← h] at this
    exact ((mem_coneRegular_iff_of_separative hR.1 hsep hp).mp this).2
  exact hR.2 p hp q hq h1 h2

/-! ### Completeness of the Boolean completion -/

/-- The regular cone of a condition of the Boolean completion is its set of subsets in the
completion. -/
theorem mem_coneRegular_booleanOrder_iff {P R A C : V} (hR : IsForcingPreorder P R)
    (hA : A ∈ booleanConditions P R) :
    C ∈ coneRegular (booleanConditions P R) (booleanOrder P R) A ↔
      C ∈ booleanConditions P R ∧ C ⊆ A := by
  rw [mem_coneRegular_iff_of_separative (booleanOrder_poset P R).1
    (booleanOrder_separative hR) hA]
  constructor
  · rintro ⟨hC, hCA⟩
    exact ⟨hC, ((kpair_mem_booleanOrder_iff P R C A).mp hCA).2.2⟩
  · rintro ⟨hC, hCA⟩
    exact ⟨hC, (kpair_mem_booleanOrder_iff P R C A).mpr ⟨hC, hA, hCA⟩⟩

/-- Completeness of the Boolean completion: every nonzero element of the completion of the
completion is the regular cone of the join of its members. -/
theorem coneRegular_regularJoin {P R A : V} (hR : IsForcingPreorder P R)
    (hA : A ∈ booleanConditions (booleanConditions P R) (booleanOrder P R)) :
    coneRegular (booleanConditions P R) (booleanOrder P R) (regularJoin P R A) = A := by
  obtain ⟨hAreg, hAne⟩ := (mem_booleanConditions_iff _ _ A).mp hA
  have hAsub : A ⊆ booleanConditions P R := hAreg.1
  obtain ⟨C₀, hC₀⟩ := hAne
  have hjoin : regularJoin P R A ∈ booleanConditions P R :=
    regularJoin_mem_booleanConditions hR hAsub hC₀
  apply mem_ext
  intro C
  rw [mem_coneRegular_booleanOrder_iff hR hjoin]
  constructor
  · rintro ⟨hC, hCJ⟩
    refine hAreg.2.2 C hC (fun D hD hDC ↦ ?_)
    have hDsub : D ⊆ C := ((kpair_mem_booleanOrder_iff P R D C).mp hDC).2.2
    have hDreg := ((mem_booleanConditions_iff P R D).mp hD).1
    obtain ⟨p, hp⟩ := ((mem_booleanConditions_iff P R D).mp hD).2
    have hpJ : p ∈ regularJoin P R A := hCJ p (hDsub p hp)
    obtain ⟨-, hh⟩ := (mem_forcingClosure_iff _ _ _ _).mp hpJ
    obtain ⟨s, hs, hsp⟩ := hh p (hDreg.1 p hp) (hR.2.1 p (hDreg.1 p hp))
    obtain ⟨E, hE, hsE⟩ := mem_sUnion_iff.mp hs
    have hEreg := ((mem_booleanConditions_iff P R E).mp (hAsub E hE)).1
    have hsP : s ∈ P := hEreg.1 s hsE
    have hsD : s ∈ D := hDreg.2.1 p hp s hsP hsp
    have hcone : coneRegular P R s ∈ booleanConditions P R :=
      coneRegular_mem_booleanConditions hR hsP
    refine ⟨coneRegular P R s, ?_, ?_⟩
    · exact hAreg.2.1 E hE _ hcone
        ((kpair_mem_booleanOrder_iff P R _ E).mpr
          ⟨hcone, hAsub E hE, coneRegular_subset_of_mem hR hEreg hsE⟩)
    · exact (kpair_mem_booleanOrder_iff P R _ D).mpr
        ⟨hcone, hD, coneRegular_subset_of_mem hR hDreg hsD⟩
  · intro hCA
    have hC := hAsub C hCA
    exact ⟨hC, subset_regularJoin hR hCA ((mem_booleanConditions_iff P R C).mp hC).1⟩

/-! ### From invariance to the support algebra -/

/-- The zero of the completion of the completion lies in every support algebra: it is the join of
the empty family. -/
theorem empty_mem_supportAlgebra (P R one K E : V) :
    (∅ : V) ∈ supportAlgebra (booleanConditions P R) (booleanOrder P R) one K E := by
  have hcomp := generatedSubalgebra_complete (booleanOrder_poset P R).1
    (supportValues_subset_regularSets (booleanOrder_poset P R).1 one K E)
  have h := hcomp.2.2.2 (∅ : V) (fun d hd ↦ absurd hd not_mem_empty)
  rwa [regularJoin_empty (booleanOrder_poset P R).1] at h

/-- The Galois step in the form it is used: an element of `RO(B)` fixed as a set by the image
action of every automorphism in the forced stabilizer of `E` lies in the support algebra of `E`.
The passage from the pointwise fixing that `GaloisStep` asks for to fixing as a set is the
identification of `RO(B)` with `B` through regular cones. -/
theorem mem_supportAlgebra_of_imageAction_fixed {P R one K E A : V} (hR : IsForcingPreorder P R)
    (hgal : GaloisStep P R one K E)
    (hAreg : IsForcingRegular (booleanConditions P R) (booleanOrder P R) A)
    (hfix : ∀ Θ ∈ forcedStabilizer (booleanConditions P R) (booleanOrder P R)
      (forcingAutomorphisms (booleanConditions P R) (booleanOrder P R)) E, imageAction Θ A = A) :
    A ∈ supportAlgebra (booleanConditions P R) (booleanOrder P R) one K E := by
  by_cases hne : ∃ C, C ∈ A
  · have hA : A ∈ booleanConditions (booleanConditions P R) (booleanOrder P R) :=
      (mem_booleanConditions_iff _ _ A).mpr ⟨hAreg, hne⟩
    obtain ⟨C₀, hC₀⟩ := hne
    have hb : regularJoin P R A ∈ booleanConditions P R :=
      regularJoin_mem_booleanConditions hR hAreg.1 hC₀
    have hcone := coneRegular_regularJoin hR hA
    have hfix' : ∀ Θ ∈ forcedStabilizer (booleanConditions P R) (booleanOrder P R)
        (forcingAutomorphisms (booleanConditions P R) (booleanOrder P R)) E,
        Θ ‘ (regularJoin P R A) = regularJoin P R A := by
      intro Θ hΘ
      have hΘa : IsForcingAutomorphism (booleanConditions P R) (booleanOrder P R) Θ :=
        (mem_forcingAutomorphisms_iff _ _ _).mp
          ((mem_forcedStabilizer _ _ _ _ _).mp hΘ).1
      have himg := imageAction_coneRegular hΘa hb
      rw [hcone, hfix Θ hΘ] at himg
      refine coneRegular_injective_of_separative (booleanOrder_poset P R)
        (booleanOrder_separative hR) (function_value_mem hΘa.1 hb) hb ?_
      rw [← himg, hcone]
    have := hgal (regularJoin P R A) hb hfix'
    rwa [hcone] at this
  · have hA0 : A = (∅ : V) := by
      apply mem_ext
      intro z
      exact ⟨fun hz ↦ absurd ⟨z, hz⟩ hne, fun hz ↦ absurd hz not_mem_empty⟩
    rw [hA0]
    exact empty_mem_supportAlgebra P R one K E

/-- The Boolean value of `σ ∈ τ` for two names fixed by the forced stabilizer of `E` lies in the
support algebra of `E`. -/
theorem atomicMembership_mem_supportAlgebra {P R one K E σ τ : V} (hR : IsForcingPreorder P R)
    (hgal : GaloisStep P R one K E)
    (hσ : IsForcingName (booleanConditions P R) σ) (hτ : IsForcingName (booleanConditions P R) τ)
    (hfix : ∀ Θ ∈ forcedStabilizer (booleanConditions P R) (booleanOrder P R)
      (forcingAutomorphisms (booleanConditions P R) (booleanOrder P R)) E,
        nameAction Θ σ = σ ∧ nameAction Θ τ = τ) :
    atomicMembership (booleanConditions P R) (booleanOrder P R) σ τ ∈
      supportAlgebra (booleanConditions P R) (booleanOrder P R) one K E := by
  refine mem_supportAlgebra_of_imageAction_fixed hR hgal
    (atomicMembership_regular (booleanOrder_poset P R).1 σ τ) (fun Θ hΘ ↦ ?_)
  have hΘa : IsForcingAutomorphism (booleanConditions P R) (booleanOrder P R) Θ :=
    (mem_forcingAutomorphisms_iff _ _ _).mp ((mem_forcedStabilizer _ _ _ _ _).mp hΘ).1
  obtain ⟨hsσ, hsτ⟩ := hfix Θ hΘ
  refine imageAction_eq_of_iff hΘa (atomicMembership_subset _ _ _ _)
    (atomicMembership_subset _ _ _ _) (fun q hq ↦ ?_)
  conv_lhs => rw [← hsσ, ← hsτ]
  exact atomicMembership_nameAction_iff hΘa hσ hτ hq

/-! ### Membership between values of hereditarily symmetric names -/

namespace ForcingContext

variable (A : ForcingContext V)

/-- The Boolean value deciding `σ ∈ τ` for two names whose supports are inside `E` lies in the
support algebra of `E`. -/
theorem solovay_atomicMembership_mem_supportAlgebra {E σ τ : V}
    (hgal : GaloisStep A.P A.R A.P ((ω : V) ×ˢ (ω : V)) E)
    (hσ : IsForcingName (booleanConditions A.P A.R) σ)
    (hτ : IsForcingName (booleanConditions A.P A.R) τ)
    (hsσ : forcedStabilizer (booleanConditions A.P A.R) (booleanOrder A.P A.R)
        (forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R)) E ⊆
      nameStabilizer (forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R)) σ)
    (hsτ : forcedStabilizer (booleanConditions A.P A.R) (booleanOrder A.P A.R)
        (forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R)) E ⊆
      nameStabilizer (forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R)) τ) :
    atomicMembership (booleanConditions A.P A.R) (booleanOrder A.P A.R) σ τ ∈
      supportAlgebra (booleanConditions A.P A.R) (booleanOrder A.P A.R) A.P
        ((ω : V) ×ˢ (ω : V)) E :=
  atomicMembership_mem_supportAlgebra A.order hgal hσ hτ
    (fun Θ hΘ ↦ ⟨(mem_sep_iff.mp (hsσ Θ hΘ)).2, (mem_sep_iff.mp (hsτ Θ hΘ)).2⟩)

/-- Membership between two values of the Boolean extension is decided by whether the generic
meets the Boolean value of the membership statement. -/
theorem booleanContext_ofName_mem_iff (σ τ : ForcingName A.booleanContext.P) :
    A.booleanContext.ofName σ ∈ A.booleanContext.ofName τ ↔
      ∃ b ∈ A.booleanContext.G, b ∈ atomicMembership (booleanConditions A.P A.R)
        (booleanOrder A.P A.R) σ.val τ.val :=
  forcingQuotientMk_mem_iff _ _ _ _ _ _ _

/-- The projection lemma of Karagila-Schilhan Lemma 9.3, given the Galois step: for any two
elements of the Solovay symmetric model there is a finite set `E` of saturated nice names and an
element `D` of the support algebra of `E` such that membership between the two elements holds
exactly when the generic of the Boolean completion meets `D`. So membership inside the symmetric
model is decided inside the complete subalgebra generated by the Boolean values of finitely many
saturated nice names over `ω × ω`. -/
theorem solovay_mem_decided_in_supportAlgebra
    (hgal : ∀ E : V, (∀ ρ ∈ E, IsSaturatedNiceName (booleanConditions A.P A.R)
        (booleanOrder A.P A.R) A.P ((ω : V) ×ˢ (ω : V)) ρ) →
      GaloisStep A.P A.R A.P ((ω : V) ×ˢ (ω : V)) E)
    (σ τ : A.solovayContext.Name) :
    ∃ E : V, IsInternallyFinite E ∧
      (∀ ρ ∈ E, IsSaturatedNiceName (booleanConditions A.P A.R) (booleanOrder A.P A.R) A.P
        ((ω : V) ×ˢ (ω : V)) ρ) ∧
      ∃ D ∈ supportAlgebra (booleanConditions A.P A.R) (booleanOrder A.P A.R) A.P
          ((ω : V) ×ˢ (ω : V)) E,
        (A.solovayContext.ofName σ ∈ A.solovayContext.ofName τ ↔
          ∃ b ∈ A.booleanContext.G, b ∈ D) := by
  obtain ⟨E₁, hE₁f, hE₁s, hE₁st⟩ := A.solovay_exists_support σ
  obtain ⟨E₂, hE₂f, hE₂s, hE₂st⟩ := A.solovay_exists_support τ
  refine ⟨E₁ ∪ E₂, internallyFinite_union hE₁f hE₂f, ?_, ?_⟩
  · intro ρ hρ
    exact (mem_union_iff.mp hρ).elim (hE₁s ρ) (hE₂s ρ)
  refine ⟨atomicMembership (booleanConditions A.P A.R) (booleanOrder A.P A.R) σ.val τ.val, ?_, ?_⟩
  · refine A.solovay_atomicMembership_mem_supportAlgebra (hgal _ ?_) σ.property.1 τ.property.1
      ?_ ?_
    · intro ρ hρ
      exact (mem_union_iff.mp hρ).elim (hE₁s ρ) (hE₂s ρ)
    · intro Θ hΘ
      rw [forcedStabilizer_union] at hΘ
      exact hE₁st Θ (mem_inter_iff.mp hΘ).1
    · intro Θ hΘ
      rw [forcedStabilizer_union] at hΘ
      exact hE₂st Θ (mem_inter_iff.mp hΘ).2
  · rw [← A.solovayContext.toOrdinary_mem_iff, A.solovayContext.toOrdinary_ofName,
      A.solovayContext.toOrdinary_ofName]
    exact A.booleanContext_ofName_mem_iff ⟨σ.val, σ.property.1⟩ ⟨τ.val, τ.property.1⟩

/-- The projection lemma for arbitrary elements of the Solovay symmetric model: every element is
the value of a hereditarily symmetric name, so membership between any two of them is decided
inside the support algebra of a finite set of saturated nice names. -/
theorem solovay_model_mem_decided_in_supportAlgebra
    (hgal : ∀ E : V, (∀ ρ ∈ E, IsSaturatedNiceName (booleanConditions A.P A.R)
        (booleanOrder A.P A.R) A.P ((ω : V) ×ˢ (ω : V)) ρ) →
      GaloisStep A.P A.R A.P ((ω : V) ×ˢ (ω : V)) E)
    (x y : A.solovayContext.Model) :
    ∃ E : V, IsInternallyFinite E ∧
      (∀ ρ ∈ E, IsSaturatedNiceName (booleanConditions A.P A.R) (booleanOrder A.P A.R) A.P
        ((ω : V) ×ˢ (ω : V)) ρ) ∧
      ∃ D ∈ supportAlgebra (booleanConditions A.P A.R) (booleanOrder A.P A.R) A.P
          ((ω : V) ×ˢ (ω : V)) E,
        (x ∈ y ↔ ∃ b ∈ A.booleanContext.G, b ∈ D) := by
  obtain ⟨σ, rfl⟩ := A.solovayContext.ofName_surjective x
  obtain ⟨τ, rfl⟩ := A.solovayContext.ofName_surjective y
  exact A.solovay_mem_decided_in_supportAlgebra hgal σ τ

end ForcingContext

end ZFVP
