import ZFVP.ModelTheory.BooleanGenericTransfer
import ZFVP.ModelTheory.SymmetricVopenkaPreservation
import ZFVP.ModelTheory.LevyCollapseSubgeneric
import ZFVP.SetTheory.SaturatedNiceNames
import ZFVP.SetTheory.CantorSpace

/-! The Solovay symmetric system `O(B, Ṙ)`: the full automorphism group of the Boolean completion
of a forcing poset, with the normal filter generated by the forced stabilizers of finitely many
names of reals (Karagila–Schilhan Definition 9.1). Its symmetric model satisfies `ZF` and inherits
Vopěnka's Principle from the ground model. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

/-- `x` is a real: a member of Cantor space. -/
def isRealFormula : SetTheorySemisentence 1 := f“x. x ∈ !cantorSpaceFormula”

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

namespace ForcingContext

/-- The symmetric system on the Boolean completion whose filter is generated by the forced
stabilizers of finite sets of names satisfying `φ`. -/
noncomputable def forcedSymmetricContext (A : ForcingContext V) (φ : SetTheorySemisentence 1) :
    SymmetricContext V where
  toForcingContext := A.booleanContext
  Γ := forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R)
  F := forcedStabilizerFilter (booleanConditions A.P A.R) (booleanOrder A.P A.R)
    (forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R))
    (IsForcedName (booleanConditions A.P A.R) (booleanOrder A.P A.R) φ) inferInstance
  poset := booleanOrder_poset _ _
  group := forcingAutomorphisms_group _ _
  normal := forcedNameFilter_normal (booleanOrder_poset _ _).1 (forcingAutomorphisms_group _ _) φ

/-- The symmetric system on the Boolean completion whose filter is generated by the forced
stabilizers of finitely many saturated nice names of subsets of `Ǩ` (the class name of all
subsets of `Ǩ`, realized by nice names). -/
noncomputable def niceSymmetricContext (A : ForcingContext V) (K : V) : SymmetricContext V where
  toForcingContext := A.booleanContext
  Γ := forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R)
  F := niceNameFilter (booleanConditions A.P A.R) (booleanOrder A.P A.R)
    (forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R)) A.P K
  poset := booleanOrder_poset _ _
  group := forcingAutomorphisms_group _ _
  normal := niceNameFilter_normal (booleanOrder_poset _ _) (forcingAutomorphisms_group _ _)
    (booleanOrder_top ⟨A.one, A.top.1⟩)

theorem niceSymmetricContext_toForcingContext (A : ForcingContext V) (K : V) :
    (A.niceSymmetricContext K).toForcingContext = A.booleanContext := rfl

theorem niceSymmetricContext_one (A : ForcingContext V) (K : V) :
    (A.niceSymmetricContext K).one = A.P := rfl

theorem forcedSymmetricContext_P (A : ForcingContext V) (φ : SetTheorySemisentence 1) :
    (A.forcedSymmetricContext φ).P = booleanConditions A.P A.R := rfl

theorem forcedSymmetricContext_R (A : ForcingContext V) (φ : SetTheorySemisentence 1) :
    (A.forcedSymmetricContext φ).R = booleanOrder A.P A.R := rfl

theorem forcedSymmetricContext_Γ (A : ForcingContext V) (φ : SetTheorySemisentence 1) :
    (A.forcedSymmetricContext φ).Γ =
      forcingAutomorphisms (booleanConditions A.P A.R) (booleanOrder A.P A.R) := rfl

theorem forcedSymmetricContext_toForcingContext (A : ForcingContext V) (φ : SetTheorySemisentence 1) :
    (A.forcedSymmetricContext φ).toForcingContext = A.booleanContext := rfl

/-- The Solovay symmetric system `O(B, Ṙ_can)` on the Boolean completion, with `Ṙ_can` the
class name of all subsets of `ω × ω` (interdefinable with the reals `2^ω`). -/
noncomputable def solovayContext (A : ForcingContext V) : SymmetricContext V :=
  A.niceSymmetricContext ((ω : V) ×ˢ (ω : V))

/-- The symmetric model `V(R)` of the Solovay system satisfies every instance of Vopěnka's
Principle available in the ground model. -/
theorem solovayContext_vopenkaInstance (A : ForcingContext V)
    (hVP : ∀ ψ : SetTheorySemisentence 2, VopenkaInstance (V := V) ψ)
    (φ : SetTheorySemisentence 2) : VopenkaInstance (V := A.solovayContext.Model) φ :=
  A.solovayContext.vopenkaInstance hVP φ

end ForcingContext

/-- The Solovay model of the Levy collapse `Coll(ω, <κ)`. -/
noncomputable def levySolovayContext (κ : V) {G : Set V}
    (hG : IsExternalForcingGeneric (levyCollapse κ) (levyOrder κ) G) : SymmetricContext V :=
  (levyContext κ hG).solovayContext

instance levySolovayModel_zf (κ : V) {G : Set V}
    (hG : IsExternalForcingGeneric (levyCollapse κ) (levyOrder κ) G) :
    (levySolovayContext κ hG).Model↓[ℒₛₑₜ] ⊧* 𝗭𝗙 :=
  SymmetricContext.modelZF _

theorem levySolovayModel_vopenkaInstance (κ : V) {G : Set V}
    (hG : IsExternalForcingGeneric (levyCollapse κ) (levyOrder κ) G)
    (hVP : ∀ ψ : SetTheorySemisentence 2, VopenkaInstance (V := V) ψ)
    (φ : SetTheorySemisentence 2) : VopenkaInstance (V := (levySolovayContext κ hG).Model) φ :=
  (levyContext κ hG).solovayContext_vopenkaInstance hVP φ

end ZFVP
