import ZFVP.ModelTheory.LevyLocalizedRegularity
import ZFVP.ModelTheory.SolovayMeasure
import ZFVP.ModelTheory.CohenGenericReals
import ZFVP.SetTheory.HODRegularity
import ZFVP.SetTheory.NaturalPairing

/-! The regularity properties of `lem:Solovay-regularity` for the HOD class model
`Sol = HOD_{V ∪ R}^{V[G]}` built inside the Levy collapse extension, and the two clauses of
`lem:Solovay-measure` for the sets of `Sol`.

A set of reals of the class model is hereditarily ordinal definable from the parameter class of
`Pf` in the extension; the hypothesis `hconv` turns that into definability from ground sets, reals
and ordinals, the Levy localization results then give Lebesgue measurability, the Baire property
and the perfect set property in the extension, and the HOD transport lemmas push those back into
the class model. The same route sends a subset of `κ̌` lying in the class model to the dichotomy
and the completeness of the filter generated by `U`. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

section

variable {κ U : V} [IsOrdinal κ] (hAC : InternalChoice V)
  (hU : IsNonprincipalSetUltrafilter κ U) (hc : IsOrdinalComplete κ U)
  (hω : (ω : V) ∈ κ) (hκ : IsInitialOrdinal κ)
  {G : Set V} (hG : IsExternalForcingGeneric (levyCollapse κ) (levyOrder κ) G)
  (Pf : SetTheorySemisentence 2) {p : (levyContext κ hG).Model}
  (hPf_check : ∀ a : V, Pf.Evalb ![(levyContext κ hG).check a, p])
  (hreal : ∀ x ∈ cantorSpace (levyContext κ hG).Model, IsAllowed Pf x p)
  [Nonempty (HODDom Pf p)] [(HODDom Pf p)↓[ℒₛₑₜ] ⊧* 𝗭𝗙]
  (hconv : ∀ x : (levyContext κ hG).Model, IsOD Pf x p →
    (levyContext κ hG).IsGroundRealDefinable x)

include hAC hPf_check in
/-- The ground model has an injection of the finite binary sequences into `ω`; its check is such an
injection of the extension and is an allowed parameter. -/
theorem levy_exists_allowed_sequenceCode :
    ∃ c : (levyContext κ hG).Model,
      c ∈ (ω : (levyContext κ hG).Model) ^ binarySequences (levyContext κ hG).Model ∧
        Injective c ∧ IsAllowed Pf c p := by
  obtain ⟨c₀, hc₀, hc₀inj⟩ := binarySequences_cardLE_omega (V := V) hAC
  refine ⟨(levyContext κ hG).check c₀, ?_, ?_, Or.inr (Or.inr (hPf_check c₀))⟩
  · have h := ((levyContext κ hG).check_function_iff c₀ (binarySequences V) (ω : V)).mpr hc₀
    rwa [(levyContext κ hG).check_omega_eq, (levyContext κ hG).check_binarySequences] at h
  · exact ((levyContext κ hG).checkEmbedding.injective_iff c₀).mpr hc₀inj

include hPf_check in
/-- The check of a ground pairing function is an injection of `ω × ω` into `ω` in the extension and
is an allowed parameter. -/
theorem levy_exists_allowed_pairCode :
    ∃ e : (levyContext κ hG).Model,
      e ∈ (ω : (levyContext κ hG).Model) ^
        ((ω : (levyContext κ hG).Model) ×ˢ (ω : (levyContext κ hG).Model)) ∧
        Injective e ∧ IsAllowed Pf e p := by
  obtain ⟨e₀, he₀, he₀inj⟩ := omega_prod_cardLE_omega (V := V)
  refine ⟨(levyContext κ hG).check e₀, ?_, ?_, Or.inr (Or.inr (hPf_check e₀))⟩
  · have h := ((levyContext κ hG).check_function_iff e₀ ((ω : V) ×ˢ (ω : V)) (ω : V)).mpr he₀
    have hprod : (levyContext κ hG).check ((ω : V) ×ˢ (ω : V)) =
        (levyContext κ hG).check (ω : V) ×ˢ (levyContext κ hG).check (ω : V) :=
      (levyContext κ hG).checkEmbedding.map_prod (ω : V) (ω : V)
    rwa [hprod, (levyContext κ hG).check_omega_eq] at h
  · exact ((levyContext κ hG).checkEmbedding.injective_iff e₀).mpr he₀inj

include hreal in
/-- A set of reals of the class model is a set of reals of the extension. -/
theorem hod_val_subset_cantorSpace {X : HODDom Pf p} (hX : X ⊆ cantorSpace (HODDom Pf p)) :
    X.val ⊆ cantorSpace (levyContext κ hG).Model := by
  rw [← val_cantorSpace Pf p hreal]
  exact (subset_val_iff Pf p _ _).mpr hX

include hAC hU hc hω hκ hconv in
/-- Every set of the class model is definable in the extension from ground sets, reals and
ordinals, hence from localized parameters. -/
theorem hod_val_locallyDefinable (X : HODDom Pf p) : IsLocallyDefinable hG X.val :=
  locallyDefinable_of_groundRealDefinable hAC hU hc hω hκ hG
    (hconv X.val (IsHOD.od Pf (hod_val_isHOD Pf p X)))

include hAC hU hc hω hκ hPf_check hreal hconv in
/-- Lebesgue measurability in the class model (`lem:Solovay-regularity`, clause LM). -/
theorem hod_lebesgueMeasurable {X : HODDom Pf p} (hX : X ⊆ cantorSpace (HODDom Pf p)) :
    IsLebesgueMeasurable X := by
  obtain ⟨cc, hcc, hccinj, hccall⟩ := levy_exists_allowed_sequenceCode hAC hG Pf hPf_check
  obtain ⟨ee, hee, heeinj, heeall⟩ := levy_exists_allowed_pairCode hG Pf hPf_check
  refine isLebesgueMeasurable_of_val Pf p hreal cc ee hcc hccinj hccall hee heeinj heeall ?_
  exact lebesgueMeasurable_of_locallyDefinable hAC hU hc hω hG
    (hod_val_subset_cantorSpace hG Pf hreal hX)
    (hod_val_locallyDefinable hAC hU hc hω hκ hG Pf hconv X)

include hAC hU hc hω hκ hPf_check hreal hconv in
/-- The Baire property in the class model (`lem:Solovay-regularity`, clause BP). -/
theorem hod_baireProperty {X : HODDom Pf p} (hX : X ⊆ cantorSpace (HODDom Pf p)) :
    BaireProperty X := by
  obtain ⟨cc, hcc, hccinj, hccall⟩ := levy_exists_allowed_sequenceCode hAC hG Pf hPf_check
  obtain ⟨ee, hee, heeinj, heeall⟩ := levy_exists_allowed_pairCode hG Pf hPf_check
  refine baireProperty_of_val Pf p hreal cc ee hcc hccinj hccall hee heeinj heeall ?_
  exact baireProperty_of_locallyDefinable hAC hU hc hω hG
    (hod_val_subset_cantorSpace hG Pf hreal hX)
    (hod_val_locallyDefinable hAC hU hc hω hκ hG Pf hconv X)

include hAC hU hc hω hκ hPf_check hreal hconv in
/-- The perfect set property in the class model (`lem:Solovay-regularity`, clause PSP), over a
arbitrary ground model. -/
theorem hod_perfectSetProperty {X : HODDom Pf p}
    (hX : X ⊆ cantorSpace (HODDom Pf p)) : PerfectSetProperty X := by
  obtain ⟨cc, hcc, hccinj, hccall⟩ := levy_exists_allowed_sequenceCode hAC hG Pf hPf_check
  obtain ⟨ee, hee, heeinj, heeall⟩ := levy_exists_allowed_pairCode hG Pf hPf_check
  refine perfectSetProperty_of_val Pf p hreal cc ee hcc hccinj hccall hee heeinj heeall
    (hod_val_subset_cantorSpace hG Pf hreal hX) ?_
  exact perfectSetProperty_of_locallyDefinable hAC hU hc hω hG
    (hod_val_subset_cantorSpace hG Pf hreal hX)
    (hod_val_locallyDefinable hAC hU hc hω hκ hG Pf hconv X)

include hAC hU hc hω hκ hconv in
/-- `lem:Solovay-measure`, dichotomy clause, for the subsets of `κ̌` lying in the class model:
each of them or its complement belongs to the filter generated by `U`. -/
theorem hod_solovayFilter_dichotomy {X : HODDom Pf p}
    (hX : X.val ⊆ (levyContext κ hG).check κ) :
    X.val ∈ (levyContext κ hG).derivedFilter κ U ∨
      relativeComplement ((levyContext κ hG).check κ) X.val ∈
        (levyContext κ hG).derivedFilter κ U :=
  solovayFilter_dichotomy_of_definable hAC hU hc hω hκ hG hX
    (hconv X.val (IsHOD.od Pf (hod_val_isHOD Pf p X)))

include hAC hU hc hω hκ hconv in
/-- `lem:Solovay-measure`, completeness clause, for the sequences lying in the class model: the
filter generated by `U` is closed under intersections of such sequences of length `< κ`. -/
theorem hod_solovayFilter_complete {δ : V} (hδ : δ ∈ κ) {g : HODDom Pf p}
    (hg : g.val ∈ (levyContext κ hG).derivedFilter κ U ^ (levyContext κ hG).check δ) :
    indexedIntersection ((levyContext κ hG).check κ) ((levyContext κ hG).check δ) g.val ∈
      (levyContext κ hG).derivedFilter κ U :=
  solovayFilter_complete_of_definable hAC hU hc hω hκ hG hδ hg
    (hconv g.val (IsHOD.od Pf (hod_val_isHOD Pf p g)))

end

end ZFVP
