import ZFVP.ModelTheory.SolovaySymmetricSubalgebraModel

/-! The support algebra read inside `RO(P)` is generated by explicit regular sets of `P`.

`supportAlgebraBase P R one K E` is defined in `ZFVP/ModelTheory/SolovaySymmetricSubalgebraModel.lean`
as the preimage, under the cone map `c b = coneRegular (booleanConditions P R) (booleanOrder P R) b`,
of the subalgebra of `RO(B)` generated by the Boolean values `‖ǩ ∈ σ‖` for `k ∈ K` and `σ ∈ E`.
That description is not in the shape the definability lemmas downstream want, which is a subalgebra
of `RO(P)` generated by a set of regular sets of `P`.

Here the two descriptions are matched. `supportValuesBase P R one K E` is the set of elements
`booleanValueBase P R (checkName one k) σ` of `RO(P)`, one for each `k ∈ K` and `σ ∈ E`, and

  `supportAlgebraBase P R one K E = generatedSubalgebra P R (supportValuesBase P R one K E)`.

The proof runs both inclusions off the minimality of `generatedSubalgebra`. One direction uses that
`supportAlgebraBase` is a complete subalgebra of `RO(P)` containing every base support value. The
other uses the image `algebraImage P R D` of a complete subalgebra `D` of `RO(P)` under the cone
map: it is a complete subalgebra of `RO(B)`, because the cone map takes the top to the top,
negations to negations and joins to joins, and it contains the support values, so it contains the
support algebra; the cone map is injective on regular sets of `P`, so a regular set whose cone lies
in the support algebra lies in `D`.

Zero elements need no separate treatment: `coneRegular_booleanValueBase_eq` gives the cone of a
Boolean value unconditionally, since an empty Boolean value has an empty set of conditions forcing
the membership. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-! ### Cones of regular sets: zero, top, injectivity -/

/-- The cone of a nonempty regular set contains the set itself. -/
theorem mem_coneRegular_self_boolean {P R b : V} (hR : IsForcingPreorder P R)
    (hb : IsForcingRegular P R b) (hne : ∃ p, p ∈ b) :
    b ∈ coneRegular (booleanConditions P R) (booleanOrder P R) b :=
  (mem_coneRegular_boolean_iff hR hb).mpr
    ⟨(mem_booleanConditions_iff _ _ _).mpr ⟨hb, hne⟩, subset_refl _⟩

/-- A regular set has an empty cone exactly when it is empty. -/
theorem coneRegular_eq_empty_iff {P R b : V} (hR : IsForcingPreorder P R)
    (hb : IsForcingRegular P R b) :
    coneRegular (booleanConditions P R) (booleanOrder P R) b = (∅ : V) ↔ b = (∅ : V) := by
  constructor
  · intro h
    by_contra hne
    have hne' : ∃ p, p ∈ b := by
      by_contra h'
      push Not at h'
      exact hne (mem_ext (fun z ↦ ⟨fun hz ↦ absurd hz (h' z), fun hz ↦ absurd hz not_mem_empty⟩))
    have := mem_coneRegular_self_boolean hR hb hne'
    rw [h] at this
    exact not_mem_empty this
  · rintro rfl
    exact coneRegular_empty_boolean hR

/-- The cone map is injective on regular sets of `P`. -/
theorem coneRegular_base_injective {P R b b' : V} (hR : IsForcingPreorder P R)
    (hb : IsForcingRegular P R b) (hb' : IsForcingRegular P R b')
    (h : coneRegular (booleanConditions P R) (booleanOrder P R) b =
      coneRegular (booleanConditions P R) (booleanOrder P R) b') : b = b' := by
  by_cases hne : ∃ p, p ∈ b
  · have hbB : b ∈ booleanConditions P R := (mem_booleanConditions_iff _ _ _).mpr ⟨hb, hne⟩
    have hne' : ∃ p, p ∈ b' := by
      by_contra h'
      push Not at h'
      have hb'0 : b' = (∅ : V) :=
        mem_ext (fun z ↦ ⟨fun hz ↦ absurd hz (h' z), fun hz ↦ absurd hz not_mem_empty⟩)
      have hc : coneRegular (booleanConditions P R) (booleanOrder P R) b = (∅ : V) := by
        rw [h, hb'0, coneRegular_empty_boolean hR]
      rw [(coneRegular_eq_empty_iff hR hb).mp hc] at hne
      obtain ⟨p, hp⟩ := hne
      exact not_mem_empty hp
    have hb'B : b' ∈ booleanConditions P R := (mem_booleanConditions_iff _ _ _).mpr ⟨hb', hne'⟩
    exact coneRegular_injective_of_separative (booleanOrder_poset P R)
      (booleanOrder_separative hR) hbB hb'B h
  · have hb0 : b = (∅ : V) := by
      push Not at hne
      exact mem_ext (fun z ↦ ⟨fun hz ↦ absurd hz (hne z), fun hz ↦ absurd hz not_mem_empty⟩)
    have hc : coneRegular (booleanConditions P R) (booleanOrder P R) b' = (∅ : V) := by
      rw [← h, hb0, coneRegular_empty_boolean hR]
    rw [hb0, (coneRegular_eq_empty_iff hR hb').mp hc]

/-- The cone of the top is the top of the completion. -/
theorem coneRegular_top_boolean {P R : V} (hR : IsForcingPreorder P R) :
    coneRegular (booleanConditions P R) (booleanOrder P R) P = booleanConditions P R := by
  apply mem_ext
  intro C
  rw [mem_coneRegular_boolean_iff hR (forcingRegular_top P R)]
  exact ⟨fun h ↦ h.1, fun h ↦ ⟨h, booleanConditions_subset h⟩⟩

/-- The cone of a Boolean value is the set of conditions of the completion forcing the membership,
with no nonemptiness hypothesis: an empty value comes from an empty set of such conditions. -/
theorem coneRegular_booleanValueBase_eq {P R : V} (hR : IsForcingPreorder P R) (ν μ : V) :
    coneRegular (booleanConditions P R) (booleanOrder P R) (booleanValueBase P R ν μ) =
      atomicMembership (booleanConditions P R) (booleanOrder P R) ν μ := by
  by_cases hne : ∃ p, p ∈ booleanValueBase P R ν μ
  · exact coneRegular_booleanValueBase hR hne
  · push Not at hne
    have hzero : booleanValueBase P R ν μ = (∅ : V) :=
      mem_ext (fun z ↦ ⟨fun hz ↦ absurd hz (hne z), fun hz ↦ absurd hz not_mem_empty⟩)
    have hatom : atomicMembership (booleanConditions P R) (booleanOrder P R) ν μ = (∅ : V) := by
      apply mem_ext
      intro C
      refine ⟨fun hC ↦ ?_, fun hC ↦ absurd hC not_mem_empty⟩
      obtain ⟨r, hr⟩ := booleanConditions_nonempty (atomicMembership_subset _ _ _ _ C hC)
      have := subset_booleanValueBase hR hC r hr
      rw [hzero] at this
      exact absurd this not_mem_empty
    rw [hzero, hatom, coneRegular_empty_boolean hR]

/-! ### The image of a complete subalgebra under the cone map -/

/-- The regular sets of the completion that are cones of elements of `D`. -/
noncomputable def algebraImage (P R D : V) : V :=
  {C ∈ regularSets (booleanConditions P R) (booleanOrder P R) ;
    ∃ b ∈ D, C = coneRegular (booleanConditions P R) (booleanOrder P R) b}

theorem mem_algebraImage_iff (P R D C : V) :
    C ∈ algebraImage P R D ↔
      IsForcingRegular (booleanConditions P R) (booleanOrder P R) C ∧
        ∃ b ∈ D, C = coneRegular (booleanConditions P R) (booleanOrder P R) b := by
  unfold algebraImage
  rw [mem_sep_iff, mem_regularSets_iff]

theorem coneRegular_mem_algebraImage {P R D b : V} (hb : b ∈ D) :
    coneRegular (booleanConditions P R) (booleanOrder P R) b ∈ algebraImage P R D :=
  (mem_algebraImage_iff _ _ _ _).mpr
    ⟨coneRegular_regular (booleanOrder_poset P R).1 b, b, hb, rfl⟩

/-- The image of a complete subalgebra of `RO(P)` under the cone map is a complete subalgebra
of `RO(B)`. -/
theorem isCompleteSubalgebra_algebraImage {P R D : V} (hR : IsForcingPreorder P R)
    (hD : IsCompleteSubalgebra P R D) :
    IsCompleteSubalgebra (booleanConditions P R) (booleanOrder P R) (algebraImage P R D) := by
  refine ⟨fun C hC ↦ (mem_sep_iff.mp hC).1, ?_, ?_, ?_⟩
  · rw [← coneRegular_top_boolean hR]
    exact coneRegular_mem_algebraImage hD.2.1
  · intro A hA
    obtain ⟨-, b, hb, rfl⟩ := (mem_algebraImage_iff _ _ _ _).mp hA
    rw [← coneRegular_forcingNegation hR (hD.regular hb)]
    exact coneRegular_mem_algebraImage (hD.2.2.1 b hb)
  · intro X hX
    have hpre : ∀ C, C ∈ sep D (fun b ↦
        coneRegular (booleanConditions P R) (booleanOrder P R) b ∈ X) (by definability) ↔
        C ∈ D ∧ coneRegular (booleanConditions P R) (booleanOrder P R) C ∈ X := fun _ ↦ mem_sep_iff
    set Y := sep D (fun b ↦ coneRegular (booleanConditions P R) (booleanOrder P R) b ∈ X)
      (by definability) with hYdef
    have hYD : Y ⊆ D := fun b hb ↦ ((hpre b).mp hb).1
    have hYreg : ∀ b ∈ Y, IsForcingRegular P R b := fun b hb ↦ hD.regular (hYD b hb)
    have hXY : ∀ C, C ∈ X ↔ ∃ b ∈ Y, C = coneRegular (booleanConditions P R) (booleanOrder P R) b := by
      intro C
      constructor
      · intro hC
        obtain ⟨-, b, hb, rfl⟩ := (mem_algebraImage_iff _ _ _ _).mp (hX C hC)
        exact ⟨b, (hpre b).mpr ⟨hb, hC⟩, rfl⟩
      · rintro ⟨b, hb, rfl⟩
        exact ((hpre b).mp hb).2
    rw [← coneRegular_regularJoin_eq hR hYreg hXY]
    exact coneRegular_mem_algebraImage (hD.2.2.2 Y hYD)

/-! ### The base support values -/

/-- The Boolean values `‖ǩ ∈ σ‖` for `k ∈ K` and `σ ∈ E`, read as elements of `RO(P)`. -/
noncomputable def supportValuesBase (P R one K E : V) : V :=
  repl (fun z ↦ booleanValueBase P R (checkName one (kpair.π₁ z)) (kpair.π₂ z))
    (by have := booleanValueBase_definable P R; definability) (K ×ˢ E)

theorem mem_supportValuesBase_iff (P R one K E b : V) :
    b ∈ supportValuesBase P R one K E ↔
      ∃ k ∈ K, ∃ σ ∈ E, b = booleanValueBase P R (checkName one k) σ := by
  unfold supportValuesBase
  rw [repl_spec]
  constructor
  · rintro ⟨z, hz, rfl⟩
    obtain ⟨k, hk, σ, hσ, rfl⟩ := mem_prod_iff.mp hz
    exact ⟨k, hk, σ, hσ, by rw [kpair.π₁_kpair, kpair.π₂_kpair]⟩
  · rintro ⟨k, hk, σ, hσ, rfl⟩
    refine ⟨⟨k, σ⟩ₖ, mem_prod_iff.mpr ⟨k, hk, σ, hσ, rfl⟩, ?_⟩
    rw [kpair.π₁_kpair, kpair.π₂_kpair]

theorem booleanValueBase_mem_supportValuesBase {P R one K E k σ : V} (hk : k ∈ K) (hσ : σ ∈ E) :
    booleanValueBase P R (checkName one k) σ ∈ supportValuesBase P R one K E :=
  (mem_supportValuesBase_iff _ _ _ _ _ _).mpr ⟨k, hk, σ, hσ, rfl⟩

theorem supportValuesBase_subset_regularSets {P R : V} (hR : IsForcingPreorder P R) (one K E : V) :
    supportValuesBase P R one K E ⊆ regularSets P R := by
  intro b hb
  obtain ⟨k, -, σ, -, rfl⟩ := (mem_supportValuesBase_iff _ _ _ _ _ _).mp hb
  exact (mem_regularSets_iff _ _ _).mpr (booleanValueBase_regular hR _ _)

/-- The cone of a base support value is the corresponding support value of the completion. -/
theorem coneRegular_supportValuesBase_mem {P R one K E k σ : V} (hk : k ∈ K) (hσ : σ ∈ E)
    (hR : IsForcingPreorder P R) :
    coneRegular (booleanConditions P R) (booleanOrder P R)
        (booleanValueBase P R (checkName one k) σ) ∈
      supportValues (booleanConditions P R) (booleanOrder P R) one K E := by
  rw [coneRegular_booleanValueBase_eq hR]
  exact atomicMembership_mem_supportValues hk hσ

theorem supportValuesBase_subset_supportAlgebraBase {P R : V} (hR : IsForcingPreorder P R)
    (one K E : V) : supportValuesBase P R one K E ⊆ supportAlgebraBase P R one K E := by
  intro b hb
  obtain ⟨k, hk, σ, hσ, rfl⟩ := (mem_supportValuesBase_iff _ _ _ _ _ _).mp hb
  exact booleanValueBase_mem_supportAlgebraBase hR
    (supportValues_subset_supportAlgebra _ _ _ _ _ _ (atomicMembership_mem_supportValues hk hσ))

/-! ### The support algebra as a generated subalgebra of `RO(P)` -/

/-- The support algebra, read inside `RO(P)`, is the complete subalgebra of `RO(P)` generated by
the base support values. -/
theorem supportAlgebraBase_eq_generatedSubalgebra {P R : V} (hR : IsForcingPreorder P R)
    (hP : ∃ p, p ∈ P) (one K E : V) :
    supportAlgebraBase P R one K E = generatedSubalgebra P R (supportValuesBase P R one K E) := by
  have hG : IsCompleteSubalgebra P R (generatedSubalgebra P R (supportValuesBase P R one K E)) :=
    generatedSubalgebra_complete hR (supportValuesBase_subset_regularSets hR one K E)
  apply SetTheory.subset_antisymm
  · -- an element whose cone is in the support algebra of the completion is in the generated algebra
    have hgen : supportValues (booleanConditions P R) (booleanOrder P R) one K E ⊆
        algebraImage P R (generatedSubalgebra P R (supportValuesBase P R one K E)) := by
      intro C hC
      obtain ⟨k, hk, σ, hσ, rfl⟩ := (mem_supportValues_iff _ _ _ _ _ _).mp hC
      rw [← coneRegular_booleanValueBase_eq hR]
      exact coneRegular_mem_algebraImage (subset_generatedSubalgebra _ _ _ _
        (booleanValueBase_mem_supportValuesBase hk hσ))
    have hmin : supportAlgebra (booleanConditions P R) (booleanOrder P R) one K E ⊆
        algebraImage P R (generatedSubalgebra P R (supportValuesBase P R one K E)) :=
      generatedSubalgebra_minimal (isCompleteSubalgebra_algebraImage hR hG) hgen
    intro b hb
    obtain ⟨hbreg, hbcone⟩ := (mem_algebraPreimage_iff _ _ _ _).mp hb
    obtain ⟨-, b', hb', hbb'⟩ := (mem_algebraImage_iff _ _ _ _).mp (hmin _ hbcone)
    have hb'reg : IsForcingRegular P R b' := hG.regular hb'
    rw [coneRegular_base_injective hR hbreg hb'reg hbb']
    exact hb'
  · exact generatedSubalgebra_minimal (isCompleteSubalgebra_supportAlgebraBase hR hP one K E)
      (supportValuesBase_subset_supportAlgebraBase hR one K E)

/-! ### Reindexing the base support values by `k × ω`

For `K = ω × ω` and an internally finite `E`, the base support values are the range of a ground
function whose domain is `k × ω` for a natural number `k`: the first coordinate enumerates `E`
through a finite sequence, the second runs over `ω` and is decoded to a pair of naturals by the
ground pairing code. This is the shape that
`ForcingContext.groundRealDefinable_of_inSubalgebraModel_finite_of_real` asks for. -/

/-- The pairs of naturals whose pairing code is `n`. -/
noncomputable def naturalPairFiber (n : V) : V :=
  {z ∈ (ω : V) ×ˢ (ω : V) ; naturalPairCode (kpair.π₁ z) (kpair.π₂ z) = n}

instance naturalPairFiber_definable : ℒₛₑₜ-function₁[V] naturalPairFiber := by
  have h : ℒₛₑₜ-relation (fun w n : V ↦ ∀ z, z ∈ w ↔ z ∈ (ω : V) ×ˢ (ω : V) ∧
      naturalPairCode (kpair.π₁ z) (kpair.π₂ z) = n) := by definability
  apply Language.Definable.of_iff h
  intro v
  change v 0 = naturalPairFiber (v 1) ↔ _
  rw [mem_ext_iff]
  simp only [naturalPairFiber, mem_sep_iff]

theorem mem_naturalPairFiber_iff (n z : V) :
    z ∈ naturalPairFiber n ↔ z ∈ (ω : V) ×ˢ (ω : V) ∧
      naturalPairCode (kpair.π₁ z) (kpair.π₂ z) = n := mem_sep_iff

/-- The pair of naturals whose pairing code is `n`. -/
noncomputable def naturalPairDecode (n : V) : V := ⋃ˢ naturalPairFiber n

instance naturalPairDecode_definable : ℒₛₑₜ-function₁[V] naturalPairDecode := by
  unfold naturalPairDecode
  definability

theorem naturalPairDecode_naturalPairCode {a b : V} (ha : a ∈ (ω : V)) (hb : b ∈ (ω : V)) :
    naturalPairDecode (naturalPairCode a b) = (⟨a, b⟩ₖ : V) := by
  have hsingle : naturalPairFiber (naturalPairCode a b) = ({⟨a, b⟩ₖ} : V) := by
    apply mem_ext
    intro z
    rw [mem_naturalPairFiber_iff, mem_singleton_iff]
    constructor
    · rintro ⟨hz, he⟩
      obtain ⟨u, hu, v, hv, rfl⟩ := mem_prod_iff.mp hz
      rw [kpair.π₁_kpair, kpair.π₂_kpair] at he
      obtain ⟨rfl, rfl⟩ := naturalPairCode_injective hu hv ha hb he
      rfl
    · rintro rfl
      exact ⟨mem_prod_iff.mpr ⟨a, ha, b, hb, rfl⟩, by rw [kpair.π₁_kpair, kpair.π₂_kpair]⟩
  unfold naturalPairDecode
  rw [hsingle, sUnion_singleton_eq]

theorem naturalPairDecode_mem {n : V} (hn : n ∈ (ω : V)) :
    naturalPairDecode n ∈ (ω : V) ×ˢ (ω : V) := by
  obtain ⟨a, ha, b, hb, rfl⟩ := exists_naturalPairCode hn
  rw [naturalPairDecode_naturalPairCode ha hb]
  exact mem_prod_iff.mpr ⟨a, ha, b, hb, rfl⟩

/-- For `K = ω × ω` and an internally finite `E`, the base support values are the range of a
function with domain `k × ω` for a natural number `k`. -/
theorem exists_indexed_supportValuesBase {P R : V} (hR : IsForcingPreorder P R) (one E : V)
    (hE : IsInternallyFinite E) :
    ∃ k S : V, k ⊆ (ω : V) ∧ S ∈ regularSets P R ^ (k ×ˢ (ω : V)) ∧
      range S = supportValuesBase P R one ((ω : V) ×ˢ (ω : V)) E := by
  obtain ⟨s, hs, hsr⟩ := exists_finiteSequence_range hE
  obtain ⟨hkω, hsf⟩ := (mem_finiteSequences_iff_domain E s).mp hs
  have : IsFunction s := IsFunction.of_mem hsf
  have hk : domain s ⊆ (ω : V) := IsOrdinal.toIsTransitive.transitive _ hkω
  have hF : ℒₛₑₜ-function₁ (fun z : V ↦ booleanValueBase P R
      (checkName one (naturalPairDecode (kpair.π₂ z))) (s ‘ (kpair.π₁ z))) := by
    have := booleanValueBase_definable P R
    definability
  refine ⟨domain s, definableGraph (domain s ×ˢ (ω : V)) _ hF, hk, ?_, ?_⟩
  · exact definableGraph_mem_function_of_mapsTo _ _ _ hF (fun z _ ↦
      (mem_regularSets_iff _ _ _).mpr (booleanValueBase_regular hR _ _))
  · rw [range_definableGraph]
    apply mem_ext
    intro y
    rw [repl_spec, mem_supportValuesBase_iff]
    constructor
    · rintro ⟨z, hz, rfl⟩
      obtain ⟨i, hi, n, hn, rfl⟩ := mem_prod_iff.mp hz
      refine ⟨naturalPairDecode n, naturalPairDecode_mem hn, s ‘ i, ?_, ?_⟩
      · rw [← hsr]
        exact mem_range_of_kpair_mem (kpair_value_mem hi)
      · simp only [kpair.π₁_kpair, kpair.π₂_kpair]
    · rintro ⟨c, hc, σ, hσ, rfl⟩
      obtain ⟨a, ha, b, hb, rfl⟩ := mem_prod_iff.mp hc
      obtain ⟨i, hiσ⟩ := mem_range_iff.mp (hsr ▸ hσ)
      have hi : i ∈ domain s := mem_domain_of_kpair_mem hiσ
      refine ⟨⟨i, naturalPairCode a b⟩ₖ, mem_prod_iff.mpr ⟨i, hi, naturalPairCode a b,
        naturalPairCode_natural ha hb, rfl⟩, ?_⟩
      simp only [kpair.π₁_kpair, kpair.π₂_kpair]
      rw [naturalPairDecode_naturalPairCode ha hb, value_eq_of_kpair_mem hiσ]

/-- The base support algebra of an internally finite set of names over `ω × ω` is generated by the
range of a function with domain `k × ω` for a natural number `k`. -/
theorem exists_supportAlgebraBase_eq_generatedSubalgebra_range {P R : V}
    (hR : IsForcingPreorder P R) (hP : ∃ p, p ∈ P) (one E : V) (hE : IsInternallyFinite E) :
    ∃ k S : V, k ⊆ (ω : V) ∧ S ∈ regularSets P R ^ (k ×ˢ (ω : V)) ∧
      supportAlgebraBase P R one ((ω : V) ×ˢ (ω : V)) E =
        generatedSubalgebra P R (range S) := by
  obtain ⟨k, S, hk, hS, hrange⟩ := exists_indexed_supportValuesBase hR one E hE
  refine ⟨k, S, hk, hS, ?_⟩
  rw [hrange]
  exact supportAlgebraBase_eq_generatedSubalgebra hR hP one _ E

end ZFVP
