import ZFVP.ModelTheory.SolovayHODRegularity
import ZFVP.ModelTheory.SolovayHODOmegaOne

/-! The trace on the class model `Sol = HOD_{V ∪ R}^{V[G]}` of the filter generated by a ground
model measure `U` on `κ`, and the proof that it is an ultrafilter of `Sol`
(lemma `Solovay-measure`).

The trace is built inside the class model as the separated subset
`{X ∈ ℘ κ̌ ; ∃ Y ∈ Ǔ, Y ⊆ X}`, so it is an element of the class model by construction. Its `val` in
the Levy extension is the set of all `X ⊆ κ̌` that are hereditarily ordinal definable over the
parameter class of `Pf` and contain a member of `Ǔ`, and membership in it is equivalent to
membership in the filter `derivedFilter κ U` of the extension. Through that equivalence the six
filter clauses, nonprincipality and `κ̌`-completeness inside the class model reduce to the
corresponding facts about `derivedFilter κ U`, proved in `SolovayMeasure` and
`SolovayHODRegularity`. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

section transport

variable (Pf : SetTheorySemisentence 2) (p : V)
  [Nonempty (HODDom Pf p)] [(HODDom Pf p)↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-- Binary intersection commutes with the inclusion of the class model. -/
theorem val_inter (X Y : HODDom Pf p) : (X ∩ Y).val = X.val ∩ Y.val :=
  (hodInclusion Pf p).map_inter X Y

/-- Singletons commute with the inclusion of the class model. -/
theorem val_singleton (x : HODDom Pf p) : ({x} : HODDom Pf p).val = ({x.val} : V) :=
  (hodInclusion Pf p).map_singleton x

/-- Relative complements commute with the inclusion of the class model. -/
theorem val_relativeComplement (K X : HODDom Pf p) :
    (relativeComplement K X).val = relativeComplement K.val X.val := by
  have h := (hodInclusion Pf p).map_separation K (fun z ↦ z ∉ X) (fun z ↦ z ∉ X.val)
    (by definability) (by definability)
    (fun z _ ↦ not_congr (mem_val_iff Pf p z X).symm)
  unfold relativeComplement
  exact h

/-- Intersections of an indexed family commute with the inclusion of the class model. -/
theorem val_indexedIntersection (K I : HODDom Pf p) {g : HODDom Pf p} [IsFunction g]
    (hdom : domain g = I) :
    (indexedIntersection K I g).val = indexedIntersection K.val I.val g.val := by
  apply mem_ext
  intro y
  rw [mem_indexedIntersection_iff]
  constructor
  · intro hy
    obtain ⟨w, hw, rfl⟩ := exists_val_of_mem Pf p hy
    rw [mem_indexedIntersection_iff] at hw
    refine ⟨(mem_val_iff Pf p w K).mpr hw.1, fun i hi ↦ ?_⟩
    obtain ⟨i', hi', rfl⟩ := exists_val_of_mem Pf p hi
    rw [← val_value Pf p g i' (by rw [hdom]; exact hi')]
    exact hw.2 i' hi'
  · rintro ⟨hyK, hyI⟩
    obtain ⟨w, hw, rfl⟩ := exists_val_of_mem Pf p hyK
    refine (mem_val_iff Pf p w _).mpr ?_
    rw [mem_indexedIntersection_iff]
    refine ⟨hw, fun i hi ↦ ?_⟩
    have h := hyI i.val ((mem_val_iff Pf p i I).mpr hi)
    rwa [← val_value Pf p g i (by rw [hdom]; exact hi)] at h

end transport

section

variable {κ : V} [IsOrdinal κ]
  {G : Set V} (hG : IsExternalForcingGeneric (levyCollapse κ) (levyOrder κ) G)
  (Pf : SetTheorySemisentence 2) {p : (levyContext κ hG).Model}
  (hPf_check : ∀ a : V, Pf.Evalb ![(levyContext κ hG).check a, p])
  (hPf_real : ∀ c : (levyContext κ hG).Model,
    c ⊆ (levyContext κ hG).check (ω : V) → Pf.Evalb ![c, p])
  [Nonempty (HODDom Pf p)] [(HODDom Pf p)↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-- A ground set, viewed as an element of the class model inside the Levy extension. -/
noncomputable def hodCheck (a : V) : HODDom Pf p :=
  toHOD Pf p (hod_check_isHOD hG Pf hPf_check hPf_real a)

@[simp] theorem hodCheck_val (a : V) :
    (hodCheck hG Pf hPf_check hPf_real a).val = (levyContext κ hG).check a := rfl

variable (U : V)

omit [IsOrdinal κ] in
/-- Unfolding of the filter generated by `U`, as a separated subset of `℘ κ̌`. -/
theorem mem_derivedFilter_iff' (X : (levyContext κ hG).Model) :
    X ∈ (levyContext κ hG).derivedFilter κ U ↔
      X ⊆ (levyContext κ hG).check κ ∧ ∃ Y ∈ (levyContext κ hG).check U, Y ⊆ X := by
  unfold ForcingContext.derivedFilter
  rw [mem_sep_iff, mem_power_iff]

/-- The trace `U*` of the filter generated by `U` on the class model: the subsets of `κ̌` lying in
the class model that contain a member of `Ǔ`. It is an element of the class model because it is
formed by separation inside the class model. -/
noncomputable def solovayTrace : HODDom Pf p :=
  sep (℘ (hodCheck hG Pf hPf_check hPf_real κ))
    (fun X ↦ ∃ Y ∈ hodCheck hG Pf hPf_check hPf_real U, Y ⊆ X)

/-- Membership in the trace, stated inside the class model. -/
theorem mem_solovayTrace_iff (X : HODDom Pf p) :
    X ∈ solovayTrace hG Pf hPf_check hPf_real U ↔
      X ⊆ hodCheck hG Pf hPf_check hPf_real κ ∧
        ∃ Y ∈ hodCheck hG Pf hPf_check hPf_real U, Y ⊆ X := by
  unfold solovayTrace
  rw [mem_sep_iff, mem_power_iff]

/-- Membership in the trace is membership of the underlying set in the filter generated by `U`. -/
theorem mem_solovayTrace_iff_val (X : HODDom Pf p) :
    X ∈ solovayTrace hG Pf hPf_check hPf_real U ↔
      X.val ∈ (levyContext κ hG).derivedFilter κ U := by
  rw [mem_solovayTrace_iff, mem_derivedFilter_iff']
  constructor
  · rintro ⟨hsub, Y, hY, hYX⟩
    exact ⟨(subset_val_iff Pf p _ _).mpr hsub, Y.val,
      (mem_val_iff Pf p Y _).mpr hY, (subset_val_iff Pf p _ _).mpr hYX⟩
  · rintro ⟨hsub, y, hy, hyX⟩
    obtain ⟨y₀, hy₀, rfl⟩ := ((levyContext κ hG).mem_check_iff U y).mp hy
    refine ⟨(subset_val_iff Pf p _ _).mp hsub, hodCheck hG Pf hPf_check hPf_real y₀, ?_, ?_⟩
    · exact (mem_val_iff Pf p _ _).mp (((levyContext κ hG).check_mem_iff y₀ U).mpr hy₀)
    · exact (subset_val_iff Pf p _ _).mp hyX

/-- The elements of the trace are exactly the members of the filter generated by `U` that lie in
the class model. -/
theorem mem_solovayTrace_val_iff (y : (levyContext κ hG).Model) :
    y ∈ (solovayTrace hG Pf hPf_check hPf_real U).val ↔
      IsHOD Pf y p ∧ y ∈ (levyContext κ hG).derivedFilter κ U := by
  constructor
  · intro hy
    obtain ⟨Y, hY, rfl⟩ := exists_val_of_mem Pf p hy
    exact ⟨hod_val_isHOD Pf p Y, (mem_solovayTrace_iff_val hG Pf hPf_check hPf_real U Y).mp hY⟩
  · rintro ⟨hHOD, hdF⟩
    have h : toHOD Pf p hHOD ∈ solovayTrace hG Pf hPf_check hPf_real U :=
      (mem_solovayTrace_iff_val hG Pf hPf_check hPf_real U (toHOD Pf p hHOD)).mpr hdF
    exact (mem_val_iff Pf p _ _).mpr h

omit [IsOrdinal κ] [Nonempty (HODDom Pf p)] [(HODDom Pf p)↓[ℒₛₑₜ] ⊧* 𝗭𝗙] in
/-- The defining predicate of the trace, read in the Levy extension, is first order over the
parameters `Ǔ` and `p`. -/
theorem solovayTracePredicate_definable :
    ℒₛₑₜ-predicate (fun X : (levyContext κ hG).Model ↦
      IsHOD Pf X p ∧ ∃ Y ∈ (levyContext κ hG).check U, Y ⊆ X) :=
  Language.Definable.and (isHOD_definable Pf p) (by definability)

/-- The trace, computed in the Levy extension: the subsets of `κ̌` that are hereditarily ordinal
definable over the parameter class of `Pf` and contain a member of `Ǔ`. -/
theorem solovayTrace_val_eq :
    (solovayTrace hG Pf hPf_check hPf_real U).val =
      sep (℘ ((levyContext κ hG).check κ))
        (fun X ↦ IsHOD Pf X p ∧ ∃ Y ∈ (levyContext κ hG).check U, Y ⊆ X)
        (solovayTracePredicate_definable hG Pf U) := by
  apply mem_ext
  intro y
  rw [mem_solovayTrace_val_iff, mem_sep_iff, mem_power_iff, mem_derivedFilter_iff']
  constructor
  · rintro ⟨hHOD, hsub, hY⟩
    exact ⟨hsub, hHOD, hY⟩
  · rintro ⟨hsub, hHOD, hY⟩
    exact ⟨hHOD, hsub, hY⟩

include hPf_check hPf_real in
/-- The trace is hereditarily ordinal definable over the parameter class of `Pf`, so it is an
element of the class model. -/
theorem isHOD_solovayTrace :
    IsHOD Pf (sep (℘ ((levyContext κ hG).check κ))
      (fun X ↦ IsHOD Pf X p ∧ ∃ Y ∈ (levyContext κ hG).check U, Y ⊆ X)
      (solovayTracePredicate_definable hG Pf U)) p := by
  rw [← solovayTrace_val_eq hG Pf hPf_check hPf_real U]
  exact hod_val_isHOD Pf p _

section clauses

variable (hAC : InternalChoice V) (hU : IsNonprincipalSetUltrafilter κ U)
  (hc : IsOrdinalComplete κ U) (hω : (ω : V) ∈ κ) (hκ : IsInitialOrdinal κ)
  (hconv : ∀ x : (levyContext κ hG).Model, IsOD Pf x p →
    (levyContext κ hG).IsGroundRealDefinable x)

include hU in
/-- The trace is a filter on `κ̌` inside the class model: it consists of subsets of `κ̌`, contains
`κ̌`, omits the empty set, and is closed upwards and under binary intersections. -/
theorem hod_solovayTrace_filter :
    solovayTrace hG Pf hPf_check hPf_real U ⊆ ℘ (hodCheck hG Pf hPf_check hPf_real κ) ∧
    hodCheck hG Pf hPf_check hPf_real κ ∈ solovayTrace hG Pf hPf_check hPf_real U ∧
    (∅ : HODDom Pf p) ∉ solovayTrace hG Pf hPf_check hPf_real U ∧
    (∀ X ∈ solovayTrace hG Pf hPf_check hPf_real U, ∀ Y,
      Y ⊆ hodCheck hG Pf hPf_check hPf_real κ → X ⊆ Y →
        Y ∈ solovayTrace hG Pf hPf_check hPf_real U) ∧
    ∀ X ∈ solovayTrace hG Pf hPf_check hPf_real U,
      ∀ Y ∈ solovayTrace hG Pf hPf_check hPf_real U,
        X ∩ Y ∈ solovayTrace hG Pf hPf_check hPf_real U := by
  obtain ⟨-, hκmem, hempty, -, hinter⟩ := solovayFilter_filter hG hU
  refine ⟨fun X hX ↦ mem_power_iff.mpr
      ((mem_solovayTrace_iff hG Pf hPf_check hPf_real U X).mp hX).1, ?_, ?_, ?_, ?_⟩
  · exact (mem_solovayTrace_iff_val hG Pf hPf_check hPf_real U _).mpr hκmem
  · intro h
    have h' := (mem_solovayTrace_iff_val hG Pf hPf_check hPf_real U _).mp h
    rw [val_empty Pf p] at h'
    exact hempty h'
  · intro X hX Y hYκ hXY
    obtain ⟨-, Z, hZ, hZX⟩ := (mem_solovayTrace_iff hG Pf hPf_check hPf_real U X).mp hX
    exact (mem_solovayTrace_iff hG Pf hPf_check hPf_real U Y).mpr
      ⟨hYκ, Z, hZ, subset_trans hZX hXY⟩
  · intro X hX Y hY
    refine (mem_solovayTrace_iff_val hG Pf hPf_check hPf_real U _).mpr ?_
    rw [val_inter Pf p]
    exact hinter _ ((mem_solovayTrace_iff_val hG Pf hPf_check hPf_real U X).mp hX) _
      ((mem_solovayTrace_iff_val hG Pf hPf_check hPf_real U Y).mp hY)

include hU in
/-- The trace is nonprincipal inside the class model. -/
theorem hod_solovayTrace_nonprincipal :
    ∀ x ∈ hodCheck hG Pf hPf_check hPf_real κ,
      ({x} : HODDom Pf p) ∉ solovayTrace hG Pf hPf_check hPf_real U := by
  intro x hx h
  have h' := (mem_solovayTrace_iff_val hG Pf hPf_check hPf_real U _).mp h
  rw [val_singleton Pf p] at h'
  exact solovayFilter_nonprincipal hG hU x.val ((mem_val_iff Pf p x _).mpr hx) h'

include hAC hU hc hω hκ hconv in
/-- Every subset of `κ̌` lying in the class model, or its relative complement, belongs to the
trace. -/
theorem hod_solovayTrace_dichotomy (X : HODDom Pf p)
    (hX : X ⊆ hodCheck hG Pf hPf_check hPf_real κ) :
    X ∈ solovayTrace hG Pf hPf_check hPf_real U ∨
      relativeComplement (hodCheck hG Pf hPf_check hPf_real κ) X ∈
        solovayTrace hG Pf hPf_check hPf_real U := by
  have hXv : X.val ⊆ (levyContext κ hG).check κ := (subset_val_iff Pf p _ _).mpr hX
  rcases hod_solovayFilter_dichotomy hAC hU hc hω hκ hG Pf hconv hXv with h | h
  · exact Or.inl ((mem_solovayTrace_iff_val hG Pf hPf_check hPf_real U X).mpr h)
  · refine Or.inr ((mem_solovayTrace_iff_val hG Pf hPf_check hPf_real U _).mpr ?_)
    rw [val_relativeComplement Pf p]
    exact h

include hAC hU hc hω hκ hconv in
/-- The trace is `κ̌`-complete inside the class model: it is closed under intersections of its own
sequences of length below `κ̌`. -/
theorem hod_solovayTrace_complete (α : HODDom Pf p)
    (hα : α ∈ hodCheck hG Pf hPf_check hPf_real κ) (g : HODDom Pf p)
    (hg : g ∈ solovayTrace hG Pf hPf_check hPf_real U ^ α) :
    indexedIntersection (hodCheck hG Pf hPf_check hPf_real κ) α g ∈
      solovayTrace hG Pf hPf_check hPf_real U := by
  obtain ⟨δ, hδ, hδv⟩ := ((levyContext κ hG).mem_check_iff κ α.val).mp
    ((mem_val_iff Pf p α _).mpr hα)
  have hgf : IsFunction g := IsFunction.of_mem hg
  have hgdom : domain g = α := domain_eq_of_mem_function hg
  have hgval : g.val ∈ (solovayTrace hG Pf hPf_check hPf_real U).val ^ α.val :=
    (mem_function_val Pf p g α _).mp hg
  have hsub : (solovayTrace hG Pf hPf_check hPf_real U).val ⊆
      (levyContext κ hG).derivedFilter κ U := by
    intro y hy
    exact ((mem_solovayTrace_val_iff hG Pf hPf_check hPf_real U y).mp hy).2
  have hgval' : g.val ∈ (levyContext κ hG).derivedFilter κ U ^ (levyContext κ hG).check δ := by
    rw [← hδv]
    exact mem_function_of_mem_function_of_subset hgval hsub
  have hres := hod_solovayFilter_complete hAC hU hc hω hκ hG Pf hconv hδ hgval'
  refine (mem_solovayTrace_iff_val hG Pf hPf_check hPf_real U _).mpr ?_
  rw [val_indexedIntersection Pf p _ _ hgdom, hodCheck_val, hδv]
  exact hres

include hAC hU hc hω hκ hconv in
/-- Lemma `Solovay-measure`: the trace of the filter generated by `U` is a nonprincipal
`κ̌`-complete ultrafilter on `κ̌` inside the class model `Sol`. -/
theorem hod_solovayTrace_nonprincipalSetUltrafilter :
    IsNonprincipalSetUltrafilter (hodCheck hG Pf hPf_check hPf_real κ)
        (solovayTrace hG Pf hPf_check hPf_real U) ∧
      IsOrdinalComplete (hodCheck hG Pf hPf_check hPf_real κ)
        (solovayTrace hG Pf hPf_check hPf_real U) := by
  obtain ⟨h1, h2, h3, h4, h5⟩ := hod_solovayTrace_filter hG Pf hPf_check hPf_real U hU
  refine ⟨⟨⟨h1, h2, h3, h4, h5, ?_⟩,
    hod_solovayTrace_nonprincipal hG Pf hPf_check hPf_real U hU⟩, ?_⟩
  · intro X hX
    exact hod_solovayTrace_dichotomy hG Pf hPf_check hPf_real U hAC hU hc hω hκ hconv X hX
  · intro α hα g hg
    exact hod_solovayTrace_complete hG Pf hPf_check hPf_real U hAC hU hc hω hκ hconv α hα g hg

end clauses

end

end ZFVP
