import ZFVP.ModelTheory.LevyAbsorptionModel
import ZFVP.SetTheory.EndExtensionLevyColumns
import ZFVP.ModelTheory.ForcingBaseChange
import ZFVP.ModelTheory.LevyProductEquivalence
import ZFVP.ModelTheory.QuotientEquivalence
import ZFVP.ModelTheory.ForcingChoice
import ZFVP.SetTheory.MeasurableStrongLimit
import ZFVP.ModelTheory.GroundRealsHOD

/-! Solovay's factor lemma, model form: for `β < κ` and a complete subalgebra `D` of the Boolean
completion of `Coll(ω, <β)` (in the application, the subalgebra generated by a real), the Levy
extension `V[G]` is an extension of the intermediate model `V[G_β ∩ D]` by the checked upper
collapse `Coll(ω, [β, κ))`, compatibly with membership and checks. The chain composes the product
lemma, the quotient factorization, base change, the converse product lemma, and absorption of the
quotient (of size below `κ`) into a column of the upper collapse. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V W : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]
  [SetStructure W] [Nonempty W] [W↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

theorem MembershipEndExtension.map_forcingTop (j : MembershipEndExtension V W) {P R one : V}
    (h : IsForcingTop P R one) : IsForcingTop (j P) (j R) (j one) := by
  refine ⟨(j.mem_iff _ _).mpr h.1, fun p hp ↦ ?_⟩
  obtain ⟨p₀, hp₀, rfl⟩ := j.endExtension P p hp
  rw [← j.map_kpair, j.mem_iff]
  exact h.2 p₀ hp₀

theorem restrictedOrder_reverseInclusion {P Q : V} (hQ : Q ⊆ P) :
    restrictedOrder (reverseInclusionOrder P) Q = reverseInclusionOrder Q := by
  apply mem_ext
  intro z
  unfold restrictedOrder reverseInclusionOrder
  rw [mem_inter_iff, mem_sep_iff, mem_sep_iff]
  constructor
  · rintro ⟨⟨_, h⟩, hz⟩
    exact ⟨hz, h⟩
  · rintro ⟨hz, h⟩
    exact ⟨⟨prod_subset_prod_of_subset hQ hQ z hz, h⟩, hz⟩

theorem levyAbove_top (κ β : V) :
    IsForcingTop (levyCollapseAbove κ β) (restrictedOrder (levyOrder κ) (levyCollapseAbove κ β)) ∅ := by
  refine ⟨empty_mem_levyCollapseAbove κ β, fun p hp ↦ ?_⟩
  refine (kpair_mem_restrictedOrder_iff _ _ _ _).mpr ⟨?_, hp, empty_mem_levyCollapseAbove κ β⟩
  exact (pair_mem_reverseInclusionOrder _ _ _).mpr ⟨levyCollapseAbove_subset κ β p hp, empty_mem_levyCollapse κ,
    fun z hz ↦ (not_mem_empty hz).elim⟩

theorem upperOrder_eq_levyColumnsOrder (κ β : V) :
    restrictedOrder (levyOrder κ) (levyCollapseAbove κ β) = levyColumnsOrder κ (κ \ β) := by
  unfold levyOrder levyColumnsOrder
  rw [levyCollapseAbove_eq_levyColumns]
  exact restrictedOrder_reverseInclusion (levyColumns_subset κ _)

section

variable {κ U : V} [IsOrdinal κ] (hAC : InternalChoice V)
  (hU : IsNonprincipalSetUltrafilter κ U) (hc : IsOrdinalComplete κ U)
  (hω : (ω : V) ∈ κ) (hκ : IsInitialOrdinal κ)
  {G : Set V} (hG : IsExternalForcingGeneric (levyCollapse κ) (levyOrder κ) G)
  (β : V) [IsOrdinal β] (hβ : β ∈ κ)

include hAC hU hc hω hκ in
/-- Solovay's factor lemma: `V[G]` is an extension of `V[G_β ∩ D]` by the checked upper collapse. -/
theorem solovay_factor {D : V}
    (hD : IsCompleteSubalgebra (levySubContext β (IsOrdinal.toIsTransitive.transitive _ hβ) hG).P
      (levySubContext β (IsOrdinal.toIsTransitive.transitive _ hβ) hG).R D) :
    ∃ Z : ForcingContext ((levySubContext β (IsOrdinal.toIsTransitive.transitive _ hβ) hG).subalgebraContext hD).Model,
      Z.P = ((levySubContext β (IsOrdinal.toIsTransitive.transitive _ hβ) hG).subalgebraContext hD).check
          (levyCollapseAbove κ β) ∧
      Z.R = ((levySubContext β (IsOrdinal.toIsTransitive.transitive _ hβ) hG).subalgebraContext hD).check
          (restrictedOrder (levyOrder κ) (levyCollapseAbove κ β)) ∧
      Z.one = ((levySubContext β (IsOrdinal.toIsTransitive.transitive _ hβ) hG).subalgebraContext hD).check ∅ ∧
      ∃ f : (levyContext κ hG).Model ≃ Z.Model, (∀ x y, (f x ∈ f y ↔ x ∈ y)) ∧
        (∀ a : V, f ((levyContext κ hG).check a) =
          Z.check (((levySubContext β (IsOrdinal.toIsTransitive.transitive _ hβ) hG).subalgebraContext hD).check a)) ∧
        ∀ y : ((levySubContext β (IsOrdinal.toIsTransitive.transitive _ hβ) hG).subalgebraContext hD).Model,
          f ((levyProductEquiv β (IsOrdinal.toIsTransitive.transitive _ hβ) hG).symm
            ((levyProductContext β (IsOrdinal.toIsTransitive.transitive _ hβ) hG).check
              (((levySubContext β (IsOrdinal.toIsTransitive.transitive _ hβ) hG).booleanEquiv.trans
                ((levySubContext β (IsOrdinal.toIsTransitive.transitive _ hβ) hG).quotientEquiv hD)).symm
                (((levySubContext β (IsOrdinal.toIsTransitive.transitive _ hβ) hG).quotientContext hD).check y)))) =
            Z.check y := by
  have hβ' : β ⊆ κ := IsOrdinal.toIsTransitive.transitive _ hβ
  set A := levySubContext β hβ' hG with hAdef
  set N := A.subalgebraContext hD with hNdef
  set C := A.quotientContext hD with hCdef
  set Qup := levyProductContext β hβ' hG with hQdef
  -- the intermediate model `V[G_β]` as an extension of `V[G_β ∩ D]`
  let e : A.Model ≃ C.Model := A.booleanEquiv.trans (A.quotientEquiv hD)
  have he : ∀ x y, (e x ∈ e y ↔ x ∈ y) := by
    intro x y
    simp only [e, Equiv.trans_apply]
    rw [A.quotientEquiv_mem_iff, A.booleanEquiv_mem_iff]
  have hecheck : ∀ x, e (A.check x) = C.check (N.check x) := by
    intro x
    simp only [e, Equiv.trans_apply]
    rw [A.booleanEquiv_check, A.quotientEquiv_check]
  -- base change of the upper collapse
  let Q' := Qup.baseChange e he
  have hQP : Q'.P = C.check (N.check (levyCollapseAbove κ β)) := hecheck _
  have hres : restrictedOrder (A.check (levyOrder κ)) (A.check (levyCollapseAbove κ β)) =
      A.check (restrictedOrder (levyOrder κ) (levyCollapseAbove κ β)) :=
    (A.checkEmbedding.map_restrictedOrder _ _).symm
  have hQR : Q'.R = C.check (N.check (restrictedOrder (levyOrder κ) (levyCollapseAbove κ β))) := by
    change e (restrictedOrder (A.check (levyOrder κ)) (A.check (levyCollapseAbove κ β))) = _
    rw [hres]
    exact hecheck _
  have hQone : Q'.one = C.check (N.check ∅) := hecheck _
  -- the two-step extension is a product extension over `V[G_β ∩ D]`
  have hAbove_pre : IsForcingPreorder (levyCollapseAbove κ β) (restrictedOrder (levyOrder κ) (levyCollapseAbove κ β)) :=
    restrictedOrder_preorder (levyCollapse_poset κ).1 (levyCollapseAbove_subset κ β)
  have h₂ : IsForcingPreorder (N.check (levyCollapseAbove κ β))
      (N.check (restrictedOrder (levyOrder κ) (levyCollapseAbove κ β))) :=
    N.checkEmbedding.map_forcingPreorder hAbove_pre
  have t₂ : IsForcingTop (N.check (levyCollapseAbove κ β))
      (N.check (restrictedOrder (levyOrder κ) (levyCollapseAbove κ β))) (N.check ∅) :=
    N.checkEmbedding.map_forcingTop (levyAbove_top κ β)
  let X := productContext C.order C.top h₂ t₂ (combinedGeneric_generic C Q' hQP hQR)
  let f₂ := twoStepEquiv C h₂ t₂ Q' hQP hQR hQone
  -- absorption inside `V[G_β ∩ D]`
  have hACN : InternalChoice N.Model := N.internalChoice_of_ground hAC
  haveI : IsOrdinal (N.check κ) := (N.check_ordinal_iff κ).mpr inferInstance
  obtain ⟨ν, hν, hsmall⟩ := levyBooleanConditions_small hAC hU hc hω hκ hβ
  have : IsOrdinal ν := IsOrdinal.of_mem hν
  have hβν : IsOrdinal (β ∪ ν) := ordinal_union_isOrdinal β ν
  have hlam0 : IsOrdinal ((β ∪ ν) ∪ (ω : V)) := ordinal_union_isOrdinal _ _
  have hlam0kappa : (β ∪ ν) ∪ (ω : V) ∈ κ := union_mem_of_ordinals (union_mem_of_ordinals hβ hν) hω
  have hbetalam : β ⊆ (β ∪ ν) ∪ (ω : V) := fun z hz ↦ mem_union_iff.mpr (Or.inl (mem_union_iff.mpr (Or.inl hz)))
  have hnulam : ν ⊆ (β ∪ ν) ∪ (ω : V) := fun z hz ↦ mem_union_iff.mpr (Or.inl (mem_union_iff.mpr (Or.inr hz)))
  have homegalam : (ω : V) ⊆ (β ∪ ν) ∪ (ω : V) := subset_union_right _ _
  have hlam0beta : (β ∪ ν) ∪ (ω : V) ∉ β := fun h ↦ mem_irrefl _ (hbetalam _ h)
  have hlam : N.check ((β ∪ ν) ∪ (ω : V)) ∈ N.check κ := (N.check_mem_iff _ _).mpr hlam0kappa
  have hlamC : N.check ((β ∪ ν) ∪ (ω : V)) ∈ N.check (κ \ β) :=
    (N.check_mem_iff _ _).mpr (mem_sdiff_iff.mpr ⟨hlam0kappa, hlam0beta⟩)
  have hωlam : (ω : N.Model) ⊆ N.check ((β ∪ ν) ∪ (ω : V)) := by
    rw [← ForcingContext.check_omega_eq]
    exact (N.checkEmbedding.subset_iff _ _).mpr homegalam
  have hQ : C.P ≤# N.check ((β ∪ ν) ∪ (ω : V)) := by
    have h1 : C.P ⊆ N.check (booleanConditions (levyCollapse β) (levyOrder β)) := A.quotientConditions_subset hD
    have h2 : N.check (booleanConditions (levyCollapse β) (levyOrder β)) ≤# N.check ν :=
      N.checkEmbedding.map_cardLE hsmall
    exact (cardLE_of_subset h1).trans (h2.trans (cardLE_of_subset ((N.checkEmbedding.subset_iff _ _).mpr hnulam)))
  have hcols : N.check (levyCollapseAbove κ β) = levyColumns (N.check κ) (N.check (κ \ β)) := by
    rw [levyCollapseAbove_eq_levyColumns]
    exact N.checkEmbedding.map_levyColumns κ (κ \ β)
  have hcolsOrder : N.check (restrictedOrder (levyOrder κ) (levyCollapseAbove κ β)) =
      levyColumnsOrder (N.check κ) (N.check (κ \ β)) := by
    rw [upperOrder_eq_levyColumnsOrder]
    exact N.checkEmbedding.map_levyColumnsOrder κ (κ \ β)
  have hXP : X.P = C.P ×ˢ levyColumns (N.check κ) (N.check (κ \ β)) := by
    change C.P ×ˢ N.check (levyCollapseAbove κ β) = _
    rw [hcols]
  have hXR : X.R = productOrder C.P C.R (levyColumns (N.check κ) (N.check (κ \ β)))
      (levyColumnsOrder (N.check κ) (N.check (κ \ β))) := by
    change productOrder C.P C.R (N.check (levyCollapseAbove κ β))
      (N.check (restrictedOrder (levyOrder κ) (levyCollapseAbove κ β))) = _
    rw [hcols, hcolsOrder]
  obtain ⟨Z, hZP, hZR, hZone, f₃, hf₃mem, hf₃check⟩ :=
    exists_columns_context hACN hlam hlamC hωlam C.order C.top hQ X hXP hXR
  refine ⟨Z, by rw [hZP, hcols], by rw [hZR, hcolsOrder], by rw [hZone, N.check_empty], ?_⟩
  let f₁ := (levyProductEquiv β hβ' hG).trans (Qup.baseChangeEquiv e he)
  refine ⟨(f₁.trans f₂.symm).trans f₃, ?_, ?_, ?_⟩
  · intro x y
    simp only [f₁, Equiv.trans_apply]
    rw [hf₃mem, ← twoStepEquiv_mem_iff C h₂ t₂ Q' hQP hQR hQone, Equiv.apply_symm_apply, Equiv.apply_symm_apply,
      Qup.baseChangeEquiv_mem_iff, levyProductEquiv_mem_iff]
  · intro a
    simp only [f₁, Equiv.trans_apply]
    rw [levyProductEquiv_check, Qup.baseChangeEquiv_check, hecheck, ← twoStepEquiv_check C h₂ t₂ Q' hQP hQR hQone,
      Equiv.symm_apply_apply]
    exact hf₃check _
  · intro y
    simp only [f₁, Equiv.trans_apply]
    rw [Equiv.apply_symm_apply, Qup.baseChangeEquiv_check, Equiv.apply_symm_apply,
      ← twoStepEquiv_check C h₂ t₂ Q' hQP hQR hQone, Equiv.symm_apply_apply]
    exact hf₃check y

end

end ZFVP
