import ZFVP.ModelTheory.GeneratedSubalgebra
import ZFVP.SetTheory.ForcingConditionAction
import ZFVP.SetTheory.SymmetricSystems

/-! An automorphism of a forcing preorder acts on subsets of the poset by taking images. The
action commutes with forcing negation and with regular joins, so an automorphism that fixes every
generator as a set fixes the whole complete subalgebra generated by those generators. The
automorphisms of a group `Γ` fixing a set `S` of regular sets form a subgroup, and every member of
that subgroup fixes `generatedSubalgebra P R S` elementwise. This is Lemma 9.3 of
Karagila-Schilhan in the form the symmetric-extension arguments need. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

/-! ### The image action of an automorphism on a set of conditions -/

/-- The pointwise image of `A` under the function `π`. -/
noncomputable def imageAction (π A : V) : V := repl (fun p ↦ π ‘ p) (by definability) A

theorem mem_imageAction_iff (π A x : V) : x ∈ imageAction π A ↔ ∃ p ∈ A, x = π ‘ p :=
  repl_spec _

instance imageAction_definable : ℒₛₑₜ-function₂[V] imageAction := by
  have h : ℒₛₑₜ-relation₃ (fun B π A : V ↦ ∀ x, x ∈ B ↔ ∃ p ∈ A, x = π ‘ p) := by definability
  apply Language.Definable.of_iff h
  intro v
  change v 0 = imageAction (v 1) (v 2) ↔ _
  rw [mem_ext_iff]
  simp only [mem_imageAction_iff]

theorem imageAction_subset {P R π A : V} (hπ : IsForcingAutomorphism P R π) (hA : A ⊆ P) :
    imageAction π A ⊆ P := by
  intro x hx
  obtain ⟨p, hp, rfl⟩ := (mem_imageAction_iff _ _ _).mp hx
  exact function_value_mem hπ.1 (hA p hp)

/-- The image action is exactly transport of membership along `π`. -/
theorem value_mem_imageAction_iff {P R π A : V} (hπ : IsForcingAutomorphism P R π) (hA : A ⊆ P)
    {q : V} (hq : q ∈ P) : π ‘ q ∈ imageAction π A ↔ q ∈ A := by
  rw [mem_imageAction_iff]
  constructor
  · rintro ⟨p, hp, he⟩
    rwa [injective_value_eq hπ.1 hπ.2.1 hq (hA p hp) he]
  · intro h
    exact ⟨q, h, rfl⟩

/-- A set of conditions is determined by the membership transport `π ‘ q ∈ B ↔ q ∈ A`. -/
theorem imageAction_eq_of_iff {P R π A B : V} (hπ : IsForcingAutomorphism P R π) (hA : A ⊆ P)
    (hB : B ⊆ P) (h : ∀ q ∈ P, π ‘ q ∈ B ↔ q ∈ A) : imageAction π A = B := by
  apply mem_ext
  intro x
  rw [mem_imageAction_iff]
  constructor
  · rintro ⟨p, hp, rfl⟩
    exact (h p (hA p hp)).mpr hp
  · intro hx
    obtain ⟨q, hq, rfl⟩ := forcingAutomorphism_surjective hπ x (hB x hx)
    exact ⟨q, (h q hq).mp hx, rfl⟩

theorem imageAction_identity {P A : V} (hA : A ⊆ P) : imageAction (identity P) A = A := by
  apply mem_ext
  intro x
  rw [mem_imageAction_iff]
  constructor
  · rintro ⟨p, hp, rfl⟩
    rwa [identity_value (hA p hp)]
  · intro hx
    exact ⟨x, hx, (identity_value (hA x hx)).symm⟩

/-- `compose π ρ` sends `p` to `ρ ‘ (π ‘ p)`, so its image action is `ρ` after `π`. -/
theorem imageAction_compose {P π ρ A : V} (hπ : π ∈ P ^ P) (hρ : ρ ∈ P ^ P) (hA : A ⊆ P) :
    imageAction (compose π ρ) A = imageAction ρ (imageAction π A) := by
  apply mem_ext
  intro x
  simp only [mem_imageAction_iff]
  constructor
  · rintro ⟨p, hp, rfl⟩
    exact ⟨π ‘ p, ⟨p, hp, rfl⟩, value_compose_of_mem_function hπ hρ (hA p hp)⟩
  · rintro ⟨y, ⟨p, hp, rfl⟩, rfl⟩
    exact ⟨p, hp, (value_compose_of_mem_function hπ hρ (hA p hp)).symm⟩

theorem imageAction_converseGraph {P R π A : V} (hπ : IsForcingAutomorphism P R π) (hA : A ⊆ P)
    (hfix : imageAction π A = A) : imageAction (converseGraph π) A = A := by
  apply mem_ext
  intro x
  rw [mem_imageAction_iff]
  constructor
  · rintro ⟨p, hp, rfl⟩
    rw [← hfix] at hp
    obtain ⟨q, hq, rfl⟩ := (mem_imageAction_iff _ _ _).mp hp
    rw [converseGraph_value_value hπ.1 hπ.2.1 (hA q (hfix ▸ hq))]
    exact hfix ▸ hq
  · intro hx
    have hxP : x ∈ P := hA x hx
    refine ⟨π ‘ x, ?_, (converseGraph_value_value hπ.1 hπ.2.1 hxP).symm⟩
    rw [← hfix]
    exact (value_mem_imageAction_iff hπ hA hxP).mpr hx

/-! ### The action commutes with the two closure operations -/

/-- The image of a forcing negation is the forcing negation of the image. -/
theorem forcingNegation_image {P R π A : V} (hπ : IsForcingAutomorphism P R π) (hA : A ⊆ P) :
    imageAction π (forcingNegation P R A) = forcingNegation P R (imageAction π A) := by
  apply imageAction_eq_of_iff hπ (forcingNegation_subset _ _ _) (forcingNegation_subset _ _ _)
  intro q hq
  exact forcingNegation_action_iff hπ (fun r hr ↦ value_mem_imageAction_iff hπ hA hr) hq

/-- The pointwise image of a family of sets of conditions. -/
noncomputable def imageFamily (π Y : V) : V := repl (fun A ↦ imageAction π A) (by definability) Y

theorem mem_imageFamily_iff (π Y B : V) : B ∈ imageFamily π Y ↔ ∃ A ∈ Y, B = imageAction π A :=
  repl_spec _

instance imageFamily_definable : ℒₛₑₜ-function₂[V] imageFamily := by
  have h : ℒₛₑₜ-relation₃ (fun C π Y : V ↦ ∀ B, B ∈ C ↔ ∃ A ∈ Y, B = imageAction π A) := by
    definability
  apply Language.Definable.of_iff h
  intro v
  change v 0 = imageFamily (v 1) (v 2) ↔ _
  rw [mem_ext_iff]
  simp only [mem_imageFamily_iff]

theorem imageFamily_eq_self {π Y : V} (hfix : ∀ A ∈ Y, imageAction π A = A) :
    imageFamily π Y = Y := by
  apply mem_ext
  intro B
  rw [mem_imageFamily_iff]
  constructor
  · rintro ⟨A, hA, rfl⟩
    rwa [hfix A hA]
  · intro hB
    exact ⟨B, hB, (hfix B hB).symm⟩

/-- The image of a regular join is the regular join of the image family. -/
theorem regularJoin_image {P R π Y : V} (hπ : IsForcingAutomorphism P R π)
    (hY : ∀ A ∈ Y, A ⊆ P) :
    imageAction π (regularJoin P R Y) = regularJoin P R (imageFamily π Y) := by
  have hsU : (⋃ˢ Y : V) ⊆ P := by
    intro p hp
    obtain ⟨A, hA, hpA⟩ := mem_sUnion_iff.mp hp
    exact hY A hA p hpA
  have hsU' : (⋃ˢ (imageFamily π Y) : V) ⊆ P := by
    intro p hp
    obtain ⟨B, hB, hpB⟩ := mem_sUnion_iff.mp hp
    obtain ⟨A, hA, rfl⟩ := (mem_imageFamily_iff _ _ _).mp hB
    exact imageAction_subset hπ (hY A hA) p hpB
  have htransport : ∀ q ∈ P, π ‘ q ∈ (⋃ˢ (imageFamily π Y) : V) ↔ q ∈ (⋃ˢ Y : V) := by
    intro q hq
    simp only [mem_sUnion_iff]
    constructor
    · rintro ⟨B, hB, hqB⟩
      obtain ⟨A, hA, rfl⟩ := (mem_imageFamily_iff _ _ _).mp hB
      exact ⟨A, hA, (value_mem_imageAction_iff hπ (hY A hA) hq).mp hqB⟩
    · rintro ⟨A, hA, hqA⟩
      exact ⟨imageAction π A, (mem_imageFamily_iff _ _ _).mpr ⟨A, hA, rfl⟩,
        (value_mem_imageAction_iff hπ (hY A hA) hq).mpr hqA⟩
  unfold regularJoin
  apply imageAction_eq_of_iff hπ (forcingClosure_subset _ _ _) (forcingClosure_subset _ _ _)
  intro q hq
  exact forcingClosure_action_iff hπ hsU hsU' htransport hq

/-! ### One closure step preserves fixed sets -/

theorem imageAction_subalgebraStep {P R π X : V} (hπ : IsForcingAutomorphism P R π)
    (hX : X ⊆ regularSets P R) (hfix : ∀ A ∈ X, imageAction π A = A) :
    ∀ d ∈ subalgebraStep P R X, imageAction π d = d := by
  intro d hd
  rcases (mem_subalgebraStep_iff P R X d).mp hd with hd | ⟨A, hA, rfl⟩ | ⟨Y, hY, rfl⟩
  · exact hfix d hd
  · have hAP : A ⊆ P := ((mem_regularSets_iff _ _ _).mp (hX A hA)).1
    rw [forcingNegation_image hπ hAP, hfix A hA]
  · have hYP : ∀ A ∈ Y, A ⊆ P :=
      fun A hA ↦ ((mem_regularSets_iff _ _ _).mp (hX A (hY A hA))).1
    rw [regularJoin_image hπ hYP, imageFamily_eq_self (fun A hA ↦ hfix A (hY A hA))]

/-! ### The main lemma -/

/-- Every closure stage of the subalgebra generated by fixed generators is fixed elementwise. -/
theorem closureStage_imageAction {P R π S θ : V} [IsOrdinal θ] (hR : IsForcingPreorder P R)
    (hπ : IsForcingAutomorphism P R π) (hS : S ⊆ regularSets P R)
    (hfix : ∀ A ∈ S, imageAction π A = A) :
    ∀ α ∈ θ, ∀ d ∈ (closureStages P R S θ) ‘ α, imageAction π d = d := by
  have hreg := closureStage_regular (θ := θ) hR hS
  apply internalWellFounded_induction (membershipRelation_wellFounded θ)
    (fun α ↦ ∀ d ∈ (closureStages P R S θ) ‘ α, imageAction π d = d) (by definability)
  intro α hα ih
  rw [closureStages_value hα]
  apply imageAction_subalgebraStep hπ
  · intro d hd
    rcases mem_union_iff.mp hd with hd | hd
    · exact hS d hd
    · obtain ⟨X, hX, hdX⟩ := mem_sUnion_iff.mp hd
      obtain ⟨β, hβ⟩ := mem_range_iff.mp hX
      obtain ⟨hβ, hβα⟩ := kpair_mem_restrict_iff.mp hβ
      have hβθ : β ∈ θ := IsOrdinal.toIsTransitive.mem_trans hβα hα
      rw [← value_eq_of_kpair_mem hβ] at hdX
      exact hreg β hβθ d hdX
  · intro A hA
    rcases mem_union_iff.mp hA with hA | hA
    · exact hfix A hA
    · obtain ⟨X, hX, hAX⟩ := mem_sUnion_iff.mp hA
      obtain ⟨β, hβ⟩ := mem_range_iff.mp hX
      obtain ⟨hβ, hβα⟩ := kpair_mem_restrict_iff.mp hβ
      have hβθ : β ∈ θ := IsOrdinal.toIsTransitive.mem_trans hβα hα
      rw [← value_eq_of_kpair_mem hβ] at hAX
      exact ih β hβθ ((pair_mem_membershipRelation _ _ _).mpr ⟨hβθ, hα, hβα⟩) A hAX

/-- Karagila-Schilhan Lemma 9.3: an automorphism fixing every generator as a set fixes every
element of the generated complete subalgebra. -/
theorem generatedSubalgebra_fixed_of_generators_fixed {P R π S : V} (hR : IsForcingPreorder P R)
    (hπ : IsForcingAutomorphism P R π) (hS : S ⊆ regularSets P R)
    (hfix : ∀ A ∈ S, imageAction π A = A) :
    ∀ d ∈ generatedSubalgebra P R S, imageAction π d = d := by
  have hS' : insert P S ⊆ regularSets P R := by
    intro d hd
    rcases mem_insert.mp hd with h | hd
    · rw [h]
      exact (mem_regularSets_iff _ _ _).mpr (forcingRegular_top P R)
    · exact hS d hd
  have hfix' : ∀ A ∈ insert P S, imageAction π A = A := by
    intro A hA
    rcases mem_insert.mp hA with h | hA
    · rw [h]
      exact imageAction_eq_of_iff hπ (fun _ h ↦ h) (fun _ h ↦ h)
        (fun q hq ↦ ⟨fun _ ↦ hq, fun _ ↦ function_value_mem hπ.1 hq⟩)
    · exact hfix A hA
  intro d hd
  obtain ⟨α, hα, hdα⟩ := (mem_generatedSubalgebra_iff _ _ _ _).mp hd
  exact closureStage_imageAction hR hπ hS' hfix' α hα d hdα

/-! ### The stabilizer subgroup -/

/-- The automorphisms in `Γ` that fix every member of `S` as a set. -/
noncomputable def imageStabilizer (Γ S : V) : V := {π ∈ Γ ; ∀ A ∈ S, imageAction π A = A}

theorem mem_imageStabilizer_iff (Γ S π : V) :
    π ∈ imageStabilizer Γ S ↔ π ∈ Γ ∧ ∀ A ∈ S, imageAction π A = A := mem_sep_iff

instance imageStabilizer_definable : ℒₛₑₜ-function₂[V] imageStabilizer := by
  have h : ℒₛₑₜ-relation₃[V] (fun H Γ S ↦ ∀ π, π ∈ H ↔ π ∈ Γ ∧ ∀ A ∈ S, imageAction π A = A) := by
    definability
  apply Language.Definable.of_iff h
  intro v
  change v 0 = imageStabilizer (v 1) (v 2) ↔ _
  rw [mem_ext_iff]
  simp only [mem_imageStabilizer_iff]

theorem imageStabilizer_subgroup {P R Γ S : V} (hΓ : IsForcingAutomorphismGroup P R Γ)
    (hS : S ⊆ regularSets P R) : IsForcingSubgroup P Γ (imageStabilizer Γ S) := by
  have hSP : ∀ A ∈ S, A ⊆ P := fun A hA ↦ ((mem_regularSets_iff _ _ _).mp (hS A hA)).1
  refine ⟨fun π hπ ↦ ((mem_imageStabilizer_iff Γ S π).mp hπ).1,
    (mem_imageStabilizer_iff _ _ _).mpr ⟨hΓ.2.1, fun A hA ↦ imageAction_identity (hSP A hA)⟩,
    ?_, ?_⟩
  · intro π hπ ρ hρ
    obtain ⟨hπΓ, hπS⟩ := (mem_imageStabilizer_iff Γ S π).mp hπ
    obtain ⟨hρΓ, hρS⟩ := (mem_imageStabilizer_iff Γ S ρ).mp hρ
    refine (mem_imageStabilizer_iff _ _ _).mpr ⟨hΓ.2.2.1 _ hπΓ _ hρΓ, fun A hA ↦ ?_⟩
    rw [imageAction_compose (hΓ.1 _ hπΓ).1 (hΓ.1 _ hρΓ).1 (hSP A hA), hπS A hA, hρS A hA]
  · intro π hπ
    obtain ⟨hπΓ, hπS⟩ := (mem_imageStabilizer_iff Γ S π).mp hπ
    exact (mem_imageStabilizer_iff _ _ _).mpr ⟨hΓ.2.2.2 _ hπΓ,
      fun A hA ↦ imageAction_converseGraph (hΓ.1 _ hπΓ) (hSP A hA) (hπS A hA)⟩

/-- Every automorphism fixing the generators as sets fixes the generated subalgebra elementwise. -/
theorem imageStabilizer_fixes_generatedSubalgebra {P R Γ S : V} (hR : IsForcingPreorder P R)
    (hΓ : IsForcingAutomorphismGroup P R Γ) (hS : S ⊆ regularSets P R)
    {π : V} (hπ : π ∈ imageStabilizer Γ S) :
    ∀ d ∈ generatedSubalgebra P R S, imageAction π d = d := by
  obtain ⟨hπΓ, hπS⟩ := (mem_imageStabilizer_iff Γ S π).mp hπ
  exact generatedSubalgebra_fixed_of_generators_fixed hR (hΓ.1 π hπΓ) hS hπS

end ZFVP
