import ZFVP.ModelTheory.GeneratedSubalgebraTrace
import ZFVP.ModelTheory.GenericFilterModel
import ZFVP.ModelTheory.LevyStageDefinable
import ZFVP.ModelTheory.LevyODParameterTree
import ZFVP.ModelTheory.SolovayRealCoding

/-! Second half of the forward direction of Karagila-Schilhan Lemma 9.3: everything in the
intermediate extension by a complete subalgebra `D` is definable in `V[G]` from the trace of the
generic on `D`, ground sets and ordinals. An element of `V[G ∩ D]` is the value of a ground name
over the conditions of `D` at that trace, and the name evaluation recursion is a formula, so the
element is definable from the trace and the check of the name. When `D` is generated by the Boolean
value sequence of a real of the extension the trace is itself definable from that real, and the
element is definable from ground sets, reals and ordinals. -/

namespace ZFVP

open LO LO.FirstOrder LO.FirstOrder.SetTheory

variable {V : Type*} [SetStructure V] [Nonempty V] [V↓[ℒₛₑₜ] ⊧* 𝗭𝗙]

namespace ForcingContext

variable (A : ForcingContext V)

/-- The trace of the Boolean generic on a checked set, written as an intersection. -/
theorem genericTrace_eq_inter (D : V) : A.genericTrace D = A.boolGenericSet ∩ A.check D := by
  apply mem_ext
  intro z
  unfold genericTrace
  rw [mem_sep_iff, mem_inter_iff]
  exact ⟨fun h ↦ ⟨h.2, h.1⟩, fun h ↦ ⟨h.2, h.1⟩⟩

/-- The trace of the generic on `D`, transported into the Boolean extension, is the generic of
the Boolean extension cut down by `Ď`. -/
theorem booleanEquiv_genericTrace (D : V) :
    A.booleanEquiv (A.genericTrace D) =
      A.booleanContext.genericSet ∩ A.booleanContext.check D := by
  have hinter : A.booleanEquiv (A.boolGenericSet ∩ A.check D) =
      A.booleanEquiv A.boolGenericSet ∩ A.booleanEquiv (A.check D) :=
    A.recoveredRealization.embedding.map_inter _ _
  rw [A.genericTrace_eq_inter D, hinter, A.booleanEquiv_boolGenericSet, A.booleanEquiv_check]

variable {D : V} (hD : IsCompleteSubalgebra A.P A.R D)

/-- Every element of the intermediate extension `V[G ∩ D]` is the value, at the trace of the
generic on `D`, of the check of a ground name over the conditions of `D`. This is the surjectivity
half of Lemma 9.3: the intermediate model is read off the trace by names of the ground model. -/
theorem exists_name_nameValue_genericTrace {x : A.booleanContext.Model}
    (hx : A.InSubalgebraModel hD x) :
    ∃ σ : V, IsForcingName (subalgebraConditions A.P A.R D) σ ∧
      A.booleanEquiv.symm x = nameValue (A.genericTrace D) (A.check σ) := by
  have hx' : A.booleanContext.InRestrictedModel (A.subalgebraConditions_subset_boolean (D := D))
      (A.top_mem_subalgebraConditions hD) (hD.trace_generic A.order A.generic) x := hx
  obtain ⟨τ, rfl⟩ := (A.booleanContext.inRestrictedModel_iff _ _ _ x).mp hx'
  refine ⟨τ.val, τ.property, ?_⟩
  set B := A.booleanContext with hB
  have hσD : IsForcingName D τ.val :=
    τ.property.mono (fun p hp ↦ ((mem_subalgebraConditions_iff _ _ _ _).mp hp).1)
  have hcheckname : IsForcingName (B.check D) (B.check τ.val) :=
    B.checkEmbedding.map_forcingName hσD
  have hmap : A.booleanEquiv (nameValue (A.genericTrace D) (A.check τ.val)) =
      nameValue (A.booleanEquiv (A.genericTrace D)) (A.booleanEquiv (A.check τ.val)) :=
    A.recoveredRealization.embedding.map_nameValue _ _
  have hval : A.booleanEquiv (nameValue (A.genericTrace D) (A.check τ.val)) =
      B.ofName (B.liftName _ _ _ τ) := by
    rw [hmap, A.booleanEquiv_genericTrace D, A.booleanEquiv_check,
      nameValue_inter_of_name hcheckname]
    exact B.nameValue_genericSet_check (B.liftName _ _ _ τ)
  exact (Equiv.symm_apply_eq _).mpr hval.symm

/-- Everything in the intermediate extension by `D` is definable in `V[G]` from the trace of the
generic on `D`, ground sets and ordinals. -/
theorem groundRealDefinable_of_inSubalgebraModel_of_trace
    (htrace : A.IsGroundRealDefinable (A.genericTrace D))
    {x : A.booleanContext.Model} (hx : A.InSubalgebraModel hD x) :
    A.IsGroundRealDefinable (A.booleanEquiv.symm x) := by
  obtain ⟨σ, _, hxv⟩ := A.exists_name_nameValue_genericTrace hD hx
  set T : V := transitiveClosure ({σ} : V) with hT
  have hσT : σ ∈ T := subset_transitiveClosure _ _ (mem_singleton_iff.mpr rfl)
  have hNclosed : IsSubnameClosed (A.check T) :=
    transitive_subnameClosed (check_transitive_of_ground (transitiveClosure_transitive _))
  have hcN : A.check σ ∈ A.check T := (A.check_mem_iff _ _).mpr hσT
  have hpair : A.check (⟨T, σ⟩ₖ : V) = (⟨A.check T, A.check σ⟩ₖ : A.Model) :=
    A.checkEmbedding.map_kpair T σ
  rw [hxv]
  refine groundRealDefinable_of_definable_from₂ htrace
    (Or.inl ⟨(⟨T, σ⟩ₖ : V), hpair.symm⟩) nameEvalFormula (fun b ↦ ?_)
  exact mem_nameValue_iff_nameEval hNclosed hcN b

end ForcingContext

/-! ### The subalgebra generated by the Boolean values of a single real -/

namespace ForcingContext

variable (A : ForcingContext V)

/-- Lemma 9.3, forward direction, second half: if the complete subalgebra `D` is generated by a
ground sequence `s` of regular sets whose generic decisions are read off a real `r` of the
extension, then every set of the intermediate extension `V[G ∩ D]` is definable in `V[G]` from
`r`, ground sets and ordinals. -/
theorem groundRealDefinable_of_inSubalgebraModel (hAC : InternalChoice V)
    {s : V} (hs : s ∈ regularSets A.P A.R ^ (ω : V))
    {r : A.Model} (hr : r ⊆ A.check (ω : V))
    (hval : ∀ n ∈ (ω : V), ((∃ p ∈ A.G, p ∈ s ‘ n) ↔ A.check n ∈ r))
    {D : V} (hD : IsCompleteSubalgebra A.P A.R D)
    (hDgen : D = generatedSubalgebra A.P A.R (range s))
    {x : A.booleanContext.Model} (hx : A.InSubalgebraModel hD x) :
    A.IsGroundRealDefinable (A.booleanEquiv.symm x) := by
  refine A.groundRealDefinable_of_inSubalgebraModel_of_trace hD ?_ hx
  subst hDgen
  exact A.genericTrace_groundRealDefinable hAC hr hs hval

end ForcingContext

/-! ### Subalgebras generated by a family of reals -/

/-- `d ∈ D` and some antichain-generic ultrafilter `U` on `Reg` (relative to `MA`) with
`val ‘ ⟨i, n⟩ ∈ U ↔ ⟨i, n⟩ ∈ x` for `i ∈ k` and `n ∈ w` contains `d`. Here `val` is a family of
sequences of regular sets indexed by `k × w` and `x` codes the family of reals reading off its
generic decisions. -/
def familyTraceFormula : SetTheorySemisentence 8 :=
  f“d D Reg MA val w k x. d ∈ D ∧ ∃ U, (∀ u ∈ U, u ∈ Reg) ∧
    (∀ u ∈ U, ∀ u' ∈ Reg, u ⊆ u' → u' ∈ U) ∧ (∀ u ∈ U, ∀ u' ∈ U, !inter.dfn u u' ∈ U) ∧
    (∀ u ∈ U, ∃ z, z ∈ u) ∧ (∀ A ∈ MA, ∃ a ∈ A, a ∈ U) ∧
    (∀ i ∈ k, ∀ n ∈ w, (!value.dfn val (!kpair.dfn i n) ∈ U ↔ !kpair.dfn i n ∈ x)) ∧ d ∈ U”

theorem eval_familyTraceFormula (d D Reg MA val w k x : V) :
    familyTraceFormula.Evalb ![d, D, Reg, MA, val, w, k, x] ↔
      d ∈ D ∧ ∃ U : V, (∀ u ∈ U, u ∈ Reg) ∧
        (∀ u ∈ U, ∀ u' ∈ Reg, u ⊆ u' → u' ∈ U) ∧ (∀ u ∈ U, ∀ u' ∈ U, u ∩ u' ∈ U) ∧
        (∀ u ∈ U, ∃ z, z ∈ u) ∧ (∀ A ∈ MA, ∃ a ∈ A, a ∈ U) ∧
        (∀ i ∈ k, ∀ n ∈ w, (val ‘ (⟨i, n⟩ₖ : V) ∈ U ↔ (⟨i, n⟩ₖ : V) ∈ x)) ∧ d ∈ U := by
  simp [familyTraceFormula]

namespace ForcingContext

variable (A : ForcingContext V)

/-- The trace of the generic on the subalgebra generated by a `k`-indexed ground family of
Boolean-value sequences is definable from ground parameters and the set `R ⊆ (ω × ω)ˇ` coding the
family of reals that reads off the generic decisions. The index set `k` is any ground set of
natural numbers, so this covers any finite family of reals. -/
theorem genericTrace_groundRealDefinable_family (hAC : InternalChoice V) {k S : V}
    (hS : S ∈ regularSets A.P A.R ^ (k ×ˢ (ω : V)))
    {R : A.Model} (hR : R ⊆ A.check ((ω : V) ×ˢ (ω : V)))
    (hval : ∀ i ∈ k, ∀ n ∈ (ω : V),
      ((∃ p ∈ A.G, p ∈ S ‘ (⟨i, n⟩ₖ : V)) ↔ A.check (⟨i, n⟩ₖ : V) ∈ R)) :
    A.IsGroundRealDefinable (A.genericTrace (generatedSubalgebra A.P A.R (range S))) := by
  have hSfun : IsFunction S := IsFunction.of_mem hS
  have hSdom : domain S = k ×ˢ (ω : V) := domain_eq_of_mem_function hS
  have hSrange : range S ⊆ regularSets A.P A.R := range_subset_of_mem_function hS
  have hpairdom : ∀ i₀ ∈ k, ∀ n₀ ∈ (ω : V), (⟨i₀, n₀⟩ₖ : V) ∈ domain S := by
    intro i₀ hi₀ n₀ hn₀
    rw [hSdom]
    exact mem_prod_iff.mpr ⟨i₀, hi₀, n₀, hn₀, rfl⟩
  have hcheckval : ∀ i₀ ∈ k, ∀ n₀ ∈ (ω : V),
      (A.check S) ‘ (⟨A.check i₀, A.check n₀⟩ₖ : A.Model) = A.check (S ‘ (⟨i₀, n₀⟩ₖ : V)) := by
    intro i₀ hi₀ n₀ hn₀
    have h := A.check_value (hpairdom i₀ hi₀ n₀ hn₀)
    rwa [A.check_kpair] at h
  have hreg : ∀ i₀ ∈ k, ∀ n₀ ∈ (ω : V), S ‘ (⟨i₀, n₀⟩ₖ : V) ∈ regularSets A.P A.R := by
    intro i₀ hi₀ n₀ hn₀
    exact function_value_mem hS (mem_prod_iff.mpr ⟨i₀, hi₀, n₀, hn₀, rfl⟩)
  refine groundRealDefinable_of_definable_from_definables
    ![A.check (generatedSubalgebra A.P A.R (range S)), A.check (regularSets A.P A.R),
      A.check (boolMaximalAntichains A.P A.R), A.check S, A.check (ω : V), A.check k, R]
    (fun i ↦ ?_) familyTraceFormula (fun b ↦ ?_)
  · match i with
    | 0 => exact groundRealDefinable_of_parameter (Or.inl ⟨_, rfl⟩)
    | 1 => exact groundRealDefinable_of_parameter (Or.inl ⟨_, rfl⟩)
    | 2 => exact groundRealDefinable_of_parameter (Or.inl ⟨_, rfl⟩)
    | 3 => exact groundRealDefinable_of_parameter (Or.inl ⟨_, rfl⟩)
    | 4 => exact groundRealDefinable_of_parameter (Or.inl ⟨_, rfl⟩)
    | 5 => exact groundRealDefinable_of_parameter (Or.inl ⟨_, rfl⟩)
    | 6 => exact groundRealDefinable_of_subset_check_omega_prod R hR
  · have he := eval_familyTraceFormula b (A.check (generatedSubalgebra A.P A.R (range S)))
      (A.check (regularSets A.P A.R)) (A.check (boolMaximalAntichains A.P A.R)) (A.check S)
      (A.check (ω : V)) (A.check k) R
    change b ∈ A.genericTrace _ ↔ familyTraceFormula.Evalb ![b, _, _, _, _, _, _, _]
    rw [he]
    unfold genericTrace
    rw [mem_sep_iff]
    have hgen := A.boolGenericSet_antichainGeneric
    constructor
    · rintro ⟨hbD, hbU⟩
      refine ⟨hbD, A.boolGenericSet, hgen.subset, hgen.upward, hgen.inter, ?_, hgen.meets, ?_, hbU⟩
      · intro u hu
        obtain ⟨_, p, _, hp⟩ := mem_sep_iff.mp hu
        exact ⟨p, hp⟩
      · intro i hi n hn
        obtain ⟨i₀, hi₀, rfl⟩ := (A.mem_check_iff _ _).mp hi
        obtain ⟨n₀, hn₀, rfl⟩ := (A.mem_check_iff _ _).mp hn
        rw [hcheckval i₀ hi₀ n₀ hn₀, A.check_mem_boolGenericSet_iff,
          ← A.check_kpair, ← hval i₀ hi₀ n₀ hn₀]
        exact ⟨fun h ↦ h.2, fun h ↦ ⟨hreg i₀ hi₀ n₀ hn₀, h⟩⟩
    · rintro ⟨hbD, U, h1, h2, h3, h4, h5, hvalU, hbU⟩
      refine ⟨hbD, ?_⟩
      have hU := antichainGeneric_of_clauses h1 h2 h3 h4 h5
      have hagree : ∀ t ∈ A.check (range S), (t ∈ A.boolGenericSet ↔ t ∈ U) := by
        intro t ht
        obtain ⟨t₀, ht₀, rfl⟩ := (A.mem_check_iff _ _).mp ht
        obtain ⟨z, hz⟩ := mem_range_iff.mp ht₀
        have hzdom : z ∈ domain S := mem_domain_of_kpair_mem hz
        rw [hSdom] at hzdom
        obtain ⟨i₀, hi₀, n₀, hn₀, rfl⟩ := mem_prod_iff.mp hzdom
        have ht₀eq : t₀ = S ‘ (⟨i₀, n₀⟩ₖ : V) := (value_eq_of_kpair_mem hz).symm
        have hU' := hvalU (A.check i₀) ((A.check_mem_iff _ _).mpr hi₀) (A.check n₀)
          ((A.check_mem_iff _ _).mpr hn₀)
        rw [hcheckval i₀ hi₀ n₀ hn₀] at hU'
        rw [ht₀eq, A.check_mem_boolGenericSet_iff, hU', ← A.check_kpair,
          ← hval i₀ hi₀ n₀ hn₀]
        exact ⟨fun h ↦ h.2, fun h ↦ ⟨hreg i₀ hi₀ n₀ hn₀, h⟩⟩
      exact (A.generatedSubalgebra_generic_unique hAC hSrange hU hagree b hbD).mpr hbU

/-- Lemma 9.3, forward direction, second half, for a family of reals: if the complete subalgebra
`D` is generated by a ground family `S` of sequences of regular sets indexed by `k × ω`, whose
generic decisions are read off the set `R ⊆ (ω × ω)ˇ` coding the family of reals, then every set
of `V[G ∩ D]` is definable in `V[G]` from ground sets, reals and ordinals. -/
theorem groundRealDefinable_of_inSubalgebraModel_finite (hAC : InternalChoice V) {k S : V}
    (hS : S ∈ regularSets A.P A.R ^ (k ×ˢ (ω : V)))
    {R : A.Model} (hR : R ⊆ A.check ((ω : V) ×ˢ (ω : V)))
    (hval : ∀ i ∈ k, ∀ n ∈ (ω : V),
      ((∃ p ∈ A.G, p ∈ S ‘ (⟨i, n⟩ₖ : V)) ↔ A.check (⟨i, n⟩ₖ : V) ∈ R))
    {D : V} (hD : IsCompleteSubalgebra A.P A.R D)
    (hDgen : D = generatedSubalgebra A.P A.R (range S))
    {x : A.booleanContext.Model} (hx : A.InSubalgebraModel hD x) :
    A.IsGroundRealDefinable (A.booleanEquiv.symm x) := by
  refine A.groundRealDefinable_of_inSubalgebraModel_of_trace hD ?_ hx
  subst hDgen
  exact A.genericTrace_groundRealDefinable_family hAC hS hR hval

/-- A checked pair lies in the preimage of a real under the pairing code exactly when the checked
code of the pair lies in the real. This is the coding of a family of reals by a single real. -/
theorem check_kpair_mem_omegaPairPreimage_iff {r : A.Model} (hr : r ⊆ A.check (ω : V))
    {i n : V} (hi : i ∈ (ω : V)) (hn : n ∈ (ω : V)) :
    A.check (⟨i, n⟩ₖ : V) ∈ omegaPairPreimage A r ↔ A.check (naturalPairCode i n) ∈ r := by
  rw [mem_omegaPairPreimage_iff']
  constructor
  · rintro ⟨-, m, hm, hpm⟩
    obtain ⟨m₀, -, rfl⟩ := (A.mem_check_iff _ _).mp (hr m hm)
    obtain ⟨-, -, rfl⟩ := (check_kpair_mem_check_omegaPairGraph_iff i n m₀).mp hpm
    exact hm
  · intro h
    exact ⟨(A.check_mem_iff _ _).mpr (mem_prod_iff.mpr ⟨i, hi, n, hn, rfl⟩), _, h,
      (check_kpair_mem_check_omegaPairGraph_iff i n _).mpr ⟨hi, hn, rfl⟩⟩

/-- The family version with the family of reals coded by a single real: the generic decisions of
the `i`-th sequence of the family are read off the `i`-th section of the real `r`, through the
ground pairing code on `ω`. -/
theorem groundRealDefinable_of_inSubalgebraModel_finite_of_real (hAC : InternalChoice V) {k S : V}
    (hk : k ⊆ (ω : V)) (hS : S ∈ regularSets A.P A.R ^ (k ×ˢ (ω : V)))
    {r : A.Model} (hr : r ⊆ A.check (ω : V))
    (hval : ∀ i ∈ k, ∀ n ∈ (ω : V),
      ((∃ p ∈ A.G, p ∈ S ‘ (⟨i, n⟩ₖ : V)) ↔ A.check (naturalPairCode i n) ∈ r))
    {D : V} (hD : IsCompleteSubalgebra A.P A.R D)
    (hDgen : D = generatedSubalgebra A.P A.R (range S))
    {x : A.booleanContext.Model} (hx : A.InSubalgebraModel hD x) :
    A.IsGroundRealDefinable (A.booleanEquiv.symm x) := by
  refine A.groundRealDefinable_of_inSubalgebraModel_finite hAC hS
    (omegaPairPreimage_subset r) (fun i hi n hn ↦ ?_) hD hDgen hx
  rw [A.check_kpair_mem_omegaPairPreimage_iff hr (hk i hi) hn]
  exact hval i hi n hn

end ForcingContext

end ZFVP
